/* Q API - constants/chemical elements.h
	      __	   __
  _______ ___/ /______ ___/ /__
 / __/ -_) _  / __/ _ \ _  / -_)
/_/  \__/\_,_/\__/\___/_,_/\__/
Copyright © 2012 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU General Public License v3. */

#ifndef __Q_constants_chemical_elements_H__
#define __Q_constants_chemical_elements_H__

/*     01										    18
     .----.										  .----.
     |1	  |										  |2   |
   1 | H  | 02							   13	14   15   16   17 | He |
     |----+----.						 .------------------------+----|
     |3	  |4   |						 |5   |6   |7	|8   |9	  |10  |
   2 | Li | Be |						 | B  | C  | N	| O  | F  | Ne |
     |----+----|						 |----+----+----+----+----+----|
     |11  |12  |						 |13  |14  |15	|16  |17  |18  |
   3 | Na | Mg | 03   04   05	06   07   08   09   10	 11   12 | Al | Si | P	| S  | Cl | Ar |
     |----+----+-------------------------------------------------+----+----+----+----+----+----|
     |19  |20  |21  |22	 |23  |24  |25	|26  |27  |28  |29  |30	 |31  |32  |33	|34  |35  |36  |
   4 | K  | Ca | Sc | Ti | V  | Cr | Mn | Fe | Co | Ni | Cu | Zn | Ga | Ge | As | Se | Br | Kr |
     |----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----|
     |37  |38  |39  |40	 |41  |42  |43	|44  |45  |46  |47  |48	 |49  |50  |51	|52  |53  |54  |
   5 | Rb | Sr | Y  | Zr | Nb | Mo | Tc | Ru | Rh | Pd | Ag | Cd | In | Sn | Sb | Te | I  | Xe |
     |----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----|
     |55  |56  |    |72	 |73  |74  |75	|76  |77  |78  |79  |80	 |81  |82  |83	|84  |85  |86  |
   6 | Cs | Ba |--. | Hf | Ta | W  | Re | Os | Ir | Pt | Au | Hg | Tl | Pb | Bi | Po | At | Rn |
     |----+----|  | |----+----+----+----+----+----+----+----+----+----+----+----+----+----+----|
     |87  |88  |  | |104 |105 |106 |107 |108 |109 |110 |111 |112 |113 |114 |115 |116 |117 |118 |
   7 | Fr | Ra |-.| | Rf | Db | Sg | Bh | Hs | Mt | Ds | Rg | Cn | Uut| Fl | Uup| Lv | Uus| Uuo|
     '---------' || '--------------------------------------------------------------------------'
		 ||
		 || .--------------------------------------------------------------------------.
		 || |57  |58  |59  |60	|61  |62  |63  |64  |65  |66  |67  |68	|69  |70  |71  |
     Lanthanides |'-| La | Ce | Pr | Nd | Pm | Sm | Eu | Gd | Tb | Dy | Ho | Er | Tm | Yb | Lu |
		 |  |----+----+----+----+----+----+----+----+----+----+----+----+----+----+----|
		 |  |89  |90  |91  |92	|93  |94  |95  |96  |97  |98  |99  |100 |101 |102 |103 |
       Actinides '--| Ac | Th | Pa | U  | Np | Pu | Am | Cm | Bk | Cf | Es | Fm | Md | No | Lr |
		    '--------------------------------------------------------------------------' */

#pragma mark - 1 H

#define Q_HYDROGEN_SYMBOL				H
#define Q_HYDROGEN_ATOMIC_NUMBER			1
#define Q_HYDROGEN_EMPIRICAL_ATOMIC_RADIUS
#define Q_HYDROGEN_CALCULATED_ATOMIC_RADIUS
#define Q_HYDROGEN_COBALENT_RADIUS
#define Q_HYDROGEN_VAN_DER_WAALS_RADIUS
#define Q_HYDROGEN_ATOMIC_VOLUME
#define Q_HYDROGEN_CRYSTAL_STRUCTURE
#define Q_HYDROGEN_MELTING_POINT
#define Q_HYDROGEN_BOILING_POINT
#define Q_HYDROGEN_FUSION_HEAT
#define Q_HYDROGEN_VAPORIZATION_HEAT
#define Q_HYDROGEN_SPECIFIC_HEAT
#define Q_HYDROGEN_DENSITY
#define Q_HYDROGEN_ELECTRICAL_CONDUCTIVITY
#define Q_HYDROGEN_THERMAL_CONDUCTIVITY
#define Q_HYDROGEN_ELECTRONEGATIVITY
#define Q_HYDROGEN_YOUNG_MODULUS
#define Q_HYDROGEN_BULK_MODULUS
#define Q_HYDROGEN_SHEER_MODULUS
#define Q_HYDROGEN_POISSON_RATIO

#pragma mark - 2 He

#define Q_HELIUM_SYMBOL					He
#define Q_HELIUM_ATOMIC_NUMBER				2
#define Q_HELIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_HELIUM_CALCULATED_ATOMIC_RADIUS
#define Q_HELIUM_COBALENT_RADIUS
#define Q_HELIUM_VAN_DER_WAALS_RADIUS
#define Q_HELIUM_ATOMIC_VOLUME
#define Q_HELIUM_CRYSTAL_STRUCTURE
#define Q_HELIUM_MELTING_POINT
#define Q_HELIUM_BOILING_POINT
#define Q_HELIUM_FUSION_HEAT
#define Q_HELIUM_VAPORIZATION_HEAT
#define Q_HELIUM_SPECIFIC_HEAT
#define Q_HELIUM_DENSITY
#define Q_HELIUM_ELECTRICAL_CONDUCTIVITY
#define Q_HELIUM_THERMAL_CONDUCTIVITY
#define Q_HELIUM_ELECTRONEGATIVITY
#define Q_HELIUM_YOUNG_MODULUS
#define Q_HELIUM_BULK_MODULUS
#define Q_HELIUM_SHEER_MODULUS
#define Q_HELIUM_POISSON_RATIO

#pragma mark - 3 Li

#define Q_LITHIUM_SYMBOL				Li
#define Q_LITHIUM_ATOMIC_NUMBER				3
#define Q_LITHIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_LITHIUM_CALCULATED_ATOMIC_RADIUS
#define Q_LITHIUM_COBALENT_RADIUS
#define Q_LITHIUM_VAN_DER_WAALS_RADIUS
#define Q_LITHIUM_ATOMIC_VOLUME
#define Q_LITHIUM_CRYSTAL_STRUCTURE
#define Q_LITHIUM_MELTING_POINT
#define Q_LITHIUM_BOILING_POINT
#define Q_LITHIUM_FUSION_HEAT
#define Q_LITHIUM_VAPORIZATION_HEAT
#define Q_LITHIUM_SPECIFIC_HEAT
#define Q_LITHIUM_DENSITY
#define Q_LITHIUM_ELECTRICAL_CONDUCTIVITY
#define Q_LITHIUM_THERMAL_CONDUCTIVITY
#define Q_LITHIUM_ELECTRONEGATIVITY
#define Q_LITHIUM_YOUNG_MODULUS
#define Q_LITHIUM_BULK_MODULUS
#define Q_LITHIUM_SHEER_MODULUS
#define Q_LITHIUM_POISSON_RATIO

#pragma mark - 4 Be

#define Q_BERYLLIUM_SYMBOL				Be
#define Q_BERYLLIUM_ATOMIC_NUMBER			4
#define Q_BERYLLIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_BERYLLIUM_CALCULATED_ATOMIC_RADIUS
#define Q_BERYLLIUM_COBALENT_RADIUS
#define Q_BERYLLIUM_VAN_DER_WAALS_RADIUS
#define Q_BERYLLIUM_ATOMIC_VOLUME
#define Q_BERYLLIUM_CRYSTAL_STRUCTURE
#define Q_BERYLLIUM_MELTING_POINT
#define Q_BERYLLIUM_BOILING_POINT
#define Q_BERYLLIUM_FUSION_HEAT
#define Q_BERYLLIUM_VAPORIZATION_HEAT
#define Q_BERYLLIUM_SPECIFIC_HEAT
#define Q_BERYLLIUM_DENSITY
#define Q_BERYLLIUM_ELECTRICAL_CONDUCTIVITY
#define Q_BERYLLIUM_THERMAL_CONDUCTIVITY
#define Q_BERYLLIUM_ELECTRONEGATIVITY
#define Q_BERYLLIUM_YOUNG_MODULUS
#define Q_BERYLLIUM_BULK_MODULUS
#define Q_BERYLLIUM_SHEER_MODULUS
#define Q_BERYLLIUM_POISSON_RATIO

#pragma mark - 5 B

#define Q_BORON_SYMBOL					B
#define Q_BORON_ATOMIC_NUMBER				5
#define Q_BORON_EMPIRICAL_ATOMIC_RADIUS
#define Q_BORON_CALCULATED_ATOMIC_RADIUS
#define Q_BORON_COBALENT_RADIUS
#define Q_BORON_VAN_DER_WAALS_RADIUS
#define Q_BORON_ATOMIC_VOLUME
#define Q_BORON_CRYSTAL_STRUCTURE
#define Q_BORON_MELTING_POINT
#define Q_BORON_BOILING_POINT
#define Q_BORON_FUSION_HEAT
#define Q_BORON_VAPORIZATION_HEAT
#define Q_BORON_SPECIFIC_HEAT
#define Q_BORON_DENSITY
#define Q_BORON_ELECTRICAL_CONDUCTIVITY
#define Q_BORON_THERMAL_CONDUCTIVITY
#define Q_BORON_ELECTRONEGATIVITY
#define Q_BORON_YOUNG_MODULUS
#define Q_BORON_BULK_MODULUS
#define Q_BORON_SHEER_MODULUS
#define Q_BORON_POISSON_RATIO

#pragma mark - 6 C

#define Q_CARBON_SYMBOL					C
#define Q_CARBON_ATOMIC_NUMBER				6
#define Q_CARBON_EMPIRICAL_ATOMIC_RADIUS
#define Q_CARBON_CALCULATED_ATOMIC_RADIUS
#define Q_CARBON_COBALENT_RADIUS
#define Q_CARBON_VAN_DER_WAALS_RADIUS
#define Q_CARBON_ATOMIC_VOLUME
#define Q_CARBON_CRYSTAL_STRUCTURE
#define Q_CARBON_MELTING_POINT
#define Q_CARBON_BOILING_POINT
#define Q_CARBON_FUSION_HEAT
#define Q_CARBON_VAPORIZATION_HEAT
#define Q_CARBON_SPECIFIC_HEAT
#define Q_CARBON_DENSITY
#define Q_CARBON_ELECTRICAL_CONDUCTIVITY
#define Q_CARBON_THERMAL_CONDUCTIVITY
#define Q_CARBON_ELECTRONEGATIVITY
#define Q_CARBON_YOUNG_MODULUS
#define Q_CARBON_BULK_MODULUS
#define Q_CARBON_SHEER_MODULUS
#define Q_CARBON_POISSON_RATIO

#pragma mark - 7 N

#define Q_NITROGEN_SYMBOL				N
#define Q_NITROGEN_ATOMIC_NUMBER			7
#define Q_NITROGEN_EMPIRICAL_ATOMIC_RADIUS
#define Q_NITROGEN_CALCULATED_ATOMIC_RADIUS
#define Q_NITROGEN_COBALENT_RADIUS
#define Q_NITROGEN_VAN_DER_WAALS_RADIUS
#define Q_NITROGEN_ATOMIC_VOLUME
#define Q_NITROGEN_CRYSTAL_STRUCTURE
#define Q_NITROGEN_MELTING_POINT
#define Q_NITROGEN_BOILING_POINT
#define Q_NITROGEN_FUSION_HEAT
#define Q_NITROGEN_VAPORIZATION_HEAT
#define Q_NITROGEN_SPECIFIC_HEAT
#define Q_NITROGEN_DENSITY
#define Q_NITROGEN_ELECTRICAL_CONDUCTIVITY
#define Q_NITROGEN_THERMAL_CONDUCTIVITY
#define Q_NITROGEN_ELECTRONEGATIVITY
#define Q_NITROGEN_YOUNG_MODULUS
#define Q_NITROGEN_BULK_MODULUS
#define Q_NITROGEN_SHEER_MODULUS
#define Q_NITROGEN_POISSON_RATIO

#pragma mark - 8 O

#define Q_OXYGEN_SYMBOL					O
#define Q_OXYGEN_ATOMIC_NUMBER				8
#define Q_OXYGEN_EMPIRICAL_ATOMIC_RADIUS
#define Q_OXYGEN_CALCULATED_ATOMIC_RADIUS
#define Q_OXYGEN_COBALENT_RADIUS
#define Q_OXYGEN_VAN_DER_WAALS_RADIUS
#define Q_OXYGEN_ATOMIC_VOLUME
#define Q_OXYGEN_CRYSTAL_STRUCTURE
#define Q_OXYGEN_MELTING_POINT
#define Q_OXYGEN_BOILING_POINT
#define Q_OXYGEN_FUSION_HEAT
#define Q_OXYGEN_VAPORIZATION_HEAT
#define Q_OXYGEN_SPECIFIC_HEAT
#define Q_OXYGEN_DENSITY
#define Q_OXYGEN_ELECTRICAL_CONDUCTIVITY
#define Q_OXYGEN_THERMAL_CONDUCTIVITY
#define Q_OXYGEN_ELECTRONEGATIVITY
#define Q_OXYGEN_YOUNG_MODULUS
#define Q_OXYGEN_BULK_MODULUS
#define Q_OXYGEN_SHEER_MODULUS
#define Q_OXYGEN_POISSON_RATIO

#pragma mark - 9 F

#define Q_FLUORINE_SYMBOL				F
#define Q_FLUORINE_ATOMIC_NUMBER			9
#define Q_FLUORINE_EMPIRICAL_ATOMIC_RADIUS
#define Q_FLUORINE_CALCULATED_ATOMIC_RADIUS
#define Q_FLUORINE_COBALENT_RADIUS
#define Q_FLUORINE_VAN_DER_WAALS_RADIUS
#define Q_FLUORINE_ATOMIC_VOLUME
#define Q_FLUORINE_CRYSTAL_STRUCTURE
#define Q_FLUORINE_MELTING_POINT
#define Q_FLUORINE_BOILING_POINT
#define Q_FLUORINE_FUSION_HEAT
#define Q_FLUORINE_VAPORIZATION_HEAT
#define Q_FLUORINE_SPECIFIC_HEAT
#define Q_FLUORINE_DENSITY
#define Q_FLUORINE_ELECTRICAL_CONDUCTIVITY
#define Q_FLUORINE_THERMAL_CONDUCTIVITY
#define Q_FLUORINE_ELECTRONEGATIVITY
#define Q_FLUORINE_YOUNG_MODULUS
#define Q_FLUORINE_BULK_MODULUS
#define Q_FLUORINE_SHEER_MODULUS
#define Q_FLUORINE_POISSON_RATIO

#pragma mark - 10 Ne

#define Q_NEON_SYMBOL					Ne
#define Q_NEON_ATOMIC_NUMBER				10
#define Q_NEON_EMPIRICAL_ATOMIC_RADIUS
#define Q_NEON_CALCULATED_ATOMIC_RADIUS
#define Q_NEON_COBALENT_RADIUS
#define Q_NEON_VAN_DER_WAALS_RADIUS
#define Q_NEON_ATOMIC_VOLUME
#define Q_NEON_CRYSTAL_STRUCTURE
#define Q_NEON_MELTING_POINT
#define Q_NEON_BOILING_POINT
#define Q_NEON_FUSION_HEAT
#define Q_NEON_VAPORIZATION_HEAT
#define Q_NEON_SPECIFIC_HEAT
#define Q_NEON_DENSITY
#define Q_NEON_ELECTRICAL_CONDUCTIVITY
#define Q_NEON_THERMAL_CONDUCTIVITY
#define Q_NEON_ELECTRONEGATIVITY
#define Q_NEON_YOUNG_MODULUS
#define Q_NEON_BULK_MODULUS
#define Q_NEON_SHEER_MODULUS
#define Q_NEON_POISSON_RATIO

#pragma mark - 11 Na

#define Q_SODIUM_SYMBOL					Na
#define Q_SODIUM_ATOMIC_NUMBER				11
#define Q_SODIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_SODIUM_CALCULATED_ATOMIC_RADIUS
#define Q_SODIUM_COBALENT_RADIUS
#define Q_SODIUM_VAN_DER_WAALS_RADIUS
#define Q_SODIUM_ATOMIC_VOLUME
#define Q_SODIUM_CRYSTAL_STRUCTURE
#define Q_SODIUM_MELTING_POINT
#define Q_SODIUM_BOILING_POINT
#define Q_SODIUM_FUSION_HEAT
#define Q_SODIUM_VAPORIZATION_HEAT
#define Q_SODIUM_SPECIFIC_HEAT
#define Q_SODIUM_DENSITY
#define Q_SODIUM_ELECTRICAL_CONDUCTIVITY
#define Q_SODIUM_THERMAL_CONDUCTIVITY
#define Q_SODIUM_ELECTRONEGATIVITY
#define Q_SODIUM_YOUNG_MODULUS
#define Q_SODIUM_BULK_MODULUS
#define Q_SODIUM_SHEER_MODULUS
#define Q_SODIUM_POISSON_RATIO

#pragma mark - 12 Mg

#define Q_MAGNESIUM_SYMBOL				Mg
#define Q_MAGNESIUM_ATOMIC_NUMBER			12
#define Q_MAGNESIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_MAGNESIUM_CALCULATED_ATOMIC_RADIUS
#define Q_MAGNESIUM_COBALENT_RADIUS
#define Q_MAGNESIUM_VAN_DER_WAALS_RADIUS
#define Q_MAGNESIUM_ATOMIC_VOLUME
#define Q_MAGNESIUM_CRYSTAL_STRUCTURE
#define Q_MAGNESIUM_MELTING_POINT
#define Q_MAGNESIUM_BOILING_POINT
#define Q_MAGNESIUM_FUSION_HEAT
#define Q_MAGNESIUM_VAPORIZATION_HEAT
#define Q_MAGNESIUM_SPECIFIC_HEAT
#define Q_MAGNESIUM_DENSITY
#define Q_MAGNESIUM_ELECTRICAL_CONDUCTIVITY
#define Q_MAGNESIUM_THERMAL_CONDUCTIVITY
#define Q_MAGNESIUM_ELECTRONEGATIVITY
#define Q_MAGNESIUM_YOUNG_MODULUS
#define Q_MAGNESIUM_BULK_MODULUS
#define Q_MAGNESIUM_SHEER_MODULUS
#define Q_MAGNESIUM_POISSON_RATIO

#pragma mark - 13 Al

#define Q_ALUMINIUM_SYMBOL				Al
#define Q_ALUMINIUM_ATOMIC_NUMBER			13
#define Q_ALUMINIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_ALUMINIUM_CALCULATED_ATOMIC_RADIUS
#define Q_ALUMINIUM_COBALENT_RADIUS
#define Q_ALUMINIUM_VAN_DER_WAALS_RADIUS
#define Q_ALUMINIUM_ATOMIC_VOLUME
#define Q_ALUMINIUM_CRYSTAL_STRUCTURE
#define Q_ALUMINIUM_MELTING_POINT
#define Q_ALUMINIUM_BOILING_POINT
#define Q_ALUMINIUM_FUSION_HEAT
#define Q_ALUMINIUM_VAPORIZATION_HEAT
#define Q_ALUMINIUM_SPECIFIC_HEAT
#define Q_ALUMINIUM_DENSITY
#define Q_ALUMINIUM_ELECTRICAL_CONDUCTIVITY
#define Q_ALUMINIUM_THERMAL_CONDUCTIVITY
#define Q_ALUMINIUM_ELECTRONEGATIVITY
#define Q_ALUMINIUM_YOUNG_MODULUS
#define Q_ALUMINIUM_BULK_MODULUS
#define Q_ALUMINIUM_SHEER_MODULUS
#define Q_ALUMINIUM_POISSON_RATIO

#pragma mark - 14 Si

#define Q_SILICON_SYMBOL				Si
#define Q_SILICON_ATOMIC_NUMBER				14
#define Q_SILICON_EMPIRICAL_ATOMIC_RADIUS
#define Q_SILICON_CALCULATED_ATOMIC_RADIUS
#define Q_SILICON_COBALENT_RADIUS
#define Q_SILICON_VAN_DER_WAALS_RADIUS
#define Q_SILICON_ATOMIC_VOLUME
#define Q_SILICON_CRYSTAL_STRUCTURE
#define Q_SILICON_MELTING_POINT
#define Q_SILICON_BOILING_POINT
#define Q_SILICON_FUSION_HEAT
#define Q_SILICON_VAPORIZATION_HEAT
#define Q_SILICON_SPECIFIC_HEAT
#define Q_SILICON_DENSITY
#define Q_SILICON_ELECTRICAL_CONDUCTIVITY
#define Q_SILICON_THERMAL_CONDUCTIVITY
#define Q_SILICON_ELECTRONEGATIVITY
#define Q_SILICON_YOUNG_MODULUS
#define Q_SILICON_BULK_MODULUS
#define Q_SILICON_SHEER_MODULUS
#define Q_SILICON_POISSON_RATIO

#pragma mark - 15 P

#define Q_PHOSPHORUS_SYMBOL				P
#define Q_PHOSPHORUS_ATOMIC_NUMBER			15
#define Q_PHOSPHORUS_EMPIRICAL_ATOMIC_RADIUS
#define Q_PHOSPHORUS_CALCULATED_ATOMIC_RADIUS
#define Q_PHOSPHORUS_COBALENT_RADIUS
#define Q_PHOSPHORUS_VAN_DER_WAALS_RADIUS
#define Q_PHOSPHORUS_ATOMIC_VOLUME
#define Q_PHOSPHORUS_CRYSTAL_STRUCTURE
#define Q_PHOSPHORUS_MELTING_POINT
#define Q_PHOSPHORUS_BOILING_POINT
#define Q_PHOSPHORUS_FUSION_HEAT
#define Q_PHOSPHORUS_VAPORIZATION_HEAT
#define Q_PHOSPHORUS_SPECIFIC_HEAT
#define Q_PHOSPHORUS_DENSITY
#define Q_PHOSPHORUS_ELECTRICAL_CONDUCTIVITY
#define Q_PHOSPHORUS_THERMAL_CONDUCTIVITY
#define Q_PHOSPHORUS_ELECTRONEGATIVITY
#define Q_PHOSPHORUS_YOUNG_MODULUS
#define Q_PHOSPHORUS_BULK_MODULUS
#define Q_PHOSPHORUS_SHEER_MODULUS
#define Q_PHOSPHORUS_POISSON_RATIO

#pragma mark - 16 S

#define Q_SULFUR_SYMBOL					S
#define Q_SULFUR_ATOMIC_NUMBER				16
#define Q_SULFUR_EMPIRICAL_ATOMIC_RADIUS
#define Q_SULFUR_CALCULATED_ATOMIC_RADIUS
#define Q_SULFUR_COBALENT_RADIUS
#define Q_SULFUR_VAN_DER_WAALS_RADIUS
#define Q_SULFUR_ATOMIC_VOLUME
#define Q_SULFUR_CRYSTAL_STRUCTURE
#define Q_SULFUR_MELTING_POINT
#define Q_SULFUR_BOILING_POINT
#define Q_SULFUR_FUSION_HEAT
#define Q_SULFUR_VAPORIZATION_HEAT
#define Q_SULFUR_SPECIFIC_HEAT
#define Q_SULFUR_DENSITY
#define Q_SULFUR_ELECTRICAL_CONDUCTIVITY
#define Q_SULFUR_THERMAL_CONDUCTIVITY
#define Q_SULFUR_ELECTRONEGATIVITY
#define Q_SULFUR_YOUNG_MODULUS
#define Q_SULFUR_BULK_MODULUS
#define Q_SULFUR_SHEER_MODULUS
#define Q_SULFUR_POISSON_RATIO

#pragma mark - 17 Cl

#define Q_CHLORINE_SYMBOL				Cl
#define Q_CHLORINE_ATOMIC_NUMBER			17
#define Q_CHLORINE_EMPIRICAL_ATOMIC_RADIUS
#define Q_CHLORINE_CALCULATED_ATOMIC_RADIUS
#define Q_CHLORINE_COBALENT_RADIUS
#define Q_CHLORINE_VAN_DER_WAALS_RADIUS
#define Q_CHLORINE_ATOMIC_VOLUME
#define Q_CHLORINE_CRYSTAL_STRUCTURE
#define Q_CHLORINE_MELTING_POINT
#define Q_CHLORINE_BOILING_POINT
#define Q_CHLORINE_FUSION_HEAT
#define Q_CHLORINE_VAPORIZATION_HEAT
#define Q_CHLORINE_SPECIFIC_HEAT
#define Q_CHLORINE_DENSITY
#define Q_CHLORINE_ELECTRICAL_CONDUCTIVITY
#define Q_CHLORINE_THERMAL_CONDUCTIVITY
#define Q_CHLORINE_ELECTRONEGATIVITY
#define Q_CHLORINE_YOUNG_MODULUS
#define Q_CHLORINE_BULK_MODULUS
#define Q_CHLORINE_SHEER_MODULUS
#define Q_CHLORINE_POISSON_RATIO

#pragma mark - 18 Ar

#define Q_ARGON_SYMBOL					Ar
#define Q_ARGON_ATOMIC_NUMBER				18
#define Q_ARGON_EMPIRICAL_ATOMIC_RADIUS
#define Q_ARGON_CALCULATED_ATOMIC_RADIUS
#define Q_ARGON_COBALENT_RADIUS
#define Q_ARGON_VAN_DER_WAALS_RADIUS
#define Q_ARGON_ATOMIC_VOLUME
#define Q_ARGON_CRYSTAL_STRUCTURE
#define Q_ARGON_MELTING_POINT
#define Q_ARGON_BOILING_POINT
#define Q_ARGON_FUSION_HEAT
#define Q_ARGON_VAPORIZATION_HEAT
#define Q_ARGON_SPECIFIC_HEAT
#define Q_ARGON_DENSITY
#define Q_ARGON_ELECTRICAL_CONDUCTIVITY
#define Q_ARGON_THERMAL_CONDUCTIVITY
#define Q_ARGON_ELECTRONEGATIVITY
#define Q_ARGON_YOUNG_MODULUS
#define Q_ARGON_BULK_MODULUS
#define Q_ARGON_SHEER_MODULUS
#define Q_ARGON_POISSON_RATIO

#pragma mark - 19 K

#define Q_POTASSIUM_SYMBOL				K
#define Q_POTASSIUM_ATOMIC_NUMBER			19
#define Q_POTASSIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_POTASSIUM_CALCULATED_ATOMIC_RADIUS
#define Q_POTASSIUM_COBALENT_RADIUS
#define Q_POTASSIUM_VAN_DER_WAALS_RADIUS
#define Q_POTASSIUM_ATOMIC_VOLUME
#define Q_POTASSIUM_CRYSTAL_STRUCTURE
#define Q_POTASSIUM_MELTING_POINT
#define Q_POTASSIUM_BOILING_POINT
#define Q_POTASSIUM_FUSION_HEAT
#define Q_POTASSIUM_VAPORIZATION_HEAT
#define Q_POTASSIUM_SPECIFIC_HEAT
#define Q_POTASSIUM_DENSITY
#define Q_POTASSIUM_ELECTRICAL_CONDUCTIVITY
#define Q_POTASSIUM_THERMAL_CONDUCTIVITY
#define Q_POTASSIUM_ELECTRONEGATIVITY
#define Q_POTASSIUM_YOUNG_MODULUS
#define Q_POTASSIUM_BULK_MODULUS
#define Q_POTASSIUM_SHEER_MODULUS
#define Q_POTASSIUM_POISSON_RATIO

#pragma mark - 20 Ca

#define Q_CALCIUM_SYMBOL				Ca
#define Q_CALCIUM_ATOMIC_NUMBER				20
#define Q_CALCIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_CALCIUM_CALCULATED_ATOMIC_RADIUS
#define Q_CALCIUM_COBALENT_RADIUS
#define Q_CALCIUM_VAN_DER_WAALS_RADIUS
#define Q_CALCIUM_ATOMIC_VOLUME
#define Q_CALCIUM_CRYSTAL_STRUCTURE
#define Q_CALCIUM_MELTING_POINT
#define Q_CALCIUM_BOILING_POINT
#define Q_CALCIUM_FUSION_HEAT
#define Q_CALCIUM_VAPORIZATION_HEAT
#define Q_CALCIUM_SPECIFIC_HEAT
#define Q_CALCIUM_DENSITY
#define Q_CALCIUM_ELECTRICAL_CONDUCTIVITY
#define Q_CALCIUM_THERMAL_CONDUCTIVITY
#define Q_CALCIUM_ELECTRONEGATIVITY
#define Q_CALCIUM_YOUNG_MODULUS
#define Q_CALCIUM_BULK_MODULUS
#define Q_CALCIUM_SHEER_MODULUS
#define Q_CALCIUM_POISSON_RATIO

#pragma mark - 21 Sc

#define Q_SCANDIUM_SYMBOL				Sc
#define Q_SCANDIUM_ATOMIC_NUMBER			21
#define Q_SCANDIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_SCANDIUM_CALCULATED_ATOMIC_RADIUS
#define Q_SCANDIUM_COBALENT_RADIUS
#define Q_SCANDIUM_VAN_DER_WAALS_RADIUS
#define Q_SCANDIUM_ATOMIC_VOLUME
#define Q_SCANDIUM_CRYSTAL_STRUCTURE
#define Q_SCANDIUM_MELTING_POINT
#define Q_SCANDIUM_BOILING_POINT
#define Q_SCANDIUM_FUSION_HEAT
#define Q_SCANDIUM_VAPORIZATION_HEAT
#define Q_SCANDIUM_SPECIFIC_HEAT
#define Q_SCANDIUM_DENSITY
#define Q_SCANDIUM_ELECTRICAL_CONDUCTIVITY
#define Q_SCANDIUM_THERMAL_CONDUCTIVITY
#define Q_SCANDIUM_ELECTRONEGATIVITY
#define Q_SCANDIUM_YOUNG_MODULUS
#define Q_SCANDIUM_BULK_MODULUS
#define Q_SCANDIUM_SHEER_MODULUS
#define Q_SCANDIUM_POISSON_RATIO

#pragma mark - 22 Ti

#define Q_TITANIUM_SYMBOL				Ti
#define Q_TITANIUM_ATOMIC_NUMBER			22
#define Q_TITANIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_TITANIUM_CALCULATED_ATOMIC_RADIUS
#define Q_TITANIUM_COBALENT_RADIUS
#define Q_TITANIUM_VAN_DER_WAALS_RADIUS
#define Q_TITANIUM_ATOMIC_VOLUME
#define Q_TITANIUM_CRYSTAL_STRUCTURE
#define Q_TITANIUM_MELTING_POINT
#define Q_TITANIUM_BOILING_POINT
#define Q_TITANIUM_FUSION_HEAT
#define Q_TITANIUM_VAPORIZATION_HEAT
#define Q_TITANIUM_SPECIFIC_HEAT
#define Q_TITANIUM_DENSITY
#define Q_TITANIUM_ELECTRICAL_CONDUCTIVITY
#define Q_TITANIUM_THERMAL_CONDUCTIVITY
#define Q_TITANIUM_ELECTRONEGATIVITY
#define Q_TITANIUM_YOUNG_MODULUS
#define Q_TITANIUM_BULK_MODULUS
#define Q_TITANIUM_SHEER_MODULUS
#define Q_TITANIUM_POISSON_RATIO

#pragma mark - 23 V

#define Q_VANADIUM_SYMBOL				V
#define Q_VANADIUM_ATOMIC_NUMBER			23
#define Q_VANADIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_VANADIUM_CALCULATED_ATOMIC_RADIUS
#define Q_VANADIUM_COBALENT_RADIUS
#define Q_VANADIUM_VAN_DER_WAALS_RADIUS
#define Q_VANADIUM_ATOMIC_VOLUME
#define Q_VANADIUM_CRYSTAL_STRUCTURE
#define Q_VANADIUM_MELTING_POINT
#define Q_VANADIUM_BOILING_POINT
#define Q_VANADIUM_FUSION_HEAT
#define Q_VANADIUM_VAPORIZATION_HEAT
#define Q_VANADIUM_SPECIFIC_HEAT
#define Q_VANADIUM_DENSITY
#define Q_VANADIUM_ELECTRICAL_CONDUCTIVITY
#define Q_VANADIUM_THERMAL_CONDUCTIVITY
#define Q_VANADIUM_ELECTRONEGATIVITY
#define Q_VANADIUM_YOUNG_MODULUS
#define Q_VANADIUM_BULK_MODULUS
#define Q_VANADIUM_SHEER_MODULUS
#define Q_VANADIUM_POISSON_RATIO

#pragma mark - 24 Cr

#define Q_CHROMIUM_SYMBOL				Cr
#define Q_CHROMIUM_ATOMIC_NUMBER			24
#define Q_CHROMIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_CHROMIUM_CALCULATED_ATOMIC_RADIUS
#define Q_CHROMIUM_COBALENT_RADIUS
#define Q_CHROMIUM_VAN_DER_WAALS_RADIUS
#define Q_CHROMIUM_ATOMIC_VOLUME
#define Q_CHROMIUM_CRYSTAL_STRUCTURE
#define Q_CHROMIUM_MELTING_POINT
#define Q_CHROMIUM_BOILING_POINT
#define Q_CHROMIUM_FUSION_HEAT
#define Q_CHROMIUM_VAPORIZATION_HEAT
#define Q_CHROMIUM_SPECIFIC_HEAT
#define Q_CHROMIUM_DENSITY
#define Q_CHROMIUM_ELECTRICAL_CONDUCTIVITY
#define Q_CHROMIUM_THERMAL_CONDUCTIVITY
#define Q_CHROMIUM_ELECTRONEGATIVITY
#define Q_CHROMIUM_YOUNG_MODULUS
#define Q_CHROMIUM_BULK_MODULUS
#define Q_CHROMIUM_SHEER_MODULUS
#define Q_CHROMIUM_POISSON_RATIO

#pragma mark - 25 Mn

#define Q_MANGANESE_SYMBOL				Mn
#define Q_MANGANESE_ATOMIC_NUMBER			25
#define Q_MANGANESE_EMPIRICAL_ATOMIC_RADIUS
#define Q_MANGANESE_CALCULATED_ATOMIC_RADIUS
#define Q_MANGANESE_COBALENT_RADIUS
#define Q_MANGANESE_VAN_DER_WAALS_RADIUS
#define Q_MANGANESE_ATOMIC_VOLUME
#define Q_MANGANESE_CRYSTAL_STRUCTURE
#define Q_MANGANESE_MELTING_POINT
#define Q_MANGANESE_BOILING_POINT
#define Q_MANGANESE_FUSION_HEAT
#define Q_MANGANESE_VAPORIZATION_HEAT
#define Q_MANGANESE_SPECIFIC_HEAT
#define Q_MANGANESE_DENSITY
#define Q_MANGANESE_ELECTRICAL_CONDUCTIVITY
#define Q_MANGANESE_THERMAL_CONDUCTIVITY
#define Q_MANGANESE_ELECTRONEGATIVITY
#define Q_MANGANESE_YOUNG_MODULUS
#define Q_MANGANESE_BULK_MODULUS
#define Q_MANGANESE_SHEER_MODULUS
#define Q_MANGANESE_POISSON_RATIO

#pragma mark - 26 Fe

#define Q_IRON_SYMBOL					Fe
#define Q_IRON_ATOMIC_NUMBER				26
#define Q_IRON_EMPIRICAL_ATOMIC_RADIUS
#define Q_IRON_CALCULATED_ATOMIC_RADIUS
#define Q_IRON_COBALENT_RADIUS
#define Q_IRON_VAN_DER_WAALS_RADIUS
#define Q_IRON_ATOMIC_VOLUME
#define Q_IRON_CRYSTAL_STRUCTURE
#define Q_IRON_MELTING_POINT
#define Q_IRON_BOILING_POINT
#define Q_IRON_FUSION_HEAT
#define Q_IRON_VAPORIZATION_HEAT
#define Q_IRON_SPECIFIC_HEAT
#define Q_IRON_DENSITY
#define Q_IRON_ELECTRICAL_CONDUCTIVITY
#define Q_IRON_THERMAL_CONDUCTIVITY
#define Q_IRON_ELECTRONEGATIVITY
#define Q_IRON_YOUNG_MODULUS
#define Q_IRON_BULK_MODULUS
#define Q_IRON_SHEER_MODULUS
#define Q_IRON_POISSON_RATIO

#pragma mark - 27 Co

#define Q_COBALT_SYMBOL					Co
#define Q_COBALT_ATOMIC_NUMBER				27
#define Q_COBALT_EMPIRICAL_ATOMIC_RADIUS
#define Q_COBALT_CALCULATED_ATOMIC_RADIUS
#define Q_COBALT_COBALENT_RADIUS
#define Q_COBALT_VAN_DER_WAALS_RADIUS
#define Q_COBALT_ATOMIC_VOLUME
#define Q_COBALT_CRYSTAL_STRUCTURE
#define Q_COBALT_MELTING_POINT
#define Q_COBALT_BOILING_POINT
#define Q_COBALT_FUSION_HEAT
#define Q_COBALT_VAPORIZATION_HEAT
#define Q_COBALT_SPECIFIC_HEAT
#define Q_COBALT_DENSITY
#define Q_COBALT_ELECTRICAL_CONDUCTIVITY
#define Q_COBALT_THERMAL_CONDUCTIVITY
#define Q_COBALT_ELECTRONEGATIVITY
#define Q_COBALT_YOUNG_MODULUS
#define Q_COBALT_BULK_MODULUS
#define Q_COBALT_SHEER_MODULUS
#define Q_COBALT_POISSON_RATIO

#pragma mark - 28 Ni

#define Q_NICKEL_SYMBOL					Ni
#define Q_NICKEL_ATOMIC_NUMBER				28
#define Q_NICKEL_EMPIRICAL_ATOMIC_RADIUS
#define Q_NICKEL_CALCULATED_ATOMIC_RADIUS
#define Q_NICKEL_COBALENT_RADIUS
#define Q_NICKEL_VAN_DER_WAALS_RADIUS
#define Q_NICKEL_ATOMIC_VOLUME
#define Q_NICKEL_CRYSTAL_STRUCTURE
#define Q_NICKEL_MELTING_POINT
#define Q_NICKEL_BOILING_POINT
#define Q_NICKEL_FUSION_HEAT
#define Q_NICKEL_VAPORIZATION_HEAT
#define Q_NICKEL_SPECIFIC_HEAT
#define Q_NICKEL_DENSITY
#define Q_NICKEL_ELECTRICAL_CONDUCTIVITY
#define Q_NICKEL_THERMAL_CONDUCTIVITY
#define Q_NICKEL_ELECTRONEGATIVITY
#define Q_NICKEL_YOUNG_MODULUS
#define Q_NICKEL_BULK_MODULUS
#define Q_NICKEL_SHEER_MODULUS
#define Q_NICKEL_POISSON_RATIO

#pragma mark - 29 Cu

#define Q_COPPER_SYMBOL					Cu
#define Q_COPPER_ATOMIC_NUMBER				29
#define Q_COPPER_EMPIRICAL_ATOMIC_RADIUS
#define Q_COPPER_CALCULATED_ATOMIC_RADIUS
#define Q_COPPER_COBALENT_RADIUS
#define Q_COPPER_VAN_DER_WAALS_RADIUS
#define Q_COPPER_ATOMIC_VOLUME
#define Q_COPPER_CRYSTAL_STRUCTURE
#define Q_COPPER_MELTING_POINT
#define Q_COPPER_BOILING_POINT
#define Q_COPPER_FUSION_HEAT
#define Q_COPPER_VAPORIZATION_HEAT
#define Q_COPPER_SPECIFIC_HEAT
#define Q_COPPER_DENSITY
#define Q_COPPER_ELECTRICAL_CONDUCTIVITY
#define Q_COPPER_THERMAL_CONDUCTIVITY
#define Q_COPPER_ELECTRONEGATIVITY
#define Q_COPPER_YOUNG_MODULUS
#define Q_COPPER_BULK_MODULUS
#define Q_COPPER_SHEER_MODULUS
#define Q_COPPER_POISSON_RATIO

#pragma mark - 30 Zn

#define Q_ZINC_SYMBOL					Zn
#define Q_ZINC_ATOMIC_NUMBER				30
#define Q_ZINC_EMPIRICAL_ATOMIC_RADIUS
#define Q_ZINC_CALCULATED_ATOMIC_RADIUS
#define Q_ZINC_COBALENT_RADIUS
#define Q_ZINC_VAN_DER_WAALS_RADIUS
#define Q_ZINC_ATOMIC_VOLUME
#define Q_ZINC_CRYSTAL_STRUCTURE
#define Q_ZINC_MELTING_POINT
#define Q_ZINC_BOILING_POINT
#define Q_ZINC_FUSION_HEAT
#define Q_ZINC_VAPORIZATION_HEAT
#define Q_ZINC_SPECIFIC_HEAT
#define Q_ZINC_DENSITY
#define Q_ZINC_ELECTRICAL_CONDUCTIVITY
#define Q_ZINC_THERMAL_CONDUCTIVITY
#define Q_ZINC_ELECTRONEGATIVITY
#define Q_ZINC_YOUNG_MODULUS
#define Q_ZINC_BULK_MODULUS
#define Q_ZINC_SHEER_MODULUS
#define Q_ZINC_POISSON_RATIO

#pragma mark - 31 Ga

#define Q_GALLIUM_SYMBOL				Ga
#define Q_GALLIUM_ATOMIC_NUMBER				31
#define Q_GALLIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_GALLIUM_CALCULATED_ATOMIC_RADIUS
#define Q_GALLIUM_COBALENT_RADIUS
#define Q_GALLIUM_VAN_DER_WAALS_RADIUS
#define Q_GALLIUM_ATOMIC_VOLUME
#define Q_GALLIUM_CRYSTAL_STRUCTURE
#define Q_GALLIUM_MELTING_POINT
#define Q_GALLIUM_BOILING_POINT
#define Q_GALLIUM_FUSION_HEAT
#define Q_GALLIUM_VAPORIZATION_HEAT
#define Q_GALLIUM_SPECIFIC_HEAT
#define Q_GALLIUM_DENSITY
#define Q_GALLIUM_ELECTRICAL_CONDUCTIVITY
#define Q_GALLIUM_THERMAL_CONDUCTIVITY
#define Q_GALLIUM_ELECTRONEGATIVITY
#define Q_GALLIUM_YOUNG_MODULUS
#define Q_GALLIUM_BULK_MODULUS
#define Q_GALLIUM_SHEER_MODULUS
#define Q_GALLIUM_POISSON_RATIO

#pragma mark - 32 Ge

#define Q_GERMANIUM_SYMBOL				Ge
#define Q_GERMANIUM_ATOMIC_NUMBER			32
#define Q_GERMANIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_GERMANIUM_CALCULATED_ATOMIC_RADIUS
#define Q_GERMANIUM_COBALENT_RADIUS
#define Q_GERMANIUM_VAN_DER_WAALS_RADIUS
#define Q_GERMANIUM_ATOMIC_VOLUME
#define Q_GERMANIUM_CRYSTAL_STRUCTURE
#define Q_GERMANIUM_MELTING_POINT
#define Q_GERMANIUM_BOILING_POINT
#define Q_GERMANIUM_FUSION_HEAT
#define Q_GERMANIUM_VAPORIZATION_HEAT
#define Q_GERMANIUM_SPECIFIC_HEAT
#define Q_GERMANIUM_DENSITY
#define Q_GERMANIUM_ELECTRICAL_CONDUCTIVITY
#define Q_GERMANIUM_THERMAL_CONDUCTIVITY
#define Q_GERMANIUM_ELECTRONEGATIVITY
#define Q_GERMANIUM_YOUNG_MODULUS
#define Q_GERMANIUM_BULK_MODULUS
#define Q_GERMANIUM_SHEER_MODULUS
#define Q_GERMANIUM_POISSON_RATIO

#pragma mark - 33 As

#define Q_ARSENIC_SYMBOL				As
#define Q_ARSENIC_ATOMIC_NUMBER				33
#define Q_ARSENIC_EMPIRICAL_ATOMIC_RADIUS
#define Q_ARSENIC_CALCULATED_ATOMIC_RADIUS
#define Q_ARSENIC_COBALENT_RADIUS
#define Q_ARSENIC_VAN_DER_WAALS_RADIUS
#define Q_ARSENIC_ATOMIC_VOLUME
#define Q_ARSENIC_CRYSTAL_STRUCTURE
#define Q_ARSENIC_MELTING_POINT
#define Q_ARSENIC_BOILING_POINT
#define Q_ARSENIC_FUSION_HEAT
#define Q_ARSENIC_VAPORIZATION_HEAT
#define Q_ARSENIC_SPECIFIC_HEAT
#define Q_ARSENIC_DENSITY
#define Q_ARSENIC_ELECTRICAL_CONDUCTIVITY
#define Q_ARSENIC_THERMAL_CONDUCTIVITY
#define Q_ARSENIC_ELECTRONEGATIVITY
#define Q_ARSENIC_YOUNG_MODULUS
#define Q_ARSENIC_BULK_MODULUS
#define Q_ARSENIC_SHEER_MODULUS
#define Q_ARSENIC_POISSON_RATIO

#pragma mark - 34 Se

#define Q_SELENIUM_SYMBOL				Se
#define Q_SELENIUM_ATOMIC_NUMBER			34
#define Q_SELENIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_SELENIUM_CALCULATED_ATOMIC_RADIUS
#define Q_SELENIUM_COBALENT_RADIUS
#define Q_SELENIUM_VAN_DER_WAALS_RADIUS
#define Q_SELENIUM_ATOMIC_VOLUME
#define Q_SELENIUM_CRYSTAL_STRUCTURE
#define Q_SELENIUM_MELTING_POINT
#define Q_SELENIUM_BOILING_POINT
#define Q_SELENIUM_FUSION_HEAT
#define Q_SELENIUM_VAPORIZATION_HEAT
#define Q_SELENIUM_SPECIFIC_HEAT
#define Q_SELENIUM_DENSITY
#define Q_SELENIUM_ELECTRICAL_CONDUCTIVITY
#define Q_SELENIUM_THERMAL_CONDUCTIVITY
#define Q_SELENIUM_ELECTRONEGATIVITY
#define Q_SELENIUM_YOUNG_MODULUS
#define Q_SELENIUM_BULK_MODULUS
#define Q_SELENIUM_SHEER_MODULUS
#define Q_SELENIUM_POISSON_RATIO

#pragma mark - 35 Br

#define Q_BROMINE_SYMBOL				Br
#define Q_BROMINE_ATOMIC_NUMBER				35
#define Q_BROMINE_EMPIRICAL_ATOMIC_RADIUS
#define Q_BROMINE_CALCULATED_ATOMIC_RADIUS
#define Q_BROMINE_COBALENT_RADIUS
#define Q_BROMINE_VAN_DER_WAALS_RADIUS
#define Q_BROMINE_ATOMIC_VOLUME
#define Q_BROMINE_CRYSTAL_STRUCTURE
#define Q_BROMINE_MELTING_POINT
#define Q_BROMINE_BOILING_POINT
#define Q_BROMINE_FUSION_HEAT
#define Q_BROMINE_VAPORIZATION_HEAT
#define Q_BROMINE_SPECIFIC_HEAT
#define Q_BROMINE_DENSITY
#define Q_BROMINE_ELECTRICAL_CONDUCTIVITY
#define Q_BROMINE_THERMAL_CONDUCTIVITY
#define Q_BROMINE_ELECTRONEGATIVITY
#define Q_BROMINE_YOUNG_MODULUS
#define Q_BROMINE_BULK_MODULUS
#define Q_BROMINE_SHEER_MODULUS
#define Q_BROMINE_POISSON_RATIO

#pragma mark - 36 Kr

#define Q_KRYPTON_SYMBOL				Kr
#define Q_KRYPTON_ATOMIC_NUMBER				36
#define Q_KRYPTON_EMPIRICAL_ATOMIC_RADIUS
#define Q_KRYPTON_CALCULATED_ATOMIC_RADIUS
#define Q_KRYPTON_COBALENT_RADIUS
#define Q_KRYPTON_VAN_DER_WAALS_RADIUS
#define Q_KRYPTON_ATOMIC_VOLUME
#define Q_KRYPTON_CRYSTAL_STRUCTURE
#define Q_KRYPTON_MELTING_POINT
#define Q_KRYPTON_BOILING_POINT
#define Q_KRYPTON_FUSION_HEAT
#define Q_KRYPTON_VAPORIZATION_HEAT
#define Q_KRYPTON_SPECIFIC_HEAT
#define Q_KRYPTON_DENSITY
#define Q_KRYPTON_ELECTRICAL_CONDUCTIVITY
#define Q_KRYPTON_THERMAL_CONDUCTIVITY
#define Q_KRYPTON_ELECTRONEGATIVITY
#define Q_KRYPTON_YOUNG_MODULUS
#define Q_KRYPTON_BULK_MODULUS
#define Q_KRYPTON_SHEER_MODULUS
#define Q_KRYPTON_POISSON_RATIO

#pragma mark - 37 Rb

#define Q_RUBIDIUM_SYMBOL				Rb
#define Q_RUBIDIUM_ATOMIC_NUMBER			37
#define Q_RUBIDIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_RUBIDIUM_CALCULATED_ATOMIC_RADIUS
#define Q_RUBIDIUM_COBALENT_RADIUS
#define Q_RUBIDIUM_VAN_DER_WAALS_RADIUS
#define Q_RUBIDIUM_ATOMIC_VOLUME
#define Q_RUBIDIUM_CRYSTAL_STRUCTURE
#define Q_RUBIDIUM_MELTING_POINT
#define Q_RUBIDIUM_BOILING_POINT
#define Q_RUBIDIUM_FUSION_HEAT
#define Q_RUBIDIUM_VAPORIZATION_HEAT
#define Q_RUBIDIUM_SPECIFIC_HEAT
#define Q_RUBIDIUM_DENSITY
#define Q_RUBIDIUM_ELECTRICAL_CONDUCTIVITY
#define Q_RUBIDIUM_THERMAL_CONDUCTIVITY
#define Q_RUBIDIUM_ELECTRONEGATIVITY
#define Q_RUBIDIUM_YOUNG_MODULUS
#define Q_RUBIDIUM_BULK_MODULUS
#define Q_RUBIDIUM_SHEER_MODULUS
#define Q_RUBIDIUM_POISSON_RATIO

#pragma mark - 38 Sr

#define Q_STRONTIUM_SYMBOL				Sr
#define Q_STRONTIUM_ATOMIC_NUMBER			38
#define Q_STRONTIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_STRONTIUM_CALCULATED_ATOMIC_RADIUS
#define Q_STRONTIUM_COBALENT_RADIUS
#define Q_STRONTIUM_VAN_DER_WAALS_RADIUS
#define Q_STRONTIUM_ATOMIC_VOLUME
#define Q_STRONTIUM_CRYSTAL_STRUCTURE
#define Q_STRONTIUM_MELTING_POINT
#define Q_STRONTIUM_BOILING_POINT
#define Q_STRONTIUM_FUSION_HEAT
#define Q_STRONTIUM_VAPORIZATION_HEAT
#define Q_STRONTIUM_SPECIFIC_HEAT
#define Q_STRONTIUM_DENSITY
#define Q_STRONTIUM_ELECTRICAL_CONDUCTIVITY
#define Q_STRONTIUM_THERMAL_CONDUCTIVITY
#define Q_STRONTIUM_ELECTRONEGATIVITY
#define Q_STRONTIUM_YOUNG_MODULUS
#define Q_STRONTIUM_BULK_MODULUS
#define Q_STRONTIUM_SHEER_MODULUS
#define Q_STRONTIUM_POISSON_RATIO

#pragma mark - 39 Y

#define Q_YTTRIUM_SYMBOL				Y
#define Q_YTTRIUM_ATOMIC_NUMBER				39
#define Q_YTTRIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_YTTRIUM_CALCULATED_ATOMIC_RADIUS
#define Q_YTTRIUM_COBALENT_RADIUS
#define Q_YTTRIUM_VAN_DER_WAALS_RADIUS
#define Q_YTTRIUM_ATOMIC_VOLUME
#define Q_YTTRIUM_CRYSTAL_STRUCTURE
#define Q_YTTRIUM_MELTING_POINT
#define Q_YTTRIUM_BOILING_POINT
#define Q_YTTRIUM_FUSION_HEAT
#define Q_YTTRIUM_VAPORIZATION_HEAT
#define Q_YTTRIUM_SPECIFIC_HEAT
#define Q_YTTRIUM_DENSITY
#define Q_YTTRIUM_ELECTRICAL_CONDUCTIVITY
#define Q_YTTRIUM_THERMAL_CONDUCTIVITY
#define Q_YTTRIUM_ELECTRONEGATIVITY
#define Q_YTTRIUM_YOUNG_MODULUS
#define Q_YTTRIUM_BULK_MODULUS
#define Q_YTTRIUM_SHEER_MODULUS
#define Q_YTTRIUM_POISSON_RATIO

#pragma mark - 40 Zr

#define Q_ZIRCONIUM_SYMBOL				Zr
#define Q_ZIRCONIUM_ATOMIC_NUMBER			40
#define Q_ZIRCONIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_ZIRCONIUM_CALCULATED_ATOMIC_RADIUS
#define Q_ZIRCONIUM_COBALENT_RADIUS
#define Q_ZIRCONIUM_VAN_DER_WAALS_RADIUS
#define Q_ZIRCONIUM_ATOMIC_VOLUME
#define Q_ZIRCONIUM_CRYSTAL_STRUCTURE
#define Q_ZIRCONIUM_MELTING_POINT
#define Q_ZIRCONIUM_BOILING_POINT
#define Q_ZIRCONIUM_FUSION_HEAT
#define Q_ZIRCONIUM_VAPORIZATION_HEAT
#define Q_ZIRCONIUM_SPECIFIC_HEAT
#define Q_ZIRCONIUM_DENSITY
#define Q_ZIRCONIUM_ELECTRICAL_CONDUCTIVITY
#define Q_ZIRCONIUM_THERMAL_CONDUCTIVITY
#define Q_ZIRCONIUM_ELECTRONEGATIVITY
#define Q_ZIRCONIUM_YOUNG_MODULUS
#define Q_ZIRCONIUM_BULK_MODULUS
#define Q_ZIRCONIUM_SHEER_MODULUS
#define Q_ZIRCONIUM_POISSON_RATIO

#pragma mark - 41 Nb

#define Q_NIOBIUM_SYMBOL				Nb
#define Q_NIOBIUM_ATOMIC_NUMBER				41
#define Q_NIOBIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_NIOBIUM_CALCULATED_ATOMIC_RADIUS
#define Q_NIOBIUM_COBALENT_RADIUS
#define Q_NIOBIUM_VAN_DER_WAALS_RADIUS
#define Q_NIOBIUM_ATOMIC_VOLUME
#define Q_NIOBIUM_CRYSTAL_STRUCTURE
#define Q_NIOBIUM_MELTING_POINT
#define Q_NIOBIUM_BOILING_POINT
#define Q_NIOBIUM_FUSION_HEAT
#define Q_NIOBIUM_VAPORIZATION_HEAT
#define Q_NIOBIUM_SPECIFIC_HEAT
#define Q_NIOBIUM_DENSITY
#define Q_NIOBIUM_ELECTRICAL_CONDUCTIVITY
#define Q_NIOBIUM_THERMAL_CONDUCTIVITY
#define Q_NIOBIUM_ELECTRONEGATIVITY
#define Q_NIOBIUM_YOUNG_MODULUS
#define Q_NIOBIUM_BULK_MODULUS
#define Q_NIOBIUM_SHEER_MODULUS
#define Q_NIOBIUM_POISSON_RATIO

#pragma mark - 42 Mo

#define Q_MOLYBDENUM_SYMBOL				Mo
#define Q_MOLYBDENUM_ATOMIC_NUMBER			42
#define Q_MOLYBDENUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_MOLYBDENUM_CALCULATED_ATOMIC_RADIUS
#define Q_MOLYBDENUM_COBALENT_RADIUS
#define Q_MOLYBDENUM_VAN_DER_WAALS_RADIUS
#define Q_MOLYBDENUM_ATOMIC_VOLUME
#define Q_MOLYBDENUM_CRYSTAL_STRUCTURE
#define Q_MOLYBDENUM_MELTING_POINT
#define Q_MOLYBDENUM_BOILING_POINT
#define Q_MOLYBDENUM_FUSION_HEAT
#define Q_MOLYBDENUM_VAPORIZATION_HEAT
#define Q_MOLYBDENUM_SPECIFIC_HEAT
#define Q_MOLYBDENUM_DENSITY
#define Q_MOLYBDENUM_ELECTRICAL_CONDUCTIVITY
#define Q_MOLYBDENUM_THERMAL_CONDUCTIVITY
#define Q_MOLYBDENUM_ELECTRONEGATIVITY
#define Q_MOLYBDENUM_YOUNG_MODULUS
#define Q_MOLYBDENUM_BULK_MODULUS
#define Q_MOLYBDENUM_SHEER_MODULUS
#define Q_MOLYBDENUM_POISSON_RATIO

#pragma mark - 43 Tc

#define Q_TECHNETIUM_SYMBOL				Tc
#define Q_TECHNETIUM_ATOMIC_NUMBER			43
#define Q_TECHNETIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_TECHNETIUM_CALCULATED_ATOMIC_RADIUS
#define Q_TECHNETIUM_COBALENT_RADIUS
#define Q_TECHNETIUM_VAN_DER_WAALS_RADIUS
#define Q_TECHNETIUM_ATOMIC_VOLUME
#define Q_TECHNETIUM_CRYSTAL_STRUCTURE
#define Q_TECHNETIUM_MELTING_POINT
#define Q_TECHNETIUM_BOILING_POINT
#define Q_TECHNETIUM_FUSION_HEAT
#define Q_TECHNETIUM_VAPORIZATION_HEAT
#define Q_TECHNETIUM_SPECIFIC_HEAT
#define Q_TECHNETIUM_DENSITY
#define Q_TECHNETIUM_ELECTRICAL_CONDUCTIVITY
#define Q_TECHNETIUM_THERMAL_CONDUCTIVITY
#define Q_TECHNETIUM_ELECTRONEGATIVITY
#define Q_TECHNETIUM_YOUNG_MODULUS
#define Q_TECHNETIUM_BULK_MODULUS
#define Q_TECHNETIUM_SHEER_MODULUS
#define Q_TECHNETIUM_POISSON_RATIO

#pragma mark - 44 Ru

#define Q_RUTHENIUM_SYMBOL				Ru
#define Q_RUTHENIUM_ATOMIC_NUMBER			44
#define Q_RUTHENIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_RUTHENIUM_CALCULATED_ATOMIC_RADIUS
#define Q_RUTHENIUM_COBALENT_RADIUS
#define Q_RUTHENIUM_VAN_DER_WAALS_RADIUS
#define Q_RUTHENIUM_ATOMIC_VOLUME
#define Q_RUTHENIUM_CRYSTAL_STRUCTURE
#define Q_RUTHENIUM_MELTING_POINT
#define Q_RUTHENIUM_BOILING_POINT
#define Q_RUTHENIUM_FUSION_HEAT
#define Q_RUTHENIUM_VAPORIZATION_HEAT
#define Q_RUTHENIUM_SPECIFIC_HEAT
#define Q_RUTHENIUM_DENSITY
#define Q_RUTHENIUM_ELECTRICAL_CONDUCTIVITY
#define Q_RUTHENIUM_THERMAL_CONDUCTIVITY
#define Q_RUTHENIUM_ELECTRONEGATIVITY
#define Q_RUTHENIUM_YOUNG_MODULUS
#define Q_RUTHENIUM_BULK_MODULUS
#define Q_RUTHENIUM_SHEER_MODULUS
#define Q_RUTHENIUM_POISSON_RATIO

#pragma mark - 45 Rh

#define Q_RHODIUM_SYMBOL				Rh
#define Q_RHODIUM_ATOMIC_NUMBER				45
#define Q_RHODIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_RHODIUM_CALCULATED_ATOMIC_RADIUS
#define Q_RHODIUM_COBALENT_RADIUS
#define Q_RHODIUM_VAN_DER_WAALS_RADIUS
#define Q_RHODIUM_ATOMIC_VOLUME
#define Q_RHODIUM_CRYSTAL_STRUCTURE
#define Q_RHODIUM_MELTING_POINT
#define Q_RHODIUM_BOILING_POINT
#define Q_RHODIUM_FUSION_HEAT
#define Q_RHODIUM_VAPORIZATION_HEAT
#define Q_RHODIUM_SPECIFIC_HEAT
#define Q_RHODIUM_DENSITY
#define Q_RHODIUM_ELECTRICAL_CONDUCTIVITY
#define Q_RHODIUM_THERMAL_CONDUCTIVITY
#define Q_RHODIUM_ELECTRONEGATIVITY
#define Q_RHODIUM_YOUNG_MODULUS
#define Q_RHODIUM_BULK_MODULUS
#define Q_RHODIUM_SHEER_MODULUS
#define Q_RHODIUM_POISSON_RATIO

#pragma mark - 46 Pd

#define Q_PALLADIUM_SYMBOL				Pd
#define Q_PALLADIUM_ATOMIC_NUMBER			46
#define Q_PALLADIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_PALLADIUM_CALCULATED_ATOMIC_RADIUS
#define Q_PALLADIUM_COBALENT_RADIUS
#define Q_PALLADIUM_VAN_DER_WAALS_RADIUS
#define Q_PALLADIUM_ATOMIC_VOLUME
#define Q_PALLADIUM_CRYSTAL_STRUCTURE
#define Q_PALLADIUM_MELTING_POINT
#define Q_PALLADIUM_BOILING_POINT
#define Q_PALLADIUM_FUSION_HEAT
#define Q_PALLADIUM_VAPORIZATION_HEAT
#define Q_PALLADIUM_SPECIFIC_HEAT
#define Q_PALLADIUM_DENSITY
#define Q_PALLADIUM_ELECTRICAL_CONDUCTIVITY
#define Q_PALLADIUM_THERMAL_CONDUCTIVITY
#define Q_PALLADIUM_ELECTRONEGATIVITY
#define Q_PALLADIUM_YOUNG_MODULUS
#define Q_PALLADIUM_BULK_MODULUS
#define Q_PALLADIUM_SHEER_MODULUS
#define Q_PALLADIUM_POISSON_RATIO

#pragma mark - 47 Ag

#define Q_SILVER_SYMBOL					Ag
#define Q_SILVER_ATOMIC_NUMBER				47
#define Q_SILVER_EMPIRICAL_ATOMIC_RADIUS
#define Q_SILVER_CALCULATED_ATOMIC_RADIUS
#define Q_SILVER_COBALENT_RADIUS
#define Q_SILVER_VAN_DER_WAALS_RADIUS
#define Q_SILVER_ATOMIC_VOLUME
#define Q_SILVER_CRYSTAL_STRUCTURE
#define Q_SILVER_MELTING_POINT
#define Q_SILVER_BOILING_POINT
#define Q_SILVER_FUSION_HEAT
#define Q_SILVER_VAPORIZATION_HEAT
#define Q_SILVER_SPECIFIC_HEAT
#define Q_SILVER_DENSITY
#define Q_SILVER_ELECTRICAL_CONDUCTIVITY
#define Q_SILVER_THERMAL_CONDUCTIVITY
#define Q_SILVER_ELECTRONEGATIVITY
#define Q_SILVER_YOUNG_MODULUS
#define Q_SILVER_BULK_MODULUS
#define Q_SILVER_SHEER_MODULUS
#define Q_SILVER_POISSON_RATIO

#pragma mark - 48 Cd

#define Q_CADMIUM_SYMBOL				Cd
#define Q_CADMIUM_ATOMIC_NUMBER				48
#define Q_CADMIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_CADMIUM_CALCULATED_ATOMIC_RADIUS
#define Q_CADMIUM_COBALENT_RADIUS
#define Q_CADMIUM_VAN_DER_WAALS_RADIUS
#define Q_CADMIUM_ATOMIC_VOLUME
#define Q_CADMIUM_CRYSTAL_STRUCTURE
#define Q_CADMIUM_MELTING_POINT
#define Q_CADMIUM_BOILING_POINT
#define Q_CADMIUM_FUSION_HEAT
#define Q_CADMIUM_VAPORIZATION_HEAT
#define Q_CADMIUM_SPECIFIC_HEAT
#define Q_CADMIUM_DENSITY
#define Q_CADMIUM_ELECTRICAL_CONDUCTIVITY
#define Q_CADMIUM_THERMAL_CONDUCTIVITY
#define Q_CADMIUM_ELECTRONEGATIVITY
#define Q_CADMIUM_YOUNG_MODULUS
#define Q_CADMIUM_BULK_MODULUS
#define Q_CADMIUM_SHEER_MODULUS
#define Q_CADMIUM_POISSON_RATIO

#pragma mark - 49 In

#define Q_INDIUM_SYMBOL					In
#define Q_INDIUM_ATOMIC_NUMBER				49
#define Q_INDIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_INDIUM_CALCULATED_ATOMIC_RADIUS
#define Q_INDIUM_COBALENT_RADIUS
#define Q_INDIUM_VAN_DER_WAALS_RADIUS
#define Q_INDIUM_ATOMIC_VOLUME
#define Q_INDIUM_CRYSTAL_STRUCTURE
#define Q_INDIUM_MELTING_POINT
#define Q_INDIUM_BOILING_POINT
#define Q_INDIUM_FUSION_HEAT
#define Q_INDIUM_VAPORIZATION_HEAT
#define Q_INDIUM_SPECIFIC_HEAT
#define Q_INDIUM_DENSITY
#define Q_INDIUM_ELECTRICAL_CONDUCTIVITY
#define Q_INDIUM_THERMAL_CONDUCTIVITY
#define Q_INDIUM_ELECTRONEGATIVITY
#define Q_INDIUM_YOUNG_MODULUS
#define Q_INDIUM_BULK_MODULUS
#define Q_INDIUM_SHEER_MODULUS
#define Q_INDIUM_POISSON_RATIO

#pragma mark - 50 Sn

#define Q_TIN_SYMBOL					Sn
#define Q_TIN_ATOMIC_NUMBER				50
#define Q_TIN_EMPIRICAL_ATOMIC_RADIUS
#define Q_TIN_CALCULATED_ATOMIC_RADIUS
#define Q_TIN_COBALENT_RADIUS
#define Q_TIN_VAN_DER_WAALS_RADIUS
#define Q_TIN_ATOMIC_VOLUME
#define Q_TIN_CRYSTAL_STRUCTURE
#define Q_TIN_MELTING_POINT
#define Q_TIN_BOILING_POINT
#define Q_TIN_FUSION_HEAT
#define Q_TIN_VAPORIZATION_HEAT
#define Q_TIN_SPECIFIC_HEAT
#define Q_TIN_DENSITY
#define Q_TIN_ELECTRICAL_CONDUCTIVITY
#define Q_TIN_THERMAL_CONDUCTIVITY
#define Q_TIN_ELECTRONEGATIVITY
#define Q_TIN_YOUNG_MODULUS
#define Q_TIN_BULK_MODULUS
#define Q_TIN_SHEER_MODULUS
#define Q_TIN_POISSON_RATIO

#pragma mark - 51 Sb

#define Q_ANTIMONY_SYMBOL				Sb
#define Q_ANTIMONY_ATOMIC_NUMBER			51
#define Q_ANTIMONY_EMPIRICAL_ATOMIC_RADIUS
#define Q_ANTIMONY_CALCULATED_ATOMIC_RADIUS
#define Q_ANTIMONY_COBALENT_RADIUS
#define Q_ANTIMONY_VAN_DER_WAALS_RADIUS
#define Q_ANTIMONY_ATOMIC_VOLUME
#define Q_ANTIMONY_CRYSTAL_STRUCTURE
#define Q_ANTIMONY_MELTING_POINT
#define Q_ANTIMONY_BOILING_POINT
#define Q_ANTIMONY_FUSION_HEAT
#define Q_ANTIMONY_VAPORIZATION_HEAT
#define Q_ANTIMONY_SPECIFIC_HEAT
#define Q_ANTIMONY_DENSITY
#define Q_ANTIMONY_ELECTRICAL_CONDUCTIVITY
#define Q_ANTIMONY_THERMAL_CONDUCTIVITY
#define Q_ANTIMONY_ELECTRONEGATIVITY
#define Q_ANTIMONY_YOUNG_MODULUS
#define Q_ANTIMONY_BULK_MODULUS
#define Q_ANTIMONY_SHEER_MODULUS
#define Q_ANTIMONY_POISSON_RATIO

#pragma mark - 52 Te

#define Q_TELLURIUM_SYMBOL				Te
#define Q_TELLURIUM_ATOMIC_NUMBER			52
#define Q_TELLURIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_TELLURIUM_CALCULATED_ATOMIC_RADIUS
#define Q_TELLURIUM_COBALENT_RADIUS
#define Q_TELLURIUM_VAN_DER_WAALS_RADIUS
#define Q_TELLURIUM_ATOMIC_VOLUME
#define Q_TELLURIUM_CRYSTAL_STRUCTURE
#define Q_TELLURIUM_MELTING_POINT
#define Q_TELLURIUM_BOILING_POINT
#define Q_TELLURIUM_FUSION_HEAT
#define Q_TELLURIUM_VAPORIZATION_HEAT
#define Q_TELLURIUM_SPECIFIC_HEAT
#define Q_TELLURIUM_DENSITY
#define Q_TELLURIUM_ELECTRICAL_CONDUCTIVITY
#define Q_TELLURIUM_THERMAL_CONDUCTIVITY
#define Q_TELLURIUM_ELECTRONEGATIVITY
#define Q_TELLURIUM_YOUNG_MODULUS
#define Q_TELLURIUM_BULK_MODULUS
#define Q_TELLURIUM_SHEER_MODULUS
#define Q_TELLURIUM_POISSON_RATIO

#pragma mark - 53 I

#define Q_IODINE_SYMBOL					I
#define Q_IODINE_ATOMIC_NUMBER				53
#define Q_IODINE_EMPIRICAL_ATOMIC_RADIUS
#define Q_IODINE_CALCULATED_ATOMIC_RADIUS
#define Q_IODINE_COBALENT_RADIUS
#define Q_IODINE_VAN_DER_WAALS_RADIUS
#define Q_IODINE_ATOMIC_VOLUME
#define Q_IODINE_CRYSTAL_STRUCTURE
#define Q_IODINE_MELTING_POINT
#define Q_IODINE_BOILING_POINT
#define Q_IODINE_FUSION_HEAT
#define Q_IODINE_VAPORIZATION_HEAT
#define Q_IODINE_SPECIFIC_HEAT
#define Q_IODINE_DENSITY
#define Q_IODINE_ELECTRICAL_CONDUCTIVITY
#define Q_IODINE_THERMAL_CONDUCTIVITY
#define Q_IODINE_ELECTRONEGATIVITY
#define Q_IODINE_YOUNG_MODULUS
#define Q_IODINE_BULK_MODULUS
#define Q_IODINE_SHEER_MODULUS
#define Q_IODINE_POISSON_RATIO

#pragma mark - 54 Xe

#define Q_XENON_SYMBOL					Xe
#define Q_XENON_ATOMIC_NUMBER				54
#define Q_XENON_EMPIRICAL_ATOMIC_RADIUS
#define Q_XENON_CALCULATED_ATOMIC_RADIUS
#define Q_XENON_COBALENT_RADIUS
#define Q_XENON_VAN_DER_WAALS_RADIUS
#define Q_XENON_ATOMIC_VOLUME
#define Q_XENON_CRYSTAL_STRUCTURE
#define Q_XENON_MELTING_POINT
#define Q_XENON_BOILING_POINT
#define Q_XENON_FUSION_HEAT
#define Q_XENON_VAPORIZATION_HEAT
#define Q_XENON_SPECIFIC_HEAT
#define Q_XENON_DENSITY
#define Q_XENON_ELECTRICAL_CONDUCTIVITY
#define Q_XENON_THERMAL_CONDUCTIVITY
#define Q_XENON_ELECTRONEGATIVITY
#define Q_XENON_YOUNG_MODULUS
#define Q_XENON_BULK_MODULUS
#define Q_XENON_SHEER_MODULUS
#define Q_XENON_POISSON_RATIO

#pragma mark - 55 Cs

#define Q_CAESIUM_SYMBOL				Cs
#define Q_CAESIUM_ATOMIC_NUMBER				55
#define Q_CAESIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_CAESIUM_CALCULATED_ATOMIC_RADIUS
#define Q_CAESIUM_COBALENT_RADIUS
#define Q_CAESIUM_VAN_DER_WAALS_RADIUS
#define Q_CAESIUM_ATOMIC_VOLUME
#define Q_CAESIUM_CRYSTAL_STRUCTURE
#define Q_CAESIUM_MELTING_POINT
#define Q_CAESIUM_BOILING_POINT
#define Q_CAESIUM_FUSION_HEAT
#define Q_CAESIUM_VAPORIZATION_HEAT
#define Q_CAESIUM_SPECIFIC_HEAT
#define Q_CAESIUM_DENSITY
#define Q_CAESIUM_ELECTRICAL_CONDUCTIVITY
#define Q_CAESIUM_THERMAL_CONDUCTIVITY
#define Q_CAESIUM_ELECTRONEGATIVITY
#define Q_CAESIUM_YOUNG_MODULUS
#define Q_CAESIUM_BULK_MODULUS
#define Q_CAESIUM_SHEER_MODULUS
#define Q_CAESIUM_POISSON_RATIO

#pragma mark - 56 Ba

#define Q_BARIUM_SYMBOL					Ba
#define Q_BARIUM_ATOMIC_NUMBER				56
#define Q_BARIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_BARIUM_CALCULATED_ATOMIC_RADIUS
#define Q_BARIUM_COBALENT_RADIUS
#define Q_BARIUM_VAN_DER_WAALS_RADIUS
#define Q_BARIUM_ATOMIC_VOLUME
#define Q_BARIUM_CRYSTAL_STRUCTURE
#define Q_BARIUM_MELTING_POINT
#define Q_BARIUM_BOILING_POINT
#define Q_BARIUM_FUSION_HEAT
#define Q_BARIUM_VAPORIZATION_HEAT
#define Q_BARIUM_SPECIFIC_HEAT
#define Q_BARIUM_DENSITY
#define Q_BARIUM_ELECTRICAL_CONDUCTIVITY
#define Q_BARIUM_THERMAL_CONDUCTIVITY
#define Q_BARIUM_ELECTRONEGATIVITY
#define Q_BARIUM_YOUNG_MODULUS
#define Q_BARIUM_BULK_MODULUS
#define Q_BARIUM_SHEER_MODULUS
#define Q_BARIUM_POISSON_RATIO

#pragma mark - 57 La

#define Q_LANTHANUM_SYMBOL				La
#define Q_LANTHANUM_ATOMIC_NUMBER			57
#define Q_LANTHANUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_LANTHANUM_CALCULATED_ATOMIC_RADIUS
#define Q_LANTHANUM_COBALENT_RADIUS
#define Q_LANTHANUM_VAN_DER_WAALS_RADIUS
#define Q_LANTHANUM_ATOMIC_VOLUME
#define Q_LANTHANUM_CRYSTAL_STRUCTURE
#define Q_LANTHANUM_MELTING_POINT
#define Q_LANTHANUM_BOILING_POINT
#define Q_LANTHANUM_FUSION_HEAT
#define Q_LANTHANUM_VAPORIZATION_HEAT
#define Q_LANTHANUM_SPECIFIC_HEAT
#define Q_LANTHANUM_DENSITY
#define Q_LANTHANUM_ELECTRICAL_CONDUCTIVITY
#define Q_LANTHANUM_THERMAL_CONDUCTIVITY
#define Q_LANTHANUM_ELECTRONEGATIVITY
#define Q_LANTHANUM_YOUNG_MODULUS
#define Q_LANTHANUM_BULK_MODULUS
#define Q_LANTHANUM_SHEER_MODULUS
#define Q_LANTHANUM_POISSON_RATIO

#pragma mark - 58 Ce

#define Q_CERIUM_SYMBOL					Ce
#define Q_CERIUM_ATOMIC_NUMBER				58
#define Q_CERIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_CERIUM_CALCULATED_ATOMIC_RADIUS
#define Q_CERIUM_COBALENT_RADIUS
#define Q_CERIUM_VAN_DER_WAALS_RADIUS
#define Q_CERIUM_ATOMIC_VOLUME
#define Q_CERIUM_CRYSTAL_STRUCTURE
#define Q_CERIUM_MELTING_POINT
#define Q_CERIUM_BOILING_POINT
#define Q_CERIUM_FUSION_HEAT
#define Q_CERIUM_VAPORIZATION_HEAT
#define Q_CERIUM_SPECIFIC_HEAT
#define Q_CERIUM_DENSITY
#define Q_CERIUM_ELECTRICAL_CONDUCTIVITY
#define Q_CERIUM_THERMAL_CONDUCTIVITY
#define Q_CERIUM_ELECTRONEGATIVITY
#define Q_CERIUM_YOUNG_MODULUS
#define Q_CERIUM_BULK_MODULUS
#define Q_CERIUM_SHEER_MODULUS
#define Q_CERIUM_POISSON_RATIO

#pragma mark - 59 Pr

#define Q_PRASEODYMIUM_SYMBOL				Pr
#define Q_PRASEODYMIUM_ATOMIC_NUMBER			59
#define Q_PRASEODYMIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_PRASEODYMIUM_CALCULATED_ATOMIC_RADIUS
#define Q_PRASEODYMIUM_COBALENT_RADIUS
#define Q_PRASEODYMIUM_VAN_DER_WAALS_RADIUS
#define Q_PRASEODYMIUM_ATOMIC_VOLUME
#define Q_PRASEODYMIUM_CRYSTAL_STRUCTURE
#define Q_PRASEODYMIUM_MELTING_POINT
#define Q_PRASEODYMIUM_BOILING_POINT
#define Q_PRASEODYMIUM_FUSION_HEAT
#define Q_PRASEODYMIUM_VAPORIZATION_HEAT
#define Q_PRASEODYMIUM_SPECIFIC_HEAT
#define Q_PRASEODYMIUM_DENSITY
#define Q_PRASEODYMIUM_ELECTRICAL_CONDUCTIVITY
#define Q_PRASEODYMIUM_THERMAL_CONDUCTIVITY
#define Q_PRASEODYMIUM_ELECTRONEGATIVITY
#define Q_PRASEODYMIUM_YOUNG_MODULUS
#define Q_PRASEODYMIUM_BULK_MODULUS
#define Q_PRASEODYMIUM_SHEER_MODULUS
#define Q_PRASEODYMIUM_POISSON_RATIO

#pragma mark - 60 Nd

#define Q_NEODYMIUM_SYMBOL				Nd
#define Q_NEODYMIUM_ATOMIC_NUMBER			60
#define Q_NEODYMIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_NEODYMIUM_CALCULATED_ATOMIC_RADIUS
#define Q_NEODYMIUM_COBALENT_RADIUS
#define Q_NEODYMIUM_VAN_DER_WAALS_RADIUS
#define Q_NEODYMIUM_ATOMIC_VOLUME
#define Q_NEODYMIUM_CRYSTAL_STRUCTURE
#define Q_NEODYMIUM_MELTING_POINT
#define Q_NEODYMIUM_BOILING_POINT
#define Q_NEODYMIUM_FUSION_HEAT
#define Q_NEODYMIUM_VAPORIZATION_HEAT
#define Q_NEODYMIUM_SPECIFIC_HEAT
#define Q_NEODYMIUM_DENSITY
#define Q_NEODYMIUM_ELECTRICAL_CONDUCTIVITY
#define Q_NEODYMIUM_THERMAL_CONDUCTIVITY
#define Q_NEODYMIUM_ELECTRONEGATIVITY
#define Q_NEODYMIUM_YOUNG_MODULUS
#define Q_NEODYMIUM_BULK_MODULUS
#define Q_NEODYMIUM_SHEER_MODULUS
#define Q_NEODYMIUM_POISSON_RATIO

#pragma mark - 61 Pm

#define Q_PROMETHIUM_SYMBOL				Pm
#define Q_PROMETHIUM_ATOMIC_NUMBER			61
#define Q_PROMETHIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_PROMETHIUM_CALCULATED_ATOMIC_RADIUS
#define Q_PROMETHIUM_COBALENT_RADIUS
#define Q_PROMETHIUM_VAN_DER_WAALS_RADIUS
#define Q_PROMETHIUM_ATOMIC_VOLUME
#define Q_PROMETHIUM_CRYSTAL_STRUCTURE
#define Q_PROMETHIUM_MELTING_POINT
#define Q_PROMETHIUM_BOILING_POINT
#define Q_PROMETHIUM_FUSION_HEAT
#define Q_PROMETHIUM_VAPORIZATION_HEAT
#define Q_PROMETHIUM_SPECIFIC_HEAT
#define Q_PROMETHIUM_DENSITY
#define Q_PROMETHIUM_ELECTRICAL_CONDUCTIVITY
#define Q_PROMETHIUM_THERMAL_CONDUCTIVITY
#define Q_PROMETHIUM_ELECTRONEGATIVITY
#define Q_PROMETHIUM_YOUNG_MODULUS
#define Q_PROMETHIUM_BULK_MODULUS
#define Q_PROMETHIUM_SHEER_MODULUS
#define Q_PROMETHIUM_POISSON_RATIO

#pragma mark - 62 Sm

#define Q_SAMARIUM_SYMBOL				Sm
#define Q_SAMARIUM_ATOMIC_NUMBER			62
#define Q_SAMARIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_SAMARIUM_CALCULATED_ATOMIC_RADIUS
#define Q_SAMARIUM_COBALENT_RADIUS
#define Q_SAMARIUM_VAN_DER_WAALS_RADIUS
#define Q_SAMARIUM_ATOMIC_VOLUME
#define Q_SAMARIUM_CRYSTAL_STRUCTURE
#define Q_SAMARIUM_MELTING_POINT
#define Q_SAMARIUM_BOILING_POINT
#define Q_SAMARIUM_FUSION_HEAT
#define Q_SAMARIUM_VAPORIZATION_HEAT
#define Q_SAMARIUM_SPECIFIC_HEAT
#define Q_SAMARIUM_DENSITY
#define Q_SAMARIUM_ELECTRICAL_CONDUCTIVITY
#define Q_SAMARIUM_THERMAL_CONDUCTIVITY
#define Q_SAMARIUM_ELECTRONEGATIVITY
#define Q_SAMARIUM_YOUNG_MODULUS
#define Q_SAMARIUM_BULK_MODULUS
#define Q_SAMARIUM_SHEER_MODULUS
#define Q_SAMARIUM_POISSON_RATIO

#pragma mark - 63 Eu

#define Q_EUROPIUM_SYMBOL				Eu
#define Q_EUROPIUM_ATOMIC_NUMBER			63
#define Q_EUROPIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_EUROPIUM_CALCULATED_ATOMIC_RADIUS
#define Q_EUROPIUM_COBALENT_RADIUS
#define Q_EUROPIUM_VAN_DER_WAALS_RADIUS
#define Q_EUROPIUM_ATOMIC_VOLUME
#define Q_EUROPIUM_CRYSTAL_STRUCTURE
#define Q_EUROPIUM_MELTING_POINT
#define Q_EUROPIUM_BOILING_POINT
#define Q_EUROPIUM_FUSION_HEAT
#define Q_EUROPIUM_VAPORIZATION_HEAT
#define Q_EUROPIUM_SPECIFIC_HEAT
#define Q_EUROPIUM_DENSITY
#define Q_EUROPIUM_ELECTRICAL_CONDUCTIVITY
#define Q_EUROPIUM_THERMAL_CONDUCTIVITY
#define Q_EUROPIUM_ELECTRONEGATIVITY
#define Q_EUROPIUM_YOUNG_MODULUS
#define Q_EUROPIUM_BULK_MODULUS
#define Q_EUROPIUM_SHEER_MODULUS
#define Q_EUROPIUM_POISSON_RATIO

#pragma mark - 64 Gd

#define Q_GADOLINIUM_SYMBOL				Gd
#define Q_GADOLINIUM_ATOMIC_NUMBER			64
#define Q_GADOLINIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_GADOLINIUM_CALCULATED_ATOMIC_RADIUS
#define Q_GADOLINIUM_COBALENT_RADIUS
#define Q_GADOLINIUM_VAN_DER_WAALS_RADIUS
#define Q_GADOLINIUM_ATOMIC_VOLUME
#define Q_GADOLINIUM_CRYSTAL_STRUCTURE
#define Q_GADOLINIUM_MELTING_POINT
#define Q_GADOLINIUM_BOILING_POINT
#define Q_GADOLINIUM_FUSION_HEAT
#define Q_GADOLINIUM_VAPORIZATION_HEAT
#define Q_GADOLINIUM_SPECIFIC_HEAT
#define Q_GADOLINIUM_DENSITY
#define Q_GADOLINIUM_ELECTRICAL_CONDUCTIVITY
#define Q_GADOLINIUM_THERMAL_CONDUCTIVITY
#define Q_GADOLINIUM_ELECTRONEGATIVITY
#define Q_GADOLINIUM_YOUNG_MODULUS
#define Q_GADOLINIUM_BULK_MODULUS
#define Q_GADOLINIUM_SHEER_MODULUS
#define Q_GADOLINIUM_POISSON_RATIO

#pragma mark - 65 Tb

#define Q_TERBIUM_SYMBOL				Tb
#define Q_TERBIUM_ATOMIC_NUMBER				65
#define Q_TERBIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_TERBIUM_CALCULATED_ATOMIC_RADIUS
#define Q_TERBIUM_COBALENT_RADIUS
#define Q_TERBIUM_VAN_DER_WAALS_RADIUS
#define Q_TERBIUM_ATOMIC_VOLUME
#define Q_TERBIUM_CRYSTAL_STRUCTURE
#define Q_TERBIUM_MELTING_POINT
#define Q_TERBIUM_BOILING_POINT
#define Q_TERBIUM_FUSION_HEAT
#define Q_TERBIUM_VAPORIZATION_HEAT
#define Q_TERBIUM_SPECIFIC_HEAT
#define Q_TERBIUM_DENSITY
#define Q_TERBIUM_ELECTRICAL_CONDUCTIVITY
#define Q_TERBIUM_THERMAL_CONDUCTIVITY
#define Q_TERBIUM_ELECTRONEGATIVITY
#define Q_TERBIUM_YOUNG_MODULUS
#define Q_TERBIUM_BULK_MODULUS
#define Q_TERBIUM_SHEER_MODULUS
#define Q_TERBIUM_POISSON_RATIO

#pragma mark - 66 Dy

#define Q_DYSPROSIUM_SYMBOL				Dy
#define Q_DYSPROSIUM_ATOMIC_NUMBER			66
#define Q_DYSPROSIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_DYSPROSIUM_CALCULATED_ATOMIC_RADIUS
#define Q_DYSPROSIUM_COBALENT_RADIUS
#define Q_DYSPROSIUM_VAN_DER_WAALS_RADIUS
#define Q_DYSPROSIUM_ATOMIC_VOLUME
#define Q_DYSPROSIUM_CRYSTAL_STRUCTURE
#define Q_DYSPROSIUM_MELTING_POINT
#define Q_DYSPROSIUM_BOILING_POINT
#define Q_DYSPROSIUM_FUSION_HEAT
#define Q_DYSPROSIUM_VAPORIZATION_HEAT
#define Q_DYSPROSIUM_SPECIFIC_HEAT
#define Q_DYSPROSIUM_DENSITY
#define Q_DYSPROSIUM_ELECTRICAL_CONDUCTIVITY
#define Q_DYSPROSIUM_THERMAL_CONDUCTIVITY
#define Q_DYSPROSIUM_ELECTRONEGATIVITY
#define Q_DYSPROSIUM_YOUNG_MODULUS
#define Q_DYSPROSIUM_BULK_MODULUS
#define Q_DYSPROSIUM_SHEER_MODULUS
#define Q_DYSPROSIUM_POISSON_RATIO

#pragma mark - 67 Ho

#define Q_HOLMIUM_SYMBOL				Ho
#define Q_HOLMIUM_ATOMIC_NUMBER				67
#define Q_HOLMIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_HOLMIUM_CALCULATED_ATOMIC_RADIUS
#define Q_HOLMIUM_COBALENT_RADIUS
#define Q_HOLMIUM_VAN_DER_WAALS_RADIUS
#define Q_HOLMIUM_ATOMIC_VOLUME
#define Q_HOLMIUM_CRYSTAL_STRUCTURE
#define Q_HOLMIUM_MELTING_POINT
#define Q_HOLMIUM_BOILING_POINT
#define Q_HOLMIUM_FUSION_HEAT
#define Q_HOLMIUM_VAPORIZATION_HEAT
#define Q_HOLMIUM_SPECIFIC_HEAT
#define Q_HOLMIUM_DENSITY
#define Q_HOLMIUM_ELECTRICAL_CONDUCTIVITY
#define Q_HOLMIUM_THERMAL_CONDUCTIVITY
#define Q_HOLMIUM_ELECTRONEGATIVITY
#define Q_HOLMIUM_YOUNG_MODULUS
#define Q_HOLMIUM_BULK_MODULUS
#define Q_HOLMIUM_SHEER_MODULUS
#define Q_HOLMIUM_POISSON_RATIO

#pragma mark - 68 Er

#define Q_ERBIUM_SYMBOL					Er
#define Q_ERBIUM_ATOMIC_NUMBER				68
#define Q_ERBIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_ERBIUM_CALCULATED_ATOMIC_RADIUS
#define Q_ERBIUM_COBALENT_RADIUS
#define Q_ERBIUM_VAN_DER_WAALS_RADIUS
#define Q_ERBIUM_ATOMIC_VOLUME
#define Q_ERBIUM_CRYSTAL_STRUCTURE
#define Q_ERBIUM_MELTING_POINT
#define Q_ERBIUM_BOILING_POINT
#define Q_ERBIUM_FUSION_HEAT
#define Q_ERBIUM_VAPORIZATION_HEAT
#define Q_ERBIUM_SPECIFIC_HEAT
#define Q_ERBIUM_DENSITY
#define Q_ERBIUM_ELECTRICAL_CONDUCTIVITY
#define Q_ERBIUM_THERMAL_CONDUCTIVITY
#define Q_ERBIUM_ELECTRONEGATIVITY
#define Q_ERBIUM_YOUNG_MODULUS
#define Q_ERBIUM_BULK_MODULUS
#define Q_ERBIUM_SHEER_MODULUS
#define Q_ERBIUM_POISSON_RATIO

#pragma mark - 69 Tm

#define Q_THULIUM_SYMBOL				Tm
#define Q_THULIUM_ATOMIC_NUMBER				69
#define Q_THULIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_THULIUM_CALCULATED_ATOMIC_RADIUS
#define Q_THULIUM_COBALENT_RADIUS
#define Q_THULIUM_VAN_DER_WAALS_RADIUS
#define Q_THULIUM_ATOMIC_VOLUME
#define Q_THULIUM_CRYSTAL_STRUCTURE
#define Q_THULIUM_MELTING_POINT
#define Q_THULIUM_BOILING_POINT
#define Q_THULIUM_FUSION_HEAT
#define Q_THULIUM_VAPORIZATION_HEAT
#define Q_THULIUM_SPECIFIC_HEAT
#define Q_THULIUM_DENSITY
#define Q_THULIUM_ELECTRICAL_CONDUCTIVITY
#define Q_THULIUM_THERMAL_CONDUCTIVITY
#define Q_THULIUM_ELECTRONEGATIVITY
#define Q_THULIUM_YOUNG_MODULUS
#define Q_THULIUM_BULK_MODULUS
#define Q_THULIUM_SHEER_MODULUS
#define Q_THULIUM_POISSON_RATIO

#pragma mark - 70 Yb

#define Q_YTTERBIUM_SYMBOL				Yb
#define Q_YTTERBIUM_ATOMIC_NUMBER			70
#define Q_YTTERBIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_YTTERBIUM_CALCULATED_ATOMIC_RADIUS
#define Q_YTTERBIUM_COBALENT_RADIUS
#define Q_YTTERBIUM_VAN_DER_WAALS_RADIUS
#define Q_YTTERBIUM_ATOMIC_VOLUME
#define Q_YTTERBIUM_CRYSTAL_STRUCTURE
#define Q_YTTERBIUM_MELTING_POINT
#define Q_YTTERBIUM_BOILING_POINT
#define Q_YTTERBIUM_FUSION_HEAT
#define Q_YTTERBIUM_VAPORIZATION_HEAT
#define Q_YTTERBIUM_SPECIFIC_HEAT
#define Q_YTTERBIUM_DENSITY
#define Q_YTTERBIUM_ELECTRICAL_CONDUCTIVITY
#define Q_YTTERBIUM_THERMAL_CONDUCTIVITY
#define Q_YTTERBIUM_ELECTRONEGATIVITY
#define Q_YTTERBIUM_YOUNG_MODULUS
#define Q_YTTERBIUM_BULK_MODULUS
#define Q_YTTERBIUM_SHEER_MODULUS
#define Q_YTTERBIUM_POISSON_RATIO

#pragma mark - 71 Lu

#define Q_LUTETIUM_SYMBOL				Lu
#define Q_LUTETIUM_ATOMIC_NUMBER			71
#define Q_LUTETIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_LUTETIUM_CALCULATED_ATOMIC_RADIUS
#define Q_LUTETIUM_COBALENT_RADIUS
#define Q_LUTETIUM_VAN_DER_WAALS_RADIUS
#define Q_LUTETIUM_ATOMIC_VOLUME
#define Q_LUTETIUM_CRYSTAL_STRUCTURE
#define Q_LUTETIUM_MELTING_POINT
#define Q_LUTETIUM_BOILING_POINT
#define Q_LUTETIUM_FUSION_HEAT
#define Q_LUTETIUM_VAPORIZATION_HEAT
#define Q_LUTETIUM_SPECIFIC_HEAT
#define Q_LUTETIUM_DENSITY
#define Q_LUTETIUM_ELECTRICAL_CONDUCTIVITY
#define Q_LUTETIUM_THERMAL_CONDUCTIVITY
#define Q_LUTETIUM_ELECTRONEGATIVITY
#define Q_LUTETIUM_YOUNG_MODULUS
#define Q_LUTETIUM_BULK_MODULUS
#define Q_LUTETIUM_SHEER_MODULUS
#define Q_LUTETIUM_POISSON_RATIO

#pragma mark - 72 Hf

#define Q_HAFNIUM_SYMBOL				Hf
#define Q_HAFNIUM_ATOMIC_NUMBER				72
#define Q_HAFNIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_HAFNIUM_CALCULATED_ATOMIC_RADIUS
#define Q_HAFNIUM_COBALENT_RADIUS
#define Q_HAFNIUM_VAN_DER_WAALS_RADIUS
#define Q_HAFNIUM_ATOMIC_VOLUME
#define Q_HAFNIUM_CRYSTAL_STRUCTURE
#define Q_HAFNIUM_MELTING_POINT
#define Q_HAFNIUM_BOILING_POINT
#define Q_HAFNIUM_FUSION_HEAT
#define Q_HAFNIUM_VAPORIZATION_HEAT
#define Q_HAFNIUM_SPECIFIC_HEAT
#define Q_HAFNIUM_DENSITY
#define Q_HAFNIUM_ELECTRICAL_CONDUCTIVITY
#define Q_HAFNIUM_THERMAL_CONDUCTIVITY
#define Q_HAFNIUM_ELECTRONEGATIVITY
#define Q_HAFNIUM_YOUNG_MODULUS
#define Q_HAFNIUM_BULK_MODULUS
#define Q_HAFNIUM_SHEER_MODULUS
#define Q_HAFNIUM_POISSON_RATIO

#pragma mark - 73 Ta

#define Q_TANTALUM_SYMBOL				Ta
#define Q_TANTALUM_ATOMIC_NUMBER			73
#define Q_TANTALUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_TANTALUM_CALCULATED_ATOMIC_RADIUS
#define Q_TANTALUM_COBALENT_RADIUS
#define Q_TANTALUM_VAN_DER_WAALS_RADIUS
#define Q_TANTALUM_ATOMIC_VOLUME
#define Q_TANTALUM_CRYSTAL_STRUCTURE
#define Q_TANTALUM_MELTING_POINT
#define Q_TANTALUM_BOILING_POINT
#define Q_TANTALUM_FUSION_HEAT
#define Q_TANTALUM_VAPORIZATION_HEAT
#define Q_TANTALUM_SPECIFIC_HEAT
#define Q_TANTALUM_DENSITY
#define Q_TANTALUM_ELECTRICAL_CONDUCTIVITY
#define Q_TANTALUM_THERMAL_CONDUCTIVITY
#define Q_TANTALUM_ELECTRONEGATIVITY
#define Q_TANTALUM_YOUNG_MODULUS
#define Q_TANTALUM_BULK_MODULUS
#define Q_TANTALUM_SHEER_MODULUS
#define Q_TANTALUM_POISSON_RATIO

#pragma mark - 74 W

#define Q_WOLFRAM_SYMBOL				W
#define Q_WOLFRAM_ATOMIC_NUMBER				74
#define Q_WOLFRAM_EMPIRICAL_ATOMIC_RADIUS
#define Q_WOLFRAM_CALCULATED_ATOMIC_RADIUS
#define Q_WOLFRAM_COBALENT_RADIUS
#define Q_WOLFRAM_VAN_DER_WAALS_RADIUS
#define Q_WOLFRAM_ATOMIC_VOLUME
#define Q_WOLFRAM_CRYSTAL_STRUCTURE
#define Q_WOLFRAM_MELTING_POINT
#define Q_WOLFRAM_BOILING_POINT
#define Q_WOLFRAM_FUSION_HEAT
#define Q_WOLFRAM_VAPORIZATION_HEAT
#define Q_WOLFRAM_SPECIFIC_HEAT
#define Q_WOLFRAM_DENSITY
#define Q_WOLFRAM_ELECTRICAL_CONDUCTIVITY
#define Q_WOLFRAM_THERMAL_CONDUCTIVITY
#define Q_WOLFRAM_ELECTRONEGATIVITY
#define Q_WOLFRAM_YOUNG_MODULUS
#define Q_WOLFRAM_BULK_MODULUS
#define Q_WOLFRAM_SHEER_MODULUS
#define Q_WOLFRAM_POISSON_RATIO

#define Q_TUNGSTEN_SYMBOL				Q_WOLFRAM_SYMBOL
#define Q_TUNGSTEN_ATOMIC_NUMBER			Q_WOLFRAM_ATOMIC_NUMBER
#define Q_TUNGSTEN_EMPIRICAL_ATOMIC_RADIUS		Q_WOLFRAM_EMPIRICAL_ATOMIC_RADIUS
#define Q_TUNGSTEN_CALCULATED_ATOMIC_RADIUS		Q_WOLFRAM_CALCULATED_ATOMIC_RADIUS
#define Q_TUNGSTEN_COBALENT_RADIUS			Q_WOLFRAM_COBALENT_RADIUS
#define Q_TUNGSTEN_VAN_DER_WAALS_RADIUS			Q_WOLFRAM_VAN_DER_WAALS_RADIUS
#define Q_TUNGSTEN_ATOMIC_VOLUME			Q_WOLFRAM_ATOMIC_VOLUME
#define Q_TUNGSTEN_CRYSTAL_STRUCTURE			Q_WOLFRAM_CRYSTAL_STRUCTURE
#define Q_TUNGSTEN_MELTING_POINT			Q_WOLFRAM_MELTING_POINT
#define Q_TUNGSTEN_BOILING_POINT			Q_WOLFRAM_BOILING_POINT
#define Q_TUNGSTEN_FUSION_HEAT				Q_WOLFRAM_FUSION_HEAT
#define Q_TUNGSTEN_VAPORIZATION_HEAT			Q_WOLFRAM_VAPORIZATION_HEAT
#define Q_TUNGSTEN_SPECIFIC_HEAT			Q_WOLFRAM_SPECIFIC_HEAT
#define Q_TUNGSTEN_DENSITY				Q_WOLFRAM_DENSITY
#define Q_TUNGSTEN_ELECTRICAL_CONDUCTIVITY		Q_WOLFRAM_ELECTRICAL_CONDUCTIVITY
#define Q_TUNGSTEN_THERMAL_CONDUCTIVITY			Q_WOLFRAM_THERMAL_CONDUCTIVITY
#define Q_TUNGSTEN_ELECTRONEGATIVITY			Q_WOLFRAM_ELECTRONEGATIVITY
#define Q_TUNGSTEN_YOUNG_MODULUS			Q_WOLFRAM_YOUNG_MODULUS
#define Q_TUNGSTEN_BULK_MODULUS				Q_WOLFRAM_BULK_MODULUS
#define Q_TUNGSTEN_SHEER_MODULUS			Q_WOLFRAM_SHEER_MODULUS
#define Q_TUNGSTEN_POISSON_RATIO			Q_WOLFRAM_POISSON_RATIO

#pragma mark - 75 Re

#define Q_RHENIUM_SYMBOL				Re
#define Q_RHENIUM_ATOMIC_NUMBER				75
#define Q_RHENIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_RHENIUM_CALCULATED_ATOMIC_RADIUS
#define Q_RHENIUM_COBALENT_RADIUS
#define Q_RHENIUM_VAN_DER_WAALS_RADIUS
#define Q_RHENIUM_ATOMIC_VOLUME
#define Q_RHENIUM_CRYSTAL_STRUCTURE
#define Q_RHENIUM_MELTING_POINT
#define Q_RHENIUM_BOILING_POINT
#define Q_RHENIUM_FUSION_HEAT
#define Q_RHENIUM_VAPORIZATION_HEAT
#define Q_RHENIUM_SPECIFIC_HEAT
#define Q_RHENIUM_DENSITY
#define Q_RHENIUM_ELECTRICAL_CONDUCTIVITY
#define Q_RHENIUM_THERMAL_CONDUCTIVITY
#define Q_RHENIUM_ELECTRONEGATIVITY
#define Q_RHENIUM_YOUNG_MODULUS
#define Q_RHENIUM_BULK_MODULUS
#define Q_RHENIUM_SHEER_MODULUS
#define Q_RHENIUM_POISSON_RATIO

#pragma mark - 76 Os

#define Q_OSMIUM_SYMBOL					Os
#define Q_OSMIUM_ATOMIC_NUMBER				76
#define Q_OSMIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_OSMIUM_CALCULATED_ATOMIC_RADIUS
#define Q_OSMIUM_COBALENT_RADIUS
#define Q_OSMIUM_VAN_DER_WAALS_RADIUS
#define Q_OSMIUM_ATOMIC_VOLUME
#define Q_OSMIUM_CRYSTAL_STRUCTURE
#define Q_OSMIUM_MELTING_POINT
#define Q_OSMIUM_BOILING_POINT
#define Q_OSMIUM_FUSION_HEAT
#define Q_OSMIUM_VAPORIZATION_HEAT
#define Q_OSMIUM_SPECIFIC_HEAT
#define Q_OSMIUM_DENSITY
#define Q_OSMIUM_ELECTRICAL_CONDUCTIVITY
#define Q_OSMIUM_THERMAL_CONDUCTIVITY
#define Q_OSMIUM_ELECTRONEGATIVITY
#define Q_OSMIUM_YOUNG_MODULUS
#define Q_OSMIUM_BULK_MODULUS
#define Q_OSMIUM_SHEER_MODULUS
#define Q_OSMIUM_POISSON_RATIO

#pragma mark - 77 Ir

#define Q_IRIDIUM_SYMBOL				Ir
#define Q_IRIDIUM_ATOMIC_NUMBER				77
#define Q_IRIDIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_IRIDIUM_CALCULATED_ATOMIC_RADIUS
#define Q_IRIDIUM_COBALENT_RADIUS
#define Q_IRIDIUM_VAN_DER_WAALS_RADIUS
#define Q_IRIDIUM_ATOMIC_VOLUME
#define Q_IRIDIUM_CRYSTAL_STRUCTURE
#define Q_IRIDIUM_MELTING_POINT
#define Q_IRIDIUM_BOILING_POINT
#define Q_IRIDIUM_FUSION_HEAT
#define Q_IRIDIUM_VAPORIZATION_HEAT
#define Q_IRIDIUM_SPECIFIC_HEAT
#define Q_IRIDIUM_DENSITY
#define Q_IRIDIUM_ELECTRICAL_CONDUCTIVITY
#define Q_IRIDIUM_THERMAL_CONDUCTIVITY
#define Q_IRIDIUM_ELECTRONEGATIVITY
#define Q_IRIDIUM_YOUNG_MODULUS
#define Q_IRIDIUM_BULK_MODULUS
#define Q_IRIDIUM_SHEER_MODULUS
#define Q_IRIDIUM_POISSON_RATIO

#pragma mark - 78 Pt

#define Q_PLATINUM_SYMBOL				Pt
#define Q_PLATINUM_ATOMIC_NUMBER			78
#define Q_PLATINUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_PLATINUM_CALCULATED_ATOMIC_RADIUS
#define Q_PLATINUM_COBALENT_RADIUS
#define Q_PLATINUM_VAN_DER_WAALS_RADIUS
#define Q_PLATINUM_ATOMIC_VOLUME
#define Q_PLATINUM_CRYSTAL_STRUCTURE
#define Q_PLATINUM_MELTING_POINT
#define Q_PLATINUM_BOILING_POINT
#define Q_PLATINUM_FUSION_HEAT
#define Q_PLATINUM_VAPORIZATION_HEAT
#define Q_PLATINUM_SPECIFIC_HEAT
#define Q_PLATINUM_DENSITY
#define Q_PLATINUM_ELECTRICAL_CONDUCTIVITY
#define Q_PLATINUM_THERMAL_CONDUCTIVITY
#define Q_PLATINUM_ELECTRONEGATIVITY
#define Q_PLATINUM_YOUNG_MODULUS
#define Q_PLATINUM_BULK_MODULUS
#define Q_PLATINUM_SHEER_MODULUS
#define Q_PLATINUM_POISSON_RATIO

#pragma mark - 79 Au

#define Q_GOLD_SYMBOL					Au
#define Q_GOLD_ATOMIC_NUMBER				79
#define Q_GOLD_EMPIRICAL_ATOMIC_RADIUS
#define Q_GOLD_CALCULATED_ATOMIC_RADIUS
#define Q_GOLD_COBALENT_RADIUS
#define Q_GOLD_VAN_DER_WAALS_RADIUS
#define Q_GOLD_ATOMIC_VOLUME
#define Q_GOLD_CRYSTAL_STRUCTURE
#define Q_GOLD_MELTING_POINT
#define Q_GOLD_BOILING_POINT
#define Q_GOLD_FUSION_HEAT
#define Q_GOLD_VAPORIZATION_HEAT
#define Q_GOLD_SPECIFIC_HEAT
#define Q_GOLD_DENSITY
#define Q_GOLD_ELECTRICAL_CONDUCTIVITY
#define Q_GOLD_THERMAL_CONDUCTIVITY
#define Q_GOLD_ELECTRONEGATIVITY
#define Q_GOLD_YOUNG_MODULUS
#define Q_GOLD_BULK_MODULUS
#define Q_GOLD_SHEER_MODULUS
#define Q_GOLD_POISSON_RATIO

#pragma mark - 80 Hg

#define Q_MERCURY_SYMBOL				Hg
#define Q_MERCURY_ATOMIC_NUMBER				80
#define Q_MERCURY_EMPIRICAL_ATOMIC_RADIUS
#define Q_MERCURY_CALCULATED_ATOMIC_RADIUS
#define Q_MERCURY_COBALENT_RADIUS
#define Q_MERCURY_VAN_DER_WAALS_RADIUS
#define Q_MERCURY_ATOMIC_VOLUME
#define Q_MERCURY_CRYSTAL_STRUCTURE
#define Q_MERCURY_MELTING_POINT
#define Q_MERCURY_BOILING_POINT
#define Q_MERCURY_FUSION_HEAT
#define Q_MERCURY_VAPORIZATION_HEAT
#define Q_MERCURY_SPECIFIC_HEAT
#define Q_MERCURY_DENSITY
#define Q_MERCURY_ELECTRICAL_CONDUCTIVITY
#define Q_MERCURY_THERMAL_CONDUCTIVITY
#define Q_MERCURY_ELECTRONEGATIVITY
#define Q_MERCURY_YOUNG_MODULUS
#define Q_MERCURY_BULK_MODULUS
#define Q_MERCURY_SHEER_MODULUS
#define Q_MERCURY_POISSON_RATIO

#pragma mark - 81 Tl

#define Q_THALLIUM_SYMBOL				Tl
#define Q_THALLIUM_ATOMIC_NUMBER			81
#define Q_THALLIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_THALLIUM_CALCULATED_ATOMIC_RADIUS
#define Q_THALLIUM_COBALENT_RADIUS
#define Q_THALLIUM_VAN_DER_WAALS_RADIUS
#define Q_THALLIUM_ATOMIC_VOLUME
#define Q_THALLIUM_CRYSTAL_STRUCTURE
#define Q_THALLIUM_MELTING_POINT
#define Q_THALLIUM_BOILING_POINT
#define Q_THALLIUM_FUSION_HEAT
#define Q_THALLIUM_VAPORIZATION_HEAT
#define Q_THALLIUM_SPECIFIC_HEAT
#define Q_THALLIUM_DENSITY
#define Q_THALLIUM_ELECTRICAL_CONDUCTIVITY
#define Q_THALLIUM_THERMAL_CONDUCTIVITY
#define Q_THALLIUM_ELECTRONEGATIVITY
#define Q_THALLIUM_YOUNG_MODULUS
#define Q_THALLIUM_BULK_MODULUS
#define Q_THALLIUM_SHEER_MODULUS
#define Q_THALLIUM_POISSON_RATIO

#pragma mark - 82 Pb

#define Q_LEAD_SYMBOL					Pb
#define Q_LEAD_ATOMIC_NUMBER				82
#define Q_LEAD_EMPIRICAL_ATOMIC_RADIUS
#define Q_LEAD_CALCULATED_ATOMIC_RADIUS
#define Q_LEAD_COBALENT_RADIUS
#define Q_LEAD_VAN_DER_WAALS_RADIUS
#define Q_LEAD_ATOMIC_VOLUME
#define Q_LEAD_CRYSTAL_STRUCTURE
#define Q_LEAD_MELTING_POINT
#define Q_LEAD_BOILING_POINT
#define Q_LEAD_FUSION_HEAT
#define Q_LEAD_VAPORIZATION_HEAT
#define Q_LEAD_SPECIFIC_HEAT
#define Q_LEAD_DENSITY
#define Q_LEAD_ELECTRICAL_CONDUCTIVITY
#define Q_LEAD_THERMAL_CONDUCTIVITY
#define Q_LEAD_ELECTRONEGATIVITY
#define Q_LEAD_YOUNG_MODULUS
#define Q_LEAD_BULK_MODULUS
#define Q_LEAD_SHEER_MODULUS
#define Q_LEAD_POISSON_RATIO

#pragma mark - 83 Bi

#define Q_BISMUTH_SYMBOL				Bi
#define Q_BISMUTH_ATOMIC_NUMBER				83
#define Q_BISMUTH_EMPIRICAL_ATOMIC_RADIUS
#define Q_BISMUTH_CALCULATED_ATOMIC_RADIUS
#define Q_BISMUTH_COBALENT_RADIUS
#define Q_BISMUTH_VAN_DER_WAALS_RADIUS
#define Q_BISMUTH_ATOMIC_VOLUME
#define Q_BISMUTH_CRYSTAL_STRUCTURE
#define Q_BISMUTH_MELTING_POINT
#define Q_BISMUTH_BOILING_POINT
#define Q_BISMUTH_FUSION_HEAT
#define Q_BISMUTH_VAPORIZATION_HEAT
#define Q_BISMUTH_SPECIFIC_HEAT
#define Q_BISMUTH_DENSITY
#define Q_BISMUTH_ELECTRICAL_CONDUCTIVITY
#define Q_BISMUTH_THERMAL_CONDUCTIVITY
#define Q_BISMUTH_ELECTRONEGATIVITY
#define Q_BISMUTH_YOUNG_MODULUS
#define Q_BISMUTH_BULK_MODULUS
#define Q_BISMUTH_SHEER_MODULUS
#define Q_BISMUTH_POISSON_RATIO

#pragma mark - 84 Po

#define Q_POLONIUM_SYMBOL				Po
#define Q_POLONIUM_ATOMIC_NUMBER			84
#define Q_POLONIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_POLONIUM_CALCULATED_ATOMIC_RADIUS
#define Q_POLONIUM_COBALENT_RADIUS
#define Q_POLONIUM_VAN_DER_WAALS_RADIUS
#define Q_POLONIUM_ATOMIC_VOLUME
#define Q_POLONIUM_CRYSTAL_STRUCTURE
#define Q_POLONIUM_MELTING_POINT
#define Q_POLONIUM_BOILING_POINT
#define Q_POLONIUM_FUSION_HEAT
#define Q_POLONIUM_VAPORIZATION_HEAT
#define Q_POLONIUM_SPECIFIC_HEAT
#define Q_POLONIUM_DENSITY
#define Q_POLONIUM_ELECTRICAL_CONDUCTIVITY
#define Q_POLONIUM_THERMAL_CONDUCTIVITY
#define Q_POLONIUM_ELECTRONEGATIVITY
#define Q_POLONIUM_YOUNG_MODULUS
#define Q_POLONIUM_BULK_MODULUS
#define Q_POLONIUM_SHEER_MODULUS
#define Q_POLONIUM_POISSON_RATIO

#pragma mark - 85 At

#define Q_ASTATINE_SYMBOL				At
#define Q_ASTATINE_ATOMIC_NUMBER			85
#define Q_ASTATINE_EMPIRICAL_ATOMIC_RADIUS
#define Q_ASTATINE_CALCULATED_ATOMIC_RADIUS
#define Q_ASTATINE_COBALENT_RADIUS
#define Q_ASTATINE_VAN_DER_WAALS_RADIUS
#define Q_ASTATINE_ATOMIC_VOLUME
#define Q_ASTATINE_CRYSTAL_STRUCTURE
#define Q_ASTATINE_MELTING_POINT
#define Q_ASTATINE_BOILING_POINT
#define Q_ASTATINE_FUSION_HEAT
#define Q_ASTATINE_VAPORIZATION_HEAT
#define Q_ASTATINE_SPECIFIC_HEAT
#define Q_ASTATINE_DENSITY
#define Q_ASTATINE_ELECTRICAL_CONDUCTIVITY
#define Q_ASTATINE_THERMAL_CONDUCTIVITY
#define Q_ASTATINE_ELECTRONEGATIVITY
#define Q_ASTATINE_YOUNG_MODULUS
#define Q_ASTATINE_BULK_MODULUS
#define Q_ASTATINE_SHEER_MODULUS
#define Q_ASTATINE_POISSON_RATIO

#pragma mark - 86 Rn

#define Q_RADON_SYMBOL					Rn
#define Q_RADON_ATOMIC_NUMBER				86
#define Q_RADON_EMPIRICAL_ATOMIC_RADIUS
#define Q_RADON_CALCULATED_ATOMIC_RADIUS
#define Q_RADON_COBALENT_RADIUS
#define Q_RADON_VAN_DER_WAALS_RADIUS
#define Q_RADON_ATOMIC_VOLUME
#define Q_RADON_CRYSTAL_STRUCTURE
#define Q_RADON_MELTING_POINT
#define Q_RADON_BOILING_POINT
#define Q_RADON_FUSION_HEAT
#define Q_RADON_VAPORIZATION_HEAT
#define Q_RADON_SPECIFIC_HEAT
#define Q_RADON_DENSITY
#define Q_RADON_ELECTRICAL_CONDUCTIVITY
#define Q_RADON_THERMAL_CONDUCTIVITY
#define Q_RADON_ELECTRONEGATIVITY
#define Q_RADON_YOUNG_MODULUS
#define Q_RADON_BULK_MODULUS
#define Q_RADON_SHEER_MODULUS
#define Q_RADON_POISSON_RATIO

#pragma mark - 87 Fr

#define Q_FRANCIUM_SYMBOL				Fr
#define Q_FRANCIUM_ATOMIC_NUMBER			87
#define Q_FRANCIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_FRANCIUM_CALCULATED_ATOMIC_RADIUS
#define Q_FRANCIUM_COBALENT_RADIUS
#define Q_FRANCIUM_VAN_DER_WAALS_RADIUS
#define Q_FRANCIUM_ATOMIC_VOLUME
#define Q_FRANCIUM_CRYSTAL_STRUCTURE
#define Q_FRANCIUM_MELTING_POINT
#define Q_FRANCIUM_BOILING_POINT
#define Q_FRANCIUM_FUSION_HEAT
#define Q_FRANCIUM_VAPORIZATION_HEAT
#define Q_FRANCIUM_SPECIFIC_HEAT
#define Q_FRANCIUM_DENSITY
#define Q_FRANCIUM_ELECTRICAL_CONDUCTIVITY
#define Q_FRANCIUM_THERMAL_CONDUCTIVITY
#define Q_FRANCIUM_ELECTRONEGATIVITY
#define Q_FRANCIUM_YOUNG_MODULUS
#define Q_FRANCIUM_BULK_MODULUS
#define Q_FRANCIUM_SHEER_MODULUS
#define Q_FRANCIUM_POISSON_RATIO

#pragma mark - 88 Ra

#define Q_RADIUM_SYMBOL					Ra
#define Q_RADIUM_ATOMIC_NUMBER				88
#define Q_RADIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_RADIUM_CALCULATED_ATOMIC_RADIUS
#define Q_RADIUM_COBALENT_RADIUS
#define Q_RADIUM_VAN_DER_WAALS_RADIUS
#define Q_RADIUM_ATOMIC_VOLUME
#define Q_RADIUM_CRYSTAL_STRUCTURE
#define Q_RADIUM_MELTING_POINT
#define Q_RADIUM_BOILING_POINT
#define Q_RADIUM_FUSION_HEAT
#define Q_RADIUM_VAPORIZATION_HEAT
#define Q_RADIUM_SPECIFIC_HEAT
#define Q_RADIUM_DENSITY
#define Q_RADIUM_ELECTRICAL_CONDUCTIVITY
#define Q_RADIUM_THERMAL_CONDUCTIVITY
#define Q_RADIUM_ELECTRONEGATIVITY
#define Q_RADIUM_YOUNG_MODULUS
#define Q_RADIUM_BULK_MODULUS
#define Q_RADIUM_SHEER_MODULUS
#define Q_RADIUM_POISSON_RATIO

#pragma mark - 89 Ac

#define Q_ACTINIUM_SYMBOL				Ac
#define Q_ACTINIUM_ATOMIC_NUMBER			89
#define Q_ACTINIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_ACTINIUM_CALCULATED_ATOMIC_RADIUS
#define Q_ACTINIUM_COBALENT_RADIUS
#define Q_ACTINIUM_VAN_DER_WAALS_RADIUS
#define Q_ACTINIUM_ATOMIC_VOLUME
#define Q_ACTINIUM_CRYSTAL_STRUCTURE
#define Q_ACTINIUM_MELTING_POINT
#define Q_ACTINIUM_BOILING_POINT
#define Q_ACTINIUM_FUSION_HEAT
#define Q_ACTINIUM_VAPORIZATION_HEAT
#define Q_ACTINIUM_SPECIFIC_HEAT
#define Q_ACTINIUM_DENSITY
#define Q_ACTINIUM_ELECTRICAL_CONDUCTIVITY
#define Q_ACTINIUM_THERMAL_CONDUCTIVITY
#define Q_ACTINIUM_ELECTRONEGATIVITY
#define Q_ACTINIUM_YOUNG_MODULUS
#define Q_ACTINIUM_BULK_MODULUS
#define Q_ACTINIUM_SHEER_MODULUS
#define Q_ACTINIUM_POISSON_RATIO

#pragma mark - 90 Th

#define Q_THORIUM_SYMBOL				Th
#define Q_THORIUM_ATOMIC_NUMBER				90
#define Q_THORIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_THORIUM_CALCULATED_ATOMIC_RADIUS
#define Q_THORIUM_COBALENT_RADIUS
#define Q_THORIUM_VAN_DER_WAALS_RADIUS
#define Q_THORIUM_ATOMIC_VOLUME
#define Q_THORIUM_CRYSTAL_STRUCTURE
#define Q_THORIUM_MELTING_POINT
#define Q_THORIUM_BOILING_POINT
#define Q_THORIUM_FUSION_HEAT
#define Q_THORIUM_VAPORIZATION_HEAT
#define Q_THORIUM_SPECIFIC_HEAT
#define Q_THORIUM_DENSITY
#define Q_THORIUM_ELECTRICAL_CONDUCTIVITY
#define Q_THORIUM_THERMAL_CONDUCTIVITY
#define Q_THORIUM_ELECTRONEGATIVITY
#define Q_THORIUM_YOUNG_MODULUS
#define Q_THORIUM_BULK_MODULUS
#define Q_THORIUM_SHEER_MODULUS
#define Q_THORIUM_POISSON_RATIO

#pragma mark - 91 Pa

#define Q_PROTACTINIUM_SYMBOL				Pa
#define Q_PROTACTINIUM_ATOMIC_NUMBER			91
#define Q_PROTACTINIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_PROTACTINIUM_CALCULATED_ATOMIC_RADIUS
#define Q_PROTACTINIUM_COBALENT_RADIUS
#define Q_PROTACTINIUM_VAN_DER_WAALS_RADIUS
#define Q_PROTACTINIUM_ATOMIC_VOLUME
#define Q_PROTACTINIUM_CRYSTAL_STRUCTURE
#define Q_PROTACTINIUM_MELTING_POINT
#define Q_PROTACTINIUM_BOILING_POINT
#define Q_PROTACTINIUM_FUSION_HEAT
#define Q_PROTACTINIUM_VAPORIZATION_HEAT
#define Q_PROTACTINIUM_SPECIFIC_HEAT
#define Q_PROTACTINIUM_DENSITY
#define Q_PROTACTINIUM_ELECTRICAL_CONDUCTIVITY
#define Q_PROTACTINIUM_THERMAL_CONDUCTIVITY
#define Q_PROTACTINIUM_ELECTRONEGATIVITY
#define Q_PROTACTINIUM_YOUNG_MODULUS
#define Q_PROTACTINIUM_BULK_MODULUS
#define Q_PROTACTINIUM_SHEER_MODULUS
#define Q_PROTACTINIUM_POISSON_RATIO

#pragma mark - 92 U

#define Q_URANIUM_SYMBOL				U
#define Q_URANIUM_ATOMIC_NUMBER				92
#define Q_URANIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_URANIUM_CALCULATED_ATOMIC_RADIUS
#define Q_URANIUM_COBALENT_RADIUS
#define Q_URANIUM_VAN_DER_WAALS_RADIUS
#define Q_URANIUM_ATOMIC_VOLUME
#define Q_URANIUM_CRYSTAL_STRUCTURE
#define Q_URANIUM_MELTING_POINT
#define Q_URANIUM_BOILING_POINT
#define Q_URANIUM_FUSION_HEAT
#define Q_URANIUM_VAPORIZATION_HEAT
#define Q_URANIUM_SPECIFIC_HEAT
#define Q_URANIUM_DENSITY
#define Q_URANIUM_ELECTRICAL_CONDUCTIVITY
#define Q_URANIUM_THERMAL_CONDUCTIVITY
#define Q_URANIUM_ELECTRONEGATIVITY
#define Q_URANIUM_YOUNG_MODULUS
#define Q_URANIUM_BULK_MODULUS
#define Q_URANIUM_SHEER_MODULUS
#define Q_URANIUM_POISSON_RATIO

#pragma mark - 93 Np

#define Q_NEPTUNIUM_SYMBOL				Np
#define Q_NEPTUNIUM_ATOMIC_NUMBER			93
#define Q_NEPTUNIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_NEPTUNIUM_CALCULATED_ATOMIC_RADIUS
#define Q_NEPTUNIUM_COBALENT_RADIUS
#define Q_NEPTUNIUM_VAN_DER_WAALS_RADIUS
#define Q_NEPTUNIUM_ATOMIC_VOLUME
#define Q_NEPTUNIUM_CRYSTAL_STRUCTURE
#define Q_NEPTUNIUM_MELTING_POINT
#define Q_NEPTUNIUM_BOILING_POINT
#define Q_NEPTUNIUM_FUSION_HEAT
#define Q_NEPTUNIUM_VAPORIZATION_HEAT
#define Q_NEPTUNIUM_SPECIFIC_HEAT
#define Q_NEPTUNIUM_DENSITY
#define Q_NEPTUNIUM_ELECTRICAL_CONDUCTIVITY
#define Q_NEPTUNIUM_THERMAL_CONDUCTIVITY
#define Q_NEPTUNIUM_ELECTRONEGATIVITY
#define Q_NEPTUNIUM_YOUNG_MODULUS
#define Q_NEPTUNIUM_BULK_MODULUS
#define Q_NEPTUNIUM_SHEER_MODULUS
#define Q_NEPTUNIUM_POISSON_RATIO

#pragma mark - 94 Pu

#define Q_PLUTONIUM_SYMBOL				Pu
#define Q_PLUTONIUM_ATOMIC_NUMBER			94
#define Q_PLUTONIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_PLUTONIUM_CALCULATED_ATOMIC_RADIUS
#define Q_PLUTONIUM_COBALENT_RADIUS
#define Q_PLUTONIUM_VAN_DER_WAALS_RADIUS
#define Q_PLUTONIUM_ATOMIC_VOLUME
#define Q_PLUTONIUM_CRYSTAL_STRUCTURE
#define Q_PLUTONIUM_MELTING_POINT
#define Q_PLUTONIUM_BOILING_POINT
#define Q_PLUTONIUM_FUSION_HEAT
#define Q_PLUTONIUM_VAPORIZATION_HEAT
#define Q_PLUTONIUM_SPECIFIC_HEAT
#define Q_PLUTONIUM_DENSITY
#define Q_PLUTONIUM_ELECTRICAL_CONDUCTIVITY
#define Q_PLUTONIUM_THERMAL_CONDUCTIVITY
#define Q_PLUTONIUM_ELECTRONEGATIVITY
#define Q_PLUTONIUM_YOUNG_MODULUS
#define Q_PLUTONIUM_BULK_MODULUS
#define Q_PLUTONIUM_SHEER_MODULUS
#define Q_PLUTONIUM_POISSON_RATIO

#pragma mark - 95 Am

#define Q_AMERICIUM_SYMBOL				Am
#define Q_AMERICIUM_ATOMIC_NUMBER			95
#define Q_AMERICIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_AMERICIUM_CALCULATED_ATOMIC_RADIUS
#define Q_AMERICIUM_COBALENT_RADIUS
#define Q_AMERICIUM_VAN_DER_WAALS_RADIUS
#define Q_AMERICIUM_ATOMIC_VOLUME
#define Q_AMERICIUM_CRYSTAL_STRUCTURE
#define Q_AMERICIUM_MELTING_POINT
#define Q_AMERICIUM_BOILING_POINT
#define Q_AMERICIUM_FUSION_HEAT
#define Q_AMERICIUM_VAPORIZATION_HEAT
#define Q_AMERICIUM_SPECIFIC_HEAT
#define Q_AMERICIUM_DENSITY
#define Q_AMERICIUM_ELECTRICAL_CONDUCTIVITY
#define Q_AMERICIUM_THERMAL_CONDUCTIVITY
#define Q_AMERICIUM_ELECTRONEGATIVITY
#define Q_AMERICIUM_YOUNG_MODULUS
#define Q_AMERICIUM_BULK_MODULUS
#define Q_AMERICIUM_SHEER_MODULUS
#define Q_AMERICIUM_POISSON_RATIO

#pragma mark - 96 Cm

#define Q_CURIUM_SYMBOL					Cm
#define Q_CURIUM_ATOMIC_NUMBER				96
#define Q_CURIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_CURIUM_CALCULATED_ATOMIC_RADIUS
#define Q_CURIUM_COBALENT_RADIUS
#define Q_CURIUM_VAN_DER_WAALS_RADIUS
#define Q_CURIUM_ATOMIC_VOLUME
#define Q_CURIUM_CRYSTAL_STRUCTURE
#define Q_CURIUM_MELTING_POINT
#define Q_CURIUM_BOILING_POINT
#define Q_CURIUM_FUSION_HEAT
#define Q_CURIUM_VAPORIZATION_HEAT
#define Q_CURIUM_SPECIFIC_HEAT
#define Q_CURIUM_DENSITY
#define Q_CURIUM_ELECTRICAL_CONDUCTIVITY
#define Q_CURIUM_THERMAL_CONDUCTIVITY
#define Q_CURIUM_ELECTRONEGATIVITY
#define Q_CURIUM_YOUNG_MODULUS
#define Q_CURIUM_BULK_MODULUS
#define Q_CURIUM_SHEER_MODULUS
#define Q_CURIUM_POISSON_RATIO

#pragma mark - 97 Bk

#define Q_BERKELIUM_SYMBOL				Bk
#define Q_BERKELIUM_ATOMIC_NUMBER			97
#define Q_BERKELIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_BERKELIUM_CALCULATED_ATOMIC_RADIUS
#define Q_BERKELIUM_COBALENT_RADIUS
#define Q_BERKELIUM_VAN_DER_WAALS_RADIUS
#define Q_BERKELIUM_ATOMIC_VOLUME
#define Q_BERKELIUM_CRYSTAL_STRUCTURE
#define Q_BERKELIUM_MELTING_POINT
#define Q_BERKELIUM_BOILING_POINT
#define Q_BERKELIUM_FUSION_HEAT
#define Q_BERKELIUM_VAPORIZATION_HEAT
#define Q_BERKELIUM_SPECIFIC_HEAT
#define Q_BERKELIUM_DENSITY
#define Q_BERKELIUM_ELECTRICAL_CONDUCTIVITY
#define Q_BERKELIUM_THERMAL_CONDUCTIVITY
#define Q_BERKELIUM_ELECTRONEGATIVITY
#define Q_BERKELIUM_YOUNG_MODULUS
#define Q_BERKELIUM_BULK_MODULUS
#define Q_BERKELIUM_SHEER_MODULUS
#define Q_BERKELIUM_POISSON_RATIO

#pragma mark - 98 Cf

#define Q_CALIFORNIUM_SYMBOL				Cf
#define Q_CALIFORNIUM_ATOMIC_NUMBER			98
#define Q_CALIFORNIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_CALIFORNIUM_CALCULATED_ATOMIC_RADIUS
#define Q_CALIFORNIUM_COBALENT_RADIUS
#define Q_CALIFORNIUM_VAN_DER_WAALS_RADIUS
#define Q_CALIFORNIUM_ATOMIC_VOLUME
#define Q_CALIFORNIUM_CRYSTAL_STRUCTURE
#define Q_CALIFORNIUM_MELTING_POINT
#define Q_CALIFORNIUM_BOILING_POINT
#define Q_CALIFORNIUM_FUSION_HEAT
#define Q_CALIFORNIUM_VAPORIZATION_HEAT
#define Q_CALIFORNIUM_SPECIFIC_HEAT
#define Q_CALIFORNIUM_DENSITY
#define Q_CALIFORNIUM_ELECTRICAL_CONDUCTIVITY
#define Q_CALIFORNIUM_THERMAL_CONDUCTIVITY
#define Q_CALIFORNIUM_ELECTRONEGATIVITY
#define Q_CALIFORNIUM_YOUNG_MODULUS
#define Q_CALIFORNIUM_BULK_MODULUS
#define Q_CALIFORNIUM_SHEER_MODULUS
#define Q_CALIFORNIUM_POISSON_RATIO

#pragma mark - 99 Es

#define Q_EINSTEINIUM_SYMBOL				Es
#define Q_EINSTEINIUM_ATOMIC_NUMBER			99
#define Q_EINSTEINIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_EINSTEINIUM_CALCULATED_ATOMIC_RADIUS
#define Q_EINSTEINIUM_COBALENT_RADIUS
#define Q_EINSTEINIUM_VAN_DER_WAALS_RADIUS
#define Q_EINSTEINIUM_ATOMIC_VOLUME
#define Q_EINSTEINIUM_CRYSTAL_STRUCTURE
#define Q_EINSTEINIUM_MELTING_POINT
#define Q_EINSTEINIUM_BOILING_POINT
#define Q_EINSTEINIUM_FUSION_HEAT
#define Q_EINSTEINIUM_VAPORIZATION_HEAT
#define Q_EINSTEINIUM_SPECIFIC_HEAT
#define Q_EINSTEINIUM_DENSITY
#define Q_EINSTEINIUM_ELECTRICAL_CONDUCTIVITY
#define Q_EINSTEINIUM_THERMAL_CONDUCTIVITY
#define Q_EINSTEINIUM_ELECTRONEGATIVITY
#define Q_EINSTEINIUM_YOUNG_MODULUS
#define Q_EINSTEINIUM_BULK_MODULUS
#define Q_EINSTEINIUM_SHEER_MODULUS
#define Q_EINSTEINIUM_POISSON_RATIO

#pragma mark - 100 Fm

#define Q_FERMIUM_SYMBOL				Fm
#define Q_FERMIUM_ATOMIC_NUMBER				100
#define Q_FERMIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_FERMIUM_CALCULATED_ATOMIC_RADIUS
#define Q_FERMIUM_COBALENT_RADIUS
#define Q_FERMIUM_VAN_DER_WAALS_RADIUS
#define Q_FERMIUM_ATOMIC_VOLUME
#define Q_FERMIUM_CRYSTAL_STRUCTURE
#define Q_FERMIUM_MELTING_POINT
#define Q_FERMIUM_BOILING_POINT
#define Q_FERMIUM_FUSION_HEAT
#define Q_FERMIUM_VAPORIZATION_HEAT
#define Q_FERMIUM_SPECIFIC_HEAT
#define Q_FERMIUM_DENSITY
#define Q_FERMIUM_ELECTRICAL_CONDUCTIVITY
#define Q_FERMIUM_THERMAL_CONDUCTIVITY
#define Q_FERMIUM_ELECTRONEGATIVITY
#define Q_FERMIUM_YOUNG_MODULUS
#define Q_FERMIUM_BULK_MODULUS
#define Q_FERMIUM_SHEER_MODULUS
#define Q_FERMIUM_POISSON_RATIO

#pragma mark - 101 Md

#define Q_MENDELEVIUM_SYMBOL				Md
#define Q_MENDELEVIUM_ATOMIC_NUMBER			101
#define Q_MENDELEVIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_MENDELEVIUM_CALCULATED_ATOMIC_RADIUS
#define Q_MENDELEVIUM_COBALENT_RADIUS
#define Q_MENDELEVIUM_VAN_DER_WAALS_RADIUS
#define Q_MENDELEVIUM_ATOMIC_VOLUME
#define Q_MENDELEVIUM_CRYSTAL_STRUCTURE
#define Q_MENDELEVIUM_MELTING_POINT
#define Q_MENDELEVIUM_BOILING_POINT
#define Q_MENDELEVIUM_FUSION_HEAT
#define Q_MENDELEVIUM_VAPORIZATION_HEAT
#define Q_MENDELEVIUM_SPECIFIC_HEAT
#define Q_MENDELEVIUM_DENSITY
#define Q_MENDELEVIUM_ELECTRICAL_CONDUCTIVITY
#define Q_MENDELEVIUM_THERMAL_CONDUCTIVITY
#define Q_MENDELEVIUM_ELECTRONEGATIVITY
#define Q_MENDELEVIUM_YOUNG_MODULUS
#define Q_MENDELEVIUM_BULK_MODULUS
#define Q_MENDELEVIUM_SHEER_MODULUS
#define Q_MENDELEVIUM_POISSON_RATIO

#pragma mark - 102 No

#define Q_NOBELIUM_SYMBOL				No
#define Q_NOBELIUM_ATOMIC_NUMBER			102
#define Q_NOBELIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_NOBELIUM_CALCULATED_ATOMIC_RADIUS
#define Q_NOBELIUM_COBALENT_RADIUS
#define Q_NOBELIUM_VAN_DER_WAALS_RADIUS
#define Q_NOBELIUM_ATOMIC_VOLUME
#define Q_NOBELIUM_CRYSTAL_STRUCTURE
#define Q_NOBELIUM_MELTING_POINT
#define Q_NOBELIUM_BOILING_POINT
#define Q_NOBELIUM_FUSION_HEAT
#define Q_NOBELIUM_VAPORIZATION_HEAT
#define Q_NOBELIUM_SPECIFIC_HEAT
#define Q_NOBELIUM_DENSITY
#define Q_NOBELIUM_ELECTRICAL_CONDUCTIVITY
#define Q_NOBELIUM_THERMAL_CONDUCTIVITY
#define Q_NOBELIUM_ELECTRONEGATIVITY
#define Q_NOBELIUM_YOUNG_MODULUS
#define Q_NOBELIUM_BULK_MODULUS
#define Q_NOBELIUM_SHEER_MODULUS
#define Q_NOBELIUM_POISSON_RATIO

#pragma mark - 103 Lr

#define Q_LAWRENCIUM_SYMBOL				Lr
#define Q_LAWRENCIUM_ATOMIC_NUMBER			103
#define Q_LAWRENCIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_LAWRENCIUM_CALCULATED_ATOMIC_RADIUS
#define Q_LAWRENCIUM_COBALENT_RADIUS
#define Q_LAWRENCIUM_VAN_DER_WAALS_RADIUS
#define Q_LAWRENCIUM_ATOMIC_VOLUME
#define Q_LAWRENCIUM_CRYSTAL_STRUCTURE
#define Q_LAWRENCIUM_MELTING_POINT
#define Q_LAWRENCIUM_BOILING_POINT
#define Q_LAWRENCIUM_FUSION_HEAT
#define Q_LAWRENCIUM_VAPORIZATION_HEAT
#define Q_LAWRENCIUM_SPECIFIC_HEAT
#define Q_LAWRENCIUM_DENSITY
#define Q_LAWRENCIUM_ELECTRICAL_CONDUCTIVITY
#define Q_LAWRENCIUM_THERMAL_CONDUCTIVITY
#define Q_LAWRENCIUM_ELECTRONEGATIVITY
#define Q_LAWRENCIUM_YOUNG_MODULUS
#define Q_LAWRENCIUM_BULK_MODULUS
#define Q_LAWRENCIUM_SHEER_MODULUS
#define Q_LAWRENCIUM_POISSON_RATIO

#pragma mark - 104 Rf

#define Q_RUTHERFORDIUM_SYMBOL				Rf
#define Q_RUTHERFORDIUM_ATOMIC_NUMBER			104
#define Q_RUTHERFORDIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_RUTHERFORDIUM_CALCULATED_ATOMIC_RADIUS
#define Q_RUTHERFORDIUM_COBALENT_RADIUS
#define Q_RUTHERFORDIUM_VAN_DER_WAALS_RADIUS
#define Q_RUTHERFORDIUM_ATOMIC_VOLUME
#define Q_RUTHERFORDIUM_CRYSTAL_STRUCTURE
#define Q_RUTHERFORDIUM_MELTING_POINT
#define Q_RUTHERFORDIUM_BOILING_POINT
#define Q_RUTHERFORDIUM_FUSION_HEAT
#define Q_RUTHERFORDIUM_VAPORIZATION_HEAT
#define Q_RUTHERFORDIUM_SPECIFIC_HEAT
#define Q_RUTHERFORDIUM_DENSITY
#define Q_RUTHERFORDIUM_ELECTRICAL_CONDUCTIVITY
#define Q_RUTHERFORDIUM_THERMAL_CONDUCTIVITY
#define Q_RUTHERFORDIUM_ELECTRONEGATIVITY
#define Q_RUTHERFORDIUM_YOUNG_MODULUS
#define Q_RUTHERFORDIUM_BULK_MODULUS
#define Q_RUTHERFORDIUM_SHEER_MODULUS
#define Q_RUTHERFORDIUM_POISSON_RATIO

#pragma mark - 105 Db

#define Q_DUBNIUM_SYMBOL				Db
#define Q_DUBNIUM_ATOMIC_NUMBER				105
#define Q_DUBNIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_DUBNIUM_CALCULATED_ATOMIC_RADIUS
#define Q_DUBNIUM_COBALENT_RADIUS
#define Q_DUBNIUM_VAN_DER_WAALS_RADIUS
#define Q_DUBNIUM_ATOMIC_VOLUME
#define Q_DUBNIUM_CRYSTAL_STRUCTURE
#define Q_DUBNIUM_MELTING_POINT
#define Q_DUBNIUM_BOILING_POINT
#define Q_DUBNIUM_FUSION_HEAT
#define Q_DUBNIUM_VAPORIZATION_HEAT
#define Q_DUBNIUM_SPECIFIC_HEAT
#define Q_DUBNIUM_DENSITY
#define Q_DUBNIUM_ELECTRICAL_CONDUCTIVITY
#define Q_DUBNIUM_THERMAL_CONDUCTIVITY
#define Q_DUBNIUM_ELECTRONEGATIVITY
#define Q_DUBNIUM_YOUNG_MODULUS
#define Q_DUBNIUM_BULK_MODULUS
#define Q_DUBNIUM_SHEER_MODULUS
#define Q_DUBNIUM_POISSON_RATIO

#pragma mark - 106 Sg

#define Q_SEABORGIUM_SYMBOL				Sg
#define Q_SEABORGIUM_ATOMIC_NUMBER			106
#define Q_SEABORGIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_SEABORGIUM_CALCULATED_ATOMIC_RADIUS
#define Q_SEABORGIUM_COBALENT_RADIUS
#define Q_SEABORGIUM_VAN_DER_WAALS_RADIUS
#define Q_SEABORGIUM_ATOMIC_VOLUME
#define Q_SEABORGIUM_CRYSTAL_STRUCTURE
#define Q_SEABORGIUM_MELTING_POINT
#define Q_SEABORGIUM_BOILING_POINT
#define Q_SEABORGIUM_FUSION_HEAT
#define Q_SEABORGIUM_VAPORIZATION_HEAT
#define Q_SEABORGIUM_SPECIFIC_HEAT
#define Q_SEABORGIUM_DENSITY
#define Q_SEABORGIUM_ELECTRICAL_CONDUCTIVITY
#define Q_SEABORGIUM_THERMAL_CONDUCTIVITY
#define Q_SEABORGIUM_ELECTRONEGATIVITY
#define Q_SEABORGIUM_YOUNG_MODULUS
#define Q_SEABORGIUM_BULK_MODULUS
#define Q_SEABORGIUM_SHEER_MODULUS
#define Q_SEABORGIUM_POISSON_RATIO

#pragma mark - 107 Bh

#define Q_BOHRIUM_SYMBOL				Bh
#define Q_BOHRIUM_ATOMIC_NUMBER				107
#define Q_BOHRIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_BOHRIUM_CALCULATED_ATOMIC_RADIUS
#define Q_BOHRIUM_COBALENT_RADIUS
#define Q_BOHRIUM_VAN_DER_WAALS_RADIUS
#define Q_BOHRIUM_ATOMIC_VOLUME
#define Q_BOHRIUM_CRYSTAL_STRUCTURE
#define Q_BOHRIUM_MELTING_POINT
#define Q_BOHRIUM_BOILING_POINT
#define Q_BOHRIUM_FUSION_HEAT
#define Q_BOHRIUM_VAPORIZATION_HEAT
#define Q_BOHRIUM_SPECIFIC_HEAT
#define Q_BOHRIUM_DENSITY
#define Q_BOHRIUM_ELECTRICAL_CONDUCTIVITY
#define Q_BOHRIUM_THERMAL_CONDUCTIVITY
#define Q_BOHRIUM_ELECTRONEGATIVITY
#define Q_BOHRIUM_YOUNG_MODULUS
#define Q_BOHRIUM_BULK_MODULUS
#define Q_BOHRIUM_SHEER_MODULUS
#define Q_BOHRIUM_POISSON_RATIO

#pragma mark - 108 Hs

#define Q_HASSIUM_SYMBOL				Hs
#define Q_HASSIUM_ATOMIC_NUMBER				108
#define Q_HASSIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_HASSIUM_CALCULATED_ATOMIC_RADIUS
#define Q_HASSIUM_COBALENT_RADIUS
#define Q_HASSIUM_VAN_DER_WAALS_RADIUS
#define Q_HASSIUM_ATOMIC_VOLUME
#define Q_HASSIUM_CRYSTAL_STRUCTURE
#define Q_HASSIUM_MELTING_POINT
#define Q_HASSIUM_BOILING_POINT
#define Q_HASSIUM_FUSION_HEAT
#define Q_HASSIUM_VAPORIZATION_HEAT
#define Q_HASSIUM_SPECIFIC_HEAT
#define Q_HASSIUM_DENSITY
#define Q_HASSIUM_ELECTRICAL_CONDUCTIVITY
#define Q_HASSIUM_THERMAL_CONDUCTIVITY
#define Q_HASSIUM_ELECTRONEGATIVITY
#define Q_HASSIUM_YOUNG_MODULUS
#define Q_HASSIUM_BULK_MODULUS
#define Q_HASSIUM_SHEER_MODULUS
#define Q_HASSIUM_POISSON_RATIO

#pragma mark - 109 Mt

#define Q_MEITNERIUM_SYMBOL				Mt
#define Q_MEITNERIUM_ATOMIC_NUMBER			109
#define Q_MEITNERIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_MEITNERIUM_CALCULATED_ATOMIC_RADIUS
#define Q_MEITNERIUM_COBALENT_RADIUS
#define Q_MEITNERIUM_VAN_DER_WAALS_RADIUS
#define Q_MEITNERIUM_ATOMIC_VOLUME
#define Q_MEITNERIUM_CRYSTAL_STRUCTURE
#define Q_MEITNERIUM_MELTING_POINT
#define Q_MEITNERIUM_BOILING_POINT
#define Q_MEITNERIUM_FUSION_HEAT
#define Q_MEITNERIUM_VAPORIZATION_HEAT
#define Q_MEITNERIUM_SPECIFIC_HEAT
#define Q_MEITNERIUM_DENSITY
#define Q_MEITNERIUM_ELECTRICAL_CONDUCTIVITY
#define Q_MEITNERIUM_THERMAL_CONDUCTIVITY
#define Q_MEITNERIUM_ELECTRONEGATIVITY
#define Q_MEITNERIUM_YOUNG_MODULUS
#define Q_MEITNERIUM_BULK_MODULUS
#define Q_MEITNERIUM_SHEER_MODULUS
#define Q_MEITNERIUM_POISSON_RATIO

#pragma mark - 110 Ds

#define Q_DARMSTADTIUM_SYMBOL				Ds
#define Q_DARMSTADTIUM_ATOMIC_NUMBER			110
#define Q_DARMSTADTIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_DARMSTADTIUM_CALCULATED_ATOMIC_RADIUS
#define Q_DARMSTADTIUM_COBALENT_RADIUS
#define Q_DARMSTADTIUM_VAN_DER_WAALS_RADIUS
#define Q_DARMSTADTIUM_ATOMIC_VOLUME
#define Q_DARMSTADTIUM_CRYSTAL_STRUCTURE
#define Q_DARMSTADTIUM_MELTING_POINT
#define Q_DARMSTADTIUM_BOILING_POINT
#define Q_DARMSTADTIUM_FUSION_HEAT
#define Q_DARMSTADTIUM_VAPORIZATION_HEAT
#define Q_DARMSTADTIUM_SPECIFIC_HEAT
#define Q_DARMSTADTIUM_DENSITY
#define Q_DARMSTADTIUM_ELECTRICAL_CONDUCTIVITY
#define Q_DARMSTADTIUM_THERMAL_CONDUCTIVITY
#define Q_DARMSTADTIUM_ELECTRONEGATIVITY
#define Q_DARMSTADTIUM_YOUNG_MODULUS
#define Q_DARMSTADTIUM_BULK_MODULUS
#define Q_DARMSTADTIUM_SHEER_MODULUS
#define Q_DARMSTADTIUM_POISSON_RATIO

#pragma mark - 111 Rg

#define Q_ROENTGENIUM_SYMBOL				Rg
#define Q_ROENTGENIUM_ATOMIC_NUMBER			111
#define Q_ROENTGENIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_ROENTGENIUM_CALCULATED_ATOMIC_RADIUS
#define Q_ROENTGENIUM_COBALENT_RADIUS
#define Q_ROENTGENIUM_VAN_DER_WAALS_RADIUS
#define Q_ROENTGENIUM_ATOMIC_VOLUME
#define Q_ROENTGENIUM_CRYSTAL_STRUCTURE
#define Q_ROENTGENIUM_MELTING_POINT
#define Q_ROENTGENIUM_BOILING_POINT
#define Q_ROENTGENIUM_FUSION_HEAT
#define Q_ROENTGENIUM_VAPORIZATION_HEAT
#define Q_ROENTGENIUM_SPECIFIC_HEAT
#define Q_ROENTGENIUM_DENSITY
#define Q_ROENTGENIUM_ELECTRICAL_CONDUCTIVITY
#define Q_ROENTGENIUM_THERMAL_CONDUCTIVITY
#define Q_ROENTGENIUM_ELECTRONEGATIVITY
#define Q_ROENTGENIUM_YOUNG_MODULUS
#define Q_ROENTGENIUM_BULK_MODULUS
#define Q_ROENTGENIUM_SHEER_MODULUS
#define Q_ROENTGENIUM_POISSON_RATIO

#pragma mark - 112 Cn

#define Q_COPERNICIUM_SYMBOL				Cn
#define Q_COPERNICIUM_ATOMIC_NUMBER			112
#define Q_COPERNICIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_COPERNICIUM_CALCULATED_ATOMIC_RADIUS
#define Q_COPERNICIUM_COBALENT_RADIUS
#define Q_COPERNICIUM_VAN_DER_WAALS_RADIUS
#define Q_COPERNICIUM_ATOMIC_VOLUME
#define Q_COPERNICIUM_CRYSTAL_STRUCTURE
#define Q_COPERNICIUM_MELTING_POINT
#define Q_COPERNICIUM_BOILING_POINT
#define Q_COPERNICIUM_FUSION_HEAT
#define Q_COPERNICIUM_VAPORIZATION_HEAT
#define Q_COPERNICIUM_SPECIFIC_HEAT
#define Q_COPERNICIUM_DENSITY
#define Q_COPERNICIUM_ELECTRICAL_CONDUCTIVITY
#define Q_COPERNICIUM_THERMAL_CONDUCTIVITY
#define Q_COPERNICIUM_ELECTRONEGATIVITY
#define Q_COPERNICIUM_YOUNG_MODULUS
#define Q_COPERNICIUM_BULK_MODULUS
#define Q_COPERNICIUM_SHEER_MODULUS
#define Q_COPERNICIUM_POISSON_RATIO

#pragma mark - 113 Uut

#define Q_UNUNTRIUM_SYMBOL				Uut
#define Q_UNUNTRIUM_ATOMIC_NUMBER			113
#define Q_UNUNTRIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_UNUNTRIUM_CALCULATED_ATOMIC_RADIUS
#define Q_UNUNTRIUM_COBALENT_RADIUS
#define Q_UNUNTRIUM_VAN_DER_WAALS_RADIUS
#define Q_UNUNTRIUM_ATOMIC_VOLUME
#define Q_UNUNTRIUM_CRYSTAL_STRUCTURE
#define Q_UNUNTRIUM_MELTING_POINT
#define Q_UNUNTRIUM_BOILING_POINT
#define Q_UNUNTRIUM_FUSION_HEAT
#define Q_UNUNTRIUM_VAPORIZATION_HEAT
#define Q_UNUNTRIUM_SPECIFIC_HEAT
#define Q_UNUNTRIUM_DENSITY
#define Q_UNUNTRIUM_ELECTRICAL_CONDUCTIVITY
#define Q_UNUNTRIUM_THERMAL_CONDUCTIVITY
#define Q_UNUNTRIUM_ELECTRONEGATIVITY
#define Q_UNUNTRIUM_YOUNG_MODULUS
#define Q_UNUNTRIUM_BULK_MODULUS
#define Q_UNUNTRIUM_SHEER_MODULUS
#define Q_UNUNTRIUM_POISSON_RATIO

#pragma mark - 114 Fl

#define Q_FLEROVIUM_SYMBOL				Fl
#define Q_FLEROVIUM_ATOMIC_NUMBER			114
#define Q_FLEROVIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_FLEROVIUM_CALCULATED_ATOMIC_RADIUS
#define Q_FLEROVIUM_COBALENT_RADIUS
#define Q_FLEROVIUM_VAN_DER_WAALS_RADIUS
#define Q_FLEROVIUM_ATOMIC_VOLUME
#define Q_FLEROVIUM_CRYSTAL_STRUCTURE
#define Q_FLEROVIUM_MELTING_POINT
#define Q_FLEROVIUM_BOILING_POINT
#define Q_FLEROVIUM_FUSION_HEAT
#define Q_FLEROVIUM_VAPORIZATION_HEAT
#define Q_FLEROVIUM_SPECIFIC_HEAT
#define Q_FLEROVIUM_DENSITY
#define Q_FLEROVIUM_ELECTRICAL_CONDUCTIVITY
#define Q_FLEROVIUM_THERMAL_CONDUCTIVITY
#define Q_FLEROVIUM_ELECTRONEGATIVITY
#define Q_FLEROVIUM_YOUNG_MODULUS
#define Q_FLEROVIUM_BULK_MODULUS
#define Q_FLEROVIUM_SHEER_MODULUS
#define Q_FLEROVIUM_POISSON_RATIO

#pragma mark - 115 Uup

#define Q_UNUNPENTIUM_SYMBOL				Uup
#define Q_UNUNPENTIUM_ATOMIC_NUMBER			115
#define Q_UNUNPENTIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_UNUNPENTIUM_CALCULATED_ATOMIC_RADIUS
#define Q_UNUNPENTIUM_COBALENT_RADIUS
#define Q_UNUNPENTIUM_VAN_DER_WAALS_RADIUS
#define Q_UNUNPENTIUM_ATOMIC_VOLUME
#define Q_UNUNPENTIUM_CRYSTAL_STRUCTURE
#define Q_UNUNPENTIUM_MELTING_POINT
#define Q_UNUNPENTIUM_BOILING_POINT
#define Q_UNUNPENTIUM_FUSION_HEAT
#define Q_UNUNPENTIUM_VAPORIZATION_HEAT
#define Q_UNUNPENTIUM_SPECIFIC_HEAT
#define Q_UNUNPENTIUM_DENSITY
#define Q_UNUNPENTIUM_ELECTRICAL_CONDUCTIVITY
#define Q_UNUNPENTIUM_THERMAL_CONDUCTIVITY
#define Q_UNUNPENTIUM_ELECTRONEGATIVITY
#define Q_UNUNPENTIUM_YOUNG_MODULUS
#define Q_UNUNPENTIUM_BULK_MODULUS
#define Q_UNUNPENTIUM_SHEER_MODULUS
#define Q_UNUNPENTIUM_POISSON_RATIO

#pragma mark - 116 Lv

#define Q_LIVERMORIUM_SYMBOL				Lv
#define Q_LIVERMORIUM_ATOMIC_NUMBER			116
#define Q_LIVERMORIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_LIVERMORIUM_CALCULATED_ATOMIC_RADIUS
#define Q_LIVERMORIUM_COBALENT_RADIUS
#define Q_LIVERMORIUM_VAN_DER_WAALS_RADIUS
#define Q_LIVERMORIUM_ATOMIC_VOLUME
#define Q_LIVERMORIUM_CRYSTAL_STRUCTURE
#define Q_LIVERMORIUM_MELTING_POINT
#define Q_LIVERMORIUM_BOILING_POINT
#define Q_LIVERMORIUM_FUSION_HEAT
#define Q_LIVERMORIUM_VAPORIZATION_HEAT
#define Q_LIVERMORIUM_SPECIFIC_HEAT
#define Q_LIVERMORIUM_DENSITY
#define Q_LIVERMORIUM_ELECTRICAL_CONDUCTIVITY
#define Q_LIVERMORIUM_THERMAL_CONDUCTIVITY
#define Q_LIVERMORIUM_ELECTRONEGATIVITY
#define Q_LIVERMORIUM_YOUNG_MODULUS
#define Q_LIVERMORIUM_BULK_MODULUS
#define Q_LIVERMORIUM_SHEER_MODULUS
#define Q_LIVERMORIUM_POISSON_RATIO

#pragma mark - 117 Uus

#define Q_UNUNSEPTIUM_SYMBOL				Uus
#define Q_UNUNSEPTIUM_ATOMIC_NUMBER			117
#define Q_UNUNSEPTIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_UNUNSEPTIUM_CALCULATED_ATOMIC_RADIUS
#define Q_UNUNSEPTIUM_COBALENT_RADIUS
#define Q_UNUNSEPTIUM_VAN_DER_WAALS_RADIUS
#define Q_UNUNSEPTIUM_ATOMIC_VOLUME
#define Q_UNUNSEPTIUM_CRYSTAL_STRUCTURE
#define Q_UNUNSEPTIUM_MELTING_POINT
#define Q_UNUNSEPTIUM_BOILING_POINT
#define Q_UNUNSEPTIUM_FUSION_HEAT
#define Q_UNUNSEPTIUM_VAPORIZATION_HEAT
#define Q_UNUNSEPTIUM_SPECIFIC_HEAT
#define Q_UNUNSEPTIUM_DENSITY
#define Q_UNUNSEPTIUM_ELECTRICAL_CONDUCTIVITY
#define Q_UNUNSEPTIUM_THERMAL_CONDUCTIVITY
#define Q_UNUNSEPTIUM_ELECTRONEGATIVITY
#define Q_UNUNSEPTIUM_YOUNG_MODULUS
#define Q_UNUNSEPTIUM_BULK_MODULUS
#define Q_UNUNSEPTIUM_SHEER_MODULUS
#define Q_UNUNSEPTIUM_POISSON_RATIO

#pragma mark - 118 Uuo

#define Q_UNUNOCTIUM_SYMBOL				Uuo
#define Q_UNUNOCTIUM_ATOMIC_NUMBER			118
#define Q_UNUNOCTIUM_EMPIRICAL_ATOMIC_RADIUS
#define Q_UNUNOCTIUM_CALCULATED_ATOMIC_RADIUS
#define Q_UNUNOCTIUM_COBALENT_RADIUS
#define Q_UNUNOCTIUM_VAN_DER_WAALS_RADIUS
#define Q_UNUNOCTIUM_ATOMIC_VOLUME
#define Q_UNUNOCTIUM_CRYSTAL_STRUCTURE
#define Q_UNUNOCTIUM_MELTING_POINT
#define Q_UNUNOCTIUM_BOILING_POINT
#define Q_UNUNOCTIUM_FUSION_HEAT
#define Q_UNUNOCTIUM_VAPORIZATION_HEAT
#define Q_UNUNOCTIUM_SPECIFIC_HEAT
#define Q_UNUNOCTIUM_DENSITY
#define Q_UNUNOCTIUM_ELECTRICAL_CONDUCTIVITY
#define Q_UNUNOCTIUM_THERMAL_CONDUCTIVITY
#define Q_UNUNOCTIUM_ELECTRONEGATIVITY
#define Q_UNUNOCTIUM_YOUNG_MODULUS
#define Q_UNUNOCTIUM_BULK_MODULUS
#define Q_UNUNOCTIUM_SHEER_MODULUS
#define Q_UNUNOCTIUM_POISSON_RATIO

#endif /* __Q_constants_chemical_elements_H__ */
