/* Z Kit C API - keys/hardware/machine/model/ZX Spectrum.h
	      __	   __
  _______ ___/ /______ ___/ /__
 / __/ -_) _  / __/ _ \ _  / -_)
/_/  \__/\_,_/\__/\___/_,_/\__/
Copyright © 2006-2015 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef __Z_keys_hardware_machine_model_ZX_Spectrum_H__
#define __Z_keys_hardware_machine_model_ZX_Spectrum_H__

/* MARK: - Official models */

#define Z_MACHINE_SINCLAIR_ZX_SPECTRUM_16K_ISSUE_1		 0
#define Z_MACHINE_SINCLAIR_ZX_SPECTRUM_48K_ISSUE_2		 1
#define Z_MACHINE_SINCLAIR_ZX_SPECTRUM_48K_ISSUE_3		 2
#define Z_MACHINE_SINCLAIR_ZX_SPECTRUM_PLUS			 3
#define Z_MACHINE_SINCLAIR_ZX_SPECTRUM_PLUS_ES			 4
#define Z_MACHINE_SINCLAIR_ZX_SPECTRUM_PLUS_128K		 5
#define Z_MACHINE_SINCLAIR_ZX_SPECTRUM_PLUS_128K_ES		 6
#define Z_MACHINE_SINCLAIR_ZX_SPECTRUM_PLUS2			 7
#define Z_MACHINE_SINCLAIR_ZX_SPECTRUM_PLUS2_ES			 8
#define Z_MACHINE_SINCLAIR_ZX_SPECTRUM_PLUS2_FR			 9
#define Z_MACHINE_SINCLAIR_ZX_SPECTRUM_PLUS2A			10
#define Z_MACHINE_SINCLAIR_ZX_SPECTRUM_PLUS2A_ES		11
#define Z_MACHINE_SINCLAIR_ZX_SPECTRUM_PLUS3			12
#define Z_MACHINE_SINCLAIR_ZX_SPECTRUM_PLUS3_ES			13

#define Z_MACHINE_STRING_SINCLAIR_ZX_SPECTRUM_16K_ISSUE_1	"ZX Spectrum 16K (Issue 1)"
#define Z_MACHINE_STRING_SINCLAIR_ZX_SPECTRUM_48K_ISSUE_2	"ZX Spectrum 48K (Issue 2)"
#define Z_MACHINE_STRING_SINCLAIR_ZX_SPECTRUM_48K_ISSUE_3	"ZX Spectrum 48K (Issue 3)"
#define Z_MACHINE_STRING_SINCLAIR_ZX_SPECTRUM_PLUS		"ZX Spectrum +"
#define Z_MACHINE_STRING_SINCLAIR_ZX_SPECTRUM_PLUS_128K		"ZX Spectrum + 128K"
#define Z_MACHINE_STRING_SINCLAIR_ZX_SPECTRUM_PLUS_128K_ES	"ZX Spectrum + 128K (ES)"
#define Z_MACHINE_STRING_SINCLAIR_ZX_SPECTRUM_PLUS2		"ZX Spectrum +2"
#define Z_MACHINE_STRING_SINCLAIR_ZX_SPECTRUM_PLUS2_ES		"ZX Spectrum +2 (ES)"
#define Z_MACHINE_STRING_SINCLAIR_ZX_SPECTRUM_PLUS2_FR		"ZX Spectrum +2 (FR)"
#define Z_MACHINE_STRING_SINCLAIR_ZX_SPECTRUM_PLUS2A		"ZX Spectrum +2A"
#define Z_MACHINE_STRING_SINCLAIR_ZX_SPECTRUM_PLUS2A_ES		"ZX Spectrum +2A (ES)"
#define Z_MACHINE_STRING_SINCLAIR_ZX_SPECTRUM_PLUS3		"ZX Spectrum +3"
#define Z_MACHINE_STRING_SINCLAIR_ZX_SPECTRUM_PLUS3_ES		"ZX Spectrum +3 (ES)"

/* MARK: - Official clones */

#define Z_MACHINE_INVES_SPECTRUM_PLUS				14
#define Z_MACHINE_TIMEX_SINCLAIR_2068				15
#define Z_MACHINE_TIMEX_COMPUTER_2048				16
#define Z_MACHINE_TIMEX_SINCLAIR_2048				17

#define Z_MACHINE_STRING_INVES_SPECTRUM_PLUS			"Inves Spectrum +"
#define Z_MACHINE_STRING_TIMEX_SINCLAIR_2068			"Timex Sinclair 2068"
#define Z_MACHINE_STRING_TIMEX_COMPUTER_2048			"Timex Computer 2048"
#define Z_MACHINE_STRING_TIMEX_SINCLAIR_2048			"Timex Sinclair 2048"

/* MARK: - Unofficial clones */

#define Z_MACHINE_ATM
#define Z_MACHINE_AZX_MONSTRUM
#define Z_MACHINE_BALTICA
#define Z_MACHINE_BEST_III
#define Z_MACHINE_BI_AM_ZX_SPECTRUM_48_64
#define Z_MACHINE_BI_AM_ZX_SPECTRUM_128
#define Z_MACHINE_COBRA
#define Z_MACHINE_CIP_03
#define Z_MACHINE_COMPOSITE
#define Z_MACHINE_CZERWENY_CZ_2000
#define Z_MACHINE_CZERWENY_CZ_SPECTRUM
#define Z_MACHINE_CZERWENY_CZ_SPECTRUM_PLUS
#define Z_MACHINE_DELTA
#define Z_MACHINE_DELTA_S_128
#define Z_MACHINE_DIDAKTIK_GAMA
#define Z_MACHINE_DIDAKTIK_KOMPAKT
#define Z_MACHINE_DIDAKTIK_M
#define Z_MACHINE_DIGRA
#define Z_MACHINE_DUBNA_48K
#define Z_MACHINE_ELLA_RA
#define Z_MACHINE_ELWRO_600_JR
#define Z_MACHINE_ELWRO_800_JR
#define Z_MACHINE_FELIX_HC_85
#define Z_MACHINE_FELIX_HC_90
#define Z_MACHINE_FELIX_HC_91
#define Z_MACHINE_FELIX_HC_2000
#define Z_MACHINE_GRANDROMMAX
#define Z_MACHINE_GRANDBOARD_2PLUS
#define Z_MACHINE_HT_3080C
#define Z_MACHINE_INVES_SPECTRUM_PLUS
#define Z_MACHINE_JET
#define Z_MACHINE_KAY_1024
#define Z_MACHINE_KRASNOGORSK
#define Z_MACHINE_KVORUM
#define Z_MACHINE_KVORUM_64
#define Z_MACHINE_KVORUM_128
#define Z_MACHINE_KVORUM_128PLUS
#define Z_MACHINE_LENINGRAD_1
#define Z_MACHINE_LENINGRAD_2
#define Z_MACHINE_MASTER
#define Z_MACHINE_MASTER_K
#define Z_MACHINE_MICRODIGITAL_TK_90X_16K
#define Z_MACHINE_MICRODIGITAL_TK_90X_48K
#define Z_MACHINE_MICRODIGITAL_TK_95
#define Z_MACHINE_MISTRUM
#define Z_MACHINE_MOSKVA_48K
#define Z_MACHINE_MOSKVA_128K
#define Z_MACHINE_NAFANJA
#define Z_MACHINE_PENTAGON_48
#define Z_MACHINE_PENTAGON_128
#define Z_MACHINE_PETERS_MC64S1
#define Z_MACHINE_PETERS_MC64S2
#define Z_MACHINE_PETERS_MD_256S3
#define Z_MACHINE_ROBIK
#define Z_MACHINE_PROFI
#define Z_MACHINE_SANTAKA_002
#define Z_MACHINE_SCORPION_ZS_256
#define Z_MACHINE_SEVER_NORD_48_002
#define Z_MACHINE_SINTEZ
#define Z_MACHINE_SPECTRAL
#define Z_MACHINE_SPEKTR_48
#define Z_MACHINE_SPRINTER
#define Z_MACHINE_TIMS
#define Z_MACHINE_UNIPOLBRIT_KOMPUTER_2086
#define Z_MACHINE_ZX_NEXT

#define Z_MACHINE_STRING_ATM				"ATM"
#define Z_MACHINE_STRING_AZX_MONSTRUM			"AZX-Monstrum"
#define Z_MACHINE_STRING_BALTICA			"Baltica"
#define Z_MACHINE_STRING_BEST_III			"Best III"
#define Z_MACHINE_STRING_BI_AM_ZX_SPECTRUM_48_64	"Bi Am ZX-Spectrum 48/64"
#define Z_MACHINE_STRING_BI_AM_ZX_SPECTRUM_128		"Bi Am ZX-Spectrum 128"
#define Z_MACHINE_STRING_COBRA				"Cobra"
#define Z_MACHINE_STRING_CIP_03				"CIP-03"
#define Z_MACHINE_STRING_COMPOSITE			"Composite"
#define Z_MACHINE_STRING_CZERWENY_CZ_2000		"Czerweny CZ 2000"
#define Z_MACHINE_STRING_CZERWENY_CZ_SPECTRUM		"Czerweny CZ Spectrum"
#define Z_MACHINE_STRING_CZERWENY_CZ_SPECTRUM_PLUS	"Czerweny CZ Spectrum Plus"
#define Z_MACHINE_STRING_DELTA				"Delta"
#define Z_MACHINE_STRING_DELTA_S_128			"Delta S-128"
#define Z_MACHINE_STRING_DIDAKTIK_GAMA			"Didaktik Gama"
#define Z_MACHINE_STRING_DIDAKTIK_KOMPAKT		"Didaktik Kompakt"
#define Z_MACHINE_STRING_DIDAKTIK_M			"Didaktik M"
#define Z_MACHINE_STRING_DIGRA				"Digra"
#define Z_MACHINE_STRING_DUBNA_48K			"Dubna 48K"
#define Z_MACHINE_STRING_ELLA_RA			"Ella Ra"
#define Z_MACHINE_STRING_ELWRO_600_JR			"Elwro 600 Jr"
#define Z_MACHINE_STRING_ELWRO_800_JR			"Elwro 800 Jr"
#define Z_MACHINE_STRING_FELIX_HC_85			"Felix HC 85"
#define Z_MACHINE_STRING_FELIX_HC_90			"Felix HC 90"
#define Z_MACHINE_STRING_FELIX_HC_91			"Felix HC 91"
#define Z_MACHINE_STRING_FELIX_HC_2000			"Felix HC 2000"
#define Z_MACHINE_STRING_GRANDROMMAX			"GrandRomMax"
#define Z_MACHINE_STRING_GRANDBOARD_2PLUS		"Grandboard 2+"
#define Z_MACHINE_STRING_HT_3080C			"HT 3080C"
#define Z_MACHINE_STRING_INVES_SPECTRUM_PLUS		"Inves Spectrum +"
#define Z_MACHINE_STRING_JET				"JET"
#define Z_MACHINE_STRING_KAY_1024			"Kay 1024"
#define Z_MACHINE_STRING_KRASNOGORSK			"Krasnogorsk"
#define Z_MACHINE_STRING_KVORUM				"Kvorum"
#define Z_MACHINE_STRING_KVORUM_64			"Kvorum 64"
#define Z_MACHINE_STRING_KVORUM_128			"Kvorum 128"
#define Z_MACHINE_STRING_KVORUM_128PLUS			"Kvorum 128+"
#define Z_MACHINE_STRING_LENINGRAD_1			"Leningrad 1"
#define Z_MACHINE_STRING_LENINGRAD_2			"Leningrad 2"
#define Z_MACHINE_STRING_MASTER				"Master"
#define Z_MACHINE_STRING_MASTER_K			"Master K"
#define Z_MACHINE_STRING_MICRODIGITAL_TK_90X_16K	"Microdigital TK 90X 16K"
#define Z_MACHINE_STRING_MICRODIGITAL_TK_90X_48K	"Microdigital TK 90X 48K"
#define Z_MACHINE_STRING_MICRODIGITAL_TK_95		"Microdigital TK 95"
#define Z_MACHINE_STRING_MISTRUM			"Mistrum"
#define Z_MACHINE_STRING_MOSKVA_48K			"Moskva 48K"
#define Z_MACHINE_STRING_MOSKVA_128K			"Moskva 128K"
#define Z_MACHINE_STRING_NAFANJA			"Nafanja"
#define Z_MACHINE_STRING_PENTAGON_48			"Pentagon 48"
#define Z_MACHINE_STRING_PENTAGON_128			"Pentagon 128"
#define Z_MACHINE_STRING_PETERS_MC64S1			"Peters MC64S1"
#define Z_MACHINE_STRING_PETERS_MC64S2			"Peters MC64S2"
#define Z_MACHINE_STRING_PETERS_MD_256S3		"Peters MD-256S3"
#define Z_MACHINE_STRING_ROBIK				"Robik"
#define Z_MACHINE_STRING_PROFI				"Profi"
#define Z_MACHINE_STRING_SANTAKA_002			"Santaka 002"
#define Z_MACHINE_STRING_SCORPION_ZS_256		"Scorpion ZS-256"
#define Z_MACHINE_STRING_SEVER_NORD_48_002		"Sever (Nord) 48/002"
#define Z_MACHINE_STRING_SINTEZ				"Sintez"
#define Z_MACHINE_STRING_SPECTRAL			"Spectral"
#define Z_MACHINE_STRING_SPEKTR_48			"Spektr 48"
#define Z_MACHINE_STRING_SPRINTER			"Sprinter"
#define Z_MACHINE_STRING_TIMS				"TimS"
#define Z_MACHINE_STRING_UNIPOLBRIT_KOMPUTER_2086	"Unipolbrit Komputer 2086"
#define Z_MACHINE_STRING_ZX_NEXT			"ZX Next"

#endif /* __Z_keys_hardware_machine_model_ZX_Spectrum_H__ */
