/* Z Kit - inspection/compiler/completion.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//___/_| Kit
Copyright (C) 2006-2019 Manuel Sainz de Baranda y Goñi.
Copyright (C) 2018 Sofía Ortega Sosa.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_inspection_compiler_completion_H
#define Z_inspection_compiler_completion_H

/* MARK: - K&R C */

#ifndef Z_COMPILER_C_HAS_OLD_STYLE_FUNCTION
#	define Z_COMPILER_C_HAS_OLD_STYLE_FUNCTION FALSE
#endif

#ifndef Z_COMPILER_C_HAS_OPERATOR_SIZEOF
#	define Z_COMPILER_C_HAS_OPERATOR_SIZEOF FALSE
#endif

#ifndef Z_COMPILER_C_HAS_STORAGE_CLASS_AUTO
#	define Z_COMPILER_C_HAS_STORAGE_CLASS_AUTO FALSE
#endif

#ifndef Z_COMPILER_C_HAS_STORAGE_CLASS_EXTERN
#	define Z_COMPILER_C_HAS_STORAGE_CLASS_EXTERN FALSE
#endif

#ifndef Z_COMPILER_C_HAS_STORAGE_CLASS_REGISTER
#	define Z_COMPILER_C_HAS_STORAGE_CLASS_REGISTER FALSE
#endif

#ifndef Z_COMPILER_C_HAS_STORAGE_CLASS_STATIC
#	define Z_COMPILER_C_HAS_STORAGE_CLASS_STATIC FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_DOUBLE
#	define Z_COMPILER_C_HAS_TYPE_DOUBLE FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_FLOAT
#	define Z_COMPILER_C_HAS_TYPE_FLOAT FALSE
#endif

/* MARK: - C89 */

#ifndef Z_COMPILER_C_HAS_C89_RULES_ON_TYPE_CONVERSION
#	define Z_COMPILER_C_HAS_C89_RULES_ON_TYPE_CONVERSION FALSE
#endif

#ifndef Z_COMPILER_C_HAS_CONSTRUCT_AS_FUNCTION_ARGUMENT
#	define Z_COMPILER_C_HAS_CONSTRUCT_AS_FUNCTION_ARGUMENT FALSE
#endif

#ifndef Z_COMPILER_C_HAS_CONSTRUCT_AS_RETURN_TYPE
#	define Z_COMPILER_C_HAS_CONSTRUCT_AS_RETURN_TYPE FALSE
#endif

#ifndef Z_COMPILER_C_HAS_CONSTRUCT_ASSIGNMENT
#	define Z_COMPILER_C_HAS_CONSTRUCT_ASSIGNMENT FALSE
#endif

#ifndef Z_COMPILER_C_HAS_CONSTRUCT_NAMESPACE
#	define Z_COMPILER_C_HAS_CONSTRUCT_NAMESPACE FALSE
#endif

#ifndef Z_COMPILER_C_HAS_ENUMERATION
#	define Z_COMPILER_C_HAS_ENUMERATION FALSE
#endif

#ifndef Z_COMPILER_C_HAS_FUNCTION_POINTER_AUTODEREFERENCING
#	define Z_COMPILER_C_HAS_FUNCTION_POINTER_AUTODEREFERENCING FALSE
#endif

#ifndef Z_COMPILER_C_HAS_FUNCTION_PROTOTYPE
#	define Z_COMPILER_C_HAS_FUNCTION_PROTOTYPE FALSE
#endif

#ifndef Z_COMPILER_C_HAS_INTEGRAL_SWITCH
#	define Z_COMPILER_C_HAS_INTEGRAL_SWITCH FALSE
#endif

#ifndef Z_COMPILER_C_HAS_LOCAL_AGGREGATE_CONSTANT_INITIALZATION
#	define Z_COMPILER_C_HAS_LOCAL_AGGREGATE_CONSTANT_INITIALZATION FALSE
#endif

#ifndef Z_COMPILER_C_HAS_PREPROCESSOR_INDENTATION
#	define Z_COMPILER_C_HAS_PREPROCESSOR_INDENTATION FALSE
#endif

#ifndef Z_COMPILER_C_HAS_REMOVAL_OF_ENTRY_AS_KEYWORD
#	define Z_COMPILER_C_HAS_REMOVAL_OF_ENTRY_AS_KEYWORD FALSE
#endif

#ifndef Z_COMPILER_C_HAS_REMOVAL_OF_LONG_FLOAT_AS_TYPE
#	define Z_COMPILER_C_HAS_REMOVAL_OF_LONG_FLOAT_AS_TYPE FALSE
#endif

#ifndef Z_COMPILER_C_HAS_STRING_LITERAL_CONCATENATION
#	define Z_COMPILER_C_HAS_STRING_LITERAL_CONCATENATION FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TRIGRAPHS
#	define Z_COMPILER_C_HAS_TRIGRAPHS FALSE
#endif

#ifndef Z_COMPILER_C_HAS_UNION_CONSTANT_INITIALIZATION
#	define Z_COMPILER_C_HAS_UNION_CONSTANT_INITIALIZATION FALSE
#endif

#ifndef Z_COMPILER_C_HAS_ESCAPE_SEQUENCE_ALERT
#	define Z_COMPILER_C_HAS_ESCAPE_SEQUENCE_ALERT FALSE
#endif

#ifndef Z_COMPILER_C_HAS_ESCAPE_SEQUENCE_HEXADECIMAL
#	define Z_COMPILER_C_HAS_ESCAPE_SEQUENCE_HEXADECIMAL FALSE
#endif

#ifndef Z_COMPILER_C_HAS_ESCAPE_SEQUENCE_VERTICAL_TAB
#	define Z_COMPILER_C_HAS_ESCAPE_SEQUENCE_VERTICAL_TAB FALSE
#endif

#ifndef Z_COMPILER_C_HAS_LITERAL_FLOAT
#	define Z_COMPILER_C_HAS_LITERAL_FLOAT FALSE
#endif

#ifndef Z_COMPILER_C_HAS_LITERAL_LONG_DOUBLE
#	define Z_COMPILER_C_HAS_LITERAL_LONG_DOUBLE FALSE
#endif

#ifndef Z_COMPILER_C_HAS_LITERAL_UNSIGNED
#	define Z_COMPILER_C_HAS_LITERAL_UNSIGNED FALSE
#endif

#ifndef Z_COMPILER_C_HAS_OPERATOR_UNARY_PLUS
#	define Z_COMPILER_C_HAS_OPERATOR_UNARY_PLUS FALSE
#endif

#ifndef Z_COMPILER_C_HAS_PREPROCESSOR_DIRECTIVE_NULL
#	define Z_COMPILER_C_HAS_PREPROCESSOR_DIRECTIVE_NULL FALSE
#endif

#ifndef Z_COMPILER_C_HAS_PREPROCESSOR_DIRECTIVE_ELIF
#	define Z_COMPILER_C_HAS_PREPROCESSOR_DIRECTIVE_ELIF FALSE
#endif

#ifndef Z_COMPILER_C_HAS_PREPROCESSOR_DIRECTIVE_ERROR
#	define Z_COMPILER_C_HAS_PREPROCESSOR_DIRECTIVE_ERROR FALSE
#endif

#ifndef Z_COMPILER_C_HAS_PREPROCESSOR_DIRECTIVE_LINE
#	define Z_COMPILER_C_HAS_PREPROCESSOR_DIRECTIVE_LINE FALSE
#endif

#ifndef Z_COMPILER_C_HAS_PREPROCESSOR_DIRECTIVE_PRAGMA
#	define Z_COMPILER_C_HAS_PREPROCESSOR_DIRECTIVE_PRAGMA FALSE
#endif

#ifndef Z_COMPILER_C_HAS_PREPROCESSOR_OPERATOR_DEFINED
#	define Z_COMPILER_C_HAS_PREPROCESSOR_OPERATOR_DEFINED FALSE
#endif

#ifndef Z_COMPILER_C_HAS_PREPROCESSOR_OPERATOR_PASTING
#	define Z_COMPILER_C_HAS_PREPROCESSOR_OPERATOR_PASTING FALSE
#endif

#ifndef Z_COMPILER_C_HAS_PREPROCESSOR_OPERATOR_STRINGIZING
#	define Z_COMPILER_C_HAS_PREPROCESSOR_OPERATOR_STRINGIZING FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_LONG_DOUBLE
#	define Z_COMPILER_C_HAS_TYPE_LONG_DOUBLE FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_UNSIGNED_CHAR
#	define Z_COMPILER_C_HAS_TYPE_UNSIGNED_CHAR FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_UNSIGNED_LONG
#	define Z_COMPILER_C_HAS_TYPE_UNSIGNED_LONG FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_UNSIGNED_SHORT
#	define Z_COMPILER_C_HAS_TYPE_UNSIGNED_SHORT FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_VOID
#	define Z_COMPILER_C_HAS_TYPE_VOID FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_VOID_POINTER
#	define Z_COMPILER_C_HAS_TYPE_VOID_POINTER FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_MODIFIER_SIGNED
#	define Z_COMPILER_C_HAS_TYPE_MODIFIER_SIGNED FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_QUALIFIER_CONST
#	define Z_COMPILER_C_HAS_TYPE_QUALIFIER_CONST FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_QUALIFIER_VOLATILE
#	define Z_COMPILER_C_HAS_TYPE_QUALIFIER_VOLATILE FALSE
#endif

/* MARK: - C95 */

#ifndef Z_COMPILER_C_HAS_DIGRAPHS
#	define Z_COMPILER_C_HAS_DIGRAPHS FALSE
#endif

/* MARK: - C99 */

#ifndef Z_COMPILER_C_HAS_C99_RULES_ON_INTEGER_LITERALS
#	define Z_COMPILER_C_HAS_C99_RULES_ON_INTEGER_LITERALS FALSE
#endif

#ifndef Z_COMPILER_C_HAS_C99_RULES_ON_TYPE_COMPATIBILITY
#	define Z_COMPILER_C_HAS_C99_RULES_ON_TYPE_COMPATIBILITY FALSE
#endif

#ifndef Z_COMPILER_C_HAS_C99_RULES_ON_TYPE_CONVERSION
#	define Z_COMPILER_C_HAS_C99_RULES_ON_TYPE_CONVERSION FALSE
#endif

#ifndef Z_COMPILER_C_HAS_COMPOUND_LITERAL
#	define Z_COMPILER_C_HAS_COMPOUND_LITERAL FALSE
#endif

#ifndef Z_COMPILER_C_HAS_CONVERSION_OF_NON_LVALUE_ARRAY_TO_POINTER
#	define Z_COMPILER_C_HAS_CONVERSION_OF_NON_LVALUE_ARRAY_TO_POINTER FALSE
#endif

#ifndef Z_COMPILER_C_HAS_CPP_STYLE_COMMENT
#	define Z_COMPILER_C_HAS_CPP_STYLE_COMMENT FALSE
#endif

#ifndef Z_COMPILER_C_HAS_DESIGNATED_INITIALIZER
#	define Z_COMPILER_C_HAS_DESIGNATED_INITIALIZER FALSE
#endif

#ifndef Z_COMPILER_C_HAS_EMPTY_MACRO_ARGUMENT
#	define Z_COMPILER_C_HAS_EMPTY_MACRO_ARGUMENT FALSE
#endif

#ifndef Z_COMPILER_C_HAS_EXTENDED_IDENTIFIER
#	define Z_COMPILER_C_HAS_EXTENDED_IDENTIFIER FALSE
#endif

#ifndef Z_COMPILER_C_HAS_FLEXIBLE_ARRAY_MEMBER
#	define Z_COMPILER_C_HAS_FLEXIBLE_ARRAY_MEMBER FALSE
#endif

#ifndef Z_COMPILER_C_HAS_FOR_WITH_DECLARATION
#	define Z_COMPILER_C_HAS_FOR_WITH_DECLARATION FALSE
#endif

#ifndef Z_COMPILER_C_HAS_IDEMPOTENT_TYPE_QUALIFIERS
#	define Z_COMPILER_C_HAS_IDEMPOTENT_TYPE_QUALIFIERS FALSE
#endif

#ifndef Z_COMPILER_C_HAS_LOCAL_AGGREGATE_NON_CONSTANT_INITIALIZATION
#	define Z_COMPILER_C_HAS_LOCAL_AGGREGATE_NON_CONSTANT_INITIALIZATION FALSE
#endif

#ifndef Z_COMPILER_C_HAS_MIXED_DECLARATIONS_AND_CODE
#	define Z_COMPILER_C_HAS_MIXED_DECLARATIONS_AND_CODE FALSE
#endif

#ifndef Z_COMPILER_C_HAS_PREPROCESSOR_ARITHMETIC_DONE_IN_INTMAX
#	define Z_COMPILER_C_HAS_PREPROCESSOR_ARITHMETIC_DONE_IN_INTMAX FALSE
#endif

#ifndef Z_COMPILER_C_HAS_RELIABLE_INTEGER_DIVISION
#	define Z_COMPILER_C_HAS_RELIABLE_INTEGER_DIVISION FALSE
#endif

#ifndef Z_COMPILER_C_HAS_REMOVAL_OF_ILL_FORMED_RETURN
#	define Z_COMPILER_C_HAS_REMOVAL_OF_ILL_FORMED_RETURN FALSE
#endif

#ifndef Z_COMPILER_C_HAS_REMOVAL_OF_IMPLICIT_FUNCTION_DECLARATION
#	define Z_COMPILER_C_HAS_REMOVAL_OF_IMPLICIT_FUNCTION_DECLARATION FALSE
#endif

#ifndef Z_COMPILER_C_HAS_REMOVAL_OF_IMPLICIT_INT
#	define Z_COMPILER_C_HAS_REMOVAL_OF_IMPLICIT_INT FALSE
#endif

#ifndef Z_COMPILER_C_HAS_STATIC_AND_TYPE_QUALIFIERS_IN_ARRAY_PARAMETER
#	define Z_COMPILER_C_HAS_STATIC_AND_TYPE_QUALIFIERS_IN_ARRAY_PARAMETER FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TRAILING_COMMA_ALLOWED_IN_ENUMERATION
#	define Z_COMPILER_C_HAS_TRAILING_COMMA_ALLOWED_IN_ENUMERATION FALSE
#endif

#ifndef Z_COMPILER_C_HAS_UNIVERSAL_CHARACTER_NAMES
#	define Z_COMPILER_C_HAS_UNIVERSAL_CHARACTER_NAMES FALSE
#endif

#ifndef Z_COMPILER_C_HAS_VARIADIC_MACRO
#	define Z_COMPILER_C_HAS_VARIADIC_MACRO FALSE
#endif

#ifndef Z_COMPILER_C_HAS_VLA
#	define Z_COMPILER_C_HAS_VLA FALSE
#endif

#ifndef Z_COMPILER_C_HAS_IDENTIFIER_FUNC
#	define Z_COMPILER_C_HAS_IDENTIFIER_FUNC FALSE
#endif

#ifndef Z_COMPILER_C_HAS_LITERAL_HEXADECIMAL_FLOATING_POINT
#	define Z_COMPILER_C_HAS_LITERAL_HEXADECIMAL_FLOATING_POINT FALSE
#endif

#ifndef Z_COMPILER_C_HAS_LITERAL_WCHAR_T_CHARACTER
#	define Z_COMPILER_C_HAS_LITERAL_WCHAR_T_CHARACTER FALSE
#endif

#ifndef Z_COMPILER_C_HAS_LITERAL_WCHAR_T_STRING
#	define Z_COMPILER_C_HAS_LITERAL_WCHAR_T_STRING FALSE
#endif

#ifndef Z_COMPILER_C_HAS_PREPROCESSOR_OPERATOR_PRAGMA
#	define Z_COMPILER_C_HAS_PREPROCESSOR_OPERATOR_PRAGMA FALSE
#endif

#ifndef Z_COMPILER_C_HAS_SPECIFIER_INLINE
#	define Z_COMPILER_C_HAS_SPECIFIER_INLINE FALSE
#endif

#ifndef Z_COMPILER_C_HAS_STANDARD_PRAGMA_CX_LIMITED_RANGE
#	define Z_COMPILER_C_HAS_STANDARD_PRAGMA_CX_LIMITED_RANGE FALSE
#endif

#ifndef Z_COMPILER_C_HAS_STANDARD_PRAGMA_FENV_ACCESS
#	define Z_COMPILER_C_HAS_STANDARD_PRAGMA_FENV_ACCESS FALSE
#endif

#ifndef Z_COMPILER_C_HAS_STANDARD_PRAGMA_FP_CONTRACT
#	define Z_COMPILER_C_HAS_STANDARD_PRAGMA_FP_CONTRACT FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_BOOL
#	define Z_COMPILER_C_HAS_TYPE_BOOL FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_DOUBLE_COMPLEX
#	define Z_COMPILER_C_HAS_TYPE_DOUBLE_COMPLEX FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_DOUBLE_IMAGINARY
#	define Z_COMPILER_C_HAS_TYPE_DOUBLE_IMAGINARY FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_FLOAT_COMPLEX
#	define Z_COMPILER_C_HAS_TYPE_FLOAT_COMPLEX FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_FLOAT_IMAGINARY
#	define Z_COMPILER_C_HAS_TYPE_FLOAT_IMAGINARY FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_LONG_DOUBLE_COMPLEX
#	define Z_COMPILER_C_HAS_TYPE_LONG_DOUBLE_COMPLEX FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_LONG_DOUBLE_IMAGINARY
#	define Z_COMPILER_C_HAS_TYPE_LONG_DOUBLE_IMAGINARY FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_LONG_LONG
#	define Z_COMPILER_C_HAS_TYPE_LONG_LONG FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_MODIFIER_COMPLEX
#	define Z_COMPILER_C_HAS_TYPE_MODIFIER_COMPLEX FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_MODIFIER_IMAGINARY
#	define Z_COMPILER_C_HAS_TYPE_MODIFIER_IMAGINARY FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_QUALIFIER_RESTRICT
#	define Z_COMPILER_C_HAS_TYPE_QUALIFIER_RESTRICT FALSE
#endif

/* MARK: - C11 */

#ifndef Z_COMPILER_C_HAS_ANONYMOUS_STRUCTURE
#	define Z_COMPILER_C_HAS_ANONYMOUS_STRUCTURE FALSE
#endif

#ifndef Z_COMPILER_C_HAS_ANONYMOUS_UNION
#	define Z_COMPILER_C_HAS_ANONYMOUS_UNION FALSE
#endif

#ifndef Z_COMPILER_C_HAS_GENERIC_SELECTION
#	define Z_COMPILER_C_HAS_GENERIC_SELECTION FALSE
#endif

#ifndef Z_COMPILER_C_HAS_STATIC_ASSERTION
#	define Z_COMPILER_C_HAS_STATIC_ASSERTION FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPEDEF_REDECLARATION
#	define Z_COMPILER_C_HAS_TYPEDEF_REDECLARATION FALSE
#endif

#ifndef Z_COMPILER_C_HAS_LITERAL_CHAR16_T_CHARACTER
#	define Z_COMPILER_C_HAS_LITERAL_CHAR16_T_CHARACTER FALSE
#endif

#ifndef Z_COMPILER_C_HAS_LITERAL_CHAR16_T_STRING
#	define Z_COMPILER_C_HAS_LITERAL_CHAR16_T_STRING FALSE
#endif

#ifndef Z_COMPILER_C_HAS_LITERAL_CHAR32_T_CHARACTER
#	define Z_COMPILER_C_HAS_LITERAL_CHAR32_T_CHARACTER FALSE
#endif

#ifndef Z_COMPILER_C_HAS_LITERAL_CHAR32_T_STRING
#	define Z_COMPILER_C_HAS_LITERAL_CHAR32_T_STRING FALSE
#endif

#ifndef Z_COMPILER_C_HAS_LITERAL_UNICODE_STRING
#	define Z_COMPILER_C_HAS_LITERAL_UNICODE_STRING FALSE
#endif

#ifndef Z_COMPILER_C_HAS_OPERATOR_ALIGNOF
#	define Z_COMPILER_C_HAS_OPERATOR_ALIGNOF FALSE
#endif

#ifndef Z_COMPILER_C_HAS_SPECIFIER_ALIGNAS
#	define Z_COMPILER_C_HAS_SPECIFIER_ALIGNAS FALSE
#endif

#ifndef Z_COMPILER_C_HAS_SPECIFIER_NORETURN
#	define Z_COMPILER_C_HAS_SPECIFIER_NORETURN FALSE
#endif

#ifndef Z_COMPILER_C_HAS_STORAGE_CLASS_THREAD_LOCAL
#	define Z_COMPILER_C_HAS_STORAGE_CLASS_THREAD_LOCAL FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_MODIFIER_ATOMIC
#	define Z_COMPILER_C_HAS_TYPE_MODIFIER_ATOMIC FALSE
#endif

#ifndef Z_COMPILER_C_HAS_TYPE_QUALIFIER_ATOMIC
#	define Z_COMPILER_C_HAS_TYPE_QUALIFIER_ATOMIC FALSE
#endif

/* MARK: - Apple C extensions support */

#ifndef Z_COMPILER_C_HAS_CLOSURE
#	define Z_COMPILER_C_HAS_CLOSURE FALSE
#endif

#ifdef __cplusplus

	/* MARK: - C++98 support */

#	ifndef Z_COMPILER_CPP_HAS_SFINAE
#		define Z_COMPILER_CPP_HAS_SFINAE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_TYPE_BOOL
#		define Z_COMPILER_CPP_HAS_TYPE_BOOL FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_TYPE_WCHAR_T
#		define Z_COMPILER_CPP_HAS_TYPE_WCHAR_T FALSE
#	endif

	/* MARK: - C++03 support */

#	ifndef Z_COMPILER_CPP_HAS_VALUE_INITIALIZATION
#		define Z_COMPILER_CPP_HAS_VALUE_INITIALIZATION FALSE
#	endif

	/* MARK: - C++11 support */

#	ifndef Z_COMPILER_CPP_HAS_C99_PREPROCESSOR
#		define Z_COMPILER_CPP_HAS_C99_PREPROCESSOR FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_CONCURRENT_STATIC_LOCAL_VARIABLE
#		define Z_COMPILER_CPP_HAS_CONCURRENT_STATIC_LOCAL_VARIABLE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_CONDITIONALLY_SUPPORTED_BEHAVIOR
#		define Z_COMPILER_CPP_HAS_CONDITIONALLY_SUPPORTED_BEHAVIOR FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_COPY_LIST_INITIALIZATION
#		define Z_COMPILER_CPP_HAS_COPY_LIST_INITIALIZATION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_CPP11_RULES_ON_UNIVERSAL_CHARACTER_NAMES
#		define Z_COMPILER_CPP_HAS_CPP11_RULES_ON_UNIVERSAL_CHARACTER_NAMES FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_DEFAULT_MEMBER_INITIALIZER
#		define Z_COMPILER_CPP_HAS_DEFAULT_MEMBER_INITIALIZER FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_DEFAULT_TEMPLATE_ARGUMENTS_FOR_FUNCTION_TEMPLATE
#		define Z_COMPILER_CPP_HAS_DEFAULT_TEMPLATE_ARGUMENTS_FOR_FUNCTION_TEMPLATE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_DEFAULTED_FUNCTION
#		define Z_COMPILER_CPP_HAS_DEFAULTED_FUNCTION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_DELEGATING_CONSTRUCTORS
#		define Z_COMPILER_CPP_HAS_DELEGATING_CONSTRUCTORS FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_DELETED_FUNCTION
#		define Z_COMPILER_CPP_HAS_DELETED_FUNCTION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_DIRECT_LIST_INITIALIZATION
#		define Z_COMPILER_CPP_HAS_DIRECT_LIST_INITIALIZATION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_EXPRESSION_SFINAE
#		define Z_COMPILER_CPP_HAS_EXPRESSION_SFINAE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_EXTENDED_FRIEND_DECLARATION
#		define Z_COMPILER_CPP_HAS_EXTENDED_FRIEND_DECLARATION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_EXTERN_TEMPLATE
#		define Z_COMPILER_CPP_HAS_EXTERN_TEMPLATE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_INHERITING_CONSTRUCTORS
#		define Z_COMPILER_CPP_HAS_INHERITING_CONSTRUCTORS FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_INITIALIZATION_OF_CLASS_OBJECT_BY_RVALUE
#		define Z_COMPILER_CPP_HAS_INITIALIZATION_OF_CLASS_OBJECT_BY_RVALUE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_INITIALIZER_LIST
#		define Z_COMPILER_CPP_HAS_INITIALIZER_LIST FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_LAMBDA
#		define Z_COMPILER_CPP_HAS_LAMBDA FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_LOCAL_TYPE_AS_TEMPLATE_ARGUMENT
#		define Z_COMPILER_CPP_HAS_LOCAL_TYPE_AS_TEMPLATE_ARGUMENT FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_MOVE_SPECIAL_MEMBER_FUNCTIONS
#		define Z_COMPILER_CPP_HAS_MOVE_SPECIAL_MEMBER_FUNCTIONS FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_MULTI_DECLARATOR_AUTO
#		define Z_COMPILER_CPP_HAS_MULTI_DECLARATOR_AUTO FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_OPAQUE_ENUMERATION_DECLARATION
#		define Z_COMPILER_CPP_HAS_OPAQUE_ENUMERATION_DECLARATION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_RANGE_BASED_FOR
#		define Z_COMPILER_CPP_HAS_RANGE_BASED_FOR FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_REFERENCE_QUALIFIED_NON_STATIC_MEMBER_FUNCTION
#		define Z_COMPILER_CPP_HAS_REFERENCE_QUALIFIED_NON_STATIC_MEMBER_FUNCTION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_REMOVAL_OF_AUTO_AS_STORAGE_CLASS
#		define Z_COMPILER_CPP_HAS_REMOVAL_OF_AUTO_AS_STORAGE_CLASS FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_RIGHT_ANGLE_BRACKETS
#		define Z_COMPILER_CPP_HAS_RIGHT_ANGLE_BRACKETS FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_RVALUE_REFERENCE
#		define Z_COMPILER_CPP_HAS_RVALUE_REFERENCE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_STANDARD_LAYOUT
#		define Z_COMPILER_CPP_HAS_STANDARD_LAYOUT FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_STANDARDIZED_ATTRIBUTE_SYNTAX
#		define Z_COMPILER_CPP_HAS_STANDARDIZED_ATTRIBUTE_SYNTAX FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_STATIC_ASSERTION
#		define Z_COMPILER_CPP_HAS_STATIC_ASSERTION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_STRONGLY_TYPED_ENUMERATION
#		define Z_COMPILER_CPP_HAS_STRONGLY_TYPED_ENUMERATION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_TEMPLATE_ALIAS
#		define Z_COMPILER_CPP_HAS_TEMPLATE_ALIAS FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_TRAILING_RETURN_TYPE
#		define Z_COMPILER_CPP_HAS_TRAILING_RETURN_TYPE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_UNNAMED_TYPE_AS_TEMPLATE_ARGUMENT
#		define Z_COMPILER_CPP_HAS_UNNAMED_TYPE_AS_TEMPLATE_ARGUMENT FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_UNRESTRICTED_UNION
#		define Z_COMPILER_CPP_HAS_UNRESTRICTED_UNION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_VARIADIC_TEMPLATE
#		define Z_COMPILER_CPP_HAS_VARIADIC_TEMPLATE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_VARIADIC_TEMPLATE_EXTENDED_PARAMETERS
#		define Z_COMPILER_CPP_HAS_VARIADIC_TEMPLATE_EXTENDED_PARAMETERS FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_ATTRIBUTE_CARRIES_DEPENDENCY
#		define Z_COMPILER_CPP_HAS_ATTRIBUTE_CARRIES_DEPENDENCY FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_ATTRIBUTE_NORETURN
#		define Z_COMPILER_CPP_HAS_ATTRIBUTE_NORETURN FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_IDENTIFIER_FUNC
#		define Z_COMPILER_CPP_HAS_IDENTIFIER_FUNC FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_LITERAL_CHAR16_T_CHARACTER
#		define Z_COMPILER_CPP_HAS_LITERAL_CHAR16_T_CHARACTER FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_LITERAL_CHAR16_T_STRING
#		define Z_COMPILER_CPP_HAS_LITERAL_CHAR16_T_STRING FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_LITERAL_CHAR32_T_CHARACTER
#		define Z_COMPILER_CPP_HAS_LITERAL_CHAR32_T_CHARACTER FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_LITERAL_CHAR32_T_STRING
#		define Z_COMPILER_CPP_HAS_LITERAL_CHAR32_T_STRING FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_LITERAL_NULLPTR
#		define Z_COMPILER_CPP_HAS_LITERAL_NULLPTR FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_LITERAL_RAW_STRING
#		define Z_COMPILER_CPP_HAS_LITERAL_RAW_STRING FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_LITERAL_USER_DEFINED
#		define Z_COMPILER_CPP_HAS_LITERAL_USER_DEFINED FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_LITERAL_UTF8_STRING
#		define Z_COMPILER_CPP_HAS_LITERAL_UTF8_STRING FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_OPERATOR_ALIGNOF
#		define Z_COMPILER_CPP_HAS_OPERATOR_ALIGNOF FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_OPERATOR_NOEXCEPT
#		define Z_COMPILER_CPP_HAS_OPERATOR_NOEXCEPT FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_OPERATOR_CASE_SIZEOF_NON_STATIC_DATA_MEMBER
#		define Z_COMPILER_CPP_HAS_OPERATOR_CASE_SIZEOF_NON_STATIC_DATA_MEMBER FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_OPERATOR_CASE_SIZEOF_PARAMETER_PACK
#		define Z_COMPILER_CPP_HAS_OPERATOR_CASE_SIZEOF_PARAMETER_PACK FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_SPECIFIER_ALIGNAS
#		define Z_COMPILER_CPP_HAS_SPECIFIER_ALIGNAS FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_SPECIFIER_CONSTEXPR
#		define Z_COMPILER_CPP_HAS_SPECIFIER_CONSTEXPR FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_SPECIFIER_DECLTYPE
#		define Z_COMPILER_CPP_HAS_SPECIFIER_DECLTYPE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_SPECIFIER_FINAL
#		define Z_COMPILER_CPP_HAS_SPECIFIER_FINAL FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_SPECIFIER_NOEXCEPT
#		define Z_COMPILER_CPP_HAS_SPECIFIER_NOEXCEPT FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_SPECIFIER_OVERRIDE
#		define Z_COMPILER_CPP_HAS_SPECIFIER_OVERRIDE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_SPECIFIER_CASE_DECLTYPE_INCOMPLETE_RETURN
#		define Z_COMPILER_CPP_HAS_SPECIFIER_CASE_DECLTYPE_INCOMPLETE_RETURN FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_SPECIFIER_CASE_EXPLICIT_CONVERSION_FUNCTION
#		define Z_COMPILER_CPP_HAS_SPECIFIER_CASE_EXPLICIT_CONVERSION_FUNCTION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_SPECIFIER_CASE_INLINE_NAMESPACE
#		define Z_COMPILER_CPP_HAS_SPECIFIER_CASE_INLINE_NAMESPACE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_STORAGE_CLASS_THREAD_LOCAL
#		define Z_COMPILER_CPP_HAS_STORAGE_CLASS_THREAD_LOCAL FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_TYPE_AUTO
#		define Z_COMPILER_CPP_HAS_TYPE_AUTO FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_TYPE_CHAR16_T
#		define Z_COMPILER_CPP_HAS_TYPE_CHAR16_T FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_TYPE_CHAR32_T
#		define Z_COMPILER_CPP_HAS_TYPE_CHAR32_T FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_TYPE_LONG_LONG
#		define Z_COMPILER_CPP_HAS_TYPE_LONG_LONG FALSE
#	endif

	/* MARK: - C++14 support */

#	ifndef Z_COMPILER_CPP_HAS_APOSTROPHE_AS_DIGIT_SEPARATOR
#		define Z_COMPILER_CPP_HAS_APOSTROPHE_AS_DIGIT_SEPARATOR FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_CPP14_RULES_ON_CONSTEXPR_FUNCTION
#		define Z_COMPILER_CPP_HAS_CPP14_RULES_ON_CONSTEXPR_FUNCTION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_CPP14_RULES_ON_CONTEXTUAL_CONVERSION
#		define Z_COMPILER_CPP_HAS_CPP14_RULES_ON_CONTEXTUAL_CONVERSION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_DEFAULT_MEMBER_INITIALIZER_FOR_AGGREGATE
#		define Z_COMPILER_CPP_HAS_DEFAULT_MEMBER_INITIALIZER_FOR_AGGREGATE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_GENERIC_LAMBDA
#		define Z_COMPILER_CPP_HAS_GENERIC_LAMBDA FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_INITIALIZED_LAMBDA_CAPTURE
#		define Z_COMPILER_CPP_HAS_INITIALIZED_LAMBDA_CAPTURE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_RETURN_TYPE_DEDUCTION_FOR_NORMAL_FUNCTION
#		define Z_COMPILER_CPP_HAS_RETURN_TYPE_DEDUCTION_FOR_NORMAL_FUNCTION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_SIZED_DEALLOCATION
#		define Z_COMPILER_CPP_HAS_SIZED_DEALLOCATION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_VARIABLE_TEMPLATE
#		define Z_COMPILER_CPP_HAS_VARIABLE_TEMPLATE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_ATTRIBUTE_DEPRECATED
#		define Z_COMPILER_CPP_HAS_ATTRIBUTE_DEPRECATED FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_LITERAL_BINARY_INTEGRAL
#		define Z_COMPILER_CPP_HAS_LITERAL_BINARY_INTEGRAL FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_SPECIFIER_CASE_DECLTYPE_AUTO
#		define Z_COMPILER_CPP_HAS_SPECIFIER_CASE_DECLTYPE_AUTO FALSE
#	endif

	/* MARK: - C++17 support */

#	ifndef Z_COMPILER_CPP_HAS_AGGREGATE_INITIALIZATION_FOR_DERIVED_CLASS
#		define Z_COMPILER_CPP_HAS_AGGREGATE_INITIALIZATION_FOR_DERIVED_CLASS FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_ATTRIBUTES_FOR_ENUMERATION
#		define Z_COMPILER_CPP_HAS_ATTRIBUTES_FOR_ENUMERATION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_ATTRIBUTES_FOR_NAMESPACE
#		define Z_COMPILER_CPP_HAS_ATTRIBUTES_FOR_NAMESPACE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_ATTRIBUTE_USING_PREFIX
#		define Z_COMPILER_CPP_HAS_ATTRIBUTE_USING_PREFIX FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_CPP17_RULES_ON_AUTO_AND_BRACED_INITIALIZATION
#		define Z_COMPILER_CPP_HAS_CPP17_RULES_ON_AUTO_AND_BRACED_INITIALIZATION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_CPP17_RULES_ON_EXPRESSION_EVALUATION_ORDER
#		define Z_COMPILER_CPP_HAS_CPP17_RULES_ON_EXPRESSION_EVALUATION_ORDER FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_CPP17_RULES_ON_INHERITING_CONSTRUCTORS
#		define Z_COMPILER_CPP_HAS_CPP17_RULES_ON_INHERITING_CONSTRUCTORS FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_CPP17_RULES_ON_NON_TYPE_TEMPLATE_ARGUMENTS
#		define Z_COMPILER_CPP_HAS_CPP17_RULES_ON_NON_TYPE_TEMPLATE_ARGUMENTS FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_CPP17_RULES_ON_TEMPLATE_TEMPLATE_ARGUMENT_MATCHING
#		define Z_COMPILER_CPP_HAS_CPP17_RULES_ON_TEMPLATE_TEMPLATE_ARGUMENT_MATCHING FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_DIFFERING_BEGIN_AND_END_TYPES_IN_RANGE_BASED_FOR
#		define Z_COMPILER_CPP_HAS_DIFFERING_BEGIN_AND_END_TYPES_IN_RANGE_BASED_FOR FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_DIRECT_LIST_INITIALIZATION_FOR_ENUMERATION
#		define Z_COMPILER_CPP_HAS_DIRECT_LIST_INITIALIZATION_FOR_ENUMERATION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_NOEXCEPT_AS_PART_OF_THE_TYPE
#		define Z_COMPILER_CPP_HAS_NOEXCEPT_AS_PART_OF_THE_TYPE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_FOLD_EXPRESSION
#		define Z_COMPILER_CPP_HAS_FOLD_EXPRESSION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_FOLD_EXPRESSION_SAFETY_WITH_EMPTY_PARAMETER_PACK
#		define Z_COMPILER_CPP_HAS_FOLD_EXPRESSION_SAFETY_WITH_EMPTY_PARAMETER_PACK FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_GUARANTEED_COPY_ELISION
#		define Z_COMPILER_CPP_HAS_GUARANTEED_COPY_ELISION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_IF_WITH_INITIALIZER
#		define Z_COMPILER_CPP_HAS_IF_WITH_INITIALIZER FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_IGNORATION_OF_UNKNOWN_ATTRIBUTES
#		define Z_COMPILER_CPP_HAS_IGNORATION_OF_UNKNOWN_ATTRIBUTES FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_LAMBDA_CAPTURE_OF_THIS_OBJECT_BY_VALUE
#		define Z_COMPILER_CPP_HAS_LAMBDA_CAPTURE_OF_THIS_OBJECT_BY_VALUE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_LAUNDER
#		define Z_COMPILER_CPP_HAS_LAUNDER FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_NESTED_NAMESPACE_DEFINITION
#		define Z_COMPILER_CPP_HAS_NESTED_NAMESPACE_DEFINITION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_NON_TYPE_TEMPLATE_PARAMETER_WITH_AUTO_TYPE
#		define Z_COMPILER_CPP_HAS_NON_TYPE_TEMPLATE_PARAMETER_WITH_AUTO_TYPE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_OVER_ALIGNED_DYNAMIC_ALLOCATION
#		define Z_COMPILER_CPP_HAS_OVER_ALIGNED_DYNAMIC_ALLOCATION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_REMOVAL_OF_DYNAMIC_EXCEPTION_SPECIFICATION
#		define Z_COMPILER_CPP_HAS_REMOVAL_OF_DYNAMIC_EXCEPTION_SPECIFICATION FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_REMOVAL_OF_INCREMENT_OPERATOR_WITH_BOOL_OPERAND
#		define Z_COMPILER_CPP_HAS_REMOVAL_OF_INCREMENT_OPERATOR_WITH_BOOL_OPERAND FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_REMOVAL_OF_REGISTER_AS_STORAGE_CLASS
#		define Z_COMPILER_CPP_HAS_REMOVAL_OF_REGISTER_AS_STORAGE_CLASS FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_REMOVAL_OF_TRIGRAPHS
#		define Z_COMPILER_CPP_HAS_REMOVAL_OF_TRIGRAPHS FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_STATIC_ASSERTION_WITH_NO_MESSAGE
#		define Z_COMPILER_CPP_HAS_STATIC_ASSERTION_WITH_NO_MESSAGE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_STRUCTURED_BINDING
#		define Z_COMPILER_CPP_HAS_STRUCTURED_BINDING FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_SWITCH_WITH_INITIALIZER
#		define Z_COMPILER_CPP_HAS_SWITCH_WITH_INITIALIZER FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_TEMPLATE_ARGUMENT_DEDUCTION_FOR_CLASS_TEMPLATE
#		define Z_COMPILER_CPP_HAS_TEMPLATE_ARGUMENT_DEDUCTION_FOR_CLASS_TEMPLATE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_TYPENAME_IN_TEMPLATE_TEMPLATE_PARAMETER
#		define Z_COMPILER_CPP_HAS_TYPENAME_IN_TEMPLATE_TEMPLATE_PARAMETER FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_VARIADIC_USING
#		define Z_COMPILER_CPP_HAS_VARIADIC_USING FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_ATTRIBUTE_FALLTHROUGH
#		define Z_COMPILER_CPP_HAS_ATTRIBUTE_FALLTHROUGH FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_ATTRIBUTE_MAYBE_UNUSED
#		define Z_COMPILER_CPP_HAS_ATTRIBUTE_MAYBE_UNUSED FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_ATTRIBUTE_NODISCARD
#		define Z_COMPILER_CPP_HAS_ATTRIBUTE_NODISCARD FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_LITERAL_HEXADECIMAL_FLOATING_POINT
#		define Z_COMPILER_CPP_HAS_LITERAL_HEXADECIMAL_FLOATING_POINT FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_LITERAL_UTF8_CHARACTER
#		define Z_COMPILER_CPP_HAS_LITERAL_UTF8_CHARACTER FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_PREPROCESSOR_OPERATOR_HAS_INCLUDE
#		define Z_COMPILER_CPP_HAS_PREPROCESSOR_OPERATOR_HAS_INCLUDE FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_SPECIFIER_CASE_CONSTEXPR_IF
#		define Z_COMPILER_CPP_HAS_SPECIFIER_CASE_CONSTEXPR_IF FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_SPECIFIER_CASE_CONSTEXPR_LAMBDA
#		define Z_COMPILER_CPP_HAS_SPECIFIER_CASE_CONSTEXPR_LAMBDA FALSE
#	endif

#	ifndef Z_COMPILER_CPP_HAS_SPECIFIER_CASE_INLINE_VARIABLE
#		define Z_COMPILER_CPP_HAS_SPECIFIER_CASE_INLINE_VARIABLE FALSE
#	endif

#endif

/* MARK: - Attributes */

#ifdef Z_COMPILER_ATTRIBUTE_ALIAS
#	define Z_COMPILER_HAS_ATTRIBUTE_ALIAS TRUE
#else
#	define Z_COMPILER_HAS_ATTRIBUTE_ALIAS FALSE
#endif

#ifdef Z_COMPILER_ATTRIBUTE_API
#	define Z_COMPILER_HAS_ATTRIBUTE_API TRUE
#else
#	define Z_COMPILER_HAS_ATTRIBUTE_API FALSE
#endif

#ifdef Z_COMPILER_ATTRIBUTE_API_ALIAS
#	define Z_COMPILER_HAS_ATTRIBUTE_API_ALIAS TRUE
#else
#	define Z_COMPILER_HAS_ATTRIBUTE_API_ALIAS FALSE
#endif

#ifdef Z_COMPILER_ATTRIBUTE_API_EXPORT
#	define Z_COMPILER_HAS_ATTRIBUTE_API_EXPORT TRUE
#else
#	define Z_COMPILER_HAS_ATTRIBUTE_API_EXPORT FALSE
#endif

#ifdef Z_COMPILER_ATTRIBUTE_API_EXPORT_ALIAS
#	define Z_COMPILER_HAS_ATTRIBUTE_API_EXPORT_ALIAS TRUE
#else
#	define Z_COMPILER_HAS_ATTRIBUTE_API_EXPORT_ALIAS FALSE
#endif

#ifdef Z_COMPILER_ATTRIBUTE_API_WEAK_EXPORT
#	define Z_COMPILER_HAS_ATTRIBUTE_API_WEAK_EXPORT TRUE
#else
#	define Z_COMPILER_HAS_ATTRIBUTE_API_WEAK_EXPORT FALSE
#endif

#ifdef Z_COMPILER_ATTRIBUTE_EBCO
#	define Z_COMPILER_HAS_ATTRIBUTE_EBCO TRUE
#else
#	define Z_COMPILER_HAS_ATTRIBUTE_EBCO FALSE
#endif

#ifdef Z_COMPILER_ATTRIBUTE_INLINE
#	define Z_COMPILER_HAS_ATTRIBUTE_INLINE TRUE
#else
#	define Z_COMPILER_HAS_ATTRIBUTE_INLINE FALSE
#endif

#ifdef Z_COMPILER_ATTRIBUTE_NO_RETURN
#	define Z_COMPILER_HAS_ATTRIBUTE_NO_RETURN TRUE
#else
#	define Z_COMPILER_HAS_ATTRIBUTE_NO_RETURN FALSE
#endif

#ifdef Z_COMPILER_ATTRIBUTE_NULL_TERMINATED
#	define Z_COMPILER_HAS_ATTRIBUTE_NULL_TERMINATED TRUE
#else
#	define Z_COMPILER_HAS_ATTRIBUTE_NULL_TERMINATED FALSE
#endif

#ifdef Z_COMPILER_ATTRIBUTE_PRIVATE
#	define Z_COMPILER_HAS_ATTRIBUTE_PRIVATE TRUE
#else
#	define Z_COMPILER_HAS_ATTRIBUTE_PRIVATE FALSE
#endif

#ifdef Z_COMPILER_ATTRIBUTE_PUBLIC
#	define Z_COMPILER_HAS_ATTRIBUTE_PUBLIC TRUE
#else
#	define Z_COMPILER_HAS_ATTRIBUTE_PUBLIC FALSE
#endif

#ifdef Z_COMPILER_ATTRIBUTE_THREAD_LOCAL
#	define Z_COMPILER_HAS_ATTRIBUTE_THREAD_LOCAL TRUE
#else
#	define Z_COMPILER_HAS_ATTRIBUTE_THREAD_LOCAL FALSE
#endif

#ifdef Z_COMPILER_ATTRIBUTE_WEAK
#	define Z_COMPILER_HAS_ATTRIBUTE_WEAK TRUE
#else
#	define Z_COMPILER_HAS_ATTRIBUTE_WEAK FALSE
#endif

/* MARK: - Built-in constants */

#ifdef Z_COMPILER_CONSTANT_FLOAT16_INFINITY
#	define Z_COMPILER_HAS_CONSTANT_FLOAT16_INFINITY TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_FLOAT16_INFINITY FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_FLOAT16_NAN
#	define Z_COMPILER_HAS_CONSTANT_FLOAT16_NAN TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_FLOAT16_NAN FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_FLOAT32_INFINITY
#	define Z_COMPILER_HAS_CONSTANT_FLOAT32_INFINITY TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_FLOAT32_INFINITY FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_FLOAT32_NAN
#	define Z_COMPILER_HAS_CONSTANT_FLOAT32_NAN TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_FLOAT32_NAN FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_FLOAT64_INFINITY
#	define Z_COMPILER_HAS_CONSTANT_FLOAT64_INFINITY TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_FLOAT64_INFINITY FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_FLOAT64_NAN
#	define Z_COMPILER_HAS_CONSTANT_FLOAT64_NAN TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_FLOAT64_NAN FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_FLOAT128_INFINITY
#	define Z_COMPILER_HAS_CONSTANT_FLOAT128_INFINITY TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_FLOAT128_INFINITY FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_FLOAT128_NAN
#	define Z_COMPILER_HAS_CONSTANT_FLOAT128_NAN TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_FLOAT128_NAN FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_FLOAT80_X87_INFINITY
#	define Z_COMPILER_HAS_CONSTANT_FLOAT80_X87_INFINITY TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_FLOAT80_X87_INFINITY FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_FLOAT80_X87_NAN
#	define Z_COMPILER_HAS_CONSTANT_FLOAT80_X87_NAN TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_FLOAT80_X87_NAN FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_FLOAT96_X87_INFINITY
#	define Z_COMPILER_HAS_CONSTANT_FLOAT96_X87_INFINITY TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_FLOAT96_X87_INFINITY FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_FLOAT96_X87_NAN
#	define Z_COMPILER_HAS_CONSTANT_FLOAT96_X87_NAN TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_FLOAT96_X87_NAN FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_FLOAT128_X87_INFINITY
#	define Z_COMPILER_HAS_CONSTANT_FLOAT128_X87_INFINITY TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_FLOAT128_X87_INFINITY FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_FLOAT128_X87_NAN
#	define Z_COMPILER_HAS_CONSTANT_FLOAT128_X87_NAN TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_FLOAT128_X87_NAN FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_CHAR_BITS
#	define Z_COMPILER_HAS_CONSTANT_CHAR_BITS TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_CHAR_BITS FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_UCHAR_MAXIMUM
#	define Z_COMPILER_HAS_CONSTANT_UCHAR_MAXIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_UCHAR_MAXIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SCHAR_MINIMUM
#	define Z_COMPILER_HAS_CONSTANT_SCHAR_MINIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SCHAR_MINIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SCHAR_MAXIMUM
#	define Z_COMPILER_HAS_CONSTANT_SCHAR_MAXIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SCHAR_MAXIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SHORT_BITS
#	define Z_COMPILER_HAS_CONSTANT_SHORT_BITS TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SHORT_BITS FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SHORT_SIZE
#	define Z_COMPILER_HAS_CONSTANT_SHORT_SIZE TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SHORT_SIZE FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_USHORT_MAXIMUM
#	define Z_COMPILER_HAS_CONSTANT_USHORT_MAXIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_USHORT_MAXIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SSHORT_MINIMUM
#	define Z_COMPILER_HAS_CONSTANT_SSHORT_MINIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SSHORT_MINIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SSHORT_MAXIMUM
#	define Z_COMPILER_HAS_CONSTANT_SSHORT_MAXIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SSHORT_MAXIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_INT_BITS
#	define Z_COMPILER_HAS_CONSTANT_INT_BITS TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_INT_BITS FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_INT_SIZE
#	define Z_COMPILER_HAS_CONSTANT_INT_SIZE TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_INT_SIZE FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_UINT_MAXIMUM
#	define Z_COMPILER_HAS_CONSTANT_UINT_MAXIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_UINT_MAXIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SINT_MINIMUM
#	define Z_COMPILER_HAS_CONSTANT_SINT_MINIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SINT_MINIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SINT_MAXIMUM
#	define Z_COMPILER_HAS_CONSTANT_SINT_MAXIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SINT_MAXIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_LONG_BITS
#	define Z_COMPILER_HAS_CONSTANT_LONG_BITS TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_LONG_BITS FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_LONG_SIZE
#	define Z_COMPILER_HAS_CONSTANT_LONG_SIZE TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_LONG_SIZE FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_ULONG_MAXIMUM
#	define Z_COMPILER_HAS_CONSTANT_ULONG_MAXIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_ULONG_MAXIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SLONG_MINIMUM
#	define Z_COMPILER_HAS_CONSTANT_SLONG_MINIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SLONG_MINIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SLONG_MAXIMUM
#	define Z_COMPILER_HAS_CONSTANT_SLONG_MAXIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SLONG_MAXIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_LLONG_BITS
#	define Z_COMPILER_HAS_CONSTANT_LLONG_BITS TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_LLONG_BITS FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_LLONG_SIZE
#	define Z_COMPILER_HAS_CONSTANT_LLONG_SIZE TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_LLONG_SIZE FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_ULLONG_MAXIMUM
#	define Z_COMPILER_HAS_CONSTANT_ULLONG_MAXIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_ULLONG_MAXIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SLLONG_MINIMUM
#	define Z_COMPILER_HAS_CONSTANT_SLLONG_MINIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SLLONG_MINIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SLLONG_MAXIMUM
#	define Z_COMPILER_HAS_CONSTANT_SLLONG_MAXIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SLLONG_MAXIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_FLOAT_BITS
#	define Z_COMPILER_HAS_CONSTANT_FLOAT_BITS TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_FLOAT_BITS FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_FLOAT_SIZE
#	define Z_COMPILER_HAS_CONSTANT_FLOAT_SIZE TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_FLOAT_SIZE FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_FLOAT_INFINITY
#	define Z_COMPILER_HAS_CONSTANT_FLOAT_INFINITY TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_FLOAT_INFINITY FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_FLOAT_NAN
#	define Z_COMPILER_HAS_CONSTANT_FLOAT_NAN TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_FLOAT_NAN FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_DOUBLE_BITS
#	define Z_COMPILER_HAS_CONSTANT_DOUBLE_BITS TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_DOUBLE_BITS FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_DOUBLE_SIZE
#	define Z_COMPILER_HAS_CONSTANT_DOUBLE_SIZE TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_DOUBLE_SIZE FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_DOUBLE_INFINITY
#	define Z_COMPILER_HAS_CONSTANT_DOUBLE_INFINITY TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_DOUBLE_INFINITY FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_DOUBLE_NAN
#	define Z_COMPILER_HAS_CONSTANT_DOUBLE_NAN TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_DOUBLE_NAN FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_LDOUBLE_BITS
#	define Z_COMPILER_HAS_CONSTANT_LDOUBLE_BITS TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_LDOUBLE_BITS FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_LDOUBLE_SIZE
#	define Z_COMPILER_HAS_CONSTANT_LDOUBLE_SIZE TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_LDOUBLE_SIZE FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_LDOUBLE_INFINITY
#	define Z_COMPILER_HAS_CONSTANT_LDOUBLE_INFINITY TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_LDOUBLE_INFINITY FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_LDOUBLE_NAN
#	define Z_COMPILER_HAS_CONSTANT_LDOUBLE_NAN TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_LDOUBLE_NAN FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_WCHAR_BITS
#	define Z_COMPILER_HAS_CONSTANT_WCHAR_BITS TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_WCHAR_BITS FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_WCHAR_SIZE
#	define Z_COMPILER_HAS_CONSTANT_WCHAR_SIZE TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_WCHAR_SIZE FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_WCHAR_MAXIMUM
#	define Z_COMPILER_HAS_CONSTANT_WCHAR_MAXIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_WCHAR_MAXIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SIZE_BITS
#	define Z_COMPILER_HAS_CONSTANT_SIZE_BITS TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SIZE_BITS FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SIZE_SIZE
#	define Z_COMPILER_HAS_CONSTANT_SIZE_SIZE TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SIZE_SIZE FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_USIZE_MAXIMUM
#	define Z_COMPILER_HAS_CONSTANT_USIZE_MAXIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_USIZE_MAXIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SSIZE_MINIMUM
#	define Z_COMPILER_HAS_CONSTANT_SSIZE_MINIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SSIZE_MINIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SSIZE_MAXIMUM
#	define Z_COMPILER_HAS_CONSTANT_SSIZE_MAXIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SSIZE_MAXIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_UINTMAX_BITS
#	define Z_COMPILER_HAS_CONSTANT_UINTMAX_BITS TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_UINTMAX_BITS FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_UINTMAX_SIZE
#	define Z_COMPILER_HAS_CONSTANT_UINTMAX_SIZE TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_UINTMAX_SIZE FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_UINTMAX_MAXIMUM
#	define Z_COMPILER_HAS_CONSTANT_UINTMAX_MAXIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_UINTMAX_MAXIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SINTMAX_BITS
#	define Z_COMPILER_HAS_CONSTANT_SINTMAX_BITS TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SINTMAX_BITS FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SINTMAX_SIZE
#	define Z_COMPILER_HAS_CONSTANT_SINTMAX_SIZE TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SINTMAX_SIZE FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SINTMAX_MINIMUM
#	define Z_COMPILER_HAS_CONSTANT_SINTMAX_MINIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SINTMAX_MINIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SINTMAX_MAXIMUM
#	define Z_COMPILER_HAS_CONSTANT_SINTMAX_MAXIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SINTMAX_MAXIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_INTPTR_BITS
#	define Z_COMPILER_HAS_CONSTANT_INTPTR_BITS TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_INTPTR_BITS FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_INTPTR_SIZE
#	define Z_COMPILER_HAS_CONSTANT_INTPTR_SIZE TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_INTPTR_SIZE FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_UINTPTR_MAXIMUM
#	define Z_COMPILER_HAS_CONSTANT_UINTPTR_MAXIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_UINTPTR_MAXIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SINTPTR_MINIMUM
#	define Z_COMPILER_HAS_CONSTANT_SINTPTR_MINIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SINTPTR_MINIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_SINTPTR_MAXIMUM
#	define Z_COMPILER_HAS_CONSTANT_SINTPTR_MAXIMUM TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_SINTPTR_MAXIMUM FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_POINTER_BITS
#	define Z_COMPILER_HAS_CONSTANT_POINTER_BITS TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_POINTER_BITS FALSE
#endif

#ifdef Z_COMPILER_CONSTANT_POINTER_SIZE
#	define Z_COMPILER_HAS_CONSTANT_POINTER_SIZE TRUE
#else
#	define Z_COMPILER_HAS_CONSTANT_POINTER_SIZE FALSE
#endif

/* MARK: - Built-in magic constants */

#ifdef Z_COMPILER_MAGIC_CONSTANT_MANGLED_FUNCTION_NAME
#	define Z_COMPILER_HAS_MAGIC_CONSTANT_MANGLED_FUNCTION_NAME TRUE
#else
#	define Z_COMPILER_HAS_MAGIC_CONSTANT_MANGLED_FUNCTION_NAME FALSE
#endif

/* MARK: - Built-in macros: Struture */

#ifdef Z_COMPILER_MACRO_OFFSET_OF
#	define Z_COMPILER_HAS_MACRO_OFFSET_OF TRUE
#else
#	define Z_COMPILER_HAS_MACRO_OFFSET_OF FALSE
#endif

/* MARK: - Built-in macros: VAL */

#ifdef Z_COMPILER_MACRO_VAL_INITIALIZE
#	define Z_COMPILER_HAS_MACRO_VAL_INITIALIZE TRUE
#else
#	define Z_COMPILER_HAS_MACRO_VAL_INITIALIZE FALSE
#endif

#ifdef Z_COMPILER_MACRO_VAL_FINALIZE
#	define Z_COMPILER_HAS_MACRO_VAL_FINALIZE TRUE
#else
#	define Z_COMPILER_HAS_MACRO_VAL_FINALIZE FALSE
#endif

#ifdef Z_COMPILER_MACRO_VAL_READ
#	define Z_COMPILER_HAS_MACRO_VAL_READ TRUE
#else
#	define Z_COMPILER_HAS_MACRO_VAL_READ FALSE
#endif

#ifdef Z_COMPILER_MACRO_VAL_COPY
#	define Z_COMPILER_HAS_MACRO_VAL_COPY TRUE
#else
#	define Z_COMPILER_HAS_MACRO_VAL_COPY FALSE
#endif

/* MARK: - Built-in types */

#ifdef Z_COMPILER_TYPE_UINT8
#	define Z_COMPILER_HAS_TYPE_UINT8 TRUE
#else
#	define Z_COMPILER_HAS_TYPE_UINT8 FALSE
#endif

#ifdef Z_COMPILER_TYPE_SINT8
#	define Z_COMPILER_HAS_TYPE_SINT8 TRUE
#else
#	define Z_COMPILER_HAS_TYPE_SINT8 FALSE
#endif

#ifdef Z_COMPILER_TYPE_UINT16
#	define Z_COMPILER_HAS_TYPE_UINT16 TRUE
#else
#	define Z_COMPILER_HAS_TYPE_UINT16 FALSE
#endif

#ifdef Z_COMPILER_TYPE_SINT16
#	define Z_COMPILER_HAS_TYPE_SINT16 TRUE
#else
#	define Z_COMPILER_HAS_TYPE_SINT16 FALSE
#endif

#ifdef Z_COMPILER_TYPE_UINT32
#	define Z_COMPILER_HAS_TYPE_UINT32 TRUE
#else
#	define Z_COMPILER_HAS_TYPE_UINT32 FALSE
#endif

#ifdef Z_COMPILER_TYPE_SINT32
#	define Z_COMPILER_HAS_TYPE_SINT32 TRUE
#else
#	define Z_COMPILER_HAS_TYPE_SINT32 FALSE
#endif

#ifdef Z_COMPILER_TYPE_UINT64
#	define Z_COMPILER_HAS_TYPE_UINT64 TRUE
#else
#	define Z_COMPILER_HAS_TYPE_UINT64 FALSE
#endif

#ifdef Z_COMPILER_TYPE_SINT64
#	define Z_COMPILER_HAS_TYPE_SINT64 TRUE
#else
#	define Z_COMPILER_HAS_TYPE_SINT64 FALSE
#endif

#ifdef Z_COMPILER_TYPE_UINT128
#	define Z_COMPILER_HAS_TYPE_UINT128 TRUE
#else
#	define Z_COMPILER_HAS_TYPE_UINT128 FALSE
#endif

#ifdef Z_COMPILER_TYPE_SINT128
#	define Z_COMPILER_HAS_TYPE_SINT128 TRUE
#else
#	define Z_COMPILER_HAS_TYPE_SINT128 FALSE
#endif

#ifdef Z_COMPILER_TYPE_FLOAT16
#	define Z_COMPILER_HAS_TYPE_FLOAT16 TRUE
#else
#	define Z_COMPILER_HAS_TYPE_FLOAT16 FALSE
#endif

#ifdef Z_COMPILER_TYPE_FLOAT32
#	define Z_COMPILER_HAS_TYPE_FLOAT32 TRUE
#else
#	define Z_COMPILER_HAS_TYPE_FLOAT32 FALSE
#endif

#ifdef Z_COMPILER_TYPE_FLOAT64
#	define Z_COMPILER_HAS_TYPE_FLOAT64 TRUE
#else
#	define Z_COMPILER_HAS_TYPE_FLOAT64 FALSE
#endif

#ifdef Z_COMPILER_TYPE_FLOAT128
#	define Z_COMPILER_HAS_TYPE_FLOAT128 TRUE
#else
#	define Z_COMPILER_HAS_TYPE_FLOAT128 FALSE
#endif

#ifdef Z_COMPILER_TYPE_FLOAT80_X87
#	define Z_COMPILER_HAS_TYPE_FLOAT80_X87 TRUE
#else
#	define Z_COMPILER_HAS_TYPE_FLOAT80_X87 FALSE
#endif

#ifdef Z_COMPILER_TYPE_FLOAT96_X87
#	define Z_COMPILER_HAS_TYPE_FLOAT96_X87 TRUE
#else
#	define Z_COMPILER_HAS_TYPE_FLOAT96_X87 FALSE
#endif

#ifdef Z_COMPILER_TYPE_FLOAT128_X87
#	define Z_COMPILER_HAS_TYPE_FLOAT128_X87 TRUE
#else
#	define Z_COMPILER_HAS_TYPE_FLOAT128_X87 FALSE
#endif

#ifdef Z_COMPILER_TYPE_VAL
#	define Z_COMPILER_HAS_TYPE_VAL TRUE
#else
#	define Z_COMPILER_HAS_TYPE_VAL FALSE
#endif

/* MARK: - Suffix macros for built-in types */

#ifdef Z_COMPILER_LITERAL_UINT8
#	define Z_COMPILER_HAS_LITERAL_UINT8 TRUE
#else
#	define Z_COMPILER_HAS_LITERAL_UINT8 FALSE
#endif

#ifdef Z_COMPILER_LITERAL_SINT8
#	define Z_COMPILER_HAS_LITERAL_SINT8 TRUE
#else
#	define Z_COMPILER_HAS_LITERAL_SINT8 FALSE
#endif

#ifdef Z_COMPILER_LITERAL_UINT16
#	define Z_COMPILER_HAS_LITERAL_UINT16 TRUE
#else
#	define Z_COMPILER_HAS_LITERAL_UINT16 FALSE
#endif

#ifdef Z_COMPILER_LITERAL_SINT16
#	define Z_COMPILER_HAS_LITERAL_SINT16 TRUE
#else
#	define Z_COMPILER_HAS_LITERAL_SINT16 FALSE
#endif

#ifdef Z_COMPILER_LITERAL_UINT32
#	define Z_COMPILER_HAS_LITERAL_UINT32 TRUE
#else
#	define Z_COMPILER_HAS_LITERAL_UINT32 FALSE
#endif

#ifdef Z_COMPILER_LITERAL_SINT32
#	define Z_COMPILER_HAS_LITERAL_SINT32 TRUE
#else
#	define Z_COMPILER_HAS_LITERAL_SINT32 FALSE
#endif

#ifdef Z_COMPILER_LITERAL_UINT64
#	define Z_COMPILER_HAS_LITERAL_UINT64 TRUE
#else
#	define Z_COMPILER_HAS_LITERAL_UINT64 FALSE
#endif

#ifdef Z_COMPILER_LITERAL_SINT64
#	define Z_COMPILER_HAS_LITERAL_SINT64 TRUE
#else
#	define Z_COMPILER_HAS_LITERAL_SINT64 FALSE
#endif

#ifdef Z_COMPILER_LITERAL_UINT128
#	define Z_COMPILER_HAS_LITERAL_UINT128 TRUE
#else
#	define Z_COMPILER_HAS_LITERAL_UINT128 FALSE
#endif

#ifdef Z_COMPILER_LITERAL_SINT128
#	define Z_COMPILER_HAS_LITERAL_SINT128 TRUE
#else
#	define Z_COMPILER_HAS_LITERAL_SINT128 FALSE
#endif

#ifdef Z_COMPILER_LITERAL_FLOAT16
#	define Z_COMPILER_HAS_LITERAL_FLOAT16 TRUE
#else
#	define Z_COMPILER_HAS_LITERAL_FLOAT16 FALSE
#endif

#ifdef Z_COMPILER_LITERAL_FLOAT32
#	define Z_COMPILER_HAS_LITERAL_FLOAT32 TRUE
#else
#	define Z_COMPILER_HAS_LITERAL_FLOAT32 FALSE
#endif

#ifdef Z_COMPILER_LITERAL_FLOAT64
#	define Z_COMPILER_HAS_LITERAL_FLOAT64 TRUE
#else
#	define Z_COMPILER_HAS_LITERAL_FLOAT64 FALSE
#endif

#ifdef Z_COMPILER_LITERAL_FLOAT128
#	define Z_COMPILER_HAS_LITERAL_FLOAT128 TRUE
#else
#	define Z_COMPILER_HAS_LITERAL_FLOAT128 FALSE
#endif

#ifdef Z_COMPILER_LITERAL_FLOAT80_X87
#	define Z_COMPILER_HAS_LITERAL_FLOAT80_X87 TRUE
#else
#	define Z_COMPILER_HAS_LITERAL_FLOAT80_X87 FALSE
#endif

#ifdef Z_COMPILER_LITERAL_FLOAT96_X87
#	define Z_COMPILER_HAS_LITERAL_FLOAT96_X87 TRUE
#else
#	define Z_COMPILER_HAS_LITERAL_FLOAT96_X87 FALSE
#endif

#ifdef Z_COMPILER_LITERAL_FLOAT128_X87
#	define Z_COMPILER_HAS_LITERAL_FLOAT128_X87 TRUE
#else
#	define Z_COMPILER_HAS_LITERAL_FLOAT128_X87 FALSE
#endif

/* MARK: - Built-in functions: Atomic operations */

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_SET_IF_EQUAL
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_SET_IF_EQUAL TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_SET_IF_EQUAL FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_GET_THEN_SET
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_SET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_SET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_GET_THEN_INCREMENT
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_INCREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_INCREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_GET_THEN_ADD
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_ADD TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_ADD FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_GET_THEN_DECREMENT
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_DECREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_DECREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_GET_THEN_SUBTRACT
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_SUBTRACT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_SUBTRACT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_GET_THEN_AND
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_AND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_AND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_GET_THEN_OR
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_OR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_OR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_GET_THEN_XOR
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_XOR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_XOR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_GET_THEN_NAND
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_NAND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_NAND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_GET_THEN_NOT
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_NOT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_GET_THEN_NOT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_INCREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_INCREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_INCREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_ADD_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_ADD_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_ADD_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_DECREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_DECREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_DECREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_SUBTRACT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_SUBTRACT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_SUBTRACT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_AND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_AND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_AND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_OR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_OR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_OR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_XOR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_XOR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_XOR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_NAND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_NAND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_NAND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT8_ATOMIC_NOT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_NOT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT8_ATOMIC_NOT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_SET_IF_EQUAL
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_SET_IF_EQUAL TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_SET_IF_EQUAL FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_GET_THEN_SET
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_SET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_SET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_GET_THEN_INCREMENT
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_INCREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_INCREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_GET_THEN_ADD
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_ADD TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_ADD FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_GET_THEN_DECREMENT
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_DECREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_DECREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_GET_THEN_SUBTRACT
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_SUBTRACT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_SUBTRACT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_GET_THEN_AND
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_AND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_AND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_GET_THEN_OR
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_OR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_OR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_GET_THEN_XOR
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_XOR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_XOR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_GET_THEN_NAND
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_NAND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_NAND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_GET_THEN_NOT
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_NOT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_GET_THEN_NOT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_INCREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_INCREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_INCREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_ADD_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_ADD_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_ADD_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_DECREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_DECREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_DECREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_SUBTRACT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_SUBTRACT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_SUBTRACT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_AND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_AND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_AND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_OR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_OR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_OR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_XOR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_XOR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_XOR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_NAND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_NAND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_NAND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT16_ATOMIC_NOT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_NOT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT16_ATOMIC_NOT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_SET_IF_EQUAL
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_SET_IF_EQUAL TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_SET_IF_EQUAL FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_GET_THEN_SET
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_SET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_SET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_GET_THEN_INCREMENT
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_INCREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_INCREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_GET_THEN_ADD
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_ADD TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_ADD FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_GET_THEN_DECREMENT
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_DECREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_DECREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_GET_THEN_SUBTRACT
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_SUBTRACT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_SUBTRACT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_GET_THEN_AND
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_AND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_AND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_GET_THEN_OR
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_OR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_OR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_GET_THEN_XOR
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_XOR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_XOR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_GET_THEN_NAND
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_NAND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_NAND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_GET_THEN_NOT
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_NOT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_GET_THEN_NOT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_INCREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_INCREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_INCREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_ADD_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_ADD_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_ADD_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_DECREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_DECREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_DECREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_SUBTRACT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_SUBTRACT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_SUBTRACT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_AND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_AND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_AND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_OR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_OR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_OR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_XOR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_XOR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_XOR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_NAND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_NAND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_NAND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT32_ATOMIC_NOT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_NOT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT32_ATOMIC_NOT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_SET_IF_EQUAL
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_SET_IF_EQUAL TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_SET_IF_EQUAL FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_GET_THEN_SET
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_SET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_SET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_GET_THEN_INCREMENT
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_INCREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_INCREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_GET_THEN_ADD
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_ADD TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_ADD FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_GET_THEN_DECREMENT
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_DECREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_DECREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_GET_THEN_SUBTRACT
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_SUBTRACT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_SUBTRACT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_GET_THEN_AND
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_AND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_AND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_GET_THEN_OR
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_OR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_OR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_GET_THEN_XOR
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_XOR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_XOR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_GET_THEN_NAND
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_NAND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_NAND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_GET_THEN_NOT
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_NOT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_GET_THEN_NOT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_INCREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_INCREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_INCREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_ADD_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_ADD_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_ADD_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_DECREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_DECREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_DECREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_SUBTRACT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_SUBTRACT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_SUBTRACT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_AND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_AND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_AND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_OR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_OR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_OR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_XOR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_XOR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_XOR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_NAND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_NAND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_NAND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT64_ATOMIC_NOT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_NOT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT64_ATOMIC_NOT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_SET_IF_EQUAL
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_SET_IF_EQUAL TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_SET_IF_EQUAL FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_GET_THEN_SET
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_SET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_SET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_GET_THEN_INCREMENT
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_INCREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_INCREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_GET_THEN_ADD
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_ADD TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_ADD FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_GET_THEN_DECREMENT
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_DECREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_DECREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_GET_THEN_SUBTRACT
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_SUBTRACT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_SUBTRACT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_GET_THEN_AND
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_AND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_AND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_GET_THEN_OR
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_OR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_OR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_GET_THEN_XOR
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_XOR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_XOR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_GET_THEN_NAND
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_NAND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_NAND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_GET_THEN_NOT
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_NOT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_GET_THEN_NOT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_INCREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_INCREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_INCREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_ADD_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_ADD_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_ADD_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_DECREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_DECREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_DECREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_SUBTRACT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_SUBTRACT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_SUBTRACT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_AND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_AND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_AND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_OR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_OR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_OR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_XOR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_XOR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_XOR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_NAND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_NAND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_NAND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_UINT128_ATOMIC_NOT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_NOT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_UINT128_ATOMIC_NOT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_SET_IF_EQUAL
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_SET_IF_EQUAL TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_SET_IF_EQUAL FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_GET_THEN_SET
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_SET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_SET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_GET_THEN_INCREMENT
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_INCREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_INCREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_GET_THEN_ADD
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_ADD TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_ADD FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_GET_THEN_DECREMENT
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_DECREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_DECREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_GET_THEN_SUBTRACT
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_SUBTRACT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_SUBTRACT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_GET_THEN_AND
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_AND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_AND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_GET_THEN_OR
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_OR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_OR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_GET_THEN_XOR
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_XOR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_XOR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_GET_THEN_NAND
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_NAND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_NAND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_GET_THEN_NOT
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_NOT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_GET_THEN_NOT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_INCREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_INCREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_INCREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_ADD_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_ADD_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_ADD_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_DECREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_DECREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_DECREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_SUBTRACT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_SUBTRACT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_SUBTRACT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_AND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_AND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_AND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_OR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_OR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_OR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_XOR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_XOR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_XOR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_NAND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_NAND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_NAND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT8_ATOMIC_NOT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_NOT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT8_ATOMIC_NOT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_SET_IF_EQUAL
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_SET_IF_EQUAL TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_SET_IF_EQUAL FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_GET_THEN_SET
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_SET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_SET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_GET_THEN_INCREMENT
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_INCREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_INCREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_GET_THEN_ADD
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_ADD TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_ADD FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_GET_THEN_DECREMENT
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_DECREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_DECREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_GET_THEN_SUBTRACT
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_SUBTRACT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_SUBTRACT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_GET_THEN_AND
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_AND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_AND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_GET_THEN_OR
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_OR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_OR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_GET_THEN_XOR
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_XOR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_XOR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_GET_THEN_NAND
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_NAND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_NAND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_GET_THEN_NOT
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_NOT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_GET_THEN_NOT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_INCREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_INCREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_INCREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_ADD_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_ADD_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_ADD_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_DECREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_DECREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_DECREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_SUBTRACT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_SUBTRACT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_SUBTRACT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_AND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_AND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_AND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_OR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_OR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_OR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_XOR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_XOR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_XOR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_NAND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_NAND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_NAND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT16_ATOMIC_NOT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_NOT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT16_ATOMIC_NOT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_SET_IF_EQUAL
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_SET_IF_EQUAL TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_SET_IF_EQUAL FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_GET_THEN_SET
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_SET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_SET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_GET_THEN_INCREMENT
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_INCREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_INCREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_GET_THEN_ADD
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_ADD TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_ADD FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_GET_THEN_DECREMENT
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_DECREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_DECREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_GET_THEN_SUBTRACT
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_SUBTRACT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_SUBTRACT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_GET_THEN_AND
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_AND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_AND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_GET_THEN_OR
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_OR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_OR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_GET_THEN_XOR
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_XOR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_XOR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_GET_THEN_NAND
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_NAND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_NAND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_GET_THEN_NOT
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_NOT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_GET_THEN_NOT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_INCREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_INCREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_INCREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_ADD_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_ADD_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_ADD_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_DECREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_DECREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_DECREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_SUBTRACT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_SUBTRACT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_SUBTRACT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_AND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_AND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_AND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_OR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_OR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_OR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_XOR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_XOR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_XOR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_NAND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_NAND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_NAND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT32_ATOMIC_NOT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_NOT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT32_ATOMIC_NOT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_SET_IF_EQUAL
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_SET_IF_EQUAL TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_SET_IF_EQUAL FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_GET_THEN_SET
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_SET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_SET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_GET_THEN_INCREMENT
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_INCREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_INCREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_GET_THEN_ADD
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_ADD TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_ADD FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_GET_THEN_DECREMENT
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_DECREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_DECREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_GET_THEN_SUBTRACT
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_SUBTRACT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_SUBTRACT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_GET_THEN_AND
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_AND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_AND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_GET_THEN_OR
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_OR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_OR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_GET_THEN_XOR
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_XOR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_XOR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_GET_THEN_NAND
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_NAND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_NAND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_GET_THEN_NOT
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_NOT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_GET_THEN_NOT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_INCREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_INCREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_INCREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_ADD_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_ADD_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_ADD_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_DECREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_DECREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_DECREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_SUBTRACT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_SUBTRACT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_SUBTRACT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_AND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_AND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_AND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_OR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_OR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_OR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_XOR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_XOR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_XOR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_NAND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_NAND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_NAND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT64_ATOMIC_NOT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_NOT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT64_ATOMIC_NOT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_SET_IF_EQUAL
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_SET_IF_EQUAL TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_SET_IF_EQUAL FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_GET_THEN_SET
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_SET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_SET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_GET_THEN_INCREMENT
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_INCREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_INCREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_GET_THEN_ADD
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_ADD TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_ADD FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_GET_THEN_DECREMENT
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_DECREMENT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_DECREMENT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_GET_THEN_SUBTRACT
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_SUBTRACT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_SUBTRACT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_GET_THEN_AND
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_AND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_AND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_GET_THEN_OR
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_OR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_OR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_GET_THEN_XOR
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_XOR TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_XOR FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_GET_THEN_NAND
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_NAND TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_NAND FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_GET_THEN_NOT
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_NOT TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_GET_THEN_NOT FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_INCREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_INCREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_INCREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_ADD_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_ADD_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_ADD_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_DECREMENT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_DECREMENT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_DECREMENT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_SUBTRACT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_SUBTRACT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_SUBTRACT_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_AND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_AND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_AND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_OR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_OR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_OR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_XOR_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_XOR_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_XOR_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_NAND_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_NAND_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_NAND_THEN_GET FALSE
#endif

#ifdef Z_COMPILER_FUNCTION_SINT128_ATOMIC_NOT_THEN_GET
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_NOT_THEN_GET TRUE
#else
#	define Z_COMPILER_HAS_FUNCTION_SINT128_ATOMIC_NOT_THEN_GET FALSE
#endif

/* MARK: - Built-in traits */

#ifdef Z_COMPILER_TRAIT_TYPE_HAS_VIRTUAL_DESTRUCTOR
#	define Z_COMPILER_HAS_TRAIT_TYPE_HAS_VIRTUAL_DESTRUCTOR TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_HAS_VIRTUAL_DESTRUCTOR FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_ABSTRACT
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_ABSTRACT TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_ABSTRACT FALSE
#endif

#ifdef  Z_COMPILER_TRAIT_TYPE_IS_AGGREGATE
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_AGGREGATE TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_AGGREGATE FALSE
#endif

#ifdef  Z_COMPILER_TRAIT_TYPE_IS_ASSIGNABLE
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_ASSIGNABLE TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_ASSIGNABLE FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_BASE
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_BASE TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_BASE FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_CLASS
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_CLASS TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_CLASS FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_CONSTRUCTIBLE
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_CONSTRUCTIBLE TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_CONSTRUCTIBLE FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_CONVERTIBLE
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_CONVERTIBLE TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_CONVERTIBLE FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_EMPTY
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_EMPTY TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_EMPTY FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_ENUMERATION
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_ENUMERATION TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_ENUMERATION FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_FINAL
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_FINAL TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_FINAL FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_INTERFACE_CLASS
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_INTERFACE_CLASS TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_INTERFACE_CLASS FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_LITERAL
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_LITERAL TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_LITERAL FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_NOTHROW_ASSIGNABLE
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_NOTHROW_ASSIGNABLE TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_NOTHROW_ASSIGNABLE FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_NOTHROW_CONSTRUCTIBLE
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_NOTHROW_CONSTRUCTIBLE TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_NOTHROW_CONSTRUCTIBLE FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_NOTHROW_COPY_ASSIGNABLE
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_NOTHROW_COPY_ASSIGNABLE TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_NOTHROW_COPY_ASSIGNABLE TRUE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_NOTHROW_COPY_CONSTRUCTIBLE
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_NOTHROW_COPY_CONSTRUCTIBLE TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_NOTHROW_COPY_CONSTRUCTIBLE FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_NOTHROW_DEFAULT_CONSTRUCTIBLE
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_NOTHROW_DEFAULT_CONSTRUCTIBLE TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_NOTHROW_DEFAULT_CONSTRUCTIBLE FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_POD
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_POD TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_POD FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_POLYMORPHIC
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_POLYMORPHIC TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_POLYMORPHIC FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_STANDARD_LAYOUT
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_STANDARD_LAYOUT TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_STANDARD_LAYOUT FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_TRIVIAL
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_TRIVIAL TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_TRIVIAL FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_TRIVIALLY_ASSIGNABLE
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_TRIVIALLY_ASSIGNABLE TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_TRIVIALLY_ASSIGNABLE FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_TRIVIALLY_CONSTRUCTIBLE
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_TRIVIALLY_CONSTRUCTIBLE TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_TRIVIALLY_CONSTRUCTIBLE FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_TRIVIALLY_COPY_ASSIGNABLE
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_TRIVIALLY_COPY_ASSIGNABLE TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_TRIVIALLY_COPY_ASSIGNABLE FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_TRIVIALLY_COPY_CONSTRUCTIBLE
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_TRIVIALLY_COPY_CONSTRUCTIBLE TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_TRIVIALLY_COPY_CONSTRUCTIBLE FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_TRIVIALLY_COPYABLE
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_TRIVIALLY_COPYABLE TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_TRIVIALLY_COPYABLE FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_TRIVIALLY_DEFAULT_CONSTRUCTIBLE
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_TRIVIALLY_DEFAULT_CONSTRUCTIBLE TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_TRIVIALLY_DEFAULT_CONSTRUCTIBLE FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_TRIVIALLY_DESTRUCTIBLE
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_TRIVIALLY_DESTRUCTIBLE TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_TRIVIALLY_DESTRUCTIBLE FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_IS_UNION
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_UNION TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_IS_UNION FALSE
#endif

#ifdef Z_COMPILER_TRAIT_TYPE_UNDERLYING_TYPE
#	define Z_COMPILER_HAS_TRAIT_TYPE_UNDERLYING_TYPE TRUE
#else
#	define Z_COMPILER_HAS_TRAIT_TYPE_UNDERLYING_TYPE FALSE
#endif

/* MARK: - Complete implementations */

#ifndef Z_COMPILER_HAS_VAL
#	if	Z_COMPILER_HAS_TYPE_VAL		    && \
		Z_COMPILER_HAS_MACRO_VAL_INITIALIZE && \
		Z_COMPILER_HAS_MACRO_VAL_FINALIZE   && \
		Z_COMPILER_HAS_MACRO_VAL_READ

#		define Z_COMPILER_HAS_VAL TRUE
#	else
#		define Z_COMPILER_HAS_VAL FALSE
#	endif
#endif

#endif /* Z_inspection_compiler_completion_H */
