/* Z Kit C API - keys/compiler.h
	      __	   __
  _______ ___/ /______ ___/ /__
 / __/ -_) _  / __/ _ \ _  / -_)
/_/  \__/\_,_/\__/\___/_,_/\__/
Copyright © 2006-2015 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef __Z_keys_compiler_H__
#define __Z_keys_compiler_H__

#define Z_COMPILER_GCC					0
#define Z_COMPILER_CLANG				1
#define Z_COMPILER_MICROSOFT_VISUAL_CPP			2
#define Z_COMPILER_ACC					3
#define Z_COMPILER_ALTIUM_MICROBLAZE_C			4
#define Z_COMPILER_ALTIUM_C_TO_HARDWARE			5
#define Z_COMPILER_AMSTERDAM_COMPILER_KIT		6
#define Z_COMPILER_APPLE_LLVM				7
#define Z_COMPILER_ARM_COMPILER
#define Z_COMPILER_AZTEC_C
#define Z_COMPILER_BORLAND_CPP
#define Z_COMPILER_CC65
#define Z_COMPILER_COMEAU_CPP
#define Z_COMPILER_COMPAQ_C_CPP
#define Z_COMPILER_CONVEX_C
#define Z_COMPILER_CRAY_C
#define Z_COMPILER_DIAB_C_CPP
#define Z_COMPILER_DICE_C
#define Z_COMPILER_DIGITAL_MARS
#define Z_COMPILER_DIGNUS_SYSTEMS_CPP
#define Z_COMPILER_DJGPP
#define Z_COMPILER_EDG_CPP_FRONTEND
#define Z_COMPILER_EKOPATH
#define Z_COMPILER_FUJITSU_CPP
#define Z_COMPILER_GREEN_HILL_C_CPP
#define Z_COMPILER_HP_ACPP
#define Z_COMPILER_HP_ANSI_C
#define Z_COMPILER_IAR_C_CPP
#define Z_COMPILER_IBM_XL_C_CPP
#define Z_COMPILER_IBM_Z_OS_C_CPP
#define Z_COMPILER_IMAGECRAFT_C
#define Z_COMPILER_INTEL_C_CPP
#define Z_COMPILER_KAI_CPP
#define Z_COMPILER_KEIL_C166
#define Z_COMPILER_KEIL_C51
#define Z_COMPILER_KEIL_CARM
#define Z_COMPILER_LCC
#define Z_COMPILER_METAWARE_HIGH_C_CPP
#define Z_COMPILER_METROWERKS_CODEWARRIOR
#define Z_COMPILER_MICROTEC_C_CPP
#define Z_COMPILER_MICROWAY_NDP_C
#define Z_COMPILER_MINGW
#define Z_COMPILER_MIPS_PRO
#define Z_COMPILER_MIRACLE_C
#define Z_COMPILER_MPW_CPP
#define Z_COMPILER_NORCROFT_C
#define Z_COMPILER_NWCC
#define Z_COMPILER_OPEN64
#define Z_COMPILER_ORACLE_PRO_C_PRECOMPILER
#define Z_COMPILER_ORACLE_SOLARIS_STUDIO
#define Z_COMPILER_PACIFIC_C
#define Z_COMPILER_PALM_C_CPP
#define Z_COMPILER_PELLES_C
#define Z_COMPILER_PORTLAND_GROUP_C_CPP
#define Z_COMPILER_RENESAS_C_CPP
#define Z_COMPILER_SAS_C
#define Z_COMPILER_SCO_OPEN_SERVER
#define Z_COMPILER_SMALL_DEVICE_C_COMPILER
#define Z_COMPILER_SN_COMPILER
#define Z_COMPILER_STRATUS_VOS_C
#define Z_COMPILER_SYMANTEC_CPP
#define Z_COMPILER_TENDRA_C_CPP
#define Z_COMPILER_TEXAS_INSTRUMENTS_C_CPP_COMPILER
#define Z_COMPILER_THINK_C
#define Z_COMPILER_TINY_C
#define Z_COMPILER_TURBO_C_CPP
#define Z_COMPILER_ULTIMATE_C_CPP
#define Z_COMPILER_USL_C
#define Z_COMPILER_WATCOM_CPP
#define Z_COMPILER_ZORTECH_CPP

#define Z_COMPILER_STRING_GCC					"GCC"
#define Z_COMPILER_STRING_CLANG					"Clang"
#define Z_COMPILER_STRING_MICROSOFT_VISUAL_CPP			"Microsoft Visual C++"
#define Z_COMPILER_STRING_ACC					"ACC"
#define Z_COMPILER_STRING_ALTIUM_MICROBLAZE_C			"Altium MicroBlaze C"
#define Z_COMPILER_STRING_ALTIUM_C_TO_HARDWARE			"Altium C-to-Hardware"
#define Z_COMPILER_STRING_AMSTERDAM_COMPILER_KIT		"Amsterdam Compiler Kit"
#define Z_COMPILER_STRING_APPLE_LLVM				"Apple LLVM"
#define Z_COMPILER_STRING_ARM_COMPILER				"ARM Compiler"
#define Z_COMPILER_STRING_AZTEC_C				"Aztec C"
#define Z_COMPILER_STRING_BORLAND_CPP				"Borland C++"
#define Z_COMPILER_STRING_CC65					"CC65"
#define Z_COMPILER_STRING_COMEAU_CPP				"Comeau C++ "
#define Z_COMPILER_STRING_COMPAQ_C_CPP				"Compaq C/C++"
#define Z_COMPILER_STRING_CONVEX_C				"Convex C"
#define Z_COMPILER_STRING_CRAY_C				"Cray C"
#define Z_COMPILER_STRING_DIAB_C_CPP				"Diab C/C++"
#define Z_COMPILER_STRING_DICE_C				"DICE C"
#define Z_COMPILER_STRING_DIGITAL_MARS				"Digital Mars"
#define Z_COMPILER_STRING_DIGNUS_SYSTEMS_CPP			"Dignus Systems/C++"
#define Z_COMPILER_STRING_DJGPP					"DJGPP"
#define Z_COMPILER_STRING_EDG_CPP_FRONTEND			"EDG C++ Frontend"
#define Z_COMPILER_STRING_EKOPARH				"EKOPath"
#define Z_COMPILER_STRING_FUJITSU_CPP				"Fujitsu C++"
#define Z_COMPILER_STRING_GREEN_HILL_C_CPP			"Green Hill C/C++"
#define Z_COMPILER_STRING_HP_ACPP				"HP aC++"
#define Z_COMPILER_STRING_HP_ANSI_C				"HP ANSI C"
#define Z_COMPILER_STRING_IAR_C_CPP				"IAR C/C++"
#define Z_COMPILER_STRING_IBM_XL_C_CPP				"IBM XL C/C++"
#define Z_COMPILER_STRING_IBM_Z_OS_C_CPP			"IBM z/OS C/C++"
#define Z_COMPILER_STRING_IMAGECRAFT_C				"ImageCraft C"
#define Z_COMPILER_STRING_INTEL_C_CPP				"Intel C/C++"
#define Z_COMPILER_STRING_KAI_CPP				"KAI C++"
#define Z_COMPILER_STRING_KEIL_C166				"KEIL C166"
#define Z_COMPILER_STRING_KEIL_C51				"KEIL C51"
#define Z_COMPILER_STRING_KEIL_CARM				"KEIL CARM"
#define Z_COMPILER_STRING_LCC					"LLC"
#define Z_COMPILER_STRING_METAWARE_HIGH_C_CPP			"MetaWare High C/C++"
#define Z_COMPILER_STRING_METROWERKS_CODEWARRIOR		"Metrowerks CodeWarrior"
#define Z_COMPILER_STRING_MICROTEC_C_CPP			"Microtec C/C++"
#define Z_COMPILER_STRING_MICROWAY_NDP_C			"Microway NDP C"
#define Z_COMPILER_STRING_MINGW					"MinGW"
#define Z_COMPILER_STRING_MIPS_PRO				"MIPSpro"
#define Z_COMPILER_STRING_MIRACLE_C				"Miracle C"
#define Z_COMPILER_STRING_MPW_CPP				"MPW C++"
#define Z_COMPILER_STRING_NORCROFT_C				"Norcroft C"
#define Z_COMPILER_STRING_NWCC					"NWCC"
#define Z_COMPILER_STRING_OPEN64				"Open64"
#define Z_COMPILER_STRING_ORACLE_PRO_C_PRECOMPILER		"Oracle Pro*C Precompiler"
#define Z_COMPILER_STRING_ORACLE_SOLARIS_STUDIO			"Oracle Solaris Studio"
#define Z_COMPILER_STRING_PACIFIC_C				"Pacific C"
#define Z_COMPILER_STRING_PALM_C_CPP				"Palm C/C++"
#define Z_COMPILER_STRING_PELLES_C				"Pelles C"
#define Z_COMPILER_STRING_PORTLAND_GROUP_C_CPP			"Portland Group C/C++"
#define Z_COMPILER_STRING_RENESAS_C_CPP				"Renesas C/C++"
#define Z_COMPILER_STRING_SAS_C					"SAS/C"
#define Z_COMPILER_STRING_SCO_OPEN_SERVER			"SCO OpenServer"
#define Z_COMPILER_STRING_SMALL_DEVICE_C_COMPILER		"Small Device C Compiler"
#define Z_COMPILER_STRING_SN_COMPILER				"SN Compiler"
#define Z_COMPILER_STRING_STRATUS_VOS_C				"Stratus VOS C"
#define Z_COMPILER_STRING_SYMANTEC_CPP				"Symantec C++"
#define Z_COMPILER_STRING_TENDRA_C_CPP				"TenDRA C - C++"
#define Z_COMPILER_STRING_TEXAS_INSTRUMENTS_C_CPP_COMPILER	"Texas Instruments C/C++ Compiler"
#define Z_COMPILER_STRING_THINK_C				"THINK C"
#define Z_COMPILER_STRING_TINY_C				"Tiny C"
#define Z_COMPILER_STRING_TURBO_C_CPP				"Turbo C/C++"
#define Z_COMPILER_STRING_ULTIMATE_C_CPP			"Ultimate C/C++"
#define Z_COMPILER_STRING_USL_C					"USL C"
#define Z_COMPILER_STRING_WATCOM_CPP				"Watcom C++"
#define Z_COMPILER_STRING_ZORTECH_CPP				"Zortech C++"

#endif /* __Z_keys_compiler_H__ */
