/* Z Kit - inspection/C/completion.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//___/_| Kit
Copyright (C) 2006-2018 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

/* MARK: - K&R C */

#ifndef Z_C_HAS_OPERATOR_SIZE_OF
#	define Z_C_HAS_OPERATOR_SIZE_OF FALSE
#endif

#ifndef Z_C_HAS_STORAGE_CLASS_AUTO
#	define Z_C_HAS_STORAGE_CLASS_AUTO FALSE
#endif

#ifndef Z_C_HAS_STORAGE_CLASS_EXTERN
#	define Z_C_HAS_STORAGE_CLASS_EXTERN FALSE
#endif

#ifndef Z_C_HAS_STORAGE_CLASS_REGISTER
#	define Z_C_HAS_STORAGE_CLASS_REGISTER FALSE
#endif

#ifndef Z_C_HAS_STORAGE_CLASS_STATIC
#	define Z_C_HAS_STORAGE_CLASS_STATIC FALSE
#endif

#ifndef Z_C_HAS_TYPE_FLOAT
#	define Z_C_HAS_TYPE_FLOAT FALSE
#endif

#ifndef Z_C_HAS_TYPE_DOUBLE
#	define Z_C_HAS_TYPE_DOUBLE FALSE
#endif

/* MARK: - C89 */

#ifndef Z_C_HAS_ENUMERATION
#	define Z_C_HAS_ENUMERATION FALSE
#endif

#ifndef Z_C_HAS_VOID_POINTER
#	define Z_C_HAS_VOID_POINTER FALSE
#endif

#ifndef Z_C_HAS_TYPE_LDOUBLE
#	define Z_C_HAS_TYPE_LDOUBLE FALSE
#endif

#ifndef Z_C_HAS_TYPE_QUALIFIER_CONSTANT
#	define Z_C_HAS_TYPE_QUALIFIER_CONSTANT FALSE
#endif

#ifndef Z_C_HAS_TYPE_QUALIFIER_VOLATILE
#	define Z_C_HAS_TYPE_QUALIFIER_VOLATILE FALSE
#endif

/* MARK: - C90 */

/* MARK: - C94 */

#ifndef Z_C_HAS_DIGRAPHS
#	define Z_C_HAS_DIGRAPHS FALSE
#endif

/* MARK: - C99 */

#ifndef Z_C_HAS_COMPOUND_LITERAL
#	define Z_C_HAS_COMPOUND_LITERAL FALSE
#endif

#ifndef Z_C_HAS_CPP_STYLE_COMMENT
#	define Z_C_HAS_CPP_STYLE_COMMENT FALSE
#endif

#ifndef Z_C_HAS_DESIGNATED_INITIALIZER
#	define Z_C_HAS_DESIGNATED_INITIALIZER FALSE
#endif

#ifndef Z_C_HAS_FLEXIBLE_ARRAY_MEMBER
#	define Z_C_HAS_FLEXIBLE_ARRAY_MEMBER FALSE
#endif

#ifndef Z_C_HAS_INLINE_FUNCION
#	define Z_C_HAS_INLINE_FUNCION FALSE
#endif

#ifndef Z_C_HAS_MIXED_DECLARATIONS_AND_CODE
#	define Z_C_HAS_MIXED_DECLARATIONS_AND_CODE FALSE
#endif

#ifndef Z_C_HAS_NON_CONSTANT_AGGREGATE_INITIALIZER
#	define Z_C_HAS_NON_CONSTANT_AGGREGATE_INITIALIZER FALSE
#endif

#ifndef Z_C_HAS_PREPROCESSOR_ARITHMETIC_DONE_IN_MAXIMUM_INTEGRAL
#	define Z_C_HAS_PREPROCESSOR_ARITHMETIC_DONE_IN_MAXIMUM_INTEGRAL FALSE
#endif

#ifndef Z_C_HAS_VARIADIC_MACRO
#	define Z_C_HAS_VARIADIC_MACRO FALSE
#endif

#ifndef Z_C_HAS_VLA
#	define Z_C_HAS_VLA FALSE
#endif

#ifndef Z_C_HAS_MAGIC_CONSTANT_FUNCTION_NAME
#	define Z_C_HAS_MAGIC_CONSTANT_FUNCTION_NAME FALSE
#endif

#ifndef Z_C_HAS_SPECIFIER_INLINE
#	define Z_C_HAS_SPECIFIER_INLINE FALSE
#endif

#ifndef Z_C_HAS_TYPE_BOOLEAN
#	define Z_C_HAS_TYPE_BOOLEAN FALSE
#endif

#ifndef Z_C_HAS_TYPE_LLONG
#	define Z_C_HAS_TYPE_LLONG FALSE
#endif

#ifndef Z_C_HAS_TYPE_QUALIFIER_RESTRICT
#	define Z_C_HAS_TYPE_QUALIFIER_RESTRICT FALSE
#endif

/* MARK: - C11 */

#ifndef Z_C_HAS_ANONYMOUS_STRUCTURE
#	define Z_C_HAS_ANONYMOUS_STRUCTURE FALSE
#endif

#ifndef Z_C_HAS_ANONYMOUS_UNION
#	define Z_C_HAS_ANONYMOUS_UNION FALSE
#endif

#ifndef Z_C_HAS_ATOMIC_OPERATIONS
#	define Z_C_HAS_ATOMIC_OPERATIONS FALSE
#endif

#ifndef Z_C_HAS_GENERIC_SELECTION
#	define Z_C_HAS_GENERIC_SELECTION FALSE
#endif

#ifndef Z_C_HAS_STATIC_ASSERTION
#	define Z_C_HAS_STATIC_ASSERTION FALSE
#endif

#ifndef Z_C_HAS_OPERATOR_ALIGN_OF
#	define Z_C_HAS_OPERATOR_ALIGN_OF FALSE
#endif

#ifndef Z_C_HAS_SPECIFIER_ALIGN_AS
#	define Z_C_HAS_SPECIFIER_ALIGN_AS FALSE
#endif

#ifndef Z_C_HAS_SPECIFIER_ATOMIC
#	define Z_C_HAS_SPECIFIER_ATOMIC FALSE
#endif

#ifndef Z_C_HAS_SPECIFIER_NO_RETURN
#	define Z_C_HAS_SPECIFIER_NO_RETURN FALSE
#endif

#ifndef Z_C_HAS_STORATE_CLASS_THREAD_LOCAL
#	define Z_C_HAS_STORATE_CLASS_THREAD_LOCAL FALSE
#endif

#ifndef Z_C_HAS_TYPE_QUALIFIER_ATOMIC
#	define Z_C_HAS_TYPE_QUALIFIER_ATOMIC FALSE
#endif

/* MARK: - C18 */

/* inspection/C/completion.h EOF */
