/* Z Kit - keys/character set.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//___/_| Kit
Copyright (C) 2006-2018 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef _Z_keys_character_set_H_
#define _Z_keys_character_set_H_

#define Z_CHARACTER_SET_ASCII		1
#define Z_CHARACTER_SET_UTF_8		2
#define Z_CHARACTER_SET_UTF_16		3
#define Z_CHARACTER_SET_UTF_32		4
#define Z_CHARACTER_SET_EBCDIC_CP037
#define Z_CHARACTER_SET_EBCDIC_CP930
#define Z_CHARACTER_SET_EBCDIC_CP1047
#define Z_CHARACTER_SET_ISO_8859_1
#define Z_CHARACTER_SET_ISO_8859_2
#define Z_CHARACTER_SET_ISO_8859_3
#define Z_CHARACTER_SET_ISO_8859_4
#define Z_CHARACTER_SET_ISO_8859_5
#define Z_CHARACTER_SET_ISO_8859_6
#define Z_CHARACTER_SET_ISO_8859_7
#define Z_CHARACTER_SET_ISO_8859_8
#define Z_CHARACTER_SET_ISO_8859_9
#define Z_CHARACTER_SET_ISO_8859_10
#define Z_CHARACTER_SET_ISO_8859_11
#define Z_CHARACTER_SET_ISO_8859_13
#define Z_CHARACTER_SET_ISO_8859_14
#define Z_CHARACTER_SET_ISO_8859_15
#define Z_CHARACTER_SET_ISO_8859_16
#define Z_CHARACTER_SET_CP437
#define Z_CHARACTER_SET_CP737
#define Z_CHARACTER_SET_CP850
#define Z_CHARACTER_SET_CP852
#define Z_CHARACTER_SET_CP855
#define Z_CHARACTER_SET_CP857
#define Z_CHARACTER_SET_CP858
#define Z_CHARACTER_SET_CP860
#define Z_CHARACTER_SET_CP861
#define Z_CHARACTER_SET_CP862
#define Z_CHARACTER_SET_CP863
#define Z_CHARACTER_SET_CP865
#define Z_CHARACTER_SET_CP866
#define Z_CHARACTER_SET_CP869
#define Z_CHARACTER_SET_CP872
#define Z_CHARACTER_SET_WINDOWS_1250
#define Z_CHARACTER_SET_WINDOWS_1251
#define Z_CHARACTER_SET_WINDOWS_1252
#define Z_CHARACTER_SET_WINDOWS_1253
#define Z_CHARACTER_SET_WINDOWS_1254
#define Z_CHARACTER_SET_WINDOWS_1255
#define Z_CHARACTER_SET_WINDOWS_1256
#define Z_CHARACTER_SET_WINDOWS_1257
#define Z_CHARACTER_SET_WINDOWS_1258
#define Z_CHARACTER_SET_MAC_OS_ROMAN
#define Z_CHARACTER_SET_KOI8_R
#define Z_CHARACTER_SET_KOI8_U
#define Z_CHARACTER_SET_KOI7
#define Z_CHARACTER_SET_MIK
#define Z_CHARACTER_SET_ISCII
#define Z_CHARACTER_SET_TSCII
#define Z_CHARACTER_SET_VISCII
#define Z_CHARACTER_SET_SHIFT_JIS
#define Z_CHARACTER_SET_EUC_JIS_2004
#define Z_CHARACTER_SET_ISO_2022_JP_2004
#define Z_CHARACTER_SET_GB_2312
#define Z_CHARACTER_SET_GBK
#define Z_CHARACTER_SET_GB_18030
#define Z_CHARACTER_SET_BIG5
#define Z_CHARACTER_SET_HKSCS
#define Z_CHARACTER_SET_KS_X_1001
#define Z_CHARACTER_SET_EUC_KR
#define Z_CHARACTER_SET_ISO_2022_KR
#define Z_CHARACTER_SET_ANSEL

#define Z_KEY_BITS_CHARACTER_SET 8
#define Z_KEY_LAST_CHARACTER_SET Z_CHARACTER_SET_ANSEL

#endif /* _Z_keys_character_set_H_ */
