/* Z Kit - keys/number.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//___/_| Kit
Copyright (C) 2006-2019 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_keys_number_H_
#define Z_keys_number_H_

#define Z_NUMBER_SET_N 1
#define Z_NUMBER_SET_Z 3
#define Z_NUMBER_SET_Q 4
#define Z_NUMBER_SET_R 5
#define Z_NUMBER_SET_I 6
#define Z_NUMBER_SET_C 7

#define Z_KEY_BITS_NUMBER_SET 8
#define Z_KEY_LAST_NUMBER_SET Z_NUMBER_SET_C

#define Z_NUMBER_FORMAT_8BIT_NATURAL		      1
#define Z_NUMBER_FORMAT_16BIT_NATURAL		      2
#define Z_NUMBER_FORMAT_32BIT_NATURAL		      3
#define Z_NUMBER_FORMAT_64BIT_NATURAL		      4
#define Z_NUMBER_FORMAT_128BIT_NATURAL		      5
#define Z_NUMBER_FORMAT_8BIT_2S_COMPLEMENT_INTEGER    6
#define Z_NUMBER_FORMAT_16BIT_2S_COMPLEMENT_INTEGER   7
#define Z_NUMBER_FORMAT_32BIT_2S_COMPLEMENT_INTEGER   8
#define Z_NUMBER_FORMAT_64BIT_2S_COMPLEMENT_INTEGER   9
#define Z_NUMBER_FORMAT_128BIT_2S_COMPLEMENT_INTEGER 10
#define Z_NUMBER_FORMAT_IEEE_754_BINARY16	     11
#define Z_NUMBER_FORMAT_IEEE_754_BINARY32	     12
#define Z_NUMBER_FORMAT_IEEE_754_BINARY64	     13
#define Z_NUMBER_FORMAT_IEEE_754_BINARY128	     14
#define Z_NUMBER_FORMAT_IEEE_754_DECIMAL32	     15
#define Z_NUMBER_FORMAT_IEEE_754_DECIMAL64	     16
#define Z_NUMBER_FORMAT_IEEE_754_DECIMAL128	     17
#define Z_NUMBER_FORMAT_X87_BINARY80		     18
#define Z_NUMBER_FORMAT_X87_BINARY96		     19
#define Z_NUMBER_FORMAT_X87_BINARY128		     20

#define Z_KEY_BITS_NUMBER_FORMAT 8
#define Z_KEY_LAST_NUMBER_FORMAT Z_NUMBER_FORMAT_INTEL_FLOAT128

#define Z_INTEGER_FORMAT_1S_COMPLEMENT 0
#define Z_INTEGER_FORMAT_2S_COMPLEMENT 1

#define Z_KEY_BITS_INTEGER_FORMAT 8
#define Z_KEY_LAST_INTEGER_FORMAT Z_INTEGER_FORMAT_2S_COMPLEMENT

#endif /* Z_keys_number_H_ */
