/* Q API - keys/science/chemistry.h
	      __	   __
  _______ ___/ /______ ___/ /__
 / __/ -_) _  / __/ _ \ _  / -_)
/_/  \__/\_,_/\__/\___/_,_/\__/
Copyright © 2006-2014 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU General Public License v3. */

#ifndef __Q_keys_science_chemistry_H__
#define __Q_keys_science_chemistry_H__

#define Q_CHEMICAL_ELEMENT_HYDROGEN	   1
#define Q_CHEMICAL_ELEMENT_HELIUM	   2
#define Q_CHEMICAL_ELEMENT_LITHIUM	   3
#define Q_CHEMICAL_ELEMENT_BERYLLIUM	   4
#define Q_CHEMICAL_ELEMENT_BORON	   5
#define Q_CHEMICAL_ELEMENT_CARBON	   6
#define Q_CHEMICAL_ELEMENT_NITROGEN	   7
#define Q_CHEMICAL_ELEMENT_OXYGEN	   8
#define Q_CHEMICAL_ELEMENT_FLUORINE	   9
#define Q_CHEMICAL_ELEMENT_NEON		  10
#define Q_CHEMICAL_ELEMENT_SODIUM	  11
#define Q_CHEMICAL_ELEMENT_MAGNESIUM	  12
#define Q_CHEMICAL_ELEMENT_ALUMINIUM	  13
#define Q_CHEMICAL_ELEMENT_SILICON	  14
#define Q_CHEMICAL_ELEMENT_PHOSPHORUS	  15
#define Q_CHEMICAL_ELEMENT_SULFUR	  16
#define Q_CHEMICAL_ELEMENT_CHLORINE	  17
#define Q_CHEMICAL_ELEMENT_ARGON	  18
#define Q_CHEMICAL_ELEMENT_POTASSIUM	  19
#define Q_CHEMICAL_ELEMENT_CALCIUM	  20
#define Q_CHEMICAL_ELEMENT_SCANDIUM	  21
#define Q_CHEMICAL_ELEMENT_TITANIUM	  22
#define Q_CHEMICAL_ELEMENT_VANADIUM	  23
#define Q_CHEMICAL_ELEMENT_CHROMIUM	  24
#define Q_CHEMICAL_ELEMENT_MANGANESE	  25
#define Q_CHEMICAL_ELEMENT_IRON		  26
#define Q_CHEMICAL_ELEMENT_COBALT	  27
#define Q_CHEMICAL_ELEMENT_NICKEL	  28
#define Q_CHEMICAL_ELEMENT_COPPER	  29
#define Q_CHEMICAL_ELEMENT_ZINC		  30
#define Q_CHEMICAL_ELEMENT_GALLIUM	  31
#define Q_CHEMICAL_ELEMENT_GERMANIUM	  32
#define Q_CHEMICAL_ELEMENT_ARSENIC	  33
#define Q_CHEMICAL_ELEMENT_SELENIUM	  34
#define Q_CHEMICAL_ELEMENT_BROMINE	  35
#define Q_CHEMICAL_ELEMENT_KRYPTON	  36
#define Q_CHEMICAL_ELEMENT_RUBIDIUM	  37
#define Q_CHEMICAL_ELEMENT_STRONTIUM	  38
#define Q_CHEMICAL_ELEMENT_YTTRIUM	  39
#define Q_CHEMICAL_ELEMENT_ZIRCONIUM	  40
#define Q_CHEMICAL_ELEMENT_NIOBIUM	  41
#define Q_CHEMICAL_ELEMENT_MOLYBDENUM	  42
#define Q_CHEMICAL_ELEMENT_TECHNETIUM	  43
#define Q_CHEMICAL_ELEMENT_RUTHENIUM	  44
#define Q_CHEMICAL_ELEMENT_RHODIUM	  45
#define Q_CHEMICAL_ELEMENT_PALLADIUM	  46
#define Q_CHEMICAL_ELEMENT_SILVER	  47
#define Q_CHEMICAL_ELEMENT_CADMIUM	  48
#define Q_CHEMICAL_ELEMENT_INDIUM	  49
#define Q_CHEMICAL_ELEMENT_TIN		  50
#define Q_CHEMICAL_ELEMENT_ANTIMONY	  51
#define Q_CHEMICAL_ELEMENT_TELLURIUM	  52
#define Q_CHEMICAL_ELEMENT_IODINE	  53
#define Q_CHEMICAL_ELEMENT_XENON	  54
#define Q_CHEMICAL_ELEMENT_CAESIUM	  55
#define Q_CHEMICAL_ELEMENT_BARIUM	  56
#define Q_CHEMICAL_ELEMENT_LANTHANUM	  57
#define Q_CHEMICAL_ELEMENT_CERIUM	  58
#define Q_CHEMICAL_ELEMENT_PRASEODYMIUM	  59
#define Q_CHEMICAL_ELEMENT_NEODYMIUM	  60
#define Q_CHEMICAL_ELEMENT_PROMETHIUM	  61
#define Q_CHEMICAL_ELEMENT_SAMARIUM	  62
#define Q_CHEMICAL_ELEMENT_EUROPIUM	  63
#define Q_CHEMICAL_ELEMENT_GADOLINIUM	  64
#define Q_CHEMICAL_ELEMENT_TERBIUM	  65
#define Q_CHEMICAL_ELEMENT_DYSPROSIUM	  66
#define Q_CHEMICAL_ELEMENT_HOLMIUM	  67
#define Q_CHEMICAL_ELEMENT_ERBIUM	  68
#define Q_CHEMICAL_ELEMENT_THULIUM	  69
#define Q_CHEMICAL_ELEMENT_YTTERBIUM	  70
#define Q_CHEMICAL_ELEMENT_LUTETIUM	  71
#define Q_CHEMICAL_ELEMENT_HAFNIUM	  72
#define Q_CHEMICAL_ELEMENT_TANTALUM	  73
#define Q_CHEMICAL_ELEMENT_WOLFRAM	  74
#define Q_CHEMICAL_ELEMENT_TUNGSTEN	  Q_CHEMICAL_ELEMENT_WOLFRAM
#define Q_CHEMICAL_ELEMENT_RHENIUM	  75
#define Q_CHEMICAL_ELEMENT_OSMIUM	  76
#define Q_CHEMICAL_ELEMENT_IRIDIUM	  77
#define Q_CHEMICAL_ELEMENT_PLATINUM	  78
#define Q_CHEMICAL_ELEMENT_GOLD		  79
#define Q_CHEMICAL_ELEMENT_MERCURY	  80
#define Q_CHEMICAL_ELEMENT_THALLIUM	  81
#define Q_CHEMICAL_ELEMENT_LEAD		  82
#define Q_CHEMICAL_ELEMENT_BISMUTH	  83
#define Q_CHEMICAL_ELEMENT_POLONIUM	  84
#define Q_CHEMICAL_ELEMENT_ASTATINE	  85
#define Q_CHEMICAL_ELEMENT_RADON	  86
#define Q_CHEMICAL_ELEMENT_FRANCIUM	  87
#define Q_CHEMICAL_ELEMENT_RADIUM	  88
#define Q_CHEMICAL_ELEMENT_ACTINIUM	  89
#define Q_CHEMICAL_ELEMENT_THORIUM	  90
#define Q_CHEMICAL_ELEMENT_PROTACTINIUM	  91
#define Q_CHEMICAL_ELEMENT_URANIUM	  92
#define Q_CHEMICAL_ELEMENT_NEPTUNIUM	  93
#define Q_CHEMICAL_ELEMENT_PLUTONIUM	  94
#define Q_CHEMICAL_ELEMENT_AMERICIUM	  95
#define Q_CHEMICAL_ELEMENT_CURIUM	  96
#define Q_CHEMICAL_ELEMENT_BERKELIUM	  97
#define Q_CHEMICAL_ELEMENT_CALIFORNIUM	  98
#define Q_CHEMICAL_ELEMENT_EINSTEINIUM	  99
#define Q_CHEMICAL_ELEMENT_FERMIUM	 100
#define Q_CHEMICAL_ELEMENT_MENDELEVIUM	 101
#define Q_CHEMICAL_ELEMENT_NOBELIUM	 102
#define Q_CHEMICAL_ELEMENT_LAWRENCIUM	 103
#define Q_CHEMICAL_ELEMENT_RUTHERFORDIUM 104
#define Q_CHEMICAL_ELEMENT_DUBNIUM	 105
#define Q_CHEMICAL_ELEMENT_SEABORGIUM	 106
#define Q_CHEMICAL_ELEMENT_BOHRIUM	 107
#define Q_CHEMICAL_ELEMENT_HASSIUM	 108
#define Q_CHEMICAL_ELEMENT_MEITNERIUM	 109
#define Q_CHEMICAL_ELEMENT_DARMSTADTIUM	 110
#define Q_CHEMICAL_ELEMENT_ROENTGENIUM	 111
#define Q_CHEMICAL_ELEMENT_COPERNICIUM	 112
#define Q_CHEMICAL_ELEMENT_UNUNTRIUM	 113
#define Q_CHEMICAL_ELEMENT_FLEROVIUM	 114
#define Q_CHEMICAL_ELEMENT_UNUNPENTIUM	 115
#define Q_CHEMICAL_ELEMENT_LIVERMORIUM	 116
#define Q_CHEMICAL_ELEMENT_UNUNSEPTIUM	 117
#define Q_CHEMICAL_ELEMENT_UNUNOCTIUM	 118

#define Q_KEY_BITS_CHEMICAL_ELEMENT 8
#define Q_KEY_LAST_CHEMICAL_ELEMENT Q_CHEMICAL_ELEMENT_UNUNOCTIUM

#define Q_CHEMICAL_ELEMENT_BLOCK_S 1
#define Q_CHEMICAL_ELEMENT_BLOCK_P 2
#define Q_CHEMICAL_ELEMENT_BLOCK_D 3
#define Q_CHEMICAL_ELEMENT_BLOCK_F 4

#define Q_KEY_BITS_CHEMICAL_ELEMENT_BLOCK 8
#define Q_KEY_LAST_CHEMICAL_ELEMENT_BLOCK Q_CHEMICAL_ELEMENT_BLOCK_F

#define Q_CHEMICAL_ELEMENT_CLASS_NON_METAL	       1
#define Q_CHEMICAL_ELEMENT_CLASS_NOBLE_GAS	       2
#define Q_CHEMICAL_ELEMENT_CLASS_ALKALI_METAL	       3
#define Q_CHEMICAL_ELEMENT_CLASS_ALKALINE_EARTH_METAL  4
#define Q_CHEMICAL_ELEMENT_CLASS_METALLOID	       5
#define Q_CHEMICAL_ELEMENT_CLASS_HALOGEN	       6
#define Q_CHEMICAL_ELEMENT_CLASS_POOR_METAL	       7
#define Q_CHEMICAL_ELEMENT_CLASS_TRANSITION_METAL      8
#define Q_CHEMICAL_ELEMENT_CLASS_LANTHANIDE	       9
#define Q_CHEMICAL_ELEMENT_CLASS_ACTINIDE	      10

#define Q_KEY_BITS_CHEMICAL_ELEMENT_CLASS 8
#define Q_KEY_LAST_CHEMICAL_ELEMENT_CLASS Q_CHEMICAL_ELEMENT_CLASS_ACTINIDE

#define Q_CHEMICAL_ELEMENT_METAL_STATE_NON_METAL 1
#define Q_CHEMICAL_ELEMENT_METAL_STATE_METAL	 2
#define Q_CHEMICAL_ELEMENT_METAL_STATE_METALLOID 3

#define Q_KEY_BITS_CHEMICAL_ELEMENT_METAL_STATE 8
#define Q_KEY_LAST_CHEMICAL_ELEMENT_METAL_STATE Q_CHEMICAL_ELEMENT_METAL_STATE_METALLOID

#define Q_CHEMICAL_ELEMENT_GAS_PHASE_MONOATOMIC	1
#define Q_CHEMICAL_ELEMENT_GAS_PHASE_DIATOMIC	2

#define Q_KEY_BITS_CHEMICAL_ELEMENT_GAS_PHASE 8
#define Q_KEY_LAST_CHEMICAL_ELEMENT_GAS_PHASE Q_CHEMICAL_ELEMENT_GAS_PHASE_DIATOMIC

#define Q_CHEMICAL_ELEMENT_DECAY_MODE_BETA_DECAY       1
#define Q_CHEMICAL_ELEMENT_DECAY_MODE_ELECTRON_CAPTURE 2
#define Q_CHEMICAL_ELEMENT_DECAY_MODE_ALPHA_EMISSION   3
#define Q_CHEMICAL_ELEMENT_DECAY_MODE_BETA_PLUS_DECAY  4

#define Q_KEY_BITS_CHEMICAL_ELEMENT_DECAY_MODE 8
#define Q_KEY_LAST_CHEMICAL_ELEMENT_DECAY_MODE Q_CHEMICAL_ELEMENT_DECAY_MODE_BETA_PLUS_DECAY

#define Q_CHEMICAL_ELEMENT_ADIABATIC_INDEX_5_3 1
#define Q_CHEMICAL_ELEMENT_ADIABATIC_INDEX_7_5 2

#define Q_KEY_BITS_CHEMICAL_ELEMENT_ADIABATIC_INDEX 8
#define Q_KEY_LAST_CHEMICAL_ELEMENT_ADIABATIC_INDEX Q_CHEMICAL_ELEMENT_ADIABATIC_INDEX_7_5

#endif /* __Q_keys_science_chemistry_H__ */
