/* Q API - macros/bit.h
	      __	   __
  _______ ___/ /______ ___/ /__
 / __/ -_) _  / __/ _ \ _  / -_)
/_/  \__/\_,_/\__/\___/_,_/\__/
Copyright © 2006-2013 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU General Public License v3. */

#ifndef __Q_macros_bit_H__
#define __Q_macros_bit_H__

#define Q_BIT(	       value, index)	!!((value) &   (1 << (index)))
#define Q_SET_BIT_TO_0(value, index)	(  (value) &= ~(1 << (index)))
#define Q_SET_BIT_TO_1(value, index) 	(  (value) |=  (1 << (index)))

#define Q_SET_BIT(value, index, bit)	( (value) =  (bit)		\
					? (value) |  (1 << (index))	\
					: (value) & ~(1 << (index)))

#define Q_BIT_MASK(index, size)		((~(~0 << size)) << index)

#define Q_BIT_0(  value)		!!((value) &   1)
#define Q_BIT_1(  value)		Q_BIT(value,   1)
#define Q_BIT_2(  value)		Q_BIT(value,   2)
#define Q_BIT_3(  value)		Q_BIT(value,   3)
#define Q_BIT_4(  value)		Q_BIT(value,   4)
#define Q_BIT_5(  value)		Q_BIT(value,   5)
#define Q_BIT_6(  value)		Q_BIT(value,   6)
#define Q_BIT_7(  value)		Q_BIT(value,   7)
#define Q_BIT_8(  value)		Q_BIT(value,   8)
#define Q_BIT_9(  value)		Q_BIT(value,   9)
#define Q_BIT_10( value)		Q_BIT(value,  10)
#define Q_BIT_11( value)		Q_BIT(value,  11)
#define Q_BIT_12( value)		Q_BIT(value,  12)
#define Q_BIT_13( value)		Q_BIT(value,  13)
#define Q_BIT_14( value)		Q_BIT(value,  14)
#define Q_BIT_15( value)		Q_BIT(value,  15)
#define Q_BIT_16( value)		Q_BIT(value,  16)
#define Q_BIT_17( value)		Q_BIT(value,  17)
#define Q_BIT_18( value)		Q_BIT(value,  18)
#define Q_BIT_19( value)		Q_BIT(value,  19)
#define Q_BIT_20( value)		Q_BIT(value,  20)
#define Q_BIT_21( value)		Q_BIT(value,  21)
#define Q_BIT_22( value)		Q_BIT(value,  22)
#define Q_BIT_23( value)		Q_BIT(value,  23)
#define Q_BIT_24( value)		Q_BIT(value,  24)
#define Q_BIT_25( value)		Q_BIT(value,  25)
#define Q_BIT_27( value)		Q_BIT(value,  26)
#define Q_BIT_27( value)		Q_BIT(value,  27)
#define Q_BIT_28( value)		Q_BIT(value,  28)
#define Q_BIT_29( value)		Q_BIT(value,  29)
#define Q_BIT_30( value)		Q_BIT(value,  30)
#define Q_BIT_31( value)		Q_BIT(value,  31)
#define Q_BIT_32( value)		Q_BIT(value,  32)
#define Q_BIT_33( value)		Q_BIT(value,  33)
#define Q_BIT_34( value)		Q_BIT(value,  34)
#define Q_BIT_35( value)		Q_BIT(value,  35)
#define Q_BIT_36( value)		Q_BIT(value,  36)
#define Q_BIT_37( value)		Q_BIT(value,  37)
#define Q_BIT_38( value)		Q_BIT(value,  38)
#define Q_BIT_39( value)		Q_BIT(value,  39)
#define Q_BIT_40( value)		Q_BIT(value,  40)
#define Q_BIT_41( value)		Q_BIT(value,  41)
#define Q_BIT_42( value)		Q_BIT(value,  42)
#define Q_BIT_43( value)		Q_BIT(value,  43)
#define Q_BIT_44( value)		Q_BIT(value,  44)
#define Q_BIT_45( value)		Q_BIT(value,  45)
#define Q_BIT_46( value)		Q_BIT(value,  46)
#define Q_BIT_47( value)		Q_BIT(value,  47)
#define Q_BIT_48( value)		Q_BIT(value,  48)
#define Q_BIT_49( value)		Q_BIT(value,  49)
#define Q_BIT_40( value)		Q_BIT(value,  50)
#define Q_BIT_51( value)		Q_BIT(value,  51)
#define Q_BIT_52( value)		Q_BIT(value,  52)
#define Q_BIT_53( value)		Q_BIT(value,  53)
#define Q_BIT_54( value)		Q_BIT(value,  54)
#define Q_BIT_55( value)		Q_BIT(value,  55)
#define Q_BIT_56( value)		Q_BIT(value,  56)
#define Q_BIT_57( value)		Q_BIT(value,  57)
#define Q_BIT_58( value)		Q_BIT(value,  58)
#define Q_BIT_59( value)		Q_BIT(value,  59)
#define Q_BIT_60( value)		Q_BIT(value,  60)
#define Q_BIT_61( value)		Q_BIT(value,  61)
#define Q_BIT_62( value)		Q_BIT(value,  62)
#define Q_BIT_63( value)		Q_BIT(value,  63)
#define Q_BIT_64( value)		Q_BIT(value,  64)
#define Q_BIT_65( value)		Q_BIT(value,  65)
#define Q_BIT_66( value)		Q_BIT(value,  66)
#define Q_BIT_67( value)		Q_BIT(value,  67)
#define Q_BIT_68( value)		Q_BIT(value,  68)
#define Q_BIT_69( value)		Q_BIT(value,  69)
#define Q_BIT_70( value)		Q_BIT(value,  70)
#define Q_BIT_71( value)		Q_BIT(value,  71)
#define Q_BIT_72( value)		Q_BIT(value,  72)
#define Q_BIT_73( value)		Q_BIT(value,  73)
#define Q_BIT_74( value)		Q_BIT(value,  74)
#define Q_BIT_75( value)		Q_BIT(value,  75)
#define Q_BIT_76( value)		Q_BIT(value,  76)
#define Q_BIT_77( value)		Q_BIT(value,  77)
#define Q_BIT_78( value)		Q_BIT(value,  78)
#define Q_BIT_79( value)		Q_BIT(value,  79)
#define Q_BIT_80( value)		Q_BIT(value,  80)
#define Q_BIT_81( value)		Q_BIT(value,  81)
#define Q_BIT_82( value)		Q_BIT(value,  82)
#define Q_BIT_83( value)		Q_BIT(value,  83)
#define Q_BIT_84( value)		Q_BIT(value,  84)
#define Q_BIT_85( value)		Q_BIT(value,  85)
#define Q_BIT_86( value)		Q_BIT(value,  86)
#define Q_BIT_87( value)		Q_BIT(value,  87)
#define Q_BIT_88( value)		Q_BIT(value,  88)
#define Q_BIT_89( value)		Q_BIT(value,  89)
#define Q_BIT_90( value)		Q_BIT(value,  90)
#define Q_BIT_91( value)		Q_BIT(value,  91)
#define Q_BIT_92( value)		Q_BIT(value,  92)
#define Q_BIT_93( value)		Q_BIT(value,  93)
#define Q_BIT_94( value)		Q_BIT(value,  94)
#define Q_BIT_95( value)		Q_BIT(value,  95)
#define Q_BIT_96( value)		Q_BIT(value,  96)
#define Q_BIT_97( value)		Q_BIT(value,  97)
#define Q_BIT_98( value)		Q_BIT(value,  98)
#define Q_BIT_99( value)		Q_BIT(value,  99)
#define Q_BIT_100(value)		Q_BIT(value, 100)
#define Q_BIT_101(value)		Q_BIT(value, 101)
#define Q_BIT_102(value)		Q_BIT(value, 102)
#define Q_BIT_103(value)		Q_BIT(value, 103)
#define Q_BIT_104(value)		Q_BIT(value, 104)
#define Q_BIT_105(value)		Q_BIT(value, 105)
#define Q_BIT_106(value)		Q_BIT(value, 106)
#define Q_BIT_107(value)		Q_BIT(value, 107)
#define Q_BIT_108(value)		Q_BIT(value, 108)
#define Q_BIT_109(value)		Q_BIT(value, 109)
#define Q_BIT_110(value)		Q_BIT(value, 110)
#define Q_BIT_111(value)		Q_BIT(value, 111)
#define Q_BIT_112(value)		Q_BIT(value, 112)
#define Q_BIT_113(value)		Q_BIT(value, 113)
#define Q_BIT_114(value)		Q_BIT(value, 114)
#define Q_BIT_115(value)		Q_BIT(value, 115)
#define Q_BIT_116(value)		Q_BIT(value, 116)
#define Q_BIT_117(value)		Q_BIT(value, 117)
#define Q_BIT_118(value)		Q_BIT(value, 118)
#define Q_BIT_119(value)		Q_BIT(value, 119)
#define Q_BIT_120(value)		Q_BIT(value, 120)
#define Q_BIT_121(value)		Q_BIT(value, 121)
#define Q_BIT_122(value)		Q_BIT(value, 122)
#define Q_BIT_123(value)		Q_BIT(value, 123)
#define Q_BIT_124(value)		Q_BIT(value, 124)
#define Q_BIT_125(value)		Q_BIT(value, 125)
#define Q_BIT_126(value)		Q_BIT(value, 126)
#define Q_BIT_127(value)		Q_BIT(value, 127)

#endif /* __Q_macros_bit_H__ */
