/* Q API - macros/bit.h
	      __	   __
  _______ ___/ /______ ___/ /__
 / __/ -_) _  / __/ _ \ _  / -_)
/_/  \__/\_,_/\__/\___/_,_/\__/
Copyright © 2006-2013 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU General Public License v3. */

#ifndef __Q_macros_bit_H__
#define __Q_macros_bit_H__

#define Q_BIT(	       value, index)	!!((value) &   (1 << (index)))
#define Q_SET_BIT_TO_0(value, index)	(  (value) &= ~(1 << (index)))
#define Q_SET_BIT_TO_1(value, index) 	(  (value) |=  (1 << (index)))

#define Q_SET_BIT(value, index, bit)	( (value) =  (bit)		\
					? (value) |  (1 << (index))	\
					: (value) & ~(1 << (index)))

#define Q_BIT_MASK(index, size)		((~(~0 << size)) << index)

#define Q_BIT_0(  value)		!!((value) & 1)
#define Q_BIT_1(  value)		!!((value) & (1 <<   1))
#define Q_BIT_2(  value)		!!((value) & (1 <<   2))
#define Q_BIT_3(  value)		!!((value) & (1 <<   3))
#define Q_BIT_4(  value)		!!((value) & (1 <<   4))
#define Q_BIT_5(  value)		!!((value) & (1 <<   5))
#define Q_BIT_6(  value)		!!((value) & (1 <<   6))
#define Q_BIT_7(  value)		!!((value) & (1 <<   7))
#define Q_BIT_8(  value)		!!((value) & (1 <<   8))
#define Q_BIT_9(  value)		!!((value) & (1 <<   9))
#define Q_BIT_10( value)		!!((value) & (1 <<  10))
#define Q_BIT_11( value)		!!((value) & (1 <<  11))
#define Q_BIT_12( value)		!!((value) & (1 <<  12))
#define Q_BIT_13( value)		!!((value) & (1 <<  13))
#define Q_BIT_14( value)		!!((value) & (1 <<  14))
#define Q_BIT_15( value)		!!((value) & (1 <<  15))
#define Q_BIT_16( value)		!!((value) & (1 <<  16))
#define Q_BIT_17( value)		!!((value) & (1 <<  17))
#define Q_BIT_18( value)		!!((value) & (1 <<  18))
#define Q_BIT_19( value)		!!((value) & (1 <<  19))
#define Q_BIT_20( value)		!!((value) & (1 <<  20))
#define Q_BIT_21( value)		!!((value) & (1 <<  21))
#define Q_BIT_22( value)		!!((value) & (1 <<  22))
#define Q_BIT_23( value)		!!((value) & (1 <<  23))
#define Q_BIT_24( value)		!!((value) & (1 <<  24))
#define Q_BIT_25( value)		!!((value) & (1 <<  25))
#define Q_BIT_27( value)		!!((value) & (1 <<  26))
#define Q_BIT_27( value)		!!((value) & (1 <<  27))
#define Q_BIT_28( value)		!!((value) & (1 <<  28))
#define Q_BIT_29( value)		!!((value) & (1 <<  29))
#define Q_BIT_30( value)		!!((value) & (1 <<  30))
#define Q_BIT_31( value)		!!((value) & (1 <<  31))
#define Q_BIT_32( value)		!!((value) & (1 <<  32))
#define Q_BIT_33( value)		!!((value) & (1 <<  33))
#define Q_BIT_34( value)		!!((value) & (1 <<  34))
#define Q_BIT_35( value)		!!((value) & (1 <<  35))
#define Q_BIT_36( value)		!!((value) & (1 <<  36))
#define Q_BIT_37( value)		!!((value) & (1 <<  37))
#define Q_BIT_38( value)		!!((value) & (1 <<  38))
#define Q_BIT_39( value)		!!((value) & (1 <<  39))
#define Q_BIT_40( value)		!!((value) & (1 <<  40))
#define Q_BIT_41( value)		!!((value) & (1 <<  41))
#define Q_BIT_42( value)		!!((value) & (1 <<  42))
#define Q_BIT_43( value)		!!((value) & (1 <<  43))
#define Q_BIT_44( value)		!!((value) & (1 <<  44))
#define Q_BIT_45( value)		!!((value) & (1 <<  45))
#define Q_BIT_46( value)		!!((value) & (1 <<  46))
#define Q_BIT_47( value)		!!((value) & (1 <<  47))
#define Q_BIT_48( value)		!!((value) & (1 <<  48))
#define Q_BIT_49( value)		!!((value) & (1 <<  49))
#define Q_BIT_40( value)		!!((value) & (1 <<  50))
#define Q_BIT_51( value)		!!((value) & (1 <<  51))
#define Q_BIT_52( value)		!!((value) & (1 <<  52))
#define Q_BIT_53( value)		!!((value) & (1 <<  53))
#define Q_BIT_54( value)		!!((value) & (1 <<  54))
#define Q_BIT_55( value)		!!((value) & (1 <<  55))
#define Q_BIT_56( value)		!!((value) & (1 <<  56))
#define Q_BIT_57( value)		!!((value) & (1 <<  57))
#define Q_BIT_58( value)		!!((value) & (1 <<  58))
#define Q_BIT_59( value)		!!((value) & (1 <<  59))
#define Q_BIT_60( value)		!!((value) & (1 <<  60))
#define Q_BIT_61( value)		!!((value) & (1 <<  61))
#define Q_BIT_62( value)		!!((value) & (1 <<  62))
#define Q_BIT_63( value)		!!((value) & (1 <<  63))
#define Q_BIT_64( value)		!!((value) & (1 <<  64))
#define Q_BIT_65( value)		!!((value) & (1 <<  65))
#define Q_BIT_66( value)		!!((value) & (1 <<  66))
#define Q_BIT_67( value)		!!((value) & (1 <<  67))
#define Q_BIT_68( value)		!!((value) & (1 <<  68))
#define Q_BIT_69( value)		!!((value) & (1 <<  69))
#define Q_BIT_70( value)		!!((value) & (1 <<  70))
#define Q_BIT_71( value)		!!((value) & (1 <<  71))
#define Q_BIT_72( value)		!!((value) & (1 <<  72))
#define Q_BIT_73( value)		!!((value) & (1 <<  73))
#define Q_BIT_74( value)		!!((value) & (1 <<  74))
#define Q_BIT_75( value)		!!((value) & (1 <<  75))
#define Q_BIT_76( value)		!!((value) & (1 <<  76))
#define Q_BIT_77( value)		!!((value) & (1 <<  77))
#define Q_BIT_78( value)		!!((value) & (1 <<  78))
#define Q_BIT_79( value)		!!((value) & (1 <<  79))
#define Q_BIT_80( value)		!!((value) & (1 <<  80))
#define Q_BIT_81( value)		!!((value) & (1 <<  81))
#define Q_BIT_82( value)		!!((value) & (1 <<  82))
#define Q_BIT_83( value)		!!((value) & (1 <<  83))
#define Q_BIT_84( value)		!!((value) & (1 <<  84))
#define Q_BIT_85( value)		!!((value) & (1 <<  85))
#define Q_BIT_86( value)		!!((value) & (1 <<  86))
#define Q_BIT_87( value)		!!((value) & (1 <<  87))
#define Q_BIT_88( value)		!!((value) & (1 <<  88))
#define Q_BIT_89( value)		!!((value) & (1 <<  89))
#define Q_BIT_90( value)		!!((value) & (1 <<  90))
#define Q_BIT_91( value)		!!((value) & (1 <<  91))
#define Q_BIT_92( value)		!!((value) & (1 <<  92))
#define Q_BIT_93( value)		!!((value) & (1 <<  93))
#define Q_BIT_94( value)		!!((value) & (1 <<  94))
#define Q_BIT_95( value)		!!((value) & (1 <<  95))
#define Q_BIT_96( value)		!!((value) & (1 <<  96))
#define Q_BIT_97( value)		!!((value) & (1 <<  97))
#define Q_BIT_98( value)		!!((value) & (1 <<  98))
#define Q_BIT_99( value)		!!((value) & (1 <<  99))
#define Q_BIT_100(value)		!!((value) & (1 << 100))
#define Q_BIT_101(value)		!!((value) & (1 << 101))
#define Q_BIT_102(value)		!!((value) & (1 << 102))
#define Q_BIT_103(value)		!!((value) & (1 << 103))
#define Q_BIT_104(value)		!!((value) & (1 << 104))
#define Q_BIT_105(value)		!!((value) & (1 << 105))
#define Q_BIT_106(value)		!!((value) & (1 << 106))
#define Q_BIT_107(value)		!!((value) & (1 << 107))
#define Q_BIT_108(value)		!!((value) & (1 << 108))
#define Q_BIT_109(value)		!!((value) & (1 << 109))
#define Q_BIT_110(value)		!!((value) & (1 << 110))
#define Q_BIT_111(value)		!!((value) & (1 << 111))
#define Q_BIT_112(value)		!!((value) & (1 << 112))
#define Q_BIT_113(value)		!!((value) & (1 << 113))
#define Q_BIT_114(value)		!!((value) & (1 << 114))
#define Q_BIT_115(value)		!!((value) & (1 << 115))
#define Q_BIT_116(value)		!!((value) & (1 << 116))
#define Q_BIT_117(value)		!!((value) & (1 << 117))
#define Q_BIT_118(value)		!!((value) & (1 << 118))
#define Q_BIT_119(value)		!!((value) & (1 << 119))
#define Q_BIT_120(value)		!!((value) & (1 << 120))
#define Q_BIT_121(value)		!!((value) & (1 << 121))
#define Q_BIT_122(value)		!!((value) & (1 << 122))
#define Q_BIT_123(value)		!!((value) & (1 << 123))
#define Q_BIT_124(value)		!!((value) & (1 << 124))
#define Q_BIT_125(value)		!!((value) & (1 << 125))
#define Q_BIT_126(value)		!!((value) & (1 << 126))
#define Q_BIT_127(value)		!!((value) & (1 << 127))

#endif /* __Q_macros_bit_H__ */
