/* Z Kit - inspection/C++/completion.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//___/_| Kit
Copyright (C) 2006-2019 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_inspection_CPP_completion_H_
#define Z_inspection_CPP_completion_H_

/* MARK: - C++98 */


/* MARK: - C++03 */

#ifndef Z_CPP_HAS_VALUE_INITIALIZATION
#	define Z_CPP_HAS_VALUE_INITIALIZATION FALSE
#endif

/* MARK: - C++11 */

#ifndef Z_CPP_HAS_C99_PREPROCESSOR
#	define Z_CPP_HAS_C99_PREPROCESSOR FALSE
#endif

#ifndef Z_CPP_HAS_CONCURRENT_STATIC_LOCAL_VARIABLE
#	define Z_CPP_HAS_CONCURRENT_STATIC_LOCAL_VARIABLE FALSE
#endif

#ifndef Z_CPP_HAS_CONDITIONALLY_SUPPORTED_BEHAVIOR
#	define Z_CPP_HAS_CONDITIONALLY_SUPPORTED_BEHAVIOR FALSE
#endif

#ifndef Z_CPP_HAS_COPY_LIST_INITIALIZATION
#	define Z_CPP_HAS_COPY_LIST_INITIALIZATION FALSE
#endif

#ifndef Z_CPP_HAS_CPP11_RULES_ON_UNIVERSAL_CHARACTER_NAMES
#	define Z_CPP_HAS_CPP11_RULES_ON_UNIVERSAL_CHARACTER_NAMES FALSE
#endif

#ifndef Z_CPP_HAS_DEFAULT_MEMBER_INITIALIZER
#	define Z_CPP_HAS_DEFAULT_MEMBER_INITIALIZER FALSE
#endif

#ifndef Z_CPP_HAS_DEFAULT_TEMPLATE_ARGUMENTS_FOR_FUNCTION_TEMPLATE
#	define Z_CPP_HAS_DEFAULT_TEMPLATE_ARGUMENTS_FOR_FUNCTION_TEMPLATE FALSE
#endif

#ifndef Z_CPP_HAS_DEFAULTED_FUNCTION
#	define Z_CPP_HAS_DEFAULTED_FUNCTION FALSE
#endif

#ifndef Z_CPP_HAS_DELEGATING_CONSTRUCTORS
#	define Z_CPP_HAS_DELEGATING_CONSTRUCTORS FALSE
#endif

#ifndef Z_CPP_HAS_DELETED_FUNCTION
#	define Z_CPP_HAS_DELETED_FUNCTION FALSE
#endif

#ifndef Z_CPP_HAS_DIRECT_LIST_INITIALIZATION
#	define Z_CPP_HAS_DIRECT_LIST_INITIALIZATION FALSE
#endif

#ifndef Z_CPP_HAS_EXPRESSION_SFINAE
#	define Z_CPP_HAS_EXPRESSION_SFINAE FALSE
#endif

#ifndef Z_CPP_HAS_EXTENDED_FRIEND_DECLARATION
#	define Z_CPP_HAS_EXTENDED_FRIEND_DECLARATION FALSE
#endif

#ifndef Z_CPP_HAS_EXTERN_TEMPLATE
#	define Z_CPP_HAS_EXTERN_TEMPLATE FALSE
#endif

#ifndef Z_CPP_HAS_INHERITING_CONSTRUCTORS
#	define Z_CPP_HAS_INHERITING_CONSTRUCTORS FALSE
#endif

#ifndef Z_CPP_HAS_INITIALIZATION_OF_CLASS_OBJECT_BY_RVALUE
#	define Z_CPP_HAS_INITIALIZATION_OF_CLASS_OBJECT_BY_RVALUE FALSE
#endif

#ifndef Z_CPP_HAS_INITIALIZER_LIST
#	define Z_CPP_HAS_INITIALIZER_LIST FALSE
#endif

#ifndef Z_CPP_HAS_INLINE_NAMESPACE
#	define Z_CPP_HAS_INLINE_NAMESPACE FALSE
#endif

#ifndef Z_CPP_HAS_LAMBDA
#	define Z_CPP_HAS_LAMBDA FALSE
#endif

#ifndef Z_CPP_HAS_LOCAL_TYPE_AS_TEMPLATE_ARGUMENT
#	define Z_CPP_HAS_LOCAL_TYPE_AS_TEMPLATE_ARGUMENT FALSE
#endif

#ifndef Z_CPP_HAS_MOVE_SPECIAL_MEMBER_FUNCTIONS
#	define Z_CPP_HAS_MOVE_SPECIAL_MEMBER_FUNCTIONS FALSE
#endif

#ifndef Z_CPP_HAS_MULTI_DECLARATOR_AUTO
#	define Z_CPP_HAS_MULTI_DECLARATOR_AUTO FALSE
#endif

#ifndef Z_CPP_HAS_OPAQUE_ENUMERATION_DECLARATION
#	define Z_CPP_HAS_OPAQUE_ENUMERATION_DECLARATION FALSE
#endif

#ifndef Z_CPP_HAS_RANGE_BASED_FOR
#	define Z_CPP_HAS_RANGE_BASED_FOR FALSE
#endif

#ifndef Z_CPP_HAS_REFERENCE_QUALIFIED_NON_STATIC_MEMBER_FUNCTION
#	define Z_CPP_HAS_REFERENCE_QUALIFIED_NON_STATIC_MEMBER_FUNCTION FALSE
#endif

#ifndef Z_CPP_HAS_REMOVAL_OF_AUTO_AS_STORAGE_CLASS
#	define Z_CPP_HAS_REMOVAL_OF_AUTO_AS_STORAGE_CLASS FALSE
#endif

#ifndef Z_CPP_HAS_RIGHT_ANGLE_BRACKETS
#	define Z_CPP_HAS_RIGHT_ANGLE_BRACKETS FALSE
#endif

#ifndef Z_CPP_HAS_RVALUE_REFERENCE
#	define Z_CPP_HAS_RVALUE_REFERENCE FALSE
#endif

#ifndef Z_CPP_HAS_STANDARD_LAYOUT
#	define Z_CPP_HAS_STANDARD_LAYOUT FALSE
#endif

#ifndef Z_CPP_HAS_STANDARDIZED_ATTRIBUTE_SYNTAX
#	define Z_CPP_HAS_STANDARDIZED_ATTRIBUTE_SYNTAX FALSE
#endif

#ifndef Z_CPP_HAS_STATIC_ASSERTION
#	define Z_CPP_HAS_STATIC_ASSERTION FALSE
#endif

#ifndef Z_CPP_HAS_STRONGLY_TYPED_ENUMERATION
#	define Z_CPP_HAS_STRONGLY_TYPED_ENUMERATION FALSE
#endif

#ifndef Z_CPP_HAS_TEMPLATE_ALIAS
#	define Z_CPP_HAS_TEMPLATE_ALIAS FALSE
#endif

#ifndef Z_CPP_HAS_TRAILING_RETURN_TYPE
#	define Z_CPP_HAS_TRAILING_RETURN_TYPE FALSE
#endif

#ifndef Z_CPP_HAS_UNNAMED_TYPE_AS_TEMPLATE_ARGUMENT
#	define Z_CPP_HAS_UNNAMED_TYPE_AS_TEMPLATE_ARGUMENT FALSE
#endif

#ifndef Z_CPP_HAS_UNRESTRICTED_UNION
#	define Z_CPP_HAS_UNRESTRICTED_UNION FALSE
#endif

#ifndef Z_CPP_HAS_VARIADIC_TEMPLATE
#	define Z_CPP_HAS_VARIADIC_TEMPLATE FALSE
#endif

#ifndef Z_CPP_HAS_VARIADIC_TEMPLATE_EXTENDED_PARAMETERS
#	define Z_CPP_HAS_VARIADIC_TEMPLATE_EXTENDED_PARAMETERS FALSE
#endif

#ifndef Z_CPP_HAS_ATTRIBUTE_CARRIES_DEPENDENCY
#	define Z_CPP_HAS_ATTRIBUTE_CARRIES_DEPENDENCY FALSE
#endif

#ifndef Z_CPP_HAS_ATTRIBUTE_NORETURN
#	define Z_CPP_HAS_ATTRIBUTE_NORETURN FALSE
#endif

#ifndef Z_CPP_HAS_IDENTIFIER_FUNC
#	define Z_CPP_HAS_IDENTIFIER_FUNC FALSE
#endif

#ifndef Z_CPP_HAS_LITERAL_CHAR16_T_CHARACTER
#	define Z_CPP_HAS_LITERAL_CHAR16_T_CHARACTER FALSE
#endif

#ifndef Z_CPP_HAS_LITERAL_CHAR16_T_STRING
#	define Z_CPP_HAS_LITERAL_CHAR16_T_STRING FALSE
#endif

#ifndef Z_CPP_HAS_LITERAL_CHAR32_T_CHARACTER
#	define Z_CPP_HAS_LITERAL_CHAR32_T_CHARACTER FALSE
#endif

#ifndef Z_CPP_HAS_LITERAL_CHAR32_T_STRING
#	define Z_CPP_HAS_LITERAL_CHAR32_T_STRING FALSE
#endif

#ifndef Z_CPP_HAS_LITERAL_NULLPTR
#	define Z_CPP_HAS_LITERAL_NULLPTR FALSE
#endif

#ifndef Z_CPP_HAS_LITERAL_RAW_STRING
#	define Z_CPP_HAS_LITERAL_RAW_STRING FALSE
#endif

#ifndef Z_CPP_HAS_LITERAL_UNICODE_STRING
#	define Z_CPP_HAS_LITERAL_UNICODE_STRING FALSE
#endif

#ifndef Z_CPP_HAS_LITERAL_USER_DEFINED
#	define Z_CPP_HAS_LITERAL_USER_DEFINED FALSE
#endif

#ifndef Z_CPP_HAS_OPERATOR_ALIGNOF
#	define Z_CPP_HAS_OPERATOR_ALIGNOF FALSE
#endif

#ifndef Z_CPP_HAS_OPERATOR_NOEXCEPT
#	define Z_CPP_HAS_OPERATOR_NOEXCEPT FALSE
#endif

#ifndef Z_CPP_HAS_OPERATOR_CASE_SIZEOF_NON_STATIC_DATA_MEMBER
#	define Z_CPP_HAS_OPERATOR_CASE_SIZEOF_NON_STATIC_DATA_MEMBER FALSE
#endif

#ifndef Z_CPP_HAS_OPERATOR_CASE_SIZEOF_PARAMETER_PACK
#	define Z_CPP_HAS_OPERATOR_CASE_SIZEOF_PARAMETER_PACK FALSE
#endif

#ifndef Z_CPP_HAS_SPECIFIER_ALIGNAS
#	define Z_CPP_HAS_SPECIFIER_ALIGNAS FALSE
#endif

#ifndef Z_CPP_HAS_SPECIFIER_CONSTEXPR
#	define Z_CPP_HAS_SPECIFIER_CONSTEXPR FALSE
#endif

#ifndef Z_CPP_HAS_SPECIFIER_DECLTYPE
#	define Z_CPP_HAS_SPECIFIER_DECLTYPE FALSE
#endif

#ifndef Z_CPP_HAS_SPECIFIER_FINAL
#	define Z_CPP_HAS_SPECIFIER_FINAL FALSE
#endif

#ifndef Z_CPP_HAS_SPECIFIER_NOEXCEPT
#	define Z_CPP_HAS_SPECIFIER_NOEXCEPT FALSE
#endif

#ifndef Z_CPP_HAS_SPECIFIER_OVERRIDE
#	define Z_CPP_HAS_SPECIFIER_OVERRIDE FALSE
#endif

#ifndef Z_CPP_HAS_SPECIFIER_CASE_DECLTYPE_INCOMPLETE_RETURN
#	define Z_CPP_HAS_SPECIFIER_CASE_DECLTYPE_INCOMPLETE_RETURN FALSE
#endif

#ifndef Z_CPP_HAS_SPECIFIER_CASE_EXPLICIT_CONVERSION_FUNCTION
#	define Z_CPP_HAS_SPECIFIER_CASE_EXPLICIT_CONVERSION_FUNCTION FALSE
#endif

#ifndef Z_CPP_HAS_STORATE_CLASS_THREAD_LOCAL
#	define Z_CPP_HAS_STORATE_CLASS_THREAD_LOCAL FALSE
#endif

#ifndef Z_CPP_HAS_TYPE_AUTO
#	define Z_CPP_HAS_TYPE_AUTO FALSE
#endif

#ifndef Z_CPP_HAS_TYPE_CHAR16_T
#	define Z_CPP_HAS_TYPE_CHAR16_T FALSE
#endif

#ifndef Z_CPP_HAS_TYPE_CHAR32_T
#	define Z_CPP_HAS_TYPE_CHAR32_T FALSE
#endif

#ifndef Z_CPP_HAS_TYPE_LONG_LONG
#	define Z_CPP_HAS_TYPE_LONG_LONG FALSE
#endif

/* MARK: - C++14 */

#ifndef Z_CPP_HAS_APOSTROPHE_AS_DIGIT_SEPARATOR
#	define Z_CPP_HAS_APOSTROPHE_AS_DIGIT_SEPARATOR FALSE
#endif

#ifndef Z_CPP_HAS_CPP14_RULES_ON_CONSTEXPR_FUNCTION
#	define Z_CPP_HAS_CPP14_RULES_ON_CONSTEXPR_FUNCTION FALSE
#endif

#ifndef Z_CPP_HAS_CPP14_RULES_ON_CONTEXTUAL_CONVERSION
#	define Z_CPP_HAS_CPP14_RULES_ON_CONTEXTUAL_CONVERSION FALSE
#endif

#ifndef Z_CPP_HAS_DEFAULT_MEMBER_INITIALIZER_FOR_AGGREGATE
#	define Z_CPP_HAS_DEFAULT_MEMBER_INITIALIZER_FOR_AGGREGATE FALSE
#endif

#ifndef Z_CPP_HAS_GENERIC_LAMBDA
#	define Z_CPP_HAS_GENERIC_LAMBDA FALSE
#endif

#ifndef Z_CPP_HAS_INITIALIZED_LAMBDA_CAPTURE
#	define Z_CPP_HAS_INITIALIZED_LAMBDA_CAPTURE FALSE
#endif

#ifndef Z_CPP_HAS_RETURN_TYPE_DEDUCTION_FOR_NORMAL_FUNCTION
#	define Z_CPP_HAS_RETURN_TYPE_DEDUCTION_FOR_NORMAL_FUNCTION FALSE
#endif

#ifndef Z_CPP_HAS_SIZED_DEALLOCATION
#	define Z_CPP_HAS_SIZED_DEALLOCATION FALSE
#endif

#ifndef Z_CPP_HAS_VARIABLE_TEMPLATE
#	define Z_CPP_HAS_VARIABLE_TEMPLATE FALSE
#endif

#ifndef Z_CPP_HAS_ATTRIBUTE_DEPRECATED
#	define Z_CPP_HAS_ATTRIBUTE_DEPRECATED FALSE
#endif

#ifndef Z_CPP_HAS_LITERAL_BINARY_INTEGRAL
#	define Z_CPP_HAS_LITERAL_BINARY_INTEGRAL FALSE
#endif

#ifndef Z_CPP_HAS_SPECIFIER_CASE_DECLTYPE_AUTO
#	define Z_CPP_HAS_SPECIFIER_CASE_DECLTYPE_AUTO FALSE
#endif

/* MARK: - C++17 */



#endif /* Z_inspection_CPP_completion_H_ */
