/* Z Kit - formats/character set/Unicode/Arabic Extended-A.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_Arabic_Extended_A_H
#define Z_formats_character_set_Unicode_Arabic_Extended_A_H

/* 08A0h-08FFh - Arabic Extended-A */

#define Z_UNICODE_ARABIC_LETTER_BEH_WITH_SMALL_V_BELOW			0x8A0
#define Z_UNICODE_ARABIC_LETTER_BEH_WITH_HAMZA_ABOVE			0x8A1
#define Z_UNICODE_ARABIC_LETTER_JEEM_WITH_TWO_DOTS_ABOVE		0x8A2
#define Z_UNICODE_ARABIC_LETTER_TAH_WITH_TWO_DOTS_ABOVE			0x8A3
#define Z_UNICODE_ARABIC_LETTER_FEH_WITH_DOT_BELOW_AND_THREE_DOTS_ABOVE	0x8A4
#define Z_UNICODE_ARABIC_LETTER_QAF_WITH_DOT_BELOW			0x8A5
#define Z_UNICODE_ARABIC_LETTER_LAM_WITH_DOUBLE_BAR			0x8A6
#define Z_UNICODE_ARABIC_LETTER_MEEM_WITH_THREE_DOTS_ABOVE		0x8A7
#define Z_UNICODE_ARABIC_LETTER_YEH_WITH_TWO_DOTS_BELOW_AND_HAMZA_ABOVE	0x8A8
#define Z_UNICODE_ARABIC_LETTER_YEH_WITH_TWO_DOTS_BELOW_AND_DOT_ABOVE	0x8A9
#define Z_UNICODE_ARABIC_LETTER_REH_WITH_LOOP				0x8AA
#define Z_UNICODE_ARABIC_LETTER_WAW_WITH_DOT_WITHIN			0x8AB
#define Z_UNICODE_ARABIC_LETTER_ROHINGYA_YEH				0x8AC
#define Z_UNICODE_ARABIC_LETTER_LOW_ALEF				0x8AD
#define Z_UNICODE_ARABIC_LETTER_DAL_WITH_THREE_DOTS_BELOW		0x8AE
#define Z_UNICODE_ARABIC_LETTER_SAD_WITH_THREE_DOTS_BELOW		0x8AF
#define Z_UNICODE_ARABIC_LETTER_GAF_WITH_INVERTED_STROKE		0x8B0
#define Z_UNICODE_ARABIC_LETTER_STRAIGHT_WAW				0x8B1
#define Z_UNICODE_ARABIC_LETTER_ZAIN_WITH_INVERTED_V_ABOVE		0x8B2
#define Z_UNICODE_ARABIC_LETTER_AIN_WITH_THREE_DOTS_BELOW		0x8B3
#define Z_UNICODE_ARABIC_LETTER_KAF_WITH_DOT_BELOW			0x8B4
#define Z_UNICODE_ARABIC_TURNED_DAMMA_BELOW				0x8E3
#define Z_UNICODE_ARABIC_CURLY_FATHA					0x8E4
#define Z_UNICODE_ARABIC_CURLY_DAMMA					0x8E5
#define Z_UNICODE_ARABIC_CURLY_KASRA					0x8E6
#define Z_UNICODE_ARABIC_CURLY_FATHATAN					0x8E7
#define Z_UNICODE_ARABIC_CURLY_DAMMATAN					0x8E8
#define Z_UNICODE_ARABIC_CURLY_KASRATAN					0x8E9
#define Z_UNICODE_ARABIC_TONE_ONE_DOT_ABOVE				0x8EA
#define Z_UNICODE_ARABIC_TONE_TWO_DOTS_ABOVE				0x8EB
#define Z_UNICODE_ARABIC_TONE_LOOP_ABOVE				0x8EC
#define Z_UNICODE_ARABIC_TONE_ONE_DOT_BELOW				0x8ED
#define Z_UNICODE_ARABIC_TONE_TWO_DOTS_BELOW				0x8EE
#define Z_UNICODE_ARABIC_TONE_LOOP_BELOW				0x8EF
#define Z_UNICODE_ARABIC_OPEN_FATHATAN					0x8F0
#define Z_UNICODE_ARABIC_OPEN_DAMMATAN					0x8F1
#define Z_UNICODE_ARABIC_OPEN_KASRATAN					0x8F2
#define Z_UNICODE_ARABIC_SMALL_HIGH_WAW					0x8F3
#define Z_UNICODE_ARABIC_FATHA_WITH_RING				0x8F4
#define Z_UNICODE_ARABIC_FATHA_WITH_DOT_ABOVE				0x8F5
#define Z_UNICODE_ARABIC_KASRA_WITH_DOT_BELOW				0x8F6
#define Z_UNICODE_ARABIC_LEFT_ARROWHEAD_ABOVE				0x8F7
#define Z_UNICODE_ARABIC_RIGHT_ARROWHEAD_ABOVE				0x8F8
#define Z_UNICODE_ARABIC_LEFT_ARROWHEAD_BELOW				0x8F9
#define Z_UNICODE_ARABIC_RIGHT_ARROWHEAD_BELOW				0x8FA
#define Z_UNICODE_ARABIC_DOUBLE_RIGHT_ARROWHEAD_ABOVE			0x8FB
#define Z_UNICODE_ARABIC_DOUBLE_RIGHT_ARROWHEAD_ABOVE_WITH_DOT		0x8FC
#define Z_UNICODE_ARABIC_RIGHT_ARROWHEAD_ABOVE_WITH_DOT			0x8FD
#define Z_UNICODE_ARABIC_DAMMA_WITH_DOT					0x8FE
#define Z_UNICODE_ARABIC_MARK_SIDEWAYS_NOON_GHUNNA			0x8FF

#endif /* Z_formats_character_set_Unicode_Arabic_Extended_A_H */
