/* Z Kit - formats/character set/Unicode/Arabic Supplement.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_Arabic_Supplement_H
#define Z_formats_character_set_Unicode_Arabic_Supplement_H

/* 0750h-077Fh - Arabic Supplement */

#define Z_UNICODE_ARABIC_LETTER_BEH_WITH_THREE_DOTS_HORIZONTALLY_BELOW			      0x750
#define Z_UNICODE_ARABIC_LETTER_BEH_WITH_DOT_BELOW_AND_THREE_DOTS_ABOVE			      0x751
#define Z_UNICODE_ARABIC_LETTER_BEH_WITH_THREE_DOTS_POINTING_UPWARDS_BELOW		      0x752
#define Z_UNICODE_ARABIC_LETTER_BEH_WITH_THREE_DOTS_POINTING_UPWARDS_BELOW_AND_TWO_DOTS_ABOVE 0x753
#define Z_UNICODE_ARABIC_LETTER_BEH_WITH_TWO_DOTS_BELOW_AND_DOT_ABOVE			      0x754
#define Z_UNICODE_ARABIC_LETTER_BEH_WITH_INVERTED_SMALL_V_BELOW				      0x755
#define Z_UNICODE_ARABIC_LETTER_BEH_WITH_SMALL_V					      0x756
#define Z_UNICODE_ARABIC_LETTER_HAH_WITH_TWO_DOTS_ABOVE					      0x757
#define Z_UNICODE_ARABIC_LETTER_HAH_WITH_THREE_DOTS_POINTING_UPWARDS_BELOW		      0x758
#define Z_UNICODE_ARABIC_LETTER_DAL_WITH_TWO_DOTS_VERTICALLY_BELOW_AND_SMALL_TAH	      0x759
#define Z_UNICODE_ARABIC_LETTER_DAL_WITH_INVERTED_SMALL_V_BELOW				      0x75A
#define Z_UNICODE_ARABIC_LETTER_REH_WITH_STROKE						      0x75B
#define Z_UNICODE_ARABIC_LETTER_SEEN_WITH_FOUR_DOTS_ABOVE				      0x75C
#define Z_UNICODE_ARABIC_LETTER_AIN_WITH_TWO_DOTS_ABOVE					      0x75D
#define Z_UNICODE_ARABIC_LETTER_AIN_WITH_THREE_DOTS_POINTING_DOWNWARDS_ABOVE		      0x75E
#define Z_UNICODE_ARABIC_LETTER_AIN_WITH_TWO_DOTS_VERTICALLY_ABOVE			      0x75F
#define Z_UNICODE_ARABIC_LETTER_FEH_WITH_TWO_DOTS_BELOW					      0x760
#define Z_UNICODE_ARABIC_LETTER_FEH_WITH_THREE_DOTS_POINTING_UPWARDS_BELOW		      0x761
#define Z_UNICODE_ARABIC_LETTER_KEHEH_WITH_DOT_ABOVE					      0x762
#define Z_UNICODE_ARABIC_LETTER_KEHEH_WITH_THREE_DOTS_ABOVE				      0x763
#define Z_UNICODE_ARABIC_LETTER_KEHEH_WITH_THREE_DOTS_POINTING_UPWARDS_BELOW		      0x764
#define Z_UNICODE_ARABIC_LETTER_MEEM_WITH_DOT_ABOVE					      0x765
#define Z_UNICODE_ARABIC_LETTER_MEEM_WITH_DOT_BELOW					      0x766
#define Z_UNICODE_ARABIC_LETTER_NOON_WITH_TWO_DOTS_BELOW				      0x767
#define Z_UNICODE_ARABIC_LETTER_NOON_WITH_SMALL_TAH					      0x768
#define Z_UNICODE_ARABIC_LETTER_NOON_WITH_SMALL_V					      0x769
#define Z_UNICODE_ARABIC_LETTER_LAM_WITH_BAR						      0x76A
#define Z_UNICODE_ARABIC_LETTER_REH_WITH_TWO_DOTS_VERTICALLY_ABOVE			      0x76B
#define Z_UNICODE_ARABIC_LETTER_REH_WITH_HAMZA_ABOVE					      0x76C
#define Z_UNICODE_ARABIC_LETTER_SEEN_WITH_TWO_DOTS_VERTICALLY_ABOVE			      0x76D
#define Z_UNICODE_ARABIC_LETTER_HAH_WITH_SMALL_ARABIC_LETTER_TAH_BELOW			      0x76E
#define Z_UNICODE_ARABIC_LETTER_HAH_WITH_SMALL_ARABIC_LETTER_TAH_AND_TWO_DOTS		      0x76F
#define Z_UNICODE_ARABIC_LETTER_SEEN_WITH_SMALL_ARABIC_LETTER_TAH_AND_TWO_DOTS		      0x770
#define Z_UNICODE_ARABIC_LETTER_REH_WITH_SMALL_ARABIC_LETTER_TAH_AND_TWO_DOTS		      0x771
#define Z_UNICODE_ARABIC_LETTER_HAH_WITH_SMALL_ARABIC_LETTER_TAH_ABOVE			      0x772
#define Z_UNICODE_ARABIC_LETTER_ALEF_WITH_EXTENDED_ARABIC_INDIC_DIGIT_TWO_ABOVE		      0x773
#define Z_UNICODE_ARABIC_LETTER_ALEF_WITH_EXTENDED_ARABIC_INDIC_DIGIT_THREE_ABOVE	      0x774
#define Z_UNICODE_ARABIC_LETTER_FARSI_YEH_WITH_EXTENDED_ARABIC_INDIC_DIGIT_TWO_ABOVE	      0x775
#define Z_UNICODE_ARABIC_LETTER_FARSI_YEH_WITH_EXTENDED_ARABIC_INDIC_DIGIT_THREE_ABOVE	      0x776
#define Z_UNICODE_ARABIC_LETTER_FARSI_YEH_WITH_EXTENDED_ARABIC_INDIC_DIGIT_FOUR_BELOW	      0x777
#define Z_UNICODE_ARABIC_LETTER_WAW_WITH_EXTENDED_ARABIC_INDIC_DIGIT_TWO_ABOVE		      0x778
#define Z_UNICODE_ARABIC_LETTER_WAW_WITH_EXTENDED_ARABIC_INDIC_DIGIT_THREE_ABOVE	      0x779
#define Z_UNICODE_ARABIC_LETTER_YEH_BARREE_WITH_EXTENDED_ARABIC_INDIC_DIGIT_TWO_ABOVE	      0x77A
#define Z_UNICODE_ARABIC_LETTER_YEH_BARREE_WITH_EXTENDED_ARABIC_INDIC_DIGIT_THREE_ABOVE	      0x77B
#define Z_UNICODE_ARABIC_LETTER_HAH_WITH_EXTENDED_ARABIC_INDIC_DIGIT_FOUR_BELOW		      0x77C
#define Z_UNICODE_ARABIC_LETTER_SEEN_WITH_EXTENDED_ARABIC_INDIC_DIGIT_FOUR_ABOVE	      0x77D
#define Z_UNICODE_ARABIC_LETTER_SEEN_WITH_INVERTED_V					      0x77E
#define Z_UNICODE_ARABIC_LETTER_KAF_WITH_TWO_DOTS_ABOVE					      0x77F

#endif /* Z_formats_character_set_Unicode_Arabic_Supplement_H */
