/* Z Kit - formats/character set/Unicode/Armenian.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_Armenian_H
#define Z_formats_character_set_Unicode_Armenian_H

/* 0530h-058Fh - Armenian */

#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_AYB		  0x531
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_BEN		  0x532
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_GIM		  0x533
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_DA		  0x534
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_ECH		  0x535
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_ZA		  0x536
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_EH		  0x537
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_ET		  0x538
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_TO		  0x539
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_ZHE		  0x53A
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_INI		  0x53B
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_LIWN		  0x53C
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_XEH		  0x53D
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_CA		  0x53E
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_KEN		  0x53F
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_HO		  0x540
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_JA		  0x541
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_GHAD		  0x542
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_CHEH		  0x543
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_MEN		  0x544
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_YI		  0x545
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_NOW		  0x546
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_SHA		  0x547
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_VO		  0x548
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_CHA		  0x549
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_PEH		  0x54A
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_JHEH		  0x54B
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_RA		  0x54C
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_SEH		  0x54D
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_VEW		  0x54E
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_TIWN		  0x54F
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_REH		  0x550
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_CO		  0x551
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_YIWN		  0x552
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_PIWR		  0x553
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_KEH		  0x554
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_OH		  0x555
#define Z_UNICODE_ARMENIAN_CAPITAL_LETTER_FEH		  0x556
#define Z_UNICODE_ARMENIAN_MODIFIER_LETTER_LEFT_HALF_RING 0x559
#define Z_UNICODE_ARMENIAN_APOSTROPHE			  0x55A
#define Z_UNICODE_ARMENIAN_EMPHASIS_MARK		  0x55B
#define Z_UNICODE_ARMENIAN_EXCLAMATION_MARK		  0x55C
#define Z_UNICODE_ARMENIAN_COMMA			  0x55D
#define Z_UNICODE_ARMENIAN_QUESTION_MARK		  0x55E
#define Z_UNICODE_ARMENIAN_ABBREVIATION_MARK		  0x55F
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_AYB		  0x561
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_BEN		  0x562
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_GIM		  0x563
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_DA		  0x564
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_ECH		  0x565
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_ZA		  0x566
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_EH		  0x567
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_ET		  0x568
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_TO		  0x569
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_ZHE		  0x56A
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_INI		  0x56B
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_LIWN		  0x56C
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_XEH		  0x56D
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_CA		  0x56E
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_KEN		  0x56F
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_HO		  0x570
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_JA		  0x571
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_GHAD		  0x572
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_CHEH		  0x573
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_MEN		  0x574
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_YI		  0x575
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_NOW		  0x576
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_SHA		  0x577
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_VO		  0x578
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_CHA		  0x579
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_PEH		  0x57A
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_JHEH		  0x57B
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_RA		  0x57C
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_SEH		  0x57D
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_VEW		  0x57E
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_TIWN		  0x57F
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_REH		  0x580
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_CO		  0x581
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_YIWN		  0x582
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_PIWR		  0x583
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_KEH		  0x584
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_OH		  0x585
#define Z_UNICODE_ARMENIAN_SMALL_LETTER_FEH		  0x586
#define Z_UNICODE_ARMENIAN_SMALL_LIGATURE_ECH_YIWN	  0x587
#define Z_UNICODE_ARMENIAN_FULL_STOP			  0x589
#define Z_UNICODE_ARMENIAN_HYPHEN			  0x58A
#define Z_UNICODE_RIGHT_FACING_ARMENIAN_ETERNITY_SIGN	  0x58D
#define Z_UNICODE_LEFT_FACING_ARMENIAN_ETERNITY_SIGN	  0x58E
#define Z_UNICODE_ARMENIAN_DRAM_SIGN			  0x58F

#endif /* Z_formats_character_set_Unicode_Armenian_H */
