/* Z Kit - formats/character set/Unicode/Bengali.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_Bengali_H
#define Z_formats_character_set_Unicode_Bengali_H

/* 0980h-09FFh - Bengali */

/* 09E4h <reserved> */
/* 09E5h <reserved> */
#define Z_UNICODE_BENGALI_ANJI						   0x980
#define Z_UNICODE_BENGALI_SIGN_CANDRABINDU				   0x981
#define Z_UNICODE_BENGALI_SIGN_ANUSVARA					   0x982
#define Z_UNICODE_BENGALI_SIGN_VISARGA					   0x983
#define Z_UNICODE_BENGALI_LETTER_A					   0x985
#define Z_UNICODE_BENGALI_LETTER_AA					   0x986
#define Z_UNICODE_BENGALI_LETTER_I					   0x987
#define Z_UNICODE_BENGALI_LETTER_II					   0x988
#define Z_UNICODE_BENGALI_LETTER_U					   0x989
#define Z_UNICODE_BENGALI_LETTER_UU					   0x98A
#define Z_UNICODE_BENGALI_LETTER_VOCALIC_R				   0x98B
#define Z_UNICODE_BENGALI_LETTER_VOCALIC_L				   0x98C
#define Z_UNICODE_BENGALI_LETTER_E					   0x98F
#define Z_UNICODE_BENGALI_LETTER_AI					   0x990
#define Z_UNICODE_BENGALI_LETTER_O					   0x993
#define Z_UNICODE_BENGALI_LETTER_AU					   0x994
#define Z_UNICODE_BENGALI_LETTER_KA					   0x995
#define Z_UNICODE_BENGALI_LETTER_KHA					   0x996
#define Z_UNICODE_BENGALI_LETTER_GA					   0x997
#define Z_UNICODE_BENGALI_LETTER_GHA					   0x998
#define Z_UNICODE_BENGALI_LETTER_NGA					   0x999
#define Z_UNICODE_BENGALI_LETTER_CA					   0x99A
#define Z_UNICODE_BENGALI_LETTER_CHA					   0x99B
#define Z_UNICODE_BENGALI_LETTER_JA					   0x99C
#define Z_UNICODE_BENGALI_LETTER_JHA					   0x99D
#define Z_UNICODE_BENGALI_LETTER_NYA					   0x99E
#define Z_UNICODE_BENGALI_LETTER_TTA					   0x99F
#define Z_UNICODE_BENGALI_LETTER_TTHA					   0x9A0
#define Z_UNICODE_BENGALI_LETTER_DDA					   0x9A1
#define Z_UNICODE_BENGALI_LETTER_DDHA					   0x9A2
#define Z_UNICODE_BENGALI_LETTER_NNA					   0x9A3
#define Z_UNICODE_BENGALI_LETTER_TA					   0x9A4
#define Z_UNICODE_BENGALI_LETTER_THA					   0x9A5
#define Z_UNICODE_BENGALI_LETTER_DA					   0x9A6
#define Z_UNICODE_BENGALI_LETTER_DHA					   0x9A7
#define Z_UNICODE_BENGALI_LETTER_NA					   0x9A8
#define Z_UNICODE_BENGALI_LETTER_PA					   0x9AA
#define Z_UNICODE_BENGALI_LETTER_PHA					   0x9AB
#define Z_UNICODE_BENGALI_LETTER_BA					   0x9AC
#define Z_UNICODE_BENGALI_LETTER_BHA					   0x9AD
#define Z_UNICODE_BENGALI_LETTER_MA					   0x9AE
#define Z_UNICODE_BENGALI_LETTER_YA					   0x9AF
#define Z_UNICODE_BENGALI_LETTER_RA					   0x9B0
#define Z_UNICODE_BENGALI_LETTER_LA					   0x9B2
#define Z_UNICODE_BENGALI_LETTER_SHA					   0x9B6
#define Z_UNICODE_BENGALI_LETTER_SSA					   0x9B7
#define Z_UNICODE_BENGALI_LETTER_SA					   0x9B8
#define Z_UNICODE_BENGALI_LETTER_HA					   0x9B9
#define Z_UNICODE_BENGALI_SIGN_NUKTA					   0x9BC
#define Z_UNICODE_BENGALI_SIGN_AVAGRAHA					   0x9BD
#define Z_UNICODE_BENGALI_VOWEL_SIGN_AA					   0x9BE
#define Z_UNICODE_BENGALI_VOWEL_SIGN_I					   0x9BF
#define Z_UNICODE_BENGALI_VOWEL_SIGN_II					   0x9C0
#define Z_UNICODE_BENGALI_VOWEL_SIGN_U					   0x9C1
#define Z_UNICODE_BENGALI_VOWEL_SIGN_UU					   0x9C2
#define Z_UNICODE_BENGALI_VOWEL_SIGN_VOCALIC_R				   0x9C3
#define Z_UNICODE_BENGALI_VOWEL_SIGN_VOCALIC_RR				   0x9C4
#define Z_UNICODE_BENGALI_VOWEL_SIGN_E					   0x9C7
#define Z_UNICODE_BENGALI_VOWEL_SIGN_AI					   0x9C8
#define Z_UNICODE_BENGALI_VOWEL_SIGN_O					   0x9CB
#define Z_UNICODE_BENGALI_VOWEL_SIGN_AU					   0x9CC
#define Z_UNICODE_BENGALI_SIGN_VIRAMA					   0x9CD
#define Z_UNICODE_BENGALI_LETTER_KHANDA_TA				   0x9CE
#define Z_UNICODE_BENGALI_AU_LENGTH_MARK				   0x9D7
#define Z_UNICODE_BENGALI_LETTER_RRA					   0x9DC
#define Z_UNICODE_BENGALI_LETTER_RHA					   0x9DD
#define Z_UNICODE_BENGALI_LETTER_YYA					   0x9DF
#define Z_UNICODE_BENGALI_LETTER_VOCALIC_RR				   0x9E0
#define Z_UNICODE_BENGALI_LETTER_VOCALIC_LL				   0x9E1
#define Z_UNICODE_BENGALI_VOWEL_SIGN_VOCALIC_L				   0x9E2
#define Z_UNICODE_BENGALI_VOWEL_SIGN_VOCALIC_LL				   0x9E3
#define Z_UNICODE_BENGALI_DIGIT_ZERO					   0x9E6
#define Z_UNICODE_BENGALI_DIGIT_ONE					   0x9E7
#define Z_UNICODE_BENGALI_DIGIT_TWO					   0x9E8
#define Z_UNICODE_BENGALI_DIGIT_THREE					   0x9E9
#define Z_UNICODE_BENGALI_DIGIT_FOUR					   0x9EA
#define Z_UNICODE_BENGALI_DIGIT_FIVE					   0x9EB
#define Z_UNICODE_BENGALI_DIGIT_SIX					   0x9EC
#define Z_UNICODE_BENGALI_DIGIT_SEVEN					   0x9ED
#define Z_UNICODE_BENGALI_DIGIT_EIGHT					   0x9EE
#define Z_UNICODE_BENGALI_DIGIT_NINE					   0x9EF
#define Z_UNICODE_BENGALI_LETTER_RA_WITH_MIDDLE_DIAGONAL		   0x9F0
#define Z_UNICODE_BENGALI_LETTER_RA_WITH_LOWER_DIAGONAL			   0x9F1
#define Z_UNICODE_BENGALI_RUPEE_MARK					   0x9F2
#define Z_UNICODE_BENGALI_RUPEE_SIGN					   0x9F3
#define Z_UNICODE_BENGALI_CURRENCY_NUMERATOR_ONE			   0x9F4
#define Z_UNICODE_BENGALI_CURRENCY_NUMERATOR_TWO			   0x9F5
#define Z_UNICODE_BENGALI_CURRENCY_NUMERATOR_THREE			   0x9F6
#define Z_UNICODE_BENGALI_CURRENCY_NUMERATOR_FOUR			   0x9F7
#define Z_UNICODE_BENGALI_CURRENCY_NUMERATOR_ONE_LESS_THAN_THE_DENOMINATOR 0x9F8
#define Z_UNICODE_BENGALI_CURRENCY_DENOMINATOR_SIXTEEN			   0x9F9
#define Z_UNICODE_BENGALI_ISSHAR					   0x9FA
#define Z_UNICODE_BENGALI_GANDA_MARK					   0x9FB

#endif /* Z_formats_character_set_Unicode_Bengali_H */
