/* Z Kit - formats/character set/Unicode/Combining Diacritical Marks.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_Combining_Diacritical_Marks_H
#define Z_formats_character_set_Unicode_Combining_Diacritical_Marks_H

/* 0300h-036Fh - Combining Diacritical Marks */

#define Z_UNICODE_COMBINING_GRAVE_ACCENT			   0x300
#define Z_UNICODE_COMBINING_ACUTE_ACCENT			   0x301
#define Z_UNICODE_COMBINING_CIRCUMFLEX_ACCENT			   0x302
#define Z_UNICODE_COMBINING_TILDE				   0x303
#define Z_UNICODE_COMBINING_MACRON				   0x304
#define Z_UNICODE_COMBINING_OVERLINE				   0x305
#define Z_UNICODE_COMBINING_BREVE				   0x306
#define Z_UNICODE_COMBINING_DOT_ABOVE				   0x307
#define Z_UNICODE_COMBINING_DIAERESIS				   0x308
#define Z_UNICODE_COMBINING_HOOK_ABOVE				   0x309
#define Z_UNICODE_COMBINING_RING_ABOVE				   0x30A
#define Z_UNICODE_COMBINING_DOUBLE_ACUTE_ACCENT			   0x30B
#define Z_UNICODE_COMBINING_CARON				   0x30C
#define Z_UNICODE_COMBINING_VERTICAL_LINE_ABOVE			   0x30D
#define Z_UNICODE_COMBINING_DOUBLE_VERTICAL_LINE_ABOVE		   0x30E
#define Z_UNICODE_COMBINING_DOUBLE_GRAVE_ACCENT			   0x30F
#define Z_UNICODE_COMBINING_CANDRABINDU				   0x310
#define Z_UNICODE_COMBINING_INVERTED_BREVE			   0x311
#define Z_UNICODE_COMBINING_TURNED_COMMA_ABOVE			   0x312
#define Z_UNICODE_COMBINING_COMMA_ABOVE				   0x313
#define Z_UNICODE_COMBINING_REVERSED_COMMA_ABOVE		   0x314
#define Z_UNICODE_COMBINING_COMMA_ABOVE_RIGHT			   0x315
#define Z_UNICODE_COMBINING_GRAVE_ACCENT_BELOW			   0x316
#define Z_UNICODE_COMBINING_ACUTE_ACCENT_BELOW			   0x317
#define Z_UNICODE_COMBINING_LEFT_TACK_BELOW			   0x318
#define Z_UNICODE_COMBINING_RIGHT_TACK_BELOW			   0x319
#define Z_UNICODE_COMBINING_LEFT_ANGLE_ABOVE			   0x31A
#define Z_UNICODE_COMBINING_HORN				   0x31B
#define Z_UNICODE_COMBINING_LEFT_HALF_RING_BELOW		   0x31C
#define Z_UNICODE_COMBINING_UP_TACK_BELOW			   0x31D
#define Z_UNICODE_COMBINING_DOWN_TACK_BELOW			   0x31E
#define Z_UNICODE_COMBINING_PLUS_SIGN_BELOW			   0x31F
#define Z_UNICODE_COMBINING_MINUS_SIGN_BELOW			   0x320
#define Z_UNICODE_COMBINING_PALATALIZED_HOOK_BELOW		   0x321
#define Z_UNICODE_COMBINING_RETROFLEX_HOOK_BELOW		   0x322
#define Z_UNICODE_COMBINING_DOT_BELOW				   0x323
#define Z_UNICODE_COMBINING_DIAERESIS_BELOW			   0x324
#define Z_UNICODE_COMBINING_RING_BELOW				   0x325
#define Z_UNICODE_COMBINING_COMMA_BELOW				   0x326
#define Z_UNICODE_COMBINING_CEDILLA				   0x327
#define Z_UNICODE_COMBINING_OGONEK				   0x328
#define Z_UNICODE_COMBINING_VERTICAL_LINE_BELOW			   0x329
#define Z_UNICODE_COMBINING_BRIDGE_BELOW			   0x32A
#define Z_UNICODE_COMBINING_INVERTED_DOUBLE_ARCH_BELOW		   0x32B
#define Z_UNICODE_COMBINING_CARON_BELOW				   0x32C
#define Z_UNICODE_COMBINING_CIRCUMFLEX_ACCENT_BELOW		   0x32D
#define Z_UNICODE_COMBINING_BREVE_BELOW				   0x32E
#define Z_UNICODE_COMBINING_INVERTED_BREVE_BELOW		   0x32F
#define Z_UNICODE_COMBINING_TILDE_BELOW				   0x330
#define Z_UNICODE_COMBINING_MACRON_BELOW			   0x331
#define Z_UNICODE_COMBINING_LOW_LINE				   0x332
#define Z_UNICODE_COMBINING_DOUBLE_LOW_LINE			   0x333
#define Z_UNICODE_COMBINING_TILDE_OVERLAY			   0x334
#define Z_UNICODE_COMBINING_SHORT_STROKE_OVERLAY		   0x335
#define Z_UNICODE_COMBINING_LONG_STROKE_OVERLAY			   0x336
#define Z_UNICODE_COMBINING_SHORT_SOLIDUS_OVERLAY		   0x337
#define Z_UNICODE_COMBINING_LONG_SOLIDUS_OVERLAY		   0x338
#define Z_UNICODE_COMBINING_RIGHT_HALF_RING_BELOW		   0x339
#define Z_UNICODE_COMBINING_INVERTED_BRIDGE_BELOW		   0x33A
#define Z_UNICODE_COMBINING_SQUARE_BELOW			   0x33B
#define Z_UNICODE_COMBINING_SEAGULL_BELOW			   0x33C
#define Z_UNICODE_COMBINING_X_ABOVE				   0x33D
#define Z_UNICODE_COMBINING_VERTICAL_TILDE			   0x33E
#define Z_UNICODE_COMBINING_DOUBLE_OVERLINE			   0x33F
#define Z_UNICODE_COMBINING_GRAVE_TONE_MARK			   0x340
#define Z_UNICODE_COMBINING_ACUTE_TONE_MARK			   0x341
#define Z_UNICODE_COMBINING_GREEK_PERISPOMENI			   0x342
#define Z_UNICODE_COMBINING_GREEK_KORONIS			   0x343
#define Z_UNICODE_COMBINING_GREEK_DIALYTIKA_TONOS		   0x344
#define Z_UNICODE_COMBINING_GREEK_YPOGEGRAMMENI			   0x345
#define Z_UNICODE_COMBINING_BRIDGE_ABOVE			   0x346
#define Z_UNICODE_COMBINING_EQUALS_SIGN_BELOW			   0x347
#define Z_UNICODE_COMBINING_DOUBLE_VERTICAL_LINE_BELOW		   0x348
#define Z_UNICODE_COMBINING_LEFT_ANGLE_BELOW			   0x349
#define Z_UNICODE_COMBINING_NOT_TILDE_ABOVE			   0x34A
#define Z_UNICODE_COMBINING_HOMOTHETIC_ABOVE			   0x34B
#define Z_UNICODE_COMBINING_ALMOST_EQUAL_TO_ABOVE		   0x34C
#define Z_UNICODE_COMBINING_LEFT_RIGHT_ARROW_BELOW		   0x34D
#define Z_UNICODE_COMBINING_UPWARDS_ARROW_BELOW			   0x34E
#define Z_UNICODE_COMBINING_GRAPHEME_JOINER			   0x34F
#define Z_UNICODE_COMBINING_RIGHT_ARROWHEAD_ABOVE		   0x350
#define Z_UNICODE_COMBINING_LEFT_HALF_RING_ABOVE		   0x351
#define Z_UNICODE_COMBINING_FERMATA				   0x352
#define Z_UNICODE_COMBINING_X_BELOW				   0x353
#define Z_UNICODE_COMBINING_LEFT_ARROWHEAD_BELOW		   0x354
#define Z_UNICODE_COMBINING_RIGHT_ARROWHEAD_BELOW		   0x355
#define Z_UNICODE_COMBINING_RIGHT_ARROWHEAD_AND_UP_ARROWHEAD_BELOW 0x356
#define Z_UNICODE_COMBINING_RIGHT_HALF_RING_ABOVE		   0x357
#define Z_UNICODE_COMBINING_DOT_ABOVE_RIGHT			   0x358
#define Z_UNICODE_COMBINING_ASTERISK_BELOW			   0x359
#define Z_UNICODE_COMBINING_DOUBLE_RING_BELOW			   0x35A
#define Z_UNICODE_COMBINING_ZIGZAG_ABOVE			   0x35B
#define Z_UNICODE_COMBINING_DOUBLE_BREVE_BELOW			   0x35C
#define Z_UNICODE_COMBINING_DOUBLE_BREVE			   0x35D
#define Z_UNICODE_COMBINING_DOUBLE_MACRON			   0x35E
#define Z_UNICODE_COMBINING_DOUBLE_MACRON_BELOW			   0x35F
#define Z_UNICODE_COMBINING_DOUBLE_TILDE			   0x360
#define Z_UNICODE_COMBINING_DOUBLE_INVERTED_BREVE		   0x361
#define Z_UNICODE_COMBINING_DOUBLE_RIGHTWARDS_ARROW_BELOW	   0x362
#define Z_UNICODE_COMBINING_LATIN_SMALL_LETTER_A		   0x363
#define Z_UNICODE_COMBINING_LATIN_SMALL_LETTER_E		   0x364
#define Z_UNICODE_COMBINING_LATIN_SMALL_LETTER_I		   0x365
#define Z_UNICODE_COMBINING_LATIN_SMALL_LETTER_O		   0x366
#define Z_UNICODE_COMBINING_LATIN_SMALL_LETTER_U		   0x367
#define Z_UNICODE_COMBINING_LATIN_SMALL_LETTER_C		   0x368
#define Z_UNICODE_COMBINING_LATIN_SMALL_LETTER_D		   0x369
#define Z_UNICODE_COMBINING_LATIN_SMALL_LETTER_H		   0x36A
#define Z_UNICODE_COMBINING_LATIN_SMALL_LETTER_M		   0x36B
#define Z_UNICODE_COMBINING_LATIN_SMALL_LETTER_R		   0x36C
#define Z_UNICODE_COMBINING_LATIN_SMALL_LETTER_T		   0x36D
#define Z_UNICODE_COMBINING_LATIN_SMALL_LETTER_V		   0x36E
#define Z_UNICODE_COMBINING_LATIN_SMALL_LETTER_X		   0x36F

#endif /* Z_formats_character_set_Unicode_Combining_Diacritical_Marks_H */
