/* Z Kit - formats/character set/Unicode/Cyrillic Supplement.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_Cyrillic_Supplement_H
#define Z_formats_character_set_Unicode_Cyrillic_Supplement_H

/* 0500h-052Fh - Cyrillic Supplement */

#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_KOMI_DE	      0x500
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_KOMI_DE		      0x501
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_KOMI_DJE	      0x502
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_KOMI_DJE	      0x503
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_KOMI_ZJE	      0x504
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_KOMI_ZJE	      0x505
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_KOMI_DZJE	      0x506
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_KOMI_DZJE	      0x507
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_KOMI_LJE	      0x508
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_KOMI_LJE	      0x509
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_KOMI_NJE	      0x50A
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_KOMI_NJE	      0x50B
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_KOMI_SJE	      0x50C
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_KOMI_SJE	      0x50D
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_KOMI_TJE	      0x50E
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_KOMI_TJE	      0x50F
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_REVERSED_ZE	      0x510
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_REVERSED_ZE	      0x511
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_EL_WITH_HOOK	      0x512
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_EL_WITH_HOOK	      0x513
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_LHA		      0x514
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_LHA		      0x515
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_RHA		      0x516
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_RHA		      0x517
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_YAE		      0x518
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_YAE		      0x519
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_QA		      0x51A
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_QA		      0x51B
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_WE		      0x51C
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_WE		      0x51D
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_ALEUT_KA	      0x51E
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_ALEUT_KA	      0x51F
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_EL_WITH_MIDDLE_HOOK 0x520
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_EL_WITH_MIDDLE_HOOK   0x521
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_EN_WITH_MIDDLE_HOOK 0x522
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_EN_WITH_MIDDLE_HOOK   0x523
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_PE_WITH_DESCENDER   0x524
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_PE_WITH_DESCENDER     0x525
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_SHHA_WITH_DESCENDER 0x526
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_SHHA_WITH_DESCENDER   0x527
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_EN_WITH_LEFT_HOOK   0x528
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_EN_WITH_LEFT_HOOK     0x529
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_DZZHE		      0x52A
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_DZZHE		      0x52B
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_DCHE		      0x52C
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_DCHE		      0x52D
#define Z_UNICODE_CYRILLIC_CAPITAL_LETTER_EL_WITH_DESCENDER   0x52E
#define Z_UNICODE_CYRILLIC_SMALL_LETTER_EL_WITH_DESCENDER     0x52F

#endif /* Z_formats_character_set_Unicode_Cyrillic_Supplement_H */
