/* Z Kit - formats/character set/Unicode/Gurmukhi.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_Gurmukhi_H
#define Z_formats_character_set_Unicode_Gurmukhi_H

/* 0A00h-0A7Fh - Gurmukhi */

/* 0A64h <reserved> */
/* 0A65h <reserved> */
#define Z_UNICODE_GURMUKHI_SIGN_ADAK_BINDI 0xA01
#define Z_UNICODE_GURMUKHI_SIGN_BINDI	   0xA02
#define Z_UNICODE_GURMUKHI_SIGN_VISARGA	   0xA03
#define Z_UNICODE_GURMUKHI_LETTER_A	   0xA05
#define Z_UNICODE_GURMUKHI_LETTER_AA	   0xA06
#define Z_UNICODE_GURMUKHI_LETTER_I	   0xA07
#define Z_UNICODE_GURMUKHI_LETTER_II	   0xA08
#define Z_UNICODE_GURMUKHI_LETTER_U	   0xA09
#define Z_UNICODE_GURMUKHI_LETTER_UU	   0xA0A
#define Z_UNICODE_GURMUKHI_LETTER_EE	   0xA0F
#define Z_UNICODE_GURMUKHI_LETTER_AI	   0xA10
#define Z_UNICODE_GURMUKHI_LETTER_OO	   0xA13
#define Z_UNICODE_GURMUKHI_LETTER_AU	   0xA14
#define Z_UNICODE_GURMUKHI_LETTER_KA	   0xA15
#define Z_UNICODE_GURMUKHI_LETTER_KHA	   0xA16
#define Z_UNICODE_GURMUKHI_LETTER_GA	   0xA17
#define Z_UNICODE_GURMUKHI_LETTER_GHA	   0xA18
#define Z_UNICODE_GURMUKHI_LETTER_NGA	   0xA19
#define Z_UNICODE_GURMUKHI_LETTER_CA	   0xA1A
#define Z_UNICODE_GURMUKHI_LETTER_CHA	   0xA1B
#define Z_UNICODE_GURMUKHI_LETTER_JA	   0xA1C
#define Z_UNICODE_GURMUKHI_LETTER_JHA	   0xA1D
#define Z_UNICODE_GURMUKHI_LETTER_NYA	   0xA1E
#define Z_UNICODE_GURMUKHI_LETTER_TTA	   0xA1F
#define Z_UNICODE_GURMUKHI_LETTER_TTHA	   0xA20
#define Z_UNICODE_GURMUKHI_LETTER_DDA	   0xA21
#define Z_UNICODE_GURMUKHI_LETTER_DDHA	   0xA22
#define Z_UNICODE_GURMUKHI_LETTER_NNA	   0xA23
#define Z_UNICODE_GURMUKHI_LETTER_TA	   0xA24
#define Z_UNICODE_GURMUKHI_LETTER_THA	   0xA25
#define Z_UNICODE_GURMUKHI_LETTER_DA	   0xA26
#define Z_UNICODE_GURMUKHI_LETTER_DHA	   0xA27
#define Z_UNICODE_GURMUKHI_LETTER_NA	   0xA28
#define Z_UNICODE_GURMUKHI_LETTER_PA	   0xA2A
#define Z_UNICODE_GURMUKHI_LETTER_PHA	   0xA2B
#define Z_UNICODE_GURMUKHI_LETTER_BA	   0xA2C
#define Z_UNICODE_GURMUKHI_LETTER_BHA	   0xA2D
#define Z_UNICODE_GURMUKHI_LETTER_MA	   0xA2E
#define Z_UNICODE_GURMUKHI_LETTER_YA	   0xA2F
#define Z_UNICODE_GURMUKHI_LETTER_RA	   0xA30
#define Z_UNICODE_GURMUKHI_LETTER_LA	   0xA32
#define Z_UNICODE_GURMUKHI_LETTER_LLA	   0xA33
#define Z_UNICODE_GURMUKHI_LETTER_VA	   0xA35
#define Z_UNICODE_GURMUKHI_LETTER_SHA	   0xA36
#define Z_UNICODE_GURMUKHI_LETTER_SA	   0xA38
#define Z_UNICODE_GURMUKHI_LETTER_HA	   0xA39
#define Z_UNICODE_GURMUKHI_SIGN_NUKTA	   0xA3C
#define Z_UNICODE_GURMUKHI_VOWEL_SIGN_AA   0xA3E
#define Z_UNICODE_GURMUKHI_VOWEL_SIGN_I	   0xA3F
#define Z_UNICODE_GURMUKHI_VOWEL_SIGN_II   0xA40
#define Z_UNICODE_GURMUKHI_VOWEL_SIGN_U	   0xA41
#define Z_UNICODE_GURMUKHI_VOWEL_SIGN_UU   0xA42
#define Z_UNICODE_GURMUKHI_VOWEL_SIGN_EE   0xA47
#define Z_UNICODE_GURMUKHI_VOWEL_SIGN_AI   0xA48
#define Z_UNICODE_GURMUKHI_VOWEL_SIGN_OO   0xA4B
#define Z_UNICODE_GURMUKHI_VOWEL_SIGN_AU   0xA4C
#define Z_UNICODE_GURMUKHI_SIGN_VIRAMA	   0xA4D
#define Z_UNICODE_GURMUKHI_SIGN_UDAAT	   0xA51
#define Z_UNICODE_GURMUKHI_LETTER_KHHA	   0xA59
#define Z_UNICODE_GURMUKHI_LETTER_GHHA	   0xA5A
#define Z_UNICODE_GURMUKHI_LETTER_ZA	   0xA5B
#define Z_UNICODE_GURMUKHI_LETTER_RRA	   0xA5C
#define Z_UNICODE_GURMUKHI_LETTER_FA	   0xA5E
#define Z_UNICODE_GURMUKHI_DIGIT_ZERO	   0xA66
#define Z_UNICODE_GURMUKHI_DIGIT_ONE	   0xA67
#define Z_UNICODE_GURMUKHI_DIGIT_TWO	   0xA68
#define Z_UNICODE_GURMUKHI_DIGIT_THREE	   0xA69
#define Z_UNICODE_GURMUKHI_DIGIT_FOUR	   0xA6A
#define Z_UNICODE_GURMUKHI_DIGIT_FIVE	   0xA6B
#define Z_UNICODE_GURMUKHI_DIGIT_SIX	   0xA6C
#define Z_UNICODE_GURMUKHI_DIGIT_SEVEN	   0xA6D
#define Z_UNICODE_GURMUKHI_DIGIT_EIGHT	   0xA6E
#define Z_UNICODE_GURMUKHI_DIGIT_NINE	   0xA6F
#define Z_UNICODE_GURMUKHI_TIPPI	   0xA70
#define Z_UNICODE_GURMUKHI_ADDAK	   0xA71
#define Z_UNICODE_GURMUKHI_IRI		   0xA72
#define Z_UNICODE_GURMUKHI_URA		   0xA73
#define Z_UNICODE_GURMUKHI_EK_ONKAR	   0xA74
#define Z_UNICODE_GURMUKHI_SIGN_YAKASH	   0xA75

#endif /* Z_formats_character_set_Unicode_Gurmukhi_H */
