/* Z Kit - formats/character set/Unicode/Hebrew.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_Hebrew_H
#define Z_formats_character_set_Unicode_Hebrew_H

/* 0590h-05FFh - Hebrew */

#define Z_UNICODE_HEBREW_ACCENT_ETNAHTA		     0x591
#define Z_UNICODE_HEBREW_ACCENT_SEGOL		     0x592
#define Z_UNICODE_HEBREW_ACCENT_SHALSHELET	     0x593
#define Z_UNICODE_HEBREW_ACCENT_ZAQEF_QATAN	     0x594
#define Z_UNICODE_HEBREW_ACCENT_ZAQEF_GADOL	     0x595
#define Z_UNICODE_HEBREW_ACCENT_TIPEHA		     0x596
#define Z_UNICODE_HEBREW_ACCENT_REVIA		     0x597
#define Z_UNICODE_HEBREW_ACCENT_ZARQA		     0x598
#define Z_UNICODE_HEBREW_ACCENT_PASHTA		     0x599
#define Z_UNICODE_HEBREW_ACCENT_YETIV		     0x59A
#define Z_UNICODE_HEBREW_ACCENT_TEVIR		     0x59B
#define Z_UNICODE_HEBREW_ACCENT_GERESH		     0x59C
#define Z_UNICODE_HEBREW_ACCENT_GERESH_MUQDAM	     0x59D
#define Z_UNICODE_HEBREW_ACCENT_GERSHAYIM	     0x59E
#define Z_UNICODE_HEBREW_ACCENT_QARNEY_PARA	     0x59F
#define Z_UNICODE_HEBREW_ACCENT_TELISHA_GEDOLA	     0x5A0
#define Z_UNICODE_HEBREW_ACCENT_PAZER		     0x5A1
#define Z_UNICODE_HEBREW_ACCENT_ATNAH_HAFUKH	     0x5A2
#define Z_UNICODE_HEBREW_ACCENT_MUNAH		     0x5A3
#define Z_UNICODE_HEBREW_ACCENT_MAHAPAKH	     0x5A4
#define Z_UNICODE_HEBREW_ACCENT_MERKHA		     0x5A5
#define Z_UNICODE_HEBREW_ACCENT_MERKHA_KEFULA	     0x5A6
#define Z_UNICODE_HEBREW_ACCENT_DARGA		     0x5A7
#define Z_UNICODE_HEBREW_ACCENT_QADMA		     0x5A8
#define Z_UNICODE_HEBREW_ACCENT_TELISHA_QETANA	     0x5A9
#define Z_UNICODE_HEBREW_ACCENT_YERAH_BEN_YOMO	     0x5AA
#define Z_UNICODE_HEBREW_ACCENT_OLE		     0x5AB
#define Z_UNICODE_HEBREW_ACCENT_ILUY		     0x5AC
#define Z_UNICODE_HEBREW_ACCENT_DEHI		     0x5AD
#define Z_UNICODE_HEBREW_ACCENT_ZINOR		     0x5AE
#define Z_UNICODE_HEBREW_MARK_MASORA_CIRCLE	     0x5AF
#define Z_UNICODE_HEBREW_POINT_SHEVA		     0x5B0
#define Z_UNICODE_HEBREW_POINT_HATAF_SEGOL	     0x5B1
#define Z_UNICODE_HEBREW_POINT_HATAF_PATAH	     0x5B2
#define Z_UNICODE_HEBREW_POINT_HATAF_QAMATS	     0x5B3
#define Z_UNICODE_HEBREW_POINT_HIRIQ		     0x5B4
#define Z_UNICODE_HEBREW_POINT_TSERE		     0x5B5
#define Z_UNICODE_HEBREW_POINT_SEGOL		     0x5B6
#define Z_UNICODE_HEBREW_POINT_PATAH		     0x5B7
#define Z_UNICODE_HEBREW_POINT_QAMATS		     0x5B8
#define Z_UNICODE_HEBREW_POINT_HOLAM		     0x5B9
#define Z_UNICODE_HEBREW_POINT_HOLAM_HASER_FOR_VAV   0x5BA
#define Z_UNICODE_HEBREW_POINT_QUBUTS		     0x5BB
#define Z_UNICODE_HEBREW_POINT_DAGESH_OR_MAPIQ	     0x5BC
#define Z_UNICODE_HEBREW_POINT_METEG		     0x5BD
#define Z_UNICODE_HEBREW_PUNCTUATION_MAQAF	     0x5BE
#define Z_UNICODE_HEBREW_POINT_RAFE		     0x5BF
#define Z_UNICODE_HEBREW_PUNCTUATION_PASEQ	     0x5C0
#define Z_UNICODE_HEBREW_POINT_SHIN_DOT		     0x5C1
#define Z_UNICODE_HEBREW_POINT_SIN_DOT		     0x5C2
#define Z_UNICODE_HEBREW_PUNCTUATION_SOF_PASUQ	     0x5C3
#define Z_UNICODE_HEBREW_MARK_UPPER_DOT		     0x5C4
#define Z_UNICODE_HEBREW_MARK_LOWER_DOT		     0x5C5
#define Z_UNICODE_HEBREW_PUNCTUATION_NUN_HAFUKHA     0x5C6
#define Z_UNICODE_HEBREW_POINT_QAMATS_QATAN	     0x5C7
#define Z_UNICODE_HEBREW_LETTER_ALEF		     0x5D0
#define Z_UNICODE_HEBREW_LETTER_BET		     0x5D1
#define Z_UNICODE_HEBREW_LETTER_GIMEL		     0x5D2
#define Z_UNICODE_HEBREW_LETTER_DALET		     0x5D3
#define Z_UNICODE_HEBREW_LETTER_HE		     0x5D4
#define Z_UNICODE_HEBREW_LETTER_VAV		     0x5D5
#define Z_UNICODE_HEBREW_LETTER_ZAYIN		     0x5D6
#define Z_UNICODE_HEBREW_LETTER_HET		     0x5D7
#define Z_UNICODE_HEBREW_LETTER_TET		     0x5D8
#define Z_UNICODE_HEBREW_LETTER_YOD		     0x5D9
#define Z_UNICODE_HEBREW_LETTER_FINAL_KAF	     0x5DA
#define Z_UNICODE_HEBREW_LETTER_KAF		     0x5DB
#define Z_UNICODE_HEBREW_LETTER_LAMED		     0x5DC
#define Z_UNICODE_HEBREW_LETTER_FINAL_MEM	     0x5DD
#define Z_UNICODE_HEBREW_LETTER_MEM		     0x5DE
#define Z_UNICODE_HEBREW_LETTER_FINAL_NUN	     0x5DF
#define Z_UNICODE_HEBREW_LETTER_NUN		     0x5E0
#define Z_UNICODE_HEBREW_LETTER_SAMEKH		     0x5E1
#define Z_UNICODE_HEBREW_LETTER_AYIN		     0x5E2
#define Z_UNICODE_HEBREW_LETTER_FINAL_PE	     0x5E3
#define Z_UNICODE_HEBREW_LETTER_PE		     0x5E4
#define Z_UNICODE_HEBREW_LETTER_FINAL_TSADI	     0x5E5
#define Z_UNICODE_HEBREW_LETTER_TSADI		     0x5E6
#define Z_UNICODE_HEBREW_LETTER_QOF		     0x5E7
#define Z_UNICODE_HEBREW_LETTER_RESH		     0x5E8
#define Z_UNICODE_HEBREW_LETTER_SHIN		     0x5E9
#define Z_UNICODE_HEBREW_LETTER_TAV		     0x5EA
#define Z_UNICODE_HEBREW_LIGATURE_YIDDISH_DOUBLE_VAV 0x5F0
#define Z_UNICODE_HEBREW_LIGATURE_YIDDISH_VAV_YOD    0x5F1
#define Z_UNICODE_HEBREW_LIGATURE_YIDDISH_DOUBLE_YOD 0x5F2
#define Z_UNICODE_HEBREW_PUNCTUATION_GERESH	     0x5F3
#define Z_UNICODE_HEBREW_PUNCTUATION_GERSHAYIM	     0x5F4

#endif /* Z_formats_character_set_Unicode_Hebrew_H */
