/* Z Kit - formats/character set/Unicode/IPA Extensions.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_IPA_Extensions_H
#define Z_formats_character_set_Unicode_IPA_Extensions_H

/* 0250h-02AFh - IPA Extensions */

#define Z_UNICODE_LATIN_SMALL_LETTER_TURNED_A			     0x250
#define Z_UNICODE_LATIN_SMALL_LETTER_ALPHA			     0x251
#define Z_UNICODE_LATIN_SMALL_LETTER_TURNED_ALPHA		     0x252
#define Z_UNICODE_LATIN_SMALL_LETTER_B_WITH_HOOK		     0x253
#define Z_UNICODE_LATIN_SMALL_LETTER_OPEN_O			     0x254
#define Z_UNICODE_LATIN_SMALL_LETTER_C_WITH_CURL		     0x255
#define Z_UNICODE_LATIN_SMALL_LETTER_D_WITH_TAIL		     0x256
#define Z_UNICODE_LATIN_SMALL_LETTER_D_WITH_HOOK		     0x257
#define Z_UNICODE_LATIN_SMALL_LETTER_REVERSED_E			     0x258
#define Z_UNICODE_LATIN_SMALL_LETTER_SCHWA			     0x259
#define Z_UNICODE_LATIN_SMALL_LETTER_SCHWA_WITH_HOOK		     0x25A
#define Z_UNICODE_LATIN_SMALL_LETTER_OPEN_E			     0x25B
#define Z_UNICODE_LATIN_SMALL_LETTER_REVERSED_OPEN_E		     0x25C
#define Z_UNICODE_LATIN_SMALL_LETTER_REVERSED_OPEN_E_WITH_HOOK	     0x25D
#define Z_UNICODE_LATIN_SMALL_LETTER_CLOSED_REVERSED_OPEN_E	     0x25E
#define Z_UNICODE_LATIN_SMALL_LETTER_DOTLESS_J_WITH_STROKE	     0x25F
#define Z_UNICODE_LATIN_SMALL_LETTER_G_WITH_HOOK		     0x260
#define Z_UNICODE_LATIN_SMALL_LETTER_SCRIPT_G			     0x261
#define Z_UNICODE_LATIN_LETTER_SMALL_CAPITAL_G			     0x262
#define Z_UNICODE_LATIN_SMALL_LETTER_GAMMA			     0x263
#define Z_UNICODE_LATIN_SMALL_LETTER_RAMS_HORN			     0x264
#define Z_UNICODE_LATIN_SMALL_LETTER_TURNED_H			     0x265
#define Z_UNICODE_LATIN_SMALL_LETTER_H_WITH_HOOK		     0x266
#define Z_UNICODE_LATIN_SMALL_LETTER_HENG_WITH_HOOK		     0x267
#define Z_UNICODE_LATIN_SMALL_LETTER_I_WITH_STROKE		     0x268
#define Z_UNICODE_LATIN_SMALL_LETTER_IOTA			     0x269
#define Z_UNICODE_LATIN_LETTER_SMALL_CAPITAL_I			     0x26A
#define Z_UNICODE_LATIN_SMALL_LETTER_L_WITH_MIDDLE_TILDE	     0x26B
#define Z_UNICODE_LATIN_SMALL_LETTER_L_WITH_BELT		     0x26C
#define Z_UNICODE_LATIN_SMALL_LETTER_L_WITH_RETROFLEX_HOOK	     0x26D
#define Z_UNICODE_LATIN_SMALL_LETTER_LEZH			     0x26E
#define Z_UNICODE_LATIN_SMALL_LETTER_TURNED_M			     0x26F
#define Z_UNICODE_LATIN_SMALL_LETTER_TURNED_M_WITH_LONG_LEG	     0x270
#define Z_UNICODE_LATIN_SMALL_LETTER_M_WITH_HOOK		     0x271
#define Z_UNICODE_LATIN_SMALL_LETTER_N_WITH_LEFT_HOOK		     0x272
#define Z_UNICODE_LATIN_SMALL_LETTER_N_WITH_RETROFLEX_HOOK	     0x273
#define Z_UNICODE_LATIN_LETTER_SMALL_CAPITAL_N			     0x274
#define Z_UNICODE_LATIN_SMALL_LETTER_BARRED_O			     0x275
#define Z_UNICODE_LATIN_LETTER_SMALL_CAPITAL_OE			     0x276
#define Z_UNICODE_LATIN_SMALL_LETTER_CLOSED_OMEGA		     0x277
#define Z_UNICODE_LATIN_SMALL_LETTER_PHI			     0x278
#define Z_UNICODE_LATIN_SMALL_LETTER_TURNED_R			     0x279
#define Z_UNICODE_LATIN_SMALL_LETTER_TURNED_R_WITH_LONG_LEG	     0x27A
#define Z_UNICODE_LATIN_SMALL_LETTER_TURNED_R_WITH_HOOK		     0x27B
#define Z_UNICODE_LATIN_SMALL_LETTER_R_WITH_LONG_LEG		     0x27C
#define Z_UNICODE_LATIN_SMALL_LETTER_R_WITH_TAIL		     0x27D
#define Z_UNICODE_LATIN_SMALL_LETTER_R_WITH_FISHHOOK		     0x27E
#define Z_UNICODE_LATIN_SMALL_LETTER_REVERSED_R_WITH_FISHHOOK	     0x27F
#define Z_UNICODE_LATIN_LETTER_SMALL_CAPITAL_R			     0x280
#define Z_UNICODE_LATIN_LETTER_SMALL_CAPITAL_INVERTED_R		     0x281
#define Z_UNICODE_LATIN_SMALL_LETTER_S_WITH_HOOK		     0x282
#define Z_UNICODE_LATIN_SMALL_LETTER_ESH			     0x283
#define Z_UNICODE_LATIN_SMALL_LETTER_DOTLESS_J_WITH_STROKE_AND_HOOK  0x284
#define Z_UNICODE_LATIN_SMALL_LETTER_SQUAT_REVERSED_ESH		     0x285
#define Z_UNICODE_LATIN_SMALL_LETTER_ESH_WITH_CURL		     0x286
#define Z_UNICODE_LATIN_SMALL_LETTER_TURNED_T			     0x287
#define Z_UNICODE_LATIN_SMALL_LETTER_T_WITH_RETROFLEX_HOOK	     0x288
#define Z_UNICODE_LATIN_SMALL_LETTER_U_BAR			     0x289
#define Z_UNICODE_LATIN_SMALL_LETTER_UPSILON			     0x28A
#define Z_UNICODE_LATIN_SMALL_LETTER_V_WITH_HOOK		     0x28B
#define Z_UNICODE_LATIN_SMALL_LETTER_TURNED_V			     0x28C
#define Z_UNICODE_LATIN_SMALL_LETTER_TURNED_W			     0x28D
#define Z_UNICODE_LATIN_SMALL_LETTER_TURNED_Y			     0x28E
#define Z_UNICODE_LATIN_LETTER_SMALL_CAPITAL_Y			     0x28F
#define Z_UNICODE_LATIN_SMALL_LETTER_Z_WITH_RETROFLEX_HOOK	     0x290
#define Z_UNICODE_LATIN_SMALL_LETTER_Z_WITH_CURL		     0x291
#define Z_UNICODE_LATIN_SMALL_LETTER_EZH			     0x292
#define Z_UNICODE_LATIN_SMALL_LETTER_EZH_WITH_CURL		     0x293
#define Z_UNICODE_LATIN_LETTER_GLOTTAL_STOP			     0x294
#define Z_UNICODE_LATIN_LETTER_PHARYNGEAL_VOICED_FRICATIVE	     0x295
#define Z_UNICODE_LATIN_LETTER_INVERTED_GLOTTAL_STOP		     0x296
#define Z_UNICODE_LATIN_LETTER_STRETCHED_C			     0x297
#define Z_UNICODE_LATIN_LETTER_BILABIAL_CLICK			     0x298
#define Z_UNICODE_LATIN_LETTER_SMALL_CAPITAL_B			     0x299
#define Z_UNICODE_LATIN_SMALL_LETTER_CLOSED_OPEN_E		     0x29A
#define Z_UNICODE_LATIN_LETTER_SMALL_CAPITAL_G_WITH_HOOK	     0x29B
#define Z_UNICODE_LATIN_LETTER_SMALL_CAPITAL_H			     0x29C
#define Z_UNICODE_LATIN_SMALL_LETTER_J_WITH_CROSSED_TAIL	     0x29D
#define Z_UNICODE_LATIN_SMALL_LETTER_TURNED_K			     0x29E
#define Z_UNICODE_LATIN_LETTER_SMALL_CAPITAL_L			     0x29F
#define Z_UNICODE_LATIN_SMALL_LETTER_Q_WITH_HOOK		     0x2A0
#define Z_UNICODE_LATIN_LETTER_GLOTTAL_STOP_WITH_STROKE		     0x2A1
#define Z_UNICODE_LATIN_LETTER_REVERSED_GLOTTAL_STOP_WITH_STROKE     0x2A2
#define Z_UNICODE_LATIN_SMALL_LETTER_DZ_DIGRAPH			     0x2A3
#define Z_UNICODE_LATIN_SMALL_LETTER_DEZH_DIGRAPH		     0x2A4
#define Z_UNICODE_LATIN_SMALL_LETTER_DZ_DIGRAPH_WITH_CURL	     0x2A5
#define Z_UNICODE_LATIN_SMALL_LETTER_TS_DIGRAPH			     0x2A6
#define Z_UNICODE_LATIN_SMALL_LETTER_TESH_DIGRAPH		     0x2A7
#define Z_UNICODE_LATIN_SMALL_LETTER_TC_DIGRAPH_WITH_CURL	     0x2A8
#define Z_UNICODE_LATIN_SMALL_LETTER_FENG_DIGRAPH		     0x2A9
#define Z_UNICODE_LATIN_SMALL_LETTER_LS_DIGRAPH			     0x2AA
#define Z_UNICODE_LATIN_SMALL_LETTER_LZ_DIGRAPH			     0x2AB
#define Z_UNICODE_LATIN_LETTER_BILABIAL_PERCUSSIVE		     0x2AC
#define Z_UNICODE_LATIN_LETTER_BIDENTAL_PERCUSSIVE		     0x2AD
#define Z_UNICODE_LATIN_SMALL_LETTER_TURNED_H_WITH_FISHHOOK	     0x2AE
#define Z_UNICODE_LATIN_SMALL_LETTER_TURNED_H_WITH_FISHHOOK_AND_TAIL 0x2AF

#endif /* Z_formats_character_set_Unicode_IPA_Extensions_H */
