/* Z Kit - formats/character set/Unicode/Kannada.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_Kannada_H
#define Z_formats_character_set_Unicode_Kannada_H

/* 0C80h-0CFFh - Kannada */

/* 0CE4h <reserved> */
/* 0CE5h <reserved> */
#define Z_UNICODE_KANNADA_SIGN_CANDRABINDU	0xC81
#define Z_UNICODE_KANNADA_SIGN_ANUSVARA		0xC82
#define Z_UNICODE_KANNADA_SIGN_VISARGA		0xC83
#define Z_UNICODE_KANNADA_LETTER_A		0xC85
#define Z_UNICODE_KANNADA_LETTER_AA		0xC86
#define Z_UNICODE_KANNADA_LETTER_I		0xC87
#define Z_UNICODE_KANNADA_LETTER_II		0xC88
#define Z_UNICODE_KANNADA_LETTER_U		0xC89
#define Z_UNICODE_KANNADA_LETTER_UU		0xC8A
#define Z_UNICODE_KANNADA_LETTER_VOCALIC_R	0xC8B
#define Z_UNICODE_KANNADA_LETTER_VOCALIC_L	0xC8C
#define Z_UNICODE_KANNADA_LETTER_E		0xC8E
#define Z_UNICODE_KANNADA_LETTER_EE		0xC8F
#define Z_UNICODE_KANNADA_LETTER_AI		0xC90
#define Z_UNICODE_KANNADA_LETTER_O		0xC92
#define Z_UNICODE_KANNADA_LETTER_OO		0xC93
#define Z_UNICODE_KANNADA_LETTER_AU		0xC94
#define Z_UNICODE_KANNADA_LETTER_KA		0xC95
#define Z_UNICODE_KANNADA_LETTER_KHA		0xC96
#define Z_UNICODE_KANNADA_LETTER_GA		0xC97
#define Z_UNICODE_KANNADA_LETTER_GHA		0xC98
#define Z_UNICODE_KANNADA_LETTER_NGA		0xC99
#define Z_UNICODE_KANNADA_LETTER_CA		0xC9A
#define Z_UNICODE_KANNADA_LETTER_CHA		0xC9B
#define Z_UNICODE_KANNADA_LETTER_JA		0xC9C
#define Z_UNICODE_KANNADA_LETTER_JHA		0xC9D
#define Z_UNICODE_KANNADA_LETTER_NYA		0xC9E
#define Z_UNICODE_KANNADA_LETTER_TTA		0xC9F
#define Z_UNICODE_KANNADA_LETTER_TTHA		0xCA0
#define Z_UNICODE_KANNADA_LETTER_DDA		0xCA1
#define Z_UNICODE_KANNADA_LETTER_DDHA		0xCA2
#define Z_UNICODE_KANNADA_LETTER_NNA		0xCA3
#define Z_UNICODE_KANNADA_LETTER_TA		0xCA4
#define Z_UNICODE_KANNADA_LETTER_THA		0xCA5
#define Z_UNICODE_KANNADA_LETTER_DA		0xCA6
#define Z_UNICODE_KANNADA_LETTER_DHA		0xCA7
#define Z_UNICODE_KANNADA_LETTER_NA		0xCA8
#define Z_UNICODE_KANNADA_LETTER_PA		0xCAA
#define Z_UNICODE_KANNADA_LETTER_PHA		0xCAB
#define Z_UNICODE_KANNADA_LETTER_BA		0xCAC
#define Z_UNICODE_KANNADA_LETTER_BHA		0xCAD
#define Z_UNICODE_KANNADA_LETTER_MA		0xCAE
#define Z_UNICODE_KANNADA_LETTER_YA		0xCAF
#define Z_UNICODE_KANNADA_LETTER_RA		0xCB0
#define Z_UNICODE_KANNADA_LETTER_RRA		0xCB1
#define Z_UNICODE_KANNADA_LETTER_LA		0xCB2
#define Z_UNICODE_KANNADA_LETTER_LLA		0xCB3
#define Z_UNICODE_KANNADA_LETTER_VA		0xCB5
#define Z_UNICODE_KANNADA_LETTER_SHA		0xCB6
#define Z_UNICODE_KANNADA_LETTER_SSA		0xCB7
#define Z_UNICODE_KANNADA_LETTER_SA		0xCB8
#define Z_UNICODE_KANNADA_LETTER_HA		0xCB9
#define Z_UNICODE_KANNADA_SIGN_NUKTA		0xCBC
#define Z_UNICODE_KANNADA_SIGN_AVAGRAHA		0xCBD
#define Z_UNICODE_KANNADA_VOWEL_SIGN_AA		0xCBE
#define Z_UNICODE_KANNADA_VOWEL_SIGN_I		0xCBF
#define Z_UNICODE_KANNADA_VOWEL_SIGN_II		0xCC0
#define Z_UNICODE_KANNADA_VOWEL_SIGN_U		0xCC1
#define Z_UNICODE_KANNADA_VOWEL_SIGN_UU		0xCC2
#define Z_UNICODE_KANNADA_VOWEL_SIGN_VOCALIC_R	0xCC3
#define Z_UNICODE_KANNADA_VOWEL_SIGN_VOCALIC_RR	0xCC4
#define Z_UNICODE_KANNADA_VOWEL_SIGN_E		0xCC6
#define Z_UNICODE_KANNADA_VOWEL_SIGN_EE		0xCC7
#define Z_UNICODE_KANNADA_VOWEL_SIGN_AI		0xCC8
#define Z_UNICODE_KANNADA_VOWEL_SIGN_O		0xCCA
#define Z_UNICODE_KANNADA_VOWEL_SIGN_OO		0xCCB
#define Z_UNICODE_KANNADA_VOWEL_SIGN_AU		0xCCC
#define Z_UNICODE_KANNADA_SIGN_VIRAMA		0xCCD
#define Z_UNICODE_KANNADA_LENGTH_MARK		0xCD5
#define Z_UNICODE_KANNADA_AI_LENGTH_MARK	0xCD6
#define Z_UNICODE_KANNADA_LETTER_FA		0xCDE
#define Z_UNICODE_KANNADA_LETTER_VOCALIC_RR	0xCE0
#define Z_UNICODE_KANNADA_LETTER_VOCALIC_LL	0xCE1
#define Z_UNICODE_KANNADA_VOWEL_SIGN_VOCALIC_L	0xCE2
#define Z_UNICODE_KANNADA_VOWEL_SIGN_VOCALIC_LL	0xCE3
#define Z_UNICODE_KANNADA_DIGIT_ZERO		0xCE6
#define Z_UNICODE_KANNADA_DIGIT_ONE		0xCE7
#define Z_UNICODE_KANNADA_DIGIT_TWO		0xCE8
#define Z_UNICODE_KANNADA_DIGIT_THREE		0xCE9
#define Z_UNICODE_KANNADA_DIGIT_FOUR		0xCEA
#define Z_UNICODE_KANNADA_DIGIT_FIVE		0xCEB
#define Z_UNICODE_KANNADA_DIGIT_SIX		0xCEC
#define Z_UNICODE_KANNADA_DIGIT_SEVEN		0xCED
#define Z_UNICODE_KANNADA_DIGIT_EIGHT		0xCEE
#define Z_UNICODE_KANNADA_DIGIT_NINE		0xCEF
#define Z_UNICODE_KANNADA_SIGN_JIHVAMULIYA	0xCF1
#define Z_UNICODE_KANNADA_SIGN_UPADHMANIYA	0xCF2

#endif /* Z_formats_character_set_Unicode_Kannada_H */
