/* Z Kit - formats/character set/Unicode/Malayalam.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_Malayalam_H
#define Z_formats_character_set_Unicode_Malayalam_H

/* 0D00h-0D7Fh - Malayalam */

/* 0D64h <reserved> */
/* 0D65h <reserved> */
#define Z_UNICODE_MALAYALAM_SIGN_CANDRABINDU	    0xD01
#define Z_UNICODE_MALAYALAM_SIGN_ANUSVARA	    0xD02
#define Z_UNICODE_MALAYALAM_SIGN_VISARGA	    0xD03
#define Z_UNICODE_MALAYALAM_LETTER_A		    0xD05
#define Z_UNICODE_MALAYALAM_LETTER_AA		    0xD06
#define Z_UNICODE_MALAYALAM_LETTER_I		    0xD07
#define Z_UNICODE_MALAYALAM_LETTER_II		    0xD08
#define Z_UNICODE_MALAYALAM_LETTER_U		    0xD09
#define Z_UNICODE_MALAYALAM_LETTER_UU		    0xD0A
#define Z_UNICODE_MALAYALAM_LETTER_VOCALIC_R	    0xD0B
#define Z_UNICODE_MALAYALAM_LETTER_VOCALIC_L	    0xD0C
#define Z_UNICODE_MALAYALAM_LETTER_E		    0xD0E
#define Z_UNICODE_MALAYALAM_LETTER_EE		    0xD0F
#define Z_UNICODE_MALAYALAM_LETTER_AI		    0xD10
#define Z_UNICODE_MALAYALAM_LETTER_O		    0xD12
#define Z_UNICODE_MALAYALAM_LETTER_OO		    0xD13
#define Z_UNICODE_MALAYALAM_LETTER_AU		    0xD14
#define Z_UNICODE_MALAYALAM_LETTER_KA		    0xD15
#define Z_UNICODE_MALAYALAM_LETTER_KHA		    0xD16
#define Z_UNICODE_MALAYALAM_LETTER_GA		    0xD17
#define Z_UNICODE_MALAYALAM_LETTER_GHA		    0xD18
#define Z_UNICODE_MALAYALAM_LETTER_NGA		    0xD19
#define Z_UNICODE_MALAYALAM_LETTER_CA		    0xD1A
#define Z_UNICODE_MALAYALAM_LETTER_CHA		    0xD1B
#define Z_UNICODE_MALAYALAM_LETTER_JA		    0xD1C
#define Z_UNICODE_MALAYALAM_LETTER_JHA		    0xD1D
#define Z_UNICODE_MALAYALAM_LETTER_NYA		    0xD1E
#define Z_UNICODE_MALAYALAM_LETTER_TTA		    0xD1F
#define Z_UNICODE_MALAYALAM_LETTER_TTHA		    0xD20
#define Z_UNICODE_MALAYALAM_LETTER_DDA		    0xD21
#define Z_UNICODE_MALAYALAM_LETTER_DDHA		    0xD22
#define Z_UNICODE_MALAYALAM_LETTER_NNA		    0xD23
#define Z_UNICODE_MALAYALAM_LETTER_TA		    0xD24
#define Z_UNICODE_MALAYALAM_LETTER_THA		    0xD25
#define Z_UNICODE_MALAYALAM_LETTER_DA		    0xD26
#define Z_UNICODE_MALAYALAM_LETTER_DHA		    0xD27
#define Z_UNICODE_MALAYALAM_LETTER_NA		    0xD28
#define Z_UNICODE_MALAYALAM_LETTER_NNNA		    0xD29
#define Z_UNICODE_MALAYALAM_LETTER_PA		    0xD2A
#define Z_UNICODE_MALAYALAM_LETTER_PHA		    0xD2B
#define Z_UNICODE_MALAYALAM_LETTER_BA		    0xD2C
#define Z_UNICODE_MALAYALAM_LETTER_BHA		    0xD2D
#define Z_UNICODE_MALAYALAM_LETTER_MA		    0xD2E
#define Z_UNICODE_MALAYALAM_LETTER_YA		    0xD2F
#define Z_UNICODE_MALAYALAM_LETTER_RA		    0xD30
#define Z_UNICODE_MALAYALAM_LETTER_RRA		    0xD31
#define Z_UNICODE_MALAYALAM_LETTER_LA		    0xD32
#define Z_UNICODE_MALAYALAM_LETTER_LLA		    0xD33
#define Z_UNICODE_MALAYALAM_LETTER_LLLA		    0xD34
#define Z_UNICODE_MALAYALAM_LETTER_VA		    0xD35
#define Z_UNICODE_MALAYALAM_LETTER_SHA		    0xD36
#define Z_UNICODE_MALAYALAM_LETTER_SSA		    0xD37
#define Z_UNICODE_MALAYALAM_LETTER_SA		    0xD38
#define Z_UNICODE_MALAYALAM_LETTER_HA		    0xD39
#define Z_UNICODE_MALAYALAM_LETTER_TTTA		    0xD3A
#define Z_UNICODE_MALAYALAM_SIGN_AVAGRAHA	    0xD3D
#define Z_UNICODE_MALAYALAM_VOWEL_SIGN_AA	    0xD3E
#define Z_UNICODE_MALAYALAM_VOWEL_SIGN_I	    0xD3F
#define Z_UNICODE_MALAYALAM_VOWEL_SIGN_II	    0xD40
#define Z_UNICODE_MALAYALAM_VOWEL_SIGN_U	    0xD41
#define Z_UNICODE_MALAYALAM_VOWEL_SIGN_UU	    0xD42
#define Z_UNICODE_MALAYALAM_VOWEL_SIGN_VOCALIC_R    0xD43
#define Z_UNICODE_MALAYALAM_VOWEL_SIGN_VOCALIC_RR   0xD44
#define Z_UNICODE_MALAYALAM_VOWEL_SIGN_E	    0xD46
#define Z_UNICODE_MALAYALAM_VOWEL_SIGN_EE	    0xD47
#define Z_UNICODE_MALAYALAM_VOWEL_SIGN_AI	    0xD48
#define Z_UNICODE_MALAYALAM_VOWEL_SIGN_O	    0xD4A
#define Z_UNICODE_MALAYALAM_VOWEL_SIGN_OO	    0xD4B
#define Z_UNICODE_MALAYALAM_VOWEL_SIGN_AU	    0xD4C
#define Z_UNICODE_MALAYALAM_SIGN_VIRAMA		    0xD4D
#define Z_UNICODE_MALAYALAM_LETTER_DOT_REPH	    0xD4E
#define Z_UNICODE_MALAYALAM_AU_LENGTH_MARK	    0xD57
#define Z_UNICODE_MALAYALAM_LETTER_ARCHAIC_II	    0xD5F
#define Z_UNICODE_MALAYALAM_LETTER_VOCALIC_RR	    0xD60
#define Z_UNICODE_MALAYALAM_LETTER_VOCALIC_LL	    0xD61
#define Z_UNICODE_MALAYALAM_VOWEL_SIGN_VOCALIC_L    0xD62
#define Z_UNICODE_MALAYALAM_VOWEL_SIGN_VOCALIC_LL   0xD63
#define Z_UNICODE_MALAYALAM_DIGIT_ZERO		    0xD66
#define Z_UNICODE_MALAYALAM_DIGIT_ONE		    0xD67
#define Z_UNICODE_MALAYALAM_DIGIT_TWO		    0xD68
#define Z_UNICODE_MALAYALAM_DIGIT_THREE		    0xD69
#define Z_UNICODE_MALAYALAM_DIGIT_FOUR		    0xD6A
#define Z_UNICODE_MALAYALAM_DIGIT_FIVE		    0xD6B
#define Z_UNICODE_MALAYALAM_DIGIT_SIX		    0xD6C
#define Z_UNICODE_MALAYALAM_DIGIT_SEVEN		    0xD6D
#define Z_UNICODE_MALAYALAM_DIGIT_EIGHT		    0xD6E
#define Z_UNICODE_MALAYALAM_DIGIT_NINE		    0xD6F
#define Z_UNICODE_MALAYALAM_NUMBER_TEN		    0xD70
#define Z_UNICODE_MALAYALAM_NUMBER_ONE_HUNDRED	    0xD71
#define Z_UNICODE_MALAYALAM_NUMBER_ONE_THOUSAND	    0xD72
#define Z_UNICODE_MALAYALAM_FRACTION_ONE_QUARTER    0xD73
#define Z_UNICODE_MALAYALAM_FRACTION_ONE_HALF	    0xD74
#define Z_UNICODE_MALAYALAM_FRACTION_THREE_QUARTERS 0xD75
#define Z_UNICODE_MALAYALAM_DATE_MARK		    0xD79
#define Z_UNICODE_MALAYALAM_LETTER_CHILLU_NN	    0xD7A
#define Z_UNICODE_MALAYALAM_LETTER_CHILLU_N	    0xD7B
#define Z_UNICODE_MALAYALAM_LETTER_CHILLU_RR	    0xD7C
#define Z_UNICODE_MALAYALAM_LETTER_CHILLU_L	    0xD7D
#define Z_UNICODE_MALAYALAM_LETTER_CHILLU_LL	    0xD7E
#define Z_UNICODE_MALAYALAM_LETTER_CHILLU_K	    0xD7F

#endif /* Z_formats_character_set_Unicode_Malayalam_H */
