/* Z Kit - formats/character set/Unicode/Oriya.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_Oriya_H
#define Z_formats_character_set_Unicode_Oriya_H

/* 0B00h-0B7Fh - Oriya */

/* 0B64h <reserved> */
/* 0B65h <reserved> */
#define Z_UNICODE_ORIYA_SIGN_CANDRABINDU	  0xB01
#define Z_UNICODE_ORIYA_SIGN_ANUSVARA		  0xB02
#define Z_UNICODE_ORIYA_SIGN_VISARGA		  0xB03
#define Z_UNICODE_ORIYA_LETTER_A		  0xB05
#define Z_UNICODE_ORIYA_LETTER_AA		  0xB06
#define Z_UNICODE_ORIYA_LETTER_I		  0xB07
#define Z_UNICODE_ORIYA_LETTER_II		  0xB08
#define Z_UNICODE_ORIYA_LETTER_U		  0xB09
#define Z_UNICODE_ORIYA_LETTER_UU		  0xB0A
#define Z_UNICODE_ORIYA_LETTER_VOCALIC_R	  0xB0B
#define Z_UNICODE_ORIYA_LETTER_VOCALIC_L	  0xB0C
#define Z_UNICODE_ORIYA_LETTER_E		  0xB0F
#define Z_UNICODE_ORIYA_LETTER_AI		  0xB10
#define Z_UNICODE_ORIYA_LETTER_O		  0xB13
#define Z_UNICODE_ORIYA_LETTER_AU		  0xB14
#define Z_UNICODE_ORIYA_LETTER_KA		  0xB15
#define Z_UNICODE_ORIYA_LETTER_KHA		  0xB16
#define Z_UNICODE_ORIYA_LETTER_GA		  0xB17
#define Z_UNICODE_ORIYA_LETTER_GHA		  0xB18
#define Z_UNICODE_ORIYA_LETTER_NGA		  0xB19
#define Z_UNICODE_ORIYA_LETTER_CA		  0xB1A
#define Z_UNICODE_ORIYA_LETTER_CHA		  0xB1B
#define Z_UNICODE_ORIYA_LETTER_JA		  0xB1C
#define Z_UNICODE_ORIYA_LETTER_JHA		  0xB1D
#define Z_UNICODE_ORIYA_LETTER_NYA		  0xB1E
#define Z_UNICODE_ORIYA_LETTER_TTA		  0xB1F
#define Z_UNICODE_ORIYA_LETTER_TTHA		  0xB20
#define Z_UNICODE_ORIYA_LETTER_DDA		  0xB21
#define Z_UNICODE_ORIYA_LETTER_DDHA		  0xB22
#define Z_UNICODE_ORIYA_LETTER_NNA		  0xB23
#define Z_UNICODE_ORIYA_LETTER_TA		  0xB24
#define Z_UNICODE_ORIYA_LETTER_THA		  0xB25
#define Z_UNICODE_ORIYA_LETTER_DA		  0xB26
#define Z_UNICODE_ORIYA_LETTER_DHA		  0xB27
#define Z_UNICODE_ORIYA_LETTER_NA		  0xB28
#define Z_UNICODE_ORIYA_LETTER_PA		  0xB2A
#define Z_UNICODE_ORIYA_LETTER_PHA		  0xB2B
#define Z_UNICODE_ORIYA_LETTER_BA		  0xB2C
#define Z_UNICODE_ORIYA_LETTER_BHA		  0xB2D
#define Z_UNICODE_ORIYA_LETTER_MA		  0xB2E
#define Z_UNICODE_ORIYA_LETTER_YA		  0xB2F
#define Z_UNICODE_ORIYA_LETTER_RA		  0xB30
#define Z_UNICODE_ORIYA_LETTER_LA		  0xB32
#define Z_UNICODE_ORIYA_LETTER_LLA		  0xB33
#define Z_UNICODE_ORIYA_LETTER_VA		  0xB35
#define Z_UNICODE_ORIYA_LETTER_SHA		  0xB36
#define Z_UNICODE_ORIYA_LETTER_SSA		  0xB37
#define Z_UNICODE_ORIYA_LETTER_SA		  0xB38
#define Z_UNICODE_ORIYA_LETTER_HA		  0xB39
#define Z_UNICODE_ORIYA_SIGN_NUKTA		  0xB3C
#define Z_UNICODE_ORIYA_SIGN_AVAGRAHA		  0xB3D
#define Z_UNICODE_ORIYA_VOWEL_SIGN_AA		  0xB3E
#define Z_UNICODE_ORIYA_VOWEL_SIGN_I		  0xB3F
#define Z_UNICODE_ORIYA_VOWEL_SIGN_II		  0xB40
#define Z_UNICODE_ORIYA_VOWEL_SIGN_U		  0xB41
#define Z_UNICODE_ORIYA_VOWEL_SIGN_UU		  0xB42
#define Z_UNICODE_ORIYA_VOWEL_SIGN_VOCALIC_R	  0xB43
#define Z_UNICODE_ORIYA_VOWEL_SIGN_VOCALIC_RR	  0xB44
#define Z_UNICODE_ORIYA_VOWEL_SIGN_E		  0xB47
#define Z_UNICODE_ORIYA_VOWEL_SIGN_AI		  0xB48
#define Z_UNICODE_ORIYA_VOWEL_SIGN_O		  0xB4B
#define Z_UNICODE_ORIYA_VOWEL_SIGN_AU		  0xB4C
#define Z_UNICODE_ORIYA_SIGN_VIRAMA		  0xB4D
#define Z_UNICODE_ORIYA_AI_LENGTH_MARK		  0xB56
#define Z_UNICODE_ORIYA_AU_LENGTH_MARK		  0xB57
#define Z_UNICODE_ORIYA_LETTER_RRA		  0xB5C
#define Z_UNICODE_ORIYA_LETTER_RHA		  0xB5D
#define Z_UNICODE_ORIYA_LETTER_YYA		  0xB5F
#define Z_UNICODE_ORIYA_LETTER_VOCALIC_RR	  0xB60
#define Z_UNICODE_ORIYA_LETTER_VOCALIC_LL	  0xB61
#define Z_UNICODE_ORIYA_VOWEL_SIGN_VOCALIC_L	  0xB62
#define Z_UNICODE_ORIYA_VOWEL_SIGN_VOCALIC_LL	  0xB63
#define Z_UNICODE_ORIYA_DIGIT_ZERO		  0xB66
#define Z_UNICODE_ORIYA_DIGIT_ONE		  0xB67
#define Z_UNICODE_ORIYA_DIGIT_TWO		  0xB68
#define Z_UNICODE_ORIYA_DIGIT_THREE		  0xB69
#define Z_UNICODE_ORIYA_DIGIT_FOUR		  0xB6A
#define Z_UNICODE_ORIYA_DIGIT_FIVE		  0xB6B
#define Z_UNICODE_ORIYA_DIGIT_SIX		  0xB6C
#define Z_UNICODE_ORIYA_DIGIT_SEVEN		  0xB6D
#define Z_UNICODE_ORIYA_DIGIT_EIGHT		  0xB6E
#define Z_UNICODE_ORIYA_DIGIT_NINE		  0xB6F
#define Z_UNICODE_ORIYA_ISSHAR			  0xB70
#define Z_UNICODE_ORIYA_LETTER_WA		  0xB71
#define Z_UNICODE_ORIYA_FRACTION_ONE_QUARTER	  0xB72
#define Z_UNICODE_ORIYA_FRACTION_ONE_HALF	  0xB73
#define Z_UNICODE_ORIYA_FRACTION_THREE_QUARTERS	  0xB74
#define Z_UNICODE_ORIYA_FRACTION_ONE_SIXTEENTH	  0xB75
#define Z_UNICODE_ORIYA_FRACTION_ONE_EIGHTH	  0xB76
#define Z_UNICODE_ORIYA_FRACTION_THREE_SIXTEENTHS 0xB77

#endif /* Z_formats_character_set_Unicode_Oriya_H */
