/* Z Kit - formats/character set/Unicode/Samaritan.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_Samaritan_H
#define Z_formats_character_set_Unicode_Samaritan_H

/* 0800h-083Fh - Samaritan */

#define Z_UNICODE_SAMARITAN_LETTER_ALAF			   0x800
#define Z_UNICODE_SAMARITAN_LETTER_BIT			   0x801
#define Z_UNICODE_SAMARITAN_LETTER_GAMAN		   0x802
#define Z_UNICODE_SAMARITAN_LETTER_DALAT		   0x803
#define Z_UNICODE_SAMARITAN_LETTER_IY			   0x804
#define Z_UNICODE_SAMARITAN_LETTER_BAA			   0x805
#define Z_UNICODE_SAMARITAN_LETTER_ZEN			   0x806
#define Z_UNICODE_SAMARITAN_LETTER_IT			   0x807
#define Z_UNICODE_SAMARITAN_LETTER_TIT			   0x808
#define Z_UNICODE_SAMARITAN_LETTER_YUT			   0x809
#define Z_UNICODE_SAMARITAN_LETTER_KAAF			   0x80A
#define Z_UNICODE_SAMARITAN_LETTER_LABAT		   0x80B
#define Z_UNICODE_SAMARITAN_LETTER_MIM			   0x80C
#define Z_UNICODE_SAMARITAN_LETTER_NUN			   0x80D
#define Z_UNICODE_SAMARITAN_LETTER_SINGAAT		   0x80E
#define Z_UNICODE_SAMARITAN_LETTER_IN			   0x80F
#define Z_UNICODE_SAMARITAN_LETTER_FI			   0x810
#define Z_UNICODE_SAMARITAN_LETTER_TSAADIY		   0x811
#define Z_UNICODE_SAMARITAN_LETTER_QUF			   0x812
#define Z_UNICODE_SAMARITAN_LETTER_RISH			   0x813
#define Z_UNICODE_SAMARITAN_LETTER_SHAN			   0x814
#define Z_UNICODE_SAMARITAN_LETTER_TAAF			   0x815
#define Z_UNICODE_SAMARITAN_MARK_IN			   0x816
#define Z_UNICODE_SAMARITAN_MARK_IN_ALAF		   0x817
#define Z_UNICODE_SAMARITAN_MARK_OCCLUSION		   0x818
#define Z_UNICODE_SAMARITAN_MARK_DAGESH			   0x819
#define Z_UNICODE_SAMARITAN_MODIFIER_LETTER_EPENTHETIC_YUT 0x81A
#define Z_UNICODE_SAMARITAN_MARK_EPENTHETIC_YUT		   0x81B
#define Z_UNICODE_SAMARITAN_VOWEL_SIGN_LONG_E		   0x81C
#define Z_UNICODE_SAMARITAN_VOWEL_SIGN_E		   0x81D
#define Z_UNICODE_SAMARITAN_VOWEL_SIGN_OVERLONG_AA	   0x81E
#define Z_UNICODE_SAMARITAN_VOWEL_SIGN_LONG_AA		   0x81F
#define Z_UNICODE_SAMARITAN_VOWEL_SIGN_AA		   0x820
#define Z_UNICODE_SAMARITAN_VOWEL_SIGN_OVERLONG_A	   0x821
#define Z_UNICODE_SAMARITAN_VOWEL_SIGN_LONG_A		   0x822
#define Z_UNICODE_SAMARITAN_VOWEL_SIGN_A		   0x823
#define Z_UNICODE_SAMARITAN_MODIFIER_LETTER_SHORT_A	   0x824
#define Z_UNICODE_SAMARITAN_VOWEL_SIGN_SHORT_A		   0x825
#define Z_UNICODE_SAMARITAN_VOWEL_SIGN_LONG_U		   0x826
#define Z_UNICODE_SAMARITAN_VOWEL_SIGN_U		   0x827
#define Z_UNICODE_SAMARITAN_MODIFIER_LETTER_I		   0x828
#define Z_UNICODE_SAMARITAN_VOWEL_SIGN_LONG_I		   0x829
#define Z_UNICODE_SAMARITAN_VOWEL_SIGN_I		   0x82A
#define Z_UNICODE_SAMARITAN_VOWEL_SIGN_O		   0x82B
#define Z_UNICODE_SAMARITAN_VOWEL_SIGN_SUKUN		   0x82C
#define Z_UNICODE_SAMARITAN_MARK_NEQUDAA		   0x82D
#define Z_UNICODE_SAMARITAN_PUNCTUATION_NEQUDAA		   0x830
#define Z_UNICODE_SAMARITAN_PUNCTUATION_AFSAAQ		   0x831
#define Z_UNICODE_SAMARITAN_PUNCTUATION_ANGED		   0x832
#define Z_UNICODE_SAMARITAN_PUNCTUATION_BAU		   0x833
#define Z_UNICODE_SAMARITAN_PUNCTUATION_ATMAAU		   0x834
#define Z_UNICODE_SAMARITAN_PUNCTUATION_SHIYYAALAA	   0x835
#define Z_UNICODE_SAMARITAN_ABBREVIATION_MARK		   0x836
#define Z_UNICODE_SAMARITAN_PUNCTUATION_MELODIC_QITSA	   0x837
#define Z_UNICODE_SAMARITAN_PUNCTUATION_ZIQAA		   0x838
#define Z_UNICODE_SAMARITAN_PUNCTUATION_QITSA		   0x839
#define Z_UNICODE_SAMARITAN_PUNCTUATION_ZAEF		   0x83A
#define Z_UNICODE_SAMARITAN_PUNCTUATION_TURU		   0x83B
#define Z_UNICODE_SAMARITAN_PUNCTUATION_ARKAANU		   0x83C
#define Z_UNICODE_SAMARITAN_PUNCTUATION_SOF_MASHFAAT	   0x83D
#define Z_UNICODE_SAMARITAN_PUNCTUATION_ANNAAU		   0x83E

#endif /* Z_formats_character_set_Unicode_Samaritan_H */
