/* Z Kit - formats/character set/Unicode/Sinhala.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_Sinhala_H
#define Z_formats_character_set_Unicode_Sinhala_H

/* 0D80h-0DFFh - Sinhala */

#define Z_UNICODE_SINHALA_SIGN_ANUSVARAYA			 0xD82
#define Z_UNICODE_SINHALA_SIGN_VISARGAYA			 0xD83
#define Z_UNICODE_SINHALA_LETTER_AYANNA				 0xD85
#define Z_UNICODE_SINHALA_LETTER_AAYANNA			 0xD86
#define Z_UNICODE_SINHALA_LETTER_AEYANNA			 0xD87
#define Z_UNICODE_SINHALA_LETTER_AEEYANNA			 0xD88
#define Z_UNICODE_SINHALA_LETTER_IYANNA				 0xD89
#define Z_UNICODE_SINHALA_LETTER_IIYANNA			 0xD8A
#define Z_UNICODE_SINHALA_LETTER_UYANNA				 0xD8B
#define Z_UNICODE_SINHALA_LETTER_UUYANNA			 0xD8C
#define Z_UNICODE_SINHALA_LETTER_IRUYANNA			 0xD8D
#define Z_UNICODE_SINHALA_LETTER_IRUUYANNA			 0xD8E
#define Z_UNICODE_SINHALA_LETTER_ILUYANNA			 0xD8F
#define Z_UNICODE_SINHALA_LETTER_ILUUYANNA			 0xD90
#define Z_UNICODE_SINHALA_LETTER_EYANNA				 0xD91
#define Z_UNICODE_SINHALA_LETTER_EEYANNA			 0xD92
#define Z_UNICODE_SINHALA_LETTER_AIYANNA			 0xD93
#define Z_UNICODE_SINHALA_LETTER_OYANNA				 0xD94
#define Z_UNICODE_SINHALA_LETTER_OOYANNA			 0xD95
#define Z_UNICODE_SINHALA_LETTER_AUYANNA			 0xD96
#define Z_UNICODE_SINHALA_LETTER_ALPAPRAANA_KAYANNA		 0xD9A
#define Z_UNICODE_SINHALA_LETTER_MAHAAPRAANA_KAYANNA		 0xD9B
#define Z_UNICODE_SINHALA_LETTER_ALPAPRAANA_GAYANNA		 0xD9C
#define Z_UNICODE_SINHALA_LETTER_MAHAAPRAANA_GAYANNA		 0xD9D
#define Z_UNICODE_SINHALA_LETTER_KANTAJA_NAASIKYAYA		 0xD9E
#define Z_UNICODE_SINHALA_LETTER_SANYAKA_GAYANNA		 0xD9F
#define Z_UNICODE_SINHALA_LETTER_ALPAPRAANA_CAYANNA		 0xDA0
#define Z_UNICODE_SINHALA_LETTER_MAHAAPRAANA_CAYANNA		 0xDA1
#define Z_UNICODE_SINHALA_LETTER_ALPAPRAANA_JAYANNA		 0xDA2
#define Z_UNICODE_SINHALA_LETTER_MAHAAPRAANA_JAYANNA		 0xDA3
#define Z_UNICODE_SINHALA_LETTER_TAALUJA_NAASIKYAYA		 0xDA4
#define Z_UNICODE_SINHALA_LETTER_TAALUJA_SANYOOGA_NAAKSIKYAYA	 0xDA5
#define Z_UNICODE_SINHALA_LETTER_SANYAKA_JAYANNA		 0xDA6
#define Z_UNICODE_SINHALA_LETTER_ALPAPRAANA_TTAYANNA		 0xDA7
#define Z_UNICODE_SINHALA_LETTER_MAHAAPRAANA_TTAYANNA		 0xDA8
#define Z_UNICODE_SINHALA_LETTER_ALPAPRAANA_DDAYANNA		 0xDA9
#define Z_UNICODE_SINHALA_LETTER_MAHAAPRAANA_DDAYANNA		 0xDAA
#define Z_UNICODE_SINHALA_LETTER_MUURDHAJA_NAYANNA		 0xDAB
#define Z_UNICODE_SINHALA_LETTER_SANYAKA_DDAYANNA		 0xDAC
#define Z_UNICODE_SINHALA_LETTER_ALPAPRAANA_TAYANNA		 0xDAD
#define Z_UNICODE_SINHALA_LETTER_MAHAAPRAANA_TAYANNA		 0xDAE
#define Z_UNICODE_SINHALA_LETTER_ALPAPRAANA_DAYANNA		 0xDAF
#define Z_UNICODE_SINHALA_LETTER_MAHAAPRAANA_DAYANNA		 0xDB0
#define Z_UNICODE_SINHALA_LETTER_DANTAJA_NAYANNA		 0xDB1
#define Z_UNICODE_SINHALA_LETTER_SANYAKA_DAYANNA		 0xDB3
#define Z_UNICODE_SINHALA_LETTER_ALPAPRAANA_PAYANNA		 0xDB4
#define Z_UNICODE_SINHALA_LETTER_MAHAAPRAANA_PAYANNA		 0xDB5
#define Z_UNICODE_SINHALA_LETTER_ALPAPRAANA_BAYANNA		 0xDB6
#define Z_UNICODE_SINHALA_LETTER_MAHAAPRAANA_BAYANNA		 0xDB7
#define Z_UNICODE_SINHALA_LETTER_MAYANNA			 0xDB8
#define Z_UNICODE_SINHALA_LETTER_AMBA_BAYANNA			 0xDB9
#define Z_UNICODE_SINHALA_LETTER_YAYANNA			 0xDBA
#define Z_UNICODE_SINHALA_LETTER_RAYANNA			 0xDBB
#define Z_UNICODE_SINHALA_LETTER_DANTAJA_LAYANNA		 0xDBD
#define Z_UNICODE_SINHALA_LETTER_VAYANNA			 0xDC0
#define Z_UNICODE_SINHALA_LETTER_TAALUJA_SAYANNA		 0xDC1
#define Z_UNICODE_SINHALA_LETTER_MUURDHAJA_SAYANNA		 0xDC2
#define Z_UNICODE_SINHALA_LETTER_DANTAJA_SAYANNA		 0xDC3
#define Z_UNICODE_SINHALA_LETTER_HAYANNA			 0xDC4
#define Z_UNICODE_SINHALA_LETTER_MUURDHAJA_LAYANNA		 0xDC5
#define Z_UNICODE_SINHALA_LETTER_FAYANNA			 0xDC6
#define Z_UNICODE_SINHALA_SIGN_AL_LAKUNA			 0xDCA
#define Z_UNICODE_SINHALA_VOWEL_SIGN_AELA_PILLA			 0xDCF
#define Z_UNICODE_SINHALA_VOWEL_SIGN_KETTI_AEDA_PILLA		 0xDD0
#define Z_UNICODE_SINHALA_VOWEL_SIGN_DIGA_AEDA_PILLA		 0xDD1
#define Z_UNICODE_SINHALA_VOWEL_SIGN_KETTI_IS_PILLA		 0xDD2
#define Z_UNICODE_SINHALA_VOWEL_SIGN_DIGA_IS_PILLA		 0xDD3
#define Z_UNICODE_SINHALA_VOWEL_SIGN_KETTI_PAA_PILLA		 0xDD4
#define Z_UNICODE_SINHALA_VOWEL_SIGN_DIGA_PAA_PILLA		 0xDD6
#define Z_UNICODE_SINHALA_VOWEL_SIGN_GAETTA_PILLA		 0xDD8
#define Z_UNICODE_SINHALA_VOWEL_SIGN_KOMBUVA			 0xDD9
#define Z_UNICODE_SINHALA_VOWEL_SIGN_DIGA_KOMBUVA		 0xDDA
#define Z_UNICODE_SINHALA_VOWEL_SIGN_KOMBU_DEKA			 0xDDB
#define Z_UNICODE_SINHALA_VOWEL_SIGN_KOMBUVA_HAA_AELA_PILLA	 0xDDC
#define Z_UNICODE_SINHALA_VOWEL_SIGN_KOMBUVA_HAA_DIGA_AELA_PILLA 0xDDD
#define Z_UNICODE_SINHALA_VOWEL_SIGN_KOMBUVA_HAA_GAYANUKITTA	 0xDDE
#define Z_UNICODE_SINHALA_VOWEL_SIGN_GAYANUKITTA		 0xDDF
#define Z_UNICODE_SINHALA_LITH_DIGIT_ZERO			 0xDE6
#define Z_UNICODE_SINHALA_LITH_DIGIT_ONE			 0xDE7
#define Z_UNICODE_SINHALA_LITH_DIGIT_TWO			 0xDE8
#define Z_UNICODE_SINHALA_LITH_DIGIT_THREE			 0xDE9
#define Z_UNICODE_SINHALA_LITH_DIGIT_FOUR			 0xDEA
#define Z_UNICODE_SINHALA_LITH_DIGIT_FIVE			 0xDEB
#define Z_UNICODE_SINHALA_LITH_DIGIT_SIX			 0xDEC
#define Z_UNICODE_SINHALA_LITH_DIGIT_SEVEN			 0xDED
#define Z_UNICODE_SINHALA_LITH_DIGIT_EIGHT			 0xDEE
#define Z_UNICODE_SINHALA_LITH_DIGIT_NINE			 0xDEF
#define Z_UNICODE_SINHALA_VOWEL_SIGN_DIGA_GAETTA_PILLA		 0xDF2
#define Z_UNICODE_SINHALA_VOWEL_SIGN_DIGA_GAYANUKITTA		 0xDF3
#define Z_UNICODE_SINHALA_PUNCTUATION_KUNDDALIYA		 0xDF4

#endif /* Z_formats_character_set_Unicode_Sinhala_H */
