/* Z Kit - formats/character set/Unicode/Spacing Modifier Letters.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_Spacing_Modifier_Letters_H
#define Z_formats_character_set_Unicode_Spacing_Modifier_Letters_H

/* 02B0h-02FFh - Spacing Modifier Letters */

#define Z_UNICODE_MODIFIER_LETTER_SMALL_H		      0x2B0
#define Z_UNICODE_MODIFIER_LETTER_SMALL_H_WITH_HOOK	      0x2B1
#define Z_UNICODE_MODIFIER_LETTER_SMALL_J		      0x2B2
#define Z_UNICODE_MODIFIER_LETTER_SMALL_R		      0x2B3
#define Z_UNICODE_MODIFIER_LETTER_SMALL_TURNED_R	      0x2B4
#define Z_UNICODE_MODIFIER_LETTER_SMALL_TURNED_R_WITH_HOOK    0x2B5
#define Z_UNICODE_MODIFIER_LETTER_SMALL_CAPITAL_INVERTED_R    0x2B6
#define Z_UNICODE_MODIFIER_LETTER_SMALL_W		      0x2B7
#define Z_UNICODE_MODIFIER_LETTER_SMALL_Y		      0x2B8
#define Z_UNICODE_MODIFIER_LETTER_PRIME			      0x2B9
#define Z_UNICODE_MODIFIER_LETTER_DOUBLE_PRIME		      0x2BA
#define Z_UNICODE_MODIFIER_LETTER_TURNED_COMMA		      0x2BB
#define Z_UNICODE_MODIFIER_LETTER_APOSTROPHE		      0x2BC
#define Z_UNICODE_MODIFIER_LETTER_REVERSED_COMMA	      0x2BD
#define Z_UNICODE_MODIFIER_LETTER_RIGHT_HALF_RING	      0x2BE
#define Z_UNICODE_MODIFIER_LETTER_LEFT_HALF_RING	      0x2BF
#define Z_UNICODE_MODIFIER_LETTER_GLOTTAL_STOP		      0x2C0
#define Z_UNICODE_MODIFIER_LETTER_REVERSED_GLOTTAL_STOP	      0x2C1
#define Z_UNICODE_MODIFIER_LETTER_LEFT_ARROWHEAD	      0x2C2
#define Z_UNICODE_MODIFIER_LETTER_RIGHT_ARROWHEAD	      0x2C3
#define Z_UNICODE_MODIFIER_LETTER_UP_ARROWHEAD		      0x2C4
#define Z_UNICODE_MODIFIER_LETTER_DOWN_ARROWHEAD	      0x2C5
#define Z_UNICODE_MODIFIER_LETTER_CIRCUMFLEX_ACCENT	      0x2C6
#define Z_UNICODE_CARON					      0x2C7
#define Z_UNICODE_MODIFIER_LETTER_VERTICAL_LINE		      0x2C8
#define Z_UNICODE_MODIFIER_LETTER_MACRON		      0x2C9
#define Z_UNICODE_MODIFIER_LETTER_ACUTE_ACCENT		      0x2CA
#define Z_UNICODE_MODIFIER_LETTER_GRAVE_ACCENT		      0x2CB
#define Z_UNICODE_MODIFIER_LETTER_LOW_VERTICAL_LINE	      0x2CC
#define Z_UNICODE_MODIFIER_LETTER_LOW_MACRON		      0x2CD
#define Z_UNICODE_MODIFIER_LETTER_LOW_GRAVE_ACCENT	      0x2CE
#define Z_UNICODE_MODIFIER_LETTER_LOW_ACUTE_ACCENT	      0x2CF
#define Z_UNICODE_MODIFIER_LETTER_TRIANGULAR_COLON	      0x2D0
#define Z_UNICODE_MODIFIER_LETTER_HALF_TRIANGULAR_COLON	      0x2D1
#define Z_UNICODE_MODIFIER_LETTER_CENTRED_RIGHT_HALF_RING     0x2D2
#define Z_UNICODE_MODIFIER_LETTER_CENTRED_LEFT_HALF_RING      0x2D3
#define Z_UNICODE_MODIFIER_LETTER_UP_TACK		      0x2D4
#define Z_UNICODE_MODIFIER_LETTER_DOWN_TACK		      0x2D5
#define Z_UNICODE_MODIFIER_LETTER_PLUS_SIGN		      0x2D6
#define Z_UNICODE_MODIFIER_LETTER_MINUS_SIGN		      0x2D7
#define Z_UNICODE_BREVE					      0x2D8
#define Z_UNICODE_DOT_ABOVE				      0x2D9
#define Z_UNICODE_RING_ABOVE				      0x2DA
#define Z_UNICODE_OGONEK				      0x2DB
#define Z_UNICODE_SMALL_TILDE				      0x2DC
#define Z_UNICODE_DOUBLE_ACUTE_ACCENT			      0x2DD
#define Z_UNICODE_MODIFIER_LETTER_RHOTIC_HOOK		      0x2DE
#define Z_UNICODE_MODIFIER_LETTER_CROSS_ACCENT		      0x2DF
#define Z_UNICODE_MODIFIER_LETTER_SMALL_GAMMA		      0x2E0
#define Z_UNICODE_MODIFIER_LETTER_SMALL_L		      0x2E1
#define Z_UNICODE_MODIFIER_LETTER_SMALL_S		      0x2E2
#define Z_UNICODE_MODIFIER_LETTER_SMALL_X		      0x2E3
#define Z_UNICODE_MODIFIER_LETTER_SMALL_REVERSED_GLOTTAL_STOP 0x2E4
#define Z_UNICODE_MODIFIER_LETTER_EXTRA_HIGH_TONE_BAR	      0x2E5
#define Z_UNICODE_MODIFIER_LETTER_HIGH_TONE_BAR		      0x2E6
#define Z_UNICODE_MODIFIER_LETTER_MID_TONE_BAR		      0x2E7
#define Z_UNICODE_MODIFIER_LETTER_LOW_TONE_BAR		      0x2E8
#define Z_UNICODE_MODIFIER_LETTER_EXTRA_LOW_TONE_BAR	      0x2E9
#define Z_UNICODE_MODIFIER_LETTER_YIN_DEPARTING_TONE_MARK     0x2EA
#define Z_UNICODE_MODIFIER_LETTER_YANG_DEPARTING_TONE_MARK    0x2EB
#define Z_UNICODE_MODIFIER_LETTER_VOICING		      0x2EC
#define Z_UNICODE_MODIFIER_LETTER_UNASPIRATED		      0x2ED
#define Z_UNICODE_MODIFIER_LETTER_DOUBLE_APOSTROPHE	      0x2EE
#define Z_UNICODE_MODIFIER_LETTER_LOW_DOWN_ARROWHEAD	      0x2EF
#define Z_UNICODE_MODIFIER_LETTER_LOW_UP_ARROWHEAD	      0x2F0
#define Z_UNICODE_MODIFIER_LETTER_LOW_LEFT_ARROWHEAD	      0x2F1
#define Z_UNICODE_MODIFIER_LETTER_LOW_RIGHT_ARROWHEAD	      0x2F2
#define Z_UNICODE_MODIFIER_LETTER_LOW_RING		      0x2F3
#define Z_UNICODE_MODIFIER_LETTER_MIDDLE_GRAVE_ACCENT	      0x2F4
#define Z_UNICODE_MODIFIER_LETTER_MIDDLE_DOUBLE_GRAVE_ACCENT  0x2F5
#define Z_UNICODE_MODIFIER_LETTER_MIDDLE_DOUBLE_ACUTE_ACCENT  0x2F6
#define Z_UNICODE_MODIFIER_LETTER_LOW_TILDE		      0x2F7
#define Z_UNICODE_MODIFIER_LETTER_RAISED_COLON		      0x2F8
#define Z_UNICODE_MODIFIER_LETTER_BEGIN_HIGH_TONE	      0x2F9
#define Z_UNICODE_MODIFIER_LETTER_END_HIGH_TONE		      0x2FA
#define Z_UNICODE_MODIFIER_LETTER_BEGIN_LOW_TONE	      0x2FB
#define Z_UNICODE_MODIFIER_LETTER_END_LOW_TONE		      0x2FC
#define Z_UNICODE_MODIFIER_LETTER_SHELF			      0x2FD
#define Z_UNICODE_MODIFIER_LETTER_OPEN_SHELF		      0x2FE
#define Z_UNICODE_MODIFIER_LETTER_LOW_LEFT_ARROW	      0x2FF

#endif /* Z_formats_character_set_Unicode_Spacing_Modifier_Letters_H */
