/* Z Kit - formats/character set/Unicode/Syriac.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_Syriac_H
#define Z_formats_character_set_Unicode_Syriac_H

/* 0700h-074Fh - Syriac */

#define Z_UNICODE_SYRIAC_END_OF_PARAGRAPH	       0x700
#define Z_UNICODE_SYRIAC_SUPRALINEAR_FULL_STOP	       0x701
#define Z_UNICODE_SYRIAC_SUBLINEAR_FULL_STOP	       0x702
#define Z_UNICODE_SYRIAC_SUPRALINEAR_COLON	       0x703
#define Z_UNICODE_SYRIAC_SUBLINEAR_COLON	       0x704
#define Z_UNICODE_SYRIAC_HORIZONTAL_COLON	       0x705
#define Z_UNICODE_SYRIAC_COLON_SKEWED_LEFT	       0x706
#define Z_UNICODE_SYRIAC_COLON_SKEWED_RIGHT	       0x707
#define Z_UNICODE_SYRIAC_SUPRALINEAR_COLON_SKEWED_LEFT 0x708
#define Z_UNICODE_SYRIAC_SUBLINEAR_COLON_SKEWED_RIGHT  0x709
#define Z_UNICODE_SYRIAC_CONTRACTION		       0x70A
#define Z_UNICODE_SYRIAC_HARKLEAN_OBELUS	       0x70B
#define Z_UNICODE_SYRIAC_HARKLEAN_METOBELUS	       0x70C
#define Z_UNICODE_SYRIAC_HARKLEAN_ASTERISCUS	       0x70D
#define Z_UNICODE_SYRIAC_ABBREVIATION_MARK	       0x70F
#define Z_UNICODE_SYRIAC_LETTER_ALAPH		       0x710
#define Z_UNICODE_SYRIAC_LETTER_SUPERSCRIPT_ALAPH      0x711
#define Z_UNICODE_SYRIAC_LETTER_BETH		       0x712
#define Z_UNICODE_SYRIAC_LETTER_GAMAL		       0x713
#define Z_UNICODE_SYRIAC_LETTER_GAMAL_GARSHUNI	       0x714
#define Z_UNICODE_SYRIAC_LETTER_DALATH		       0x715
#define Z_UNICODE_SYRIAC_LETTER_DOTLESS_DALATH_RISH    0x716
#define Z_UNICODE_SYRIAC_LETTER_HE		       0x717
#define Z_UNICODE_SYRIAC_LETTER_WAW		       0x718
#define Z_UNICODE_SYRIAC_LETTER_ZAIN		       0x719
#define Z_UNICODE_SYRIAC_LETTER_HETH		       0x71A
#define Z_UNICODE_SYRIAC_LETTER_TETH		       0x71B
#define Z_UNICODE_SYRIAC_LETTER_TETH_GARSHUNI	       0x71C
#define Z_UNICODE_SYRIAC_LETTER_YUDH		       0x71D
#define Z_UNICODE_SYRIAC_LETTER_YUDH_HE		       0x71E
#define Z_UNICODE_SYRIAC_LETTER_KAPH		       0x71F
#define Z_UNICODE_SYRIAC_LETTER_LAMADH		       0x720
#define Z_UNICODE_SYRIAC_LETTER_MIM		       0x721
#define Z_UNICODE_SYRIAC_LETTER_NUN		       0x722
#define Z_UNICODE_SYRIAC_LETTER_SEMKATH		       0x723
#define Z_UNICODE_SYRIAC_LETTER_FINAL_SEMKATH	       0x724
#define Z_UNICODE_SYRIAC_LETTER_E		       0x725
#define Z_UNICODE_SYRIAC_LETTER_PE		       0x726
#define Z_UNICODE_SYRIAC_LETTER_REVERSED_PE	       0x727
#define Z_UNICODE_SYRIAC_LETTER_SADHE		       0x728
#define Z_UNICODE_SYRIAC_LETTER_QAPH		       0x729
#define Z_UNICODE_SYRIAC_LETTER_RISH		       0x72A
#define Z_UNICODE_SYRIAC_LETTER_SHIN		       0x72B
#define Z_UNICODE_SYRIAC_LETTER_TAW		       0x72C
#define Z_UNICODE_SYRIAC_LETTER_PERSIAN_BHETH	       0x72D
#define Z_UNICODE_SYRIAC_LETTER_PERSIAN_GHAMAL	       0x72E
#define Z_UNICODE_SYRIAC_LETTER_PERSIAN_DHALATH	       0x72F
#define Z_UNICODE_SYRIAC_PTHAHA_ABOVE		       0x730
#define Z_UNICODE_SYRIAC_PTHAHA_BELOW		       0x731
#define Z_UNICODE_SYRIAC_PTHAHA_DOTTED		       0x732
#define Z_UNICODE_SYRIAC_ZQAPHA_ABOVE		       0x733
#define Z_UNICODE_SYRIAC_ZQAPHA_BELOW		       0x734
#define Z_UNICODE_SYRIAC_ZQAPHA_DOTTED		       0x735
#define Z_UNICODE_SYRIAC_RBASA_ABOVE		       0x736
#define Z_UNICODE_SYRIAC_RBASA_BELOW		       0x737
#define Z_UNICODE_SYRIAC_DOTTED_ZLAMA_HORIZONTAL       0x738
#define Z_UNICODE_SYRIAC_DOTTED_ZLAMA_ANGULAR	       0x739
#define Z_UNICODE_SYRIAC_HBASA_ABOVE		       0x73A
#define Z_UNICODE_SYRIAC_HBASA_BELOW		       0x73B
#define Z_UNICODE_SYRIAC_HBASA_ESASA_DOTTED	       0x73C
#define Z_UNICODE_SYRIAC_ESASA_ABOVE		       0x73D
#define Z_UNICODE_SYRIAC_ESASA_BELOW		       0x73E
#define Z_UNICODE_SYRIAC_RWAHA			       0x73F
#define Z_UNICODE_SYRIAC_FEMININE_DOT		       0x740
#define Z_UNICODE_SYRIAC_QUSHSHAYA		       0x741
#define Z_UNICODE_SYRIAC_RUKKAKHA		       0x742
#define Z_UNICODE_SYRIAC_TWO_VERTICAL_DOTS_ABOVE       0x743
#define Z_UNICODE_SYRIAC_TWO_VERTICAL_DOTS_BELOW       0x744
#define Z_UNICODE_SYRIAC_THREE_DOTS_ABOVE	       0x745
#define Z_UNICODE_SYRIAC_THREE_DOTS_BELOW	       0x746
#define Z_UNICODE_SYRIAC_OBLIQUE_LINE_ABOVE	       0x747
#define Z_UNICODE_SYRIAC_OBLIQUE_LINE_BELOW	       0x748
#define Z_UNICODE_SYRIAC_MUSIC			       0x749
#define Z_UNICODE_SYRIAC_BARREKH		       0x74A
#define Z_UNICODE_SYRIAC_LETTER_SOGDIAN_ZHAIN	       0x74D
#define Z_UNICODE_SYRIAC_LETTER_SOGDIAN_KHAPH	       0x74E
#define Z_UNICODE_SYRIAC_LETTER_SOGDIAN_FE	       0x74F

#endif /* Z_formats_character_set_Unicode_Syriac_H */
