/* Z Kit - formats/character set/Unicode/Tamil.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_Tamil_H
#define Z_formats_character_set_Unicode_Tamil_H

/* 0B80h-0BFFh - Tamil */

/* 0BE4h <reserved> */
/* 0BE5h <reserved> */
#define Z_UNICODE_TAMIL_SIGN_ANUSVARA	    0xB82
#define Z_UNICODE_TAMIL_SIGN_VISARGA	    0xB83
#define Z_UNICODE_TAMIL_LETTER_A	    0xB85
#define Z_UNICODE_TAMIL_LETTER_AA	    0xB86
#define Z_UNICODE_TAMIL_LETTER_I	    0xB87
#define Z_UNICODE_TAMIL_LETTER_II	    0xB88
#define Z_UNICODE_TAMIL_LETTER_U	    0xB89
#define Z_UNICODE_TAMIL_LETTER_UU	    0xB8A
#define Z_UNICODE_TAMIL_LETTER_E	    0xB8E
#define Z_UNICODE_TAMIL_LETTER_EE	    0xB8F
#define Z_UNICODE_TAMIL_LETTER_AI	    0xB90
#define Z_UNICODE_TAMIL_LETTER_O	    0xB92
#define Z_UNICODE_TAMIL_LETTER_OO	    0xB93
#define Z_UNICODE_TAMIL_LETTER_AU	    0xB94
#define Z_UNICODE_TAMIL_LETTER_KA	    0xB95
#define Z_UNICODE_TAMIL_LETTER_NGA	    0xB99
#define Z_UNICODE_TAMIL_LETTER_CA	    0xB9A
#define Z_UNICODE_TAMIL_LETTER_JA	    0xB9C
#define Z_UNICODE_TAMIL_LETTER_NYA	    0xB9E
#define Z_UNICODE_TAMIL_LETTER_TTA	    0xB9F
#define Z_UNICODE_TAMIL_LETTER_NNA	    0xBA3
#define Z_UNICODE_TAMIL_LETTER_TA	    0xBA4
#define Z_UNICODE_TAMIL_LETTER_NA	    0xBA8
#define Z_UNICODE_TAMIL_LETTER_NNNA	    0xBA9
#define Z_UNICODE_TAMIL_LETTER_PA	    0xBAA
#define Z_UNICODE_TAMIL_LETTER_MA	    0xBAE
#define Z_UNICODE_TAMIL_LETTER_YA	    0xBAF
#define Z_UNICODE_TAMIL_LETTER_RA	    0xBB0
#define Z_UNICODE_TAMIL_LETTER_RRA	    0xBB1
#define Z_UNICODE_TAMIL_LETTER_LA	    0xBB2
#define Z_UNICODE_TAMIL_LETTER_LLA	    0xBB3
#define Z_UNICODE_TAMIL_LETTER_LLLA	    0xBB4
#define Z_UNICODE_TAMIL_LETTER_VA	    0xBB5
#define Z_UNICODE_TAMIL_LETTER_SHA	    0xBB6
#define Z_UNICODE_TAMIL_LETTER_SSA	    0xBB7
#define Z_UNICODE_TAMIL_LETTER_SA	    0xBB8
#define Z_UNICODE_TAMIL_LETTER_HA	    0xBB9
#define Z_UNICODE_TAMIL_VOWEL_SIGN_AA	    0xBBE
#define Z_UNICODE_TAMIL_VOWEL_SIGN_I	    0xBBF
#define Z_UNICODE_TAMIL_VOWEL_SIGN_II	    0xBC0
#define Z_UNICODE_TAMIL_VOWEL_SIGN_U	    0xBC1
#define Z_UNICODE_TAMIL_VOWEL_SIGN_UU	    0xBC2
#define Z_UNICODE_TAMIL_VOWEL_SIGN_E	    0xBC6
#define Z_UNICODE_TAMIL_VOWEL_SIGN_EE	    0xBC7
#define Z_UNICODE_TAMIL_VOWEL_SIGN_AI	    0xBC8
#define Z_UNICODE_TAMIL_VOWEL_SIGN_O	    0xBCA
#define Z_UNICODE_TAMIL_VOWEL_SIGN_OO	    0xBCB
#define Z_UNICODE_TAMIL_VOWEL_SIGN_AU	    0xBCC
#define Z_UNICODE_TAMIL_SIGN_VIRAMA	    0xBCD
#define Z_UNICODE_TAMIL_OM		    0xBD0
#define Z_UNICODE_TAMIL_AU_LENGTH_MARK	    0xBD7
#define Z_UNICODE_TAMIL_DIGIT_ZERO	    0xBE6
#define Z_UNICODE_TAMIL_DIGIT_ONE	    0xBE7
#define Z_UNICODE_TAMIL_DIGIT_TWO	    0xBE8
#define Z_UNICODE_TAMIL_DIGIT_THREE	    0xBE9
#define Z_UNICODE_TAMIL_DIGIT_FOUR	    0xBEA
#define Z_UNICODE_TAMIL_DIGIT_FIVE	    0xBEB
#define Z_UNICODE_TAMIL_DIGIT_SIX	    0xBEC
#define Z_UNICODE_TAMIL_DIGIT_SEVEN	    0xBED
#define Z_UNICODE_TAMIL_DIGIT_EIGHT	    0xBEE
#define Z_UNICODE_TAMIL_DIGIT_NINE	    0xBEF
#define Z_UNICODE_TAMIL_NUMBER_TEN	    0xBF0
#define Z_UNICODE_TAMIL_NUMBER_ONE_HUNDRED  0xBF1
#define Z_UNICODE_TAMIL_NUMBER_ONE_THOUSAND 0xBF2
#define Z_UNICODE_TAMIL_DAY_SIGN	    0xBF3
#define Z_UNICODE_TAMIL_MONTH_SIGN	    0xBF4
#define Z_UNICODE_TAMIL_YEAR_SIGN	    0xBF5
#define Z_UNICODE_TAMIL_DEBIT_SIGN	    0xBF6
#define Z_UNICODE_TAMIL_CREDIT_SIGN	    0xBF7
#define Z_UNICODE_TAMIL_AS_ABOVE_SIGN	    0xBF8
#define Z_UNICODE_TAMIL_RUPEE_SIGN	    0xBF9
#define Z_UNICODE_TAMIL_NUMBER_SIGN	    0xBFA

#endif /* Z_formats_character_set_Unicode_Tamil_H */
