/* Z Kit - formats/character set/Unicode/Telugu.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_Telugu_H
#define Z_formats_character_set_Unicode_Telugu_H

/* 0C00h-0C7Fh - Telugu */

/* 0C64h <reserved> */
/* 0C65h <reserved> */
#define Z_UNICODE_TELUGU_SIGN_COMBINING_CANDRABINDU_ABOVE	      0xC00
#define Z_UNICODE_TELUGU_SIGN_CANDRABINDU			      0xC01
#define Z_UNICODE_TELUGU_SIGN_ANUSVARA				      0xC02
#define Z_UNICODE_TELUGU_SIGN_VISARGA				      0xC03
#define Z_UNICODE_TELUGU_LETTER_A				      0xC05
#define Z_UNICODE_TELUGU_LETTER_AA				      0xC06
#define Z_UNICODE_TELUGU_LETTER_I				      0xC07
#define Z_UNICODE_TELUGU_LETTER_II				      0xC08
#define Z_UNICODE_TELUGU_LETTER_U				      0xC09
#define Z_UNICODE_TELUGU_LETTER_UU				      0xC0A
#define Z_UNICODE_TELUGU_LETTER_VOCALIC_R			      0xC0B
#define Z_UNICODE_TELUGU_LETTER_VOCALIC_L			      0xC0C
#define Z_UNICODE_TELUGU_LETTER_E				      0xC0E
#define Z_UNICODE_TELUGU_LETTER_EE				      0xC0F
#define Z_UNICODE_TELUGU_LETTER_AI				      0xC10
#define Z_UNICODE_TELUGU_LETTER_O				      0xC12
#define Z_UNICODE_TELUGU_LETTER_OO				      0xC13
#define Z_UNICODE_TELUGU_LETTER_AU				      0xC14
#define Z_UNICODE_TELUGU_LETTER_KA				      0xC15
#define Z_UNICODE_TELUGU_LETTER_KHA				      0xC16
#define Z_UNICODE_TELUGU_LETTER_GA				      0xC17
#define Z_UNICODE_TELUGU_LETTER_GHA				      0xC18
#define Z_UNICODE_TELUGU_LETTER_NGA				      0xC19
#define Z_UNICODE_TELUGU_LETTER_CA				      0xC1A
#define Z_UNICODE_TELUGU_LETTER_CHA				      0xC1B
#define Z_UNICODE_TELUGU_LETTER_JA				      0xC1C
#define Z_UNICODE_TELUGU_LETTER_JHA				      0xC1D
#define Z_UNICODE_TELUGU_LETTER_NYA				      0xC1E
#define Z_UNICODE_TELUGU_LETTER_TTA				      0xC1F
#define Z_UNICODE_TELUGU_LETTER_TTHA				      0xC20
#define Z_UNICODE_TELUGU_LETTER_DDA				      0xC21
#define Z_UNICODE_TELUGU_LETTER_DDHA				      0xC22
#define Z_UNICODE_TELUGU_LETTER_NNA				      0xC23
#define Z_UNICODE_TELUGU_LETTER_TA				      0xC24
#define Z_UNICODE_TELUGU_LETTER_THA				      0xC25
#define Z_UNICODE_TELUGU_LETTER_DA				      0xC26
#define Z_UNICODE_TELUGU_LETTER_DHA				      0xC27
#define Z_UNICODE_TELUGU_LETTER_NA				      0xC28
#define Z_UNICODE_TELUGU_LETTER_PA				      0xC2A
#define Z_UNICODE_TELUGU_LETTER_PHA				      0xC2B
#define Z_UNICODE_TELUGU_LETTER_BA				      0xC2C
#define Z_UNICODE_TELUGU_LETTER_BHA				      0xC2D
#define Z_UNICODE_TELUGU_LETTER_MA				      0xC2E
#define Z_UNICODE_TELUGU_LETTER_YA				      0xC2F
#define Z_UNICODE_TELUGU_LETTER_RA				      0xC30
#define Z_UNICODE_TELUGU_LETTER_RRA				      0xC31
#define Z_UNICODE_TELUGU_LETTER_LA				      0xC32
#define Z_UNICODE_TELUGU_LETTER_LLA				      0xC33
#define Z_UNICODE_TELUGU_LETTER_LLLA				      0xC34
#define Z_UNICODE_TELUGU_LETTER_VA				      0xC35
#define Z_UNICODE_TELUGU_LETTER_SHA				      0xC36
#define Z_UNICODE_TELUGU_LETTER_SSA				      0xC37
#define Z_UNICODE_TELUGU_LETTER_SA				      0xC38
#define Z_UNICODE_TELUGU_LETTER_HA				      0xC39
#define Z_UNICODE_TELUGU_SIGN_AVAGRAHA				      0xC3D
#define Z_UNICODE_TELUGU_VOWEL_SIGN_AA				      0xC3E
#define Z_UNICODE_TELUGU_VOWEL_SIGN_I				      0xC3F
#define Z_UNICODE_TELUGU_VOWEL_SIGN_II				      0xC40
#define Z_UNICODE_TELUGU_VOWEL_SIGN_U				      0xC41
#define Z_UNICODE_TELUGU_VOWEL_SIGN_UU				      0xC42
#define Z_UNICODE_TELUGU_VOWEL_SIGN_VOCALIC_R			      0xC43
#define Z_UNICODE_TELUGU_VOWEL_SIGN_VOCALIC_RR			      0xC44
#define Z_UNICODE_TELUGU_VOWEL_SIGN_E				      0xC46
#define Z_UNICODE_TELUGU_VOWEL_SIGN_EE				      0xC47
#define Z_UNICODE_TELUGU_VOWEL_SIGN_AI				      0xC48
#define Z_UNICODE_TELUGU_VOWEL_SIGN_O				      0xC4A
#define Z_UNICODE_TELUGU_VOWEL_SIGN_OO				      0xC4B
#define Z_UNICODE_TELUGU_VOWEL_SIGN_AU				      0xC4C
#define Z_UNICODE_TELUGU_SIGN_VIRAMA				      0xC4D
#define Z_UNICODE_TELUGU_LENGTH_MARK				      0xC55
#define Z_UNICODE_TELUGU_AI_LENGTH_MARK				      0xC56
#define Z_UNICODE_TELUGU_LETTER_TSA				      0xC58
#define Z_UNICODE_TELUGU_LETTER_DZA				      0xC59
#define Z_UNICODE_TELUGU_LETTER_RRRA				      0xC5A
#define Z_UNICODE_TELUGU_LETTER_VOCALIC_RR			      0xC60
#define Z_UNICODE_TELUGU_LETTER_VOCALIC_LL			      0xC61
#define Z_UNICODE_TELUGU_VOWEL_SIGN_VOCALIC_L			      0xC62
#define Z_UNICODE_TELUGU_VOWEL_SIGN_VOCALIC_LL			      0xC63
#define Z_UNICODE_TELUGU_DIGIT_ZERO				      0xC66
#define Z_UNICODE_TELUGU_DIGIT_ONE				      0xC67
#define Z_UNICODE_TELUGU_DIGIT_TWO				      0xC68
#define Z_UNICODE_TELUGU_DIGIT_THREE				      0xC69
#define Z_UNICODE_TELUGU_DIGIT_FOUR				      0xC6A
#define Z_UNICODE_TELUGU_DIGIT_FIVE				      0xC6B
#define Z_UNICODE_TELUGU_DIGIT_SIX				      0xC6C
#define Z_UNICODE_TELUGU_DIGIT_SEVEN				      0xC6D
#define Z_UNICODE_TELUGU_DIGIT_EIGHT				      0xC6E
#define Z_UNICODE_TELUGU_DIGIT_NINE				      0xC6F
#define Z_UNICODE_TELUGU_FRACTION_DIGIT_ZERO_FOR_ODD_POWERS_OF_FOUR   0xC78
#define Z_UNICODE_TELUGU_FRACTION_DIGIT_ONE_FOR_ODD_POWERS_OF_FOUR    0xC79
#define Z_UNICODE_TELUGU_FRACTION_DIGIT_TWO_FOR_ODD_POWERS_OF_FOUR    0xC7A
#define Z_UNICODE_TELUGU_FRACTION_DIGIT_THREE_FOR_ODD_POWERS_OF_FOUR  0xC7B
#define Z_UNICODE_TELUGU_FRACTION_DIGIT_ONE_FOR_EVEN_POWERS_OF_FOUR   0xC7C
#define Z_UNICODE_TELUGU_FRACTION_DIGIT_TWO_FOR_EVEN_POWERS_OF_FOUR   0xC7D
#define Z_UNICODE_TELUGU_FRACTION_DIGIT_THREE_FOR_EVEN_POWERS_OF_FOUR 0xC7E
#define Z_UNICODE_TELUGU_SIGN_TUUMU				      0xC7F

#endif /* Z_formats_character_set_Unicode_Telugu_H */
