/* Z Kit - formats/character set/Unicode/Thaana.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_Thaana_H
#define Z_formats_character_set_Unicode_Thaana_H

/* 0780h-07BFh - Thaana */

#define Z_UNICODE_THAANA_LETTER_HAA	  0x780
#define Z_UNICODE_THAANA_LETTER_SHAVIYANI 0x781
#define Z_UNICODE_THAANA_LETTER_NOONU	  0x782
#define Z_UNICODE_THAANA_LETTER_RAA	  0x783
#define Z_UNICODE_THAANA_LETTER_BAA	  0x784
#define Z_UNICODE_THAANA_LETTER_LHAVIYANI 0x785
#define Z_UNICODE_THAANA_LETTER_KAAFU	  0x786
#define Z_UNICODE_THAANA_LETTER_ALIFU	  0x787
#define Z_UNICODE_THAANA_LETTER_VAAVU	  0x788
#define Z_UNICODE_THAANA_LETTER_MEEMU	  0x789
#define Z_UNICODE_THAANA_LETTER_FAAFU	  0x78A
#define Z_UNICODE_THAANA_LETTER_DHAALU	  0x78B
#define Z_UNICODE_THAANA_LETTER_THAA	  0x78C
#define Z_UNICODE_THAANA_LETTER_LAAMU	  0x78D
#define Z_UNICODE_THAANA_LETTER_GAAFU	  0x78E
#define Z_UNICODE_THAANA_LETTER_GNAVIYANI 0x78F
#define Z_UNICODE_THAANA_LETTER_SEENU	  0x790
#define Z_UNICODE_THAANA_LETTER_DAVIYANI  0x791
#define Z_UNICODE_THAANA_LETTER_ZAVIYANI  0x792
#define Z_UNICODE_THAANA_LETTER_TAVIYANI  0x793
#define Z_UNICODE_THAANA_LETTER_YAA	  0x794
#define Z_UNICODE_THAANA_LETTER_PAVIYANI  0x795
#define Z_UNICODE_THAANA_LETTER_JAVIYANI  0x796
#define Z_UNICODE_THAANA_LETTER_CHAVIYANI 0x797
#define Z_UNICODE_THAANA_LETTER_TTAA	  0x798
#define Z_UNICODE_THAANA_LETTER_HHAA	  0x799
#define Z_UNICODE_THAANA_LETTER_KHAA	  0x79A
#define Z_UNICODE_THAANA_LETTER_THAALU	  0x79B
#define Z_UNICODE_THAANA_LETTER_ZAA	  0x79C
#define Z_UNICODE_THAANA_LETTER_SHEENU	  0x79D
#define Z_UNICODE_THAANA_LETTER_SAADHU	  0x79E
#define Z_UNICODE_THAANA_LETTER_DAADHU	  0x79F
#define Z_UNICODE_THAANA_LETTER_TO	  0x7A0
#define Z_UNICODE_THAANA_LETTER_ZO	  0x7A1
#define Z_UNICODE_THAANA_LETTER_AINU	  0x7A2
#define Z_UNICODE_THAANA_LETTER_GHAINU	  0x7A3
#define Z_UNICODE_THAANA_LETTER_QAAFU	  0x7A4
#define Z_UNICODE_THAANA_LETTER_WAAVU	  0x7A5
#define Z_UNICODE_THAANA_ABAFILI	  0x7A6
#define Z_UNICODE_THAANA_AABAAFILI	  0x7A7
#define Z_UNICODE_THAANA_IBIFILI	  0x7A8
#define Z_UNICODE_THAANA_EEBEEFILI	  0x7A9
#define Z_UNICODE_THAANA_UBUFILI	  0x7AA
#define Z_UNICODE_THAANA_OOBOOFILI	  0x7AB
#define Z_UNICODE_THAANA_EBEFILI	  0x7AC
#define Z_UNICODE_THAANA_EYBEYFILI	  0x7AD
#define Z_UNICODE_THAANA_OBOFILI	  0x7AE
#define Z_UNICODE_THAANA_OABOAFILI	  0x7AF
#define Z_UNICODE_THAANA_SUKUN		  0x7B0
#define Z_UNICODE_THAANA_LETTER_NAA	  0x7B1

#endif /* Z_formats_character_set_Unicode_Thaana_H */
