/* Z Kit - formats/character set/Unicode/Thai.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_formats_character_set_Unicode_Thai_H
#define Z_formats_character_set_Unicode_Thai_H

/* 0E00h-0E7Fh - Thai */

#define Z_UNICODE_THAI_CHARACTER_KO_KAI		  0xE01
#define Z_UNICODE_THAI_CHARACTER_KHO_KHAI	  0xE02
#define Z_UNICODE_THAI_CHARACTER_KHO_KHUAT	  0xE03
#define Z_UNICODE_THAI_CHARACTER_KHO_KHWAI	  0xE04
#define Z_UNICODE_THAI_CHARACTER_KHO_KHON	  0xE05
#define Z_UNICODE_THAI_CHARACTER_KHO_RAKHANG	  0xE06
#define Z_UNICODE_THAI_CHARACTER_NGO_NGU	  0xE07
#define Z_UNICODE_THAI_CHARACTER_CHO_CHAN	  0xE08
#define Z_UNICODE_THAI_CHARACTER_CHO_CHING	  0xE09
#define Z_UNICODE_THAI_CHARACTER_CHO_CHANG	  0xE0A
#define Z_UNICODE_THAI_CHARACTER_SO_SO		  0xE0B
#define Z_UNICODE_THAI_CHARACTER_CHO_CHOE	  0xE0C
#define Z_UNICODE_THAI_CHARACTER_YO_YING	  0xE0D
#define Z_UNICODE_THAI_CHARACTER_DO_CHADA	  0xE0E
#define Z_UNICODE_THAI_CHARACTER_TO_PATAK	  0xE0F
#define Z_UNICODE_THAI_CHARACTER_THO_THAN	  0xE10
#define Z_UNICODE_THAI_CHARACTER_THO_NANGMONTHO	  0xE11
#define Z_UNICODE_THAI_CHARACTER_THO_PHUTHAO	  0xE12
#define Z_UNICODE_THAI_CHARACTER_NO_NEN		  0xE13
#define Z_UNICODE_THAI_CHARACTER_DO_DEK		  0xE14
#define Z_UNICODE_THAI_CHARACTER_TO_TAO		  0xE15
#define Z_UNICODE_THAI_CHARACTER_THO_THUNG	  0xE16
#define Z_UNICODE_THAI_CHARACTER_THO_THAHAN	  0xE17
#define Z_UNICODE_THAI_CHARACTER_THO_THONG	  0xE18
#define Z_UNICODE_THAI_CHARACTER_NO_NU		  0xE19
#define Z_UNICODE_THAI_CHARACTER_BO_BAIMAI	  0xE1A
#define Z_UNICODE_THAI_CHARACTER_PO_PLA		  0xE1B
#define Z_UNICODE_THAI_CHARACTER_PHO_PHUNG	  0xE1C
#define Z_UNICODE_THAI_CHARACTER_FO_FA		  0xE1D
#define Z_UNICODE_THAI_CHARACTER_PHO_PHAN	  0xE1E
#define Z_UNICODE_THAI_CHARACTER_FO_FAN		  0xE1F
#define Z_UNICODE_THAI_CHARACTER_PHO_SAMPHAO	  0xE20
#define Z_UNICODE_THAI_CHARACTER_MO_MA		  0xE21
#define Z_UNICODE_THAI_CHARACTER_YO_YAK		  0xE22
#define Z_UNICODE_THAI_CHARACTER_RO_RUA		  0xE23
#define Z_UNICODE_THAI_CHARACTER_RU		  0xE24
#define Z_UNICODE_THAI_CHARACTER_LO_LING	  0xE25
#define Z_UNICODE_THAI_CHARACTER_LU		  0xE26
#define Z_UNICODE_THAI_CHARACTER_WO_WAEN	  0xE27
#define Z_UNICODE_THAI_CHARACTER_SO_SALA	  0xE28
#define Z_UNICODE_THAI_CHARACTER_SO_RUSI	  0xE29
#define Z_UNICODE_THAI_CHARACTER_SO_SUA		  0xE2A
#define Z_UNICODE_THAI_CHARACTER_HO_HIP		  0xE2B
#define Z_UNICODE_THAI_CHARACTER_LO_CHULA	  0xE2C
#define Z_UNICODE_THAI_CHARACTER_O_ANG		  0xE2D
#define Z_UNICODE_THAI_CHARACTER_HO_NOKHUK	  0xE2E
#define Z_UNICODE_THAI_CHARACTER_PAIYANNOI	  0xE2F
#define Z_UNICODE_THAI_CHARACTER_SARA_A		  0xE30
#define Z_UNICODE_THAI_CHARACTER_MAI_HAN_AKAT	  0xE31
#define Z_UNICODE_THAI_CHARACTER_SARA_AA	  0xE32
#define Z_UNICODE_THAI_CHARACTER_SARA_AM	  0xE33
#define Z_UNICODE_THAI_CHARACTER_SARA_I		  0xE34
#define Z_UNICODE_THAI_CHARACTER_SARA_II	  0xE35
#define Z_UNICODE_THAI_CHARACTER_SARA_UE	  0xE36
#define Z_UNICODE_THAI_CHARACTER_SARA_UEE	  0xE37
#define Z_UNICODE_THAI_CHARACTER_SARA_U		  0xE38
#define Z_UNICODE_THAI_CHARACTER_SARA_UU	  0xE39
#define Z_UNICODE_THAI_CHARACTER_PHINTHU	  0xE3A
#define Z_UNICODE_THAI_CURRENCY_SYMBOL_BAHT	  0xE3F
#define Z_UNICODE_THAI_CHARACTER_SARA_E		  0xE40
#define Z_UNICODE_THAI_CHARACTER_SARA_AE	  0xE41
#define Z_UNICODE_THAI_CHARACTER_SARA_O		  0xE42
#define Z_UNICODE_THAI_CHARACTER_SARA_AI_MAIMUAN  0xE43
#define Z_UNICODE_THAI_CHARACTER_SARA_AI_MAIMALAI 0xE44
#define Z_UNICODE_THAI_CHARACTER_LAKKHANGYAO	  0xE45
#define Z_UNICODE_THAI_CHARACTER_MAIYAMOK	  0xE46
#define Z_UNICODE_THAI_CHARACTER_MAITAIKHU	  0xE47
#define Z_UNICODE_THAI_CHARACTER_MAI_EK		  0xE48
#define Z_UNICODE_THAI_CHARACTER_MAI_THO	  0xE49
#define Z_UNICODE_THAI_CHARACTER_MAI_TRI	  0xE4A
#define Z_UNICODE_THAI_CHARACTER_MAI_CHATTAWA	  0xE4B
#define Z_UNICODE_THAI_CHARACTER_THANTHAKHAT	  0xE4C
#define Z_UNICODE_THAI_CHARACTER_NIKHAHIT	  0xE4D
#define Z_UNICODE_THAI_CHARACTER_YAMAKKAN	  0xE4E
#define Z_UNICODE_THAI_CHARACTER_FONGMAN	  0xE4F
#define Z_UNICODE_THAI_DIGIT_ZERO		  0xE50
#define Z_UNICODE_THAI_DIGIT_ONE		  0xE51
#define Z_UNICODE_THAI_DIGIT_TWO		  0xE52
#define Z_UNICODE_THAI_DIGIT_THREE		  0xE53
#define Z_UNICODE_THAI_DIGIT_FOUR		  0xE54
#define Z_UNICODE_THAI_DIGIT_FIVE		  0xE55
#define Z_UNICODE_THAI_DIGIT_SIX		  0xE56
#define Z_UNICODE_THAI_DIGIT_SEVEN		  0xE57
#define Z_UNICODE_THAI_DIGIT_EIGHT		  0xE58
#define Z_UNICODE_THAI_DIGIT_NINE		  0xE59
#define Z_UNICODE_THAI_CHARACTER_ANGKHANKHU	  0xE5A
#define Z_UNICODE_THAI_CHARACTER_KHOMUT		  0xE5B

#endif /* Z_formats_character_set_Unicode_Thai_H */
