/* Z Kit C API - keys/hardware/CPU.h
	      __	   __
  _______ ___/ /______ ___/ /__
 / __/ -_) _  / __/ _ \ _  / -_)
/_/  \__/\_,_/\__/\___/_,_/\__/
Copyright © 2006-2016 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef __Z_keys_hardware_CPU_H__
#define __Z_keys_hardware_CPU_H__
					
#define Z_CPU_ARCHITECTURE_X86_16	  1
#define Z_CPU_ARCHITECTURE_X86_32	  2
#define Z_CPU_ARCHITECTURE_X86_64	  3
#define Z_CPU_ARCHITECTURE_POWER_PC_32	  4
#define Z_CPU_ARCHITECTURE_POWER_PC_64	  5
#define Z_CPU_ARCHITECTURE_A_ARCH_32	  6
#define Z_CPU_ARCHITECTURE_A_ARCH_64	  7
#define Z_CPU_ARCHITECTURE_ALPHA	  8
#define Z_CPU_ARCHITECTURE_BLACKFIN	  9
#define Z_CPU_ARCHITECTURE_CONVEX	  10
#define Z_CPU_ARCHITECTURE_EPIPHANY	  11
#define Z_CPU_ARCHITECTURE_H8_300	  12
#define Z_CPU_ARCHITECTURE_ITANIUM	  13
#define Z_CPU_ARCHITECTURE_M68K		  14
#define Z_CPU_ARCHITECTURE_MIPS		  15
#define Z_CPU_ARCHITECTURE_PA_RISC	  16
#define Z_CPU_ARCHITECTURE_PYRAMID_9810	  17
#define Z_CPU_ARCHITECTURE_RS_6000	  18
#define Z_CPU_ARCHITECTURE_SPARC	  19
#define Z_CPU_ARCHITECTURE_SUPER_H	  20
#define Z_CPU_ARCHITECTURE_SYSTEM_370	  21
#define Z_CPU_ARCHITECTURE_SYSTEM_390	  22
#define Z_CPU_ARCHITECTURE_TMS320	  23
#define Z_CPU_ARCHITECTURE_Z_ARCHITECTURE 24
#define Z_CPU_ARCHITECTURE_Z80		  25

#define Z_CPU_ARCHITECTURE_STRING_X86_16	 "x86-16"
#define Z_CPU_ARCHITECTURE_STRING_X86_32	 "x86-32"
#define Z_CPU_ARCHITECTURE_STRING_X86_64	 "x86-64"
#define Z_CPU_ARCHITECTURE_STRING_POWER_PC_32	 "PowerPC 32-bit"
#define Z_CPU_ARCHITECTURE_STRING_POWER_PC_64	 "PowerPC 64-bit"
#define Z_CPU_ARCHITECTURE_STRING_A_ARCH_32	 "AArch32"
#define Z_CPU_ARCHITECTURE_STRING_A_ARCH_64	 "AArch64"
#define Z_CPU_ARCHITECTURE_STRING_ALPHA		 "Alpha"
#define Z_CPU_ARCHITECTURE_STRING_BLACKFIN	 "Blackfin"
#define Z_CPU_ARCHITECTURE_STRING_CONVEX	 "Convex"
#define Z_CPU_ARCHITECTURE_STRING_EPIPHANY	 "Epiphany"
#define Z_CPU_ARCHITECTURE_STRING_H8_300	 "H8/300"
#define Z_CPU_ARCHITECTURE_STRING_ITANIUM	 "Itanium"
#define Z_CPU_ARCHITECTURE_STRING_M68K		 "M68K"
#define Z_CPU_ARCHITECTURE_STRING_MIPS		 "MIPS"
#define Z_CPU_ARCHITECTURE_STRING_PA_RISC	 "PA-RISC"
#define Z_CPU_ARCHITECTURE_STRING_PYRAMID_9810	 "Pyramid 9810"
#define Z_CPU_ARCHITECTURE_STRING_RS_6000	 "RS/6000"
#define Z_CPU_ARCHITECTURE_STRING_SPARC		 "SPARC"
#define Z_CPU_ARCHITECTURE_STRING_SUPER_H	 "SuperH"
#define Z_CPU_ARCHITECTURE_STRING_SYSTEM_370	 "System/370"
#define Z_CPU_ARCHITECTURE_STRING_SYSTEM_390	 "System/390"
#define Z_CPU_ARCHITECTURE_STRING_TMS320	 "TMS320"
#define Z_CPU_ARCHITECTURE_STRING_Z_ARCHITECTURE "z/Architecture"
#define Z_CPU_ARCHITECTURE_STRING_Z80		 "Z80"

#endif /* __Z_keys_hardware_CPU_H__ */
