#!/usr/bin/ruby

# Z Kit scripts - Z
#               __           __
#   _______ ___/ /______ ___/ /__
#  / __/ -_) _  / __/ _ \ _  / -_)
# /_/  \__/\_,_/\__/\___/_,_/\__/
# Copyright © 2006-2015 Manuel Sainz de Baranda y Goñi.
# Released under the terms of the GNU Lesser General Public License v3. */

macros = {
	'BUILD_TIME' => "#{`date +%s`}"
}

output = []

ARGV.uniq.each do |name|
	value = macros[name]
	output << "-D#{name}=" + value.strip if !value.nil?
end

print output.join(' ')
