#!/usr/bin/ruby

# Z Kit scripts - Z
#               __           __
#   _______ ___/ /______ ___/ /__
#  / __/ -_) _  / __/ _ \ _  / -_)
# /_/  \__/\_,_/\__/\___/_,_/\__/
# Copyright © 2006-2015 Manuel Sainz de Baranda y Goñi.
# Released under the terms of the GNU Lesser General Public License v3. */

output = []

ARGV.uniq.each do |name|
	case name
	when 'BUILD_TIME'
		output << "-DZ_BUILD_TIME=#{`date +%s`.strip}"
	end
end

print output.join(' ')
