/* Q API - keys/formats/value.h
	      __	   __
  _______ ___/ /______ ___/ /__
 / __/ -_) _  / __/ _ \ _  / -_)
/_/  \__/\_,_/\__/\___/_,_/\__/
Copyright © 2006-2012 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU General Public License v3. */

#ifndef __Q_keys_formats_value_H__
#define __Q_keys_formats_value_H__

#define Q_VALUE_FORMAT_8BIT_NATURAL			0
#define Q_VALUE_FORMAT_16BIT_NATURAL			1
#define Q_VALUE_FORMAT_32BIT_NATURAL			2
#define Q_VALUE_FORMAT_64BIT_NATURAL			3
#define Q_VALUE_FORMAT_128BIT_NATURAL			4
#define Q_VALUE_FORMAT_256BIT_NATURAL			5
#define Q_VALUE_FORMAT_512BIT_NATURAL			6
#define Q_VALUE_FORMAT_1024BIT_NATURAL			7
#define Q_VALUE_FORMAT_8BIT_INTEGER			8
#define Q_VALUE_FORMAT_16BIT_INTEGER			9
#define Q_VALUE_FORMAT_32BIT_INTEGER			10
#define Q_VALUE_FORMAT_64BIT_INTEGER			11
#define Q_VALUE_FORMAT_128BIT_INTEGER			12
#define Q_VALUE_FORMAT_256BIT_INTEGER			13
#define Q_VALUE_FORMAT_512BIT_INTEGER			14
#define Q_VALUE_FORMAT_1024BIT_INTEGER			15

#define Q_VALUE_FORMAT_16BIT_REAL_IEEE_754_BINARY	16
#define Q_VALUE_FORMAT_32BIT_REAL_IEEE_754_BINARY	17
#define Q_VALUE_FORMAT_64BIT_REAL_IEEE_754_BINARY	18
#define Q_VALUE_FORMAT_128BIT_REAL_IEEE_754_BINARY	19
#define Q_VALUE_FORMAT_32BIT_REAL_IEEE_754_DECIMAL	20
#define Q_VALUE_FORMAT_64BIT_REAL_IEEE_754_DECIMAL	21
#define Q_VALUE_FORMAT_128BIT_REAL_IEEE_754_DECIMAL	22

#define Q_VALUE_FORMAT_80BIT_REAL
#define Q_VALUE_FORMAT_96BIT_REAL
#define Q_VALUE_FORMAT_128BIT_REAL

#endif /* __Q_keys_formats_value_H__ */
