/* Zeta API - Z/inspection/C/modules/C89.h
 ______ ____________  ___
|__   /|  ___|__  __|/   \
  /  /_|  __|  |  | /  *  \
 /_____|_____| |__|/__/ \__\
Copyright (C) 2006-2022 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_inspection_C_modules_C89_H
#define Z_inspection_C_modules_C89_H

#include <Z/inspection/C/modules/C78.h>

#define Z_LANGUAGE_HAS_C89_CONSTANT_INITIALIZATION_FOR_LOCAL_AGGREGATE TRUE
#define Z_LANGUAGE_HAS_C89_CONSTANT_INITIALIZATION_FOR_UNION	       TRUE
#define Z_LANGUAGE_HAS_C89_CONSTRUCT_AS_FUNCTION_ARGUMENT	       TRUE
#define Z_LANGUAGE_HAS_C89_CONSTRUCT_RETURN			       TRUE
#define Z_LANGUAGE_HAS_C89_CONSTRUCT_ASSIGNMENT			       TRUE
#define Z_LANGUAGE_HAS_C89_CONSTRUCT_NAMESPACE			       TRUE
#define Z_LANGUAGE_HAS_C89_ENUMERATION				       TRUE
#define Z_LANGUAGE_HAS_C89_FUNCTION_POINTER_AUTODEREFERENCING	       TRUE
#define Z_LANGUAGE_HAS_C89_FUNCTION_PROTOTYPE			       TRUE
#define Z_LANGUAGE_HAS_C89_INTEGRAL_SWITCH			       TRUE
#define Z_LANGUAGE_HAS_C89_PREPROCESSOR_INDENTATION		       TRUE
#define Z_LANGUAGE_HAS_C89_REMOVAL_OF_ENTRY_AS_KEYWORD		       TRUE
#define Z_LANGUAGE_HAS_C89_REMOVAL_OF_LONG_FLOAT_AS_TYPE	       TRUE
#define Z_LANGUAGE_HAS_C89_STRING_LITERAL_CONCATENATION		       TRUE
#define Z_LANGUAGE_HAS_C89_TRIGRAPHS				       TRUE
#define Z_LANGUAGE_HAS_C89_VALUE_PRESERVING_UNSIGNED_CONVERSION	       TRUE
#define Z_LANGUAGE_HAS_C89_ESCAPE_SEQUENCE_ALERT		       TRUE
#define Z_LANGUAGE_HAS_C89_ESCAPE_SEQUENCE_HEXADECIMAL		       TRUE
#define Z_LANGUAGE_HAS_C89_ESCAPE_SEQUENCE_VERTICAL_TAB		       TRUE
#define Z_LANGUAGE_HAS_C89_LITERAL_FLOAT			       TRUE
#define Z_LANGUAGE_HAS_C89_LITERAL_UNSIGNED			       TRUE
#define Z_LANGUAGE_HAS_C89_LITERAL_WCHAR_T_CHARACTER		       TRUE
#define Z_LANGUAGE_HAS_C89_LITERAL_WCHAR_T_STRING		       TRUE
#define Z_LANGUAGE_HAS_C89_OPERATOR_UNARY_PLUS			       TRUE
#define Z_LANGUAGE_HAS_C89_PREPROCESSOR_DIRECTIVE_NULL		       TRUE
#define Z_LANGUAGE_HAS_C89_PREPROCESSOR_DIRECTIVE_ELIF		       TRUE
#define Z_LANGUAGE_HAS_C89_PREPROCESSOR_DIRECTIVE_ERROR		       TRUE
#define Z_LANGUAGE_HAS_C89_PREPROCESSOR_DIRECTIVE_LINE		       TRUE
#define Z_LANGUAGE_HAS_C89_PREPROCESSOR_DIRECTIVE_PRAGMA	       TRUE
#define Z_LANGUAGE_HAS_C89_PREPROCESSOR_OPERATOR_DEFINED	       TRUE
#define Z_LANGUAGE_HAS_C89_PREPROCESSOR_OPERATOR_PASTING	       TRUE
#define Z_LANGUAGE_HAS_C89_PREPROCESSOR_OPERATOR_STRINGIZING	       TRUE
#define Z_LANGUAGE_HAS_C89_TYPE_LONG_DOUBLE			       TRUE
#define Z_LANGUAGE_HAS_C89_TYPE_UNSIGNED_CHAR			       TRUE
#define Z_LANGUAGE_HAS_C89_TYPE_UNSIGNED_LONG			       TRUE
#define Z_LANGUAGE_HAS_C89_TYPE_UNSIGNED_SHORT			       TRUE
#define Z_LANGUAGE_HAS_C89_TYPE_VOID				       TRUE
#define Z_LANGUAGE_HAS_C89_TYPE_VOID_POINTER			       TRUE
#define Z_LANGUAGE_HAS_C89_TYPE_MODIFIER_SIGNED			       TRUE
#define Z_LANGUAGE_HAS_C89_TYPE_QUALIFIER_CONST			       TRUE
#define Z_LANGUAGE_HAS_C89_TYPE_QUALIFIER_VOLATILE		       TRUE

#endif /* Z_inspection_C_modules_C89_H */
