/* Zeta API - Z/inspection/C/modules/C89.h
 ______  ______________  ___
|__   / |  ___|___  ___|/   \
  /  /__|  __|   |  |  /  -  \
 /______|_____|  |__| /__/ \__\
Copyright (C) 2006-2024 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_inspection_C_modules_C89_H
#define Z_inspection_C_modules_C89_H

#include <Z/inspection/C/modules/C78.h>

#define Z_LANGUAGE_HAS_C89_CONSTANT_INITIALIZATION_FOR_LOCAL_AGGREGATE 1
#define Z_LANGUAGE_HAS_C89_CONSTANT_INITIALIZATION_FOR_UNION	       1
#define Z_LANGUAGE_HAS_C89_CONSTRUCT_AS_FUNCTION_ARGUMENT	       1
#define Z_LANGUAGE_HAS_C89_CONSTRUCT_RETURN			       1
#define Z_LANGUAGE_HAS_C89_CONSTRUCT_ASSIGNMENT			       1
#define Z_LANGUAGE_HAS_C89_CONSTRUCT_NAMESPACE			       1
#define Z_LANGUAGE_HAS_C89_ENUMERATION				       1
#define Z_LANGUAGE_HAS_C89_FUNCTION_POINTER_AUTODEREFERENCING	       1
#define Z_LANGUAGE_HAS_C89_FUNCTION_PROTOTYPE			       1
#define Z_LANGUAGE_HAS_C89_INTEGRAL_SWITCH			       1
#define Z_LANGUAGE_HAS_C89_PREPROCESSOR_INDENTATION		       1
#define Z_LANGUAGE_HAS_C89_REMOVAL_OF_ENTRY_AS_KEYWORD		       1
#define Z_LANGUAGE_HAS_C89_REMOVAL_OF_LONG_FLOAT_AS_TYPE	       1
#define Z_LANGUAGE_HAS_C89_STRING_LITERAL_CONCATENATION		       1
#define Z_LANGUAGE_HAS_C89_TRIGRAPHS				       1
#define Z_LANGUAGE_HAS_C89_VALUE_PRESERVING_UNSIGNED_CONVERSION	       1
#define Z_LANGUAGE_HAS_C89_ESCAPE_SEQUENCE_ALERT		       1
#define Z_LANGUAGE_HAS_C89_ESCAPE_SEQUENCE_HEXADECIMAL		       1
#define Z_LANGUAGE_HAS_C89_ESCAPE_SEQUENCE_VERTICAL_TAB		       1
#define Z_LANGUAGE_HAS_C89_LITERAL_FLOAT			       1
#define Z_LANGUAGE_HAS_C89_LITERAL_UNSIGNED			       1
#define Z_LANGUAGE_HAS_C89_LITERAL_WCHAR_T_CHARACTER		       1
#define Z_LANGUAGE_HAS_C89_LITERAL_WCHAR_T_STRING		       1
#define Z_LANGUAGE_HAS_C89_OPERATOR_UNARY_PLUS			       1
#define Z_LANGUAGE_HAS_C89_PREPROCESSOR_DIRECTIVE_NULL		       1
#define Z_LANGUAGE_HAS_C89_PREPROCESSOR_DIRECTIVE_ELIF		       1
#define Z_LANGUAGE_HAS_C89_PREPROCESSOR_DIRECTIVE_ERROR		       1
#define Z_LANGUAGE_HAS_C89_PREPROCESSOR_DIRECTIVE_LINE		       1
#define Z_LANGUAGE_HAS_C89_PREPROCESSOR_DIRECTIVE_PRAGMA	       1
#define Z_LANGUAGE_HAS_C89_PREPROCESSOR_OPERATOR_DEFINED	       1
#define Z_LANGUAGE_HAS_C89_PREPROCESSOR_OPERATOR_PASTING	       1
#define Z_LANGUAGE_HAS_C89_PREPROCESSOR_OPERATOR_STRINGIZING	       1
#define Z_LANGUAGE_HAS_C89_TYPE_LONG_DOUBLE			       1
#define Z_LANGUAGE_HAS_C89_TYPE_UNSIGNED_CHAR			       1
#define Z_LANGUAGE_HAS_C89_TYPE_UNSIGNED_LONG			       1
#define Z_LANGUAGE_HAS_C89_TYPE_UNSIGNED_SHORT			       1
#define Z_LANGUAGE_HAS_C89_TYPE_VOID				       1
#define Z_LANGUAGE_HAS_C89_TYPE_VOID_POINTER			       1
#define Z_LANGUAGE_HAS_C89_TYPE_MODIFIER_SIGNED			       1
#define Z_LANGUAGE_HAS_C89_TYPE_QUALIFIER_CONST			       1
#define Z_LANGUAGE_HAS_C89_TYPE_QUALIFIER_VOLATILE		       1

#endif /* Z_inspection_C_modules_C89_H */
