/* Z Kit - inspection/C/modules/C89.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//___/_| Kit
Copyright (C) 2006-2019 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_inspection_C_modules_C89_H
#define Z_inspection_C_modules_C89_H

#include <Z/inspection/C/modules/KR C.h>

#define Z_C_HAS_C89_RULES_ON_TYPE_CONVERSION	       TRUE
#define Z_C_HAS_CONSTRUCT_AS_FUNCTION_ARGUMENT	       TRUE
#define Z_C_HAS_CONSTRUCT_AS_RETURN_TYPE	       TRUE
#define Z_C_HAS_CONSTRUCT_ASSIGNMENT		       TRUE
#define Z_C_HAS_CONSTRUCT_NAMESPACE		       TRUE
#define Z_C_HAS_ENUMERATION			       TRUE
#define Z_C_HAS_FUNCTION_POINTER_AUTODEREFERENCING     TRUE
#define Z_C_HAS_FUNCTION_PROTOTYPE		       TRUE
#define Z_C_HAS_INTEGRAL_SWITCH			       TRUE
#define Z_C_HAS_LOCAL_AGGREGATE_CONSTANT_INITIALZATION TRUE
#define Z_C_HAS_PREPROCESSOR_INDENTATION	       TRUE
#define Z_C_HAS_REMOVAL_OF_ENTRY_AS_KEYWORD	       TRUE
#define Z_C_HAS_REMOVAL_OF_LONG_FLOAT_AS_TYPE	       TRUE
#define Z_C_HAS_STRING_LITERAL_CONCATENATION	       TRUE
#define Z_C_HAS_TRIGRAPHS			       TRUE
#define Z_C_HAS_UNION_CONSTANT_INITIALIZATION	       TRUE
#define Z_C_HAS_ESCAPE_SEQUENCE_ALERT		       TRUE
#define Z_C_HAS_ESCAPE_SEQUENCE_HEXADECIMAL	       TRUE
#define Z_C_HAS_ESCAPE_SEQUENCE_VERTICAL_TAB	       TRUE
#define Z_C_HAS_LITERAL_FLOAT			       TRUE
#define Z_C_HAS_LITERAL_LONG_DOUBLE		       TRUE
#define Z_C_HAS_LITERAL_UNSIGNED		       TRUE
#define Z_C_HAS_OPERATOR_UNARY_PLUS		       TRUE
#define Z_C_HAS_PREPROCESSOR_DIRECTIVE_NULL	       TRUE
#define Z_C_HAS_PREPROCESSOR_DIRECTIVE_ELIF	       TRUE
#define Z_C_HAS_PREPROCESSOR_DIRECTIVE_ERROR	       TRUE
#define Z_C_HAS_PREPROCESSOR_DIRECTIVE_LINE	       TRUE
#define Z_C_HAS_PREPROCESSOR_DIRECTIVE_PRAGMA	       TRUE
#define Z_C_HAS_PREPROCESSOR_OPERATOR_DEFINED	       TRUE
#define Z_C_HAS_PREPROCESSOR_OPERATOR_PASTING	       TRUE
#define Z_C_HAS_PREPROCESSOR_OPERATOR_STRINGIZING      TRUE
#define Z_C_HAS_TYPE_LONG_DOUBLE		       TRUE
#define Z_C_HAS_TYPE_UNSIGNED_CHAR		       TRUE
#define Z_C_HAS_TYPE_UNSIGNED_LONG		       TRUE
#define Z_C_HAS_TYPE_UNSIGNED_SHORT		       TRUE
#define Z_C_HAS_TYPE_VOID			       TRUE
#define Z_C_HAS_TYPE_VOID_POINTER		       TRUE
#define Z_C_HAS_TYPE_MODIFIER_SIGNED		       TRUE
#define Z_C_HAS_TYPE_QUALIFIER_CONST		       TRUE
#define Z_C_HAS_TYPE_QUALIFIER_VOLATILE		       TRUE

#endif /* Z_inspection_C_modules_C89_H */
