/* Z Kit - inspection/compiler/modules/Clang.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_inspection_compiler_modules_MSVC_H

/* MARK: - Identification */

#define Z_COMPILER_NAME Z_COMPILER_NAME_MSVC

#if _MSC_VER == 800
#	define Z_COMPILER_VERSION Z_VERSION(1,0,0)

#elif _MSC_VER == 900
#	define Z_COMPILER_VERSION Z_VERSION(2,0,0)

#elif _MSC_VER == 1000 /* Developer Studio v4.0 */
#	define Z_COMPILER_VERSION Z_VERSION(4,0,0)

#elif _MSC_VER == 1020 /* Developer Studio v4.2 */
#	define Z_COMPILER_VERSION Z_VERSION(4,2,0)

#elif _MSC_VER == 1100 /* Visual Studio 97 v5.0 */
#	define Z_COMPILER_VERSION Z_VERSION(5,0,0)

#elif _MSC_VER == 1200 /* Visual Studio 6.0 v6.0 */
#	define Z_COMPILER_VERSION Z_VERSION(6,0,0)

#elif _MSC_VER == 1300 /* Visual Studio .NET 2002 v7.0 */
#	define Z_COMPILER_VERSION Z_VERSION(7,0,0)

#elif _MSC_VER == 1310 /* Visual Studio .NET 2003 v7.1 */
#	define Z_COMPILER_VERSION Z_VERSION(7,1,0)

#elif _MSC_VER == 1400 /* Visual Studio 2005 v8.0 */
#	define Z_COMPILER_VERSION Z_VERSION(8,0,0)

#elif _MSC_VER == 1500 /* Visual Studio 2008 v9.0 */
#	define Z_COMPILER_VERSION Z_VERSION(9,0,0)

#elif _MSC_VER == 1600 /* Visual Studio 2010 v10.0 */
#	define Z_COMPILER_VERSION Z_VERSION(10,0,0)

#elif _MSC_VER == 1700 /* Visual Studio 2012 v11.0 */
#	define Z_COMPILER_VERSION Z_VERSION(11,0,0)

#elif _MSC_VER == 1800 /* Visual Studio 2013 v12.0 */
#	define Z_COMPILER_VERSION Z_VERSION(12,0,0)

#elif _MSC_VER == 1900 /* Visual Studio 2015 v14.0 */
#	define Z_COMPILER_VERSION Z_VERSION(14,0,0)

#elif _MSC_VER == 1910 /* Visual Studio 2017 v15.0 */
#	define Z_COMPILER_VERSION Z_VERSION(14,1,0)

#elif _MSC_VER == 1911 /* Visual Studio 2017 v15.3 */
#	define Z_COMPILER_VERSION Z_VERSION(14,11,0)

#elif _MSC_VER == 1912 /* Visual Studio 2017 v15.5 */
#	define Z_COMPILER_VERSION Z_VERSION(14,12,0)

#elif _MSC_VER == 1913 /* Visual Studio 2017 v15.6 */
#	define Z_COMPILER_VERSION Z_VERSION(14,13,0)

#elif _MSC_VER == 1914 /* Visual Studio 2017 v15.7 */
#	define Z_COMPILER_VERSION Z_VERSION(14,14,0)

#elif _MSC_VER == 1915 /* Visual Studio 2017 v15.8 */
#	define Z_COMPILER_VERSION Z_VERSION(14,15,0)

#elif _MSC_VER == 1916 /* Visual Studio 2017 v15.9 */
#	define Z_COMPILER_VERSION Z_VERSION(14,16,0)

#elif _MSC_VER == 1920 /* Visual Studio 2019 v16.0 */
#	define Z_COMPILER_VERSION Z_VERSION(14,2,0)

#elif _MSC_VER == 1921 /* Visual Studio 2019 v16.1 */
#	define Z_COMPILER_VERSION Z_VERSION(14,21,0)

#elif _MSC_VER == 1922 /* Visual Studio 2019 v16.2 */
#	define Z_COMPILER_VERSION Z_VERSION(14,22,0)

#elif _MSC_VER == 1923 /* Visual Studio 2019 v16.3 */
#	define Z_COMPILER_VERSION Z_VERSION(14,23,0)
#endif

/* MARK: - ISA */

/*#define Z_COMPILER_ISA*/

/* MARK: - ISA: Integral endianness */

/*#define Z_COMPILER_ISA_INTEGRAL_ENDIANNESS_ALL*/
/*#define Z_COMPILER_ISA_INTEGRAL_ENDIANNESS_8BIT*/
/*#define Z_COMPILER_ISA_INTEGRAL_ENDIANNESS_16BIT*/
/*#define Z_COMPILER_ISA_INTEGRAL_ENDIANNESS_24BIT*/
/*#define Z_COMPILER_ISA_INTEGRAL_ENDIANNESS_32BIT*/
/*#define Z_COMPILER_ISA_INTEGRAL_ENDIANNESS_40BIT*/
/*#define Z_COMPILER_ISA_INTEGRAL_ENDIANNESS_48BIT*/
/*#define Z_COMPILER_ISA_INTEGRAL_ENDIANNESS_56BIT*/
/*#define Z_COMPILER_ISA_INTEGRAL_ENDIANNESS_64BIT*/
/*#define Z_COMPILER_ISA_INTEGRAL_ENDIANNESS_128BIT*/

/* MARK: - ISA: Integer format */

/*#define Z_COMPILER_ISA_INTEGER_FORMAT_ALL*/
/*#define Z_COMPILER_ISA_INTEGER_FORMAT_8BIT*/
/*#define Z_COMPILER_ISA_INTEGER_FORMAT_16BIT*/
/*#define Z_COMPILER_ISA_INTEGER_FORMAT_24BIT*/
/*#define Z_COMPILER_ISA_INTEGER_FORMAT_32BIT*/
/*#define Z_COMPILER_ISA_INTEGER_FORMAT_40BIT*/
/*#define Z_COMPILER_ISA_INTEGER_FORMAT_48BIT*/
/*#define Z_COMPILER_ISA_INTEGER_FORMAT_56BIT*/
/*#define Z_COMPILER_ISA_INTEGER_FORMAT_64BIT*/
/*#define Z_COMPILER_ISA_INTEGER_FORMAT_128BIT*/

/* MARK: - Platform */

/*#define Z_COMPILER_PLATFORM*/

/* MARK: - OS */

/*#define Z_COMPIER_OS*/

/* MARK: - Bit field order */

/*#define Z_COMPILER_BIT_FIELD_ORDER_ALL*/
/*#define Z_COMPILER_BIT_FIELD_ORDER_8BIT*/
/*#define Z_COMPILER_BIT_FIELD_ORDER_16BIT*/
/*#define Z_COMPILER_BIT_FIELD_ORDER_32BIT*/
/*#define Z_COMPILER_BIT_FIELD_ORDER_64BIT*/
/*#define Z_COMPILER_BIT_FIELD_ORDER_128BIT*/

/* MARK: - Data model */

/*#define Z_COMPILER_DATA_MODEL*/

/* MARK: - Floating-point */

/*#define Z_COMPILER_FIXED_FUNDAMENTAL_FLOAT*/
/*#define Z_COMPILER_FIXED_FUNDAMENTAL_DOUBLE*/
/*#define Z_COMPILER_FIXED_FUNDAMENTAL_LDOUBLE*/
/*#define Z_COMPILER_FIXED_FUNDAMENTAL_FLOAT32X*/
/*#define Z_COMPILER_FIXED_FUNDAMENTAL_FLOAT64X*/
/*#define Z_COMPILER_FIXED_FUNDAMENTAL_FLOAT128X*/
/*#define Z_COMPILER_FIXED_FUNDAMENTAL_DECIMAL64X*/
/*#define Z_COMPILER_FIXED_FUNDAMENTAL_DECIMAL128X*/

/* MARK: - Language: K&R C */

/*#define Z_COMPILER_C_HAS_OLD_STYLE_FUNCTION*/
/*#define Z_COMPILER_C_HAS_OPERATOR_SIZEOF*/
/*#define Z_COMPILER_C_HAS_STORAGE_CLASS_AUTO*/
/*#define Z_COMPILER_C_HAS_STORAGE_CLASS_EXTERN*/
/*#define Z_COMPILER_C_HAS_STORAGE_CLASS_REGISTER*/
/*#define Z_COMPILER_C_HAS_STORAGE_CLASS_STATIC*/
/*#define Z_COMPILER_C_HAS_TYPE_DOUBLE*/
/*#define Z_COMPILER_C_HAS_TYPE_FLOAT*/

/* MARK: - Language: C89 */

/*#define Z_COMPILER_C_HAS_CONSTANT_INITIALIZATION_FOR_LOCAL_AGGREGATE*/
/*#define Z_COMPILER_C_HAS_CONSTANT_INITIALIZATION_FOR_UNION*/
/*#define Z_COMPILER_C_HAS_CONSTRUCT_AS_FUNCTION_ARGUMENT*/
/*#define Z_COMPILER_C_HAS_CONSTRUCT_RETURN*/
/*#define Z_COMPILER_C_HAS_CONSTRUCT_ASSIGNMENT*/
/*#define Z_COMPILER_C_HAS_CONSTRUCT_NAMESPACE*/
/*#define Z_COMPILER_C_HAS_ENUMERATION*/
/*#define Z_COMPILER_C_HAS_FUNCTION_POINTER_AUTODEREFERENCING*/
/*#define Z_COMPILER_C_HAS_FUNCTION_PROTOTYPE*/
/*#define Z_COMPILER_C_HAS_INTEGRAL_SWITCH*/
/*#define Z_COMPILER_C_HAS_PREPROCESSOR_INDENTATION*/
/*#define Z_COMPILER_C_HAS_REMOVAL_OF_ENTRY_AS_KEYWORD*/
/*#define Z_COMPILER_C_HAS_REMOVAL_OF_LONG_FLOAT_AS_TYPE*/
/*#define Z_COMPILER_C_HAS_STRING_LITERAL_CONCATENATION*/
/*#define Z_COMPILER_C_HAS_TRIGRAPHS*/
/*#define Z_COMPILER_C_HAS_VALUE_PRESERVING_UNSIGNED_CONVERSION*/
/*#define Z_COMPILER_C_HAS_ESCAPE_SEQUENCE_ALERT*/
/*#define Z_COMPILER_C_HAS_ESCAPE_SEQUENCE_HEXADECIMAL*/
/*#define Z_COMPILER_C_HAS_ESCAPE_SEQUENCE_VERTICAL_TAB*/
/*#define Z_COMPILER_C_HAS_LITERAL_FLOAT*/
/*#define Z_COMPILER_C_HAS_LITERAL_LONG_DOUBLE*/
/*#define Z_COMPILER_C_HAS_LITERAL_UNSIGNED*/
/*#define Z_COMPILER_C_HAS_LITERAL_WCHAR_T_CHARACTER*/
/*#define Z_COMPILER_C_HAS_LITERAL_WCHAR_T_STRING*/
/*#define Z_COMPILER_C_HAS_OPERATOR_UNARY_PLUS*/
/*#define Z_COMPILER_C_HAS_PREPROCESSOR_DIRECTIVE_NULL*/
/*#define Z_COMPILER_C_HAS_PREPROCESSOR_DIRECTIVE_ELIF*/
/*#define Z_COMPILER_C_HAS_PREPROCESSOR_DIRECTIVE_ERROR*/
/*#define Z_COMPILER_C_HAS_PREPROCESSOR_DIRECTIVE_LINE*/
/*#define Z_COMPILER_C_HAS_PREPROCESSOR_DIRECTIVE_PRAGMA*/
/*#define Z_COMPILER_C_HAS_PREPROCESSOR_OPERATOR_DEFINED*/
/*#define Z_COMPILER_C_HAS_PREPROCESSOR_OPERATOR_PASTING*/
/*#define Z_COMPILER_C_HAS_PREPROCESSOR_OPERATOR_STRINGIZING*/
/*#define Z_COMPILER_C_HAS_TYPE_LONG_DOUBLE*/
/*#define Z_COMPILER_C_HAS_TYPE_UNSIGNED_CHAR*/
/*#define Z_COMPILER_C_HAS_TYPE_UNSIGNED_LONG*/
/*#define Z_COMPILER_C_HAS_TYPE_UNSIGNED_SHORT*/
/*#define Z_COMPILER_C_HAS_TYPE_VOID*/
/*#define Z_COMPILER_C_HAS_TYPE_VOID_POINTER*/
/*#define Z_COMPILER_C_HAS_TYPE_MODIFIER_SIGNED*/
/*#define Z_COMPILER_C_HAS_TYPE_QUALIFIER_CONST*/
/*#define Z_COMPILER_C_HAS_TYPE_QUALIFIER_VOLATILE*/

/* MARK: - Language: C95 */

/*#define Z_COMPILER_C_HAS_DIGRAPHS*/

/* MARK: - Language: C99 */

/*#define Z_COMPILER_C_HAS_COMPOUND_LITERAL*/
/*#define Z_COMPILER_C_HAS_CONVERSION_OF_NON_LVALUE_ARRAY_TO_POINTER*/
/*#define Z_COMPILER_C_HAS_CPP_STYLE_COMMENT*/
/*#define Z_COMPILER_C_HAS_DESIGNATED_INITIALIZATION*/
/*#define Z_COMPILER_C_HAS_EMPTY_MACRO_ARGUMENT*/
/*#define Z_COMPILER_C_HAS_EXTENDED_IDENTIFIER*/
/*#define Z_COMPILER_C_HAS_FLEXIBLE_ARRAY_MEMBER*/
/*#define Z_COMPILER_C_HAS_FOR_WITH_DECLARATION*/
/*#define Z_COMPILER_C_HAS_IDEMPOTENT_TYPE_QUALIFIERS*/
/*#define Z_COMPILER_C_HAS_MIXED_DECLARATIONS_AND_CODE*/
/*#define Z_COMPILER_C_HAS_NON_CONSTANT_INITIALIZATION_FOR_LOCAL_AGGREGATE*/
/*#define Z_COMPILER_C_HAS_PREPROCESSOR_ARITHMETIC_DONE_IN_INTMAX*/
/*#define Z_COMPILER_C_HAS_RELIABLE_INTEGER_DIVISION*/
/*#define Z_COMPILER_C_HAS_REMOVAL_OF_ILL_FORMED_RETURN*/
/*#define Z_COMPILER_C_HAS_REMOVAL_OF_IMPLICIT_FUNCTION_DECLARATION*/
/*#define Z_COMPILER_C_HAS_REMOVAL_OF_IMPLICIT_INT*/
/*#define Z_COMPILER_C_HAS_STATIC_IN_ARRAY_PARAMETER_DECLARATION*/
/*#define Z_COMPILER_C_HAS_TRAILING_COMMA_ALLOWED_IN_ENUMERATION*/
/*#define Z_COMPILER_C_HAS_TYPE_QUALIFIERS_IN_ARRAY_PARAMETER_DECLARATION*/
/*#define Z_COMPILER_C_HAS_UNIVERSAL_CHARACTER_NAME*/
/*#define Z_COMPILER_C_HAS_VARIADIC_MACRO*/
/*#define Z_COMPILER_C_HAS_VLA*/
/*#define Z_COMPILER_C_HAS_IDENTIFIER_FUNC*/
/*#define Z_COMPILER_C_HAS_LITERAL_HEXADECIMAL_FLOATING_POINT*/
/*#define Z_COMPILER_C_HAS_PREPROCESSOR_OPERATOR_PRAGMA*/
/*#define Z_COMPILER_C_HAS_SPECIFIER_INLINE*/
/*#define Z_COMPILER_C_HAS_STANDARD_PRAGMA_CX_LIMITED_RANGE*/
/*#define Z_COMPILER_C_HAS_STANDARD_PRAGMA_FENV_ACCESS*/
/*#define Z_COMPILER_C_HAS_STANDARD_PRAGMA_FP_CONTRACT*/
/*#define Z_COMPILER_C_HAS_TYPE_BOOL*/
/*#define Z_COMPILER_C_HAS_TYPE_DOUBLE_COMPLEX*/
/*#define Z_COMPILER_C_HAS_TYPE_DOUBLE_IMAGINARY*/
/*#define Z_COMPILER_C_HAS_TYPE_FLOAT_COMPLEX*/
/*#define Z_COMPILER_C_HAS_TYPE_FLOAT_IMAGINARY*/
/*#define Z_COMPILER_C_HAS_TYPE_LONG_DOUBLE_COMPLEX*/
/*#define Z_COMPILER_C_HAS_TYPE_LONG_DOUBLE_IMAGINARY*/
/*#define Z_COMPILER_C_HAS_TYPE_LONG_LONG*/
/*#define Z_COMPILER_C_HAS_TYPE_QUALIFIER_RESTRICT*/
/*#define Z_COMPILER_C_HAS_TYPE_MODIFIER_COMPLEX*/
/*#define Z_COMPILER_C_HAS_TYPE_MODIFIER_IMAGINARY*/

/* MARK: - Language: C11 */

/*#define Z_COMPILER_C_HAS_ANONYMOUS_STRUCTURE_AS_MEMBER*/
/*#define Z_COMPILER_C_HAS_ANONYMOUS_UNION_AS_MEMBER*/
/*#define Z_COMPILER_C_HAS_GENERIC_SELECTION*/
/*#define Z_COMPILER_C_HAS_STATIC_ASSERTION*/
/*#define Z_COMPILER_C_HAS_TYPEDEF_REDECLARATION*/
/*#define Z_COMPILER_C_HAS_LITERAL_CHAR16_T_CHARACTER*/
/*#define Z_COMPILER_C_HAS_LITERAL_CHAR16_T_STRING*/
/*#define Z_COMPILER_C_HAS_LITERAL_CHAR32_T_CHARACTER*/
/*#define Z_COMPILER_C_HAS_LITERAL_CHAR32_T_STRING*/
/*#define Z_COMPILER_C_HAS_LITERAL_UTF8_STRING*/
/*#define Z_COMPILER_C_HAS_OPERATOR_ALIGNOF*/
/*#define Z_COMPILER_C_HAS_SPECIFIER_ALIGNAS*/
/*#define Z_COMPILER_C_HAS_SPECIFIER_NORETURN*/
/*#define Z_COMPILER_C_HAS_STORAGE_CLASS_THREAD_LOCAL*/
/*#define Z_COMPILER_C_HAS_TYPE_MODIFIER_ATOMIC*/
/*#define Z_COMPILER_C_HAS_TYPE_QUALIFIER_ATOMIC*/

/* MARK: - Language: Apple C extensions */

/*#define Z_COMPILER_C_HAS_BLOCK_OBJECT*/

/*#ifdef __cplusplus*/

	/* MARK: - Language: C++98 */

/*#	define Z_COMPILER_CPP_HAS_SFINAE*/
/*#	define Z_COMPILER_CPP_HAS_TYPE_BOOL*/
/*#	define Z_COMPILER_CPP_HAS_TYPE_WCHAR_T*/

	/* MARK: - Language: C++03 */

/*#	define Z_COMPILER_CPP_HAS_VALUE_INITIALIZATION*/

	/* MARK: - Language: C++11 */

/*#	define Z_COMPILER_CPP_HAS_C99_PREPROCESSOR*/
/*#	define Z_COMPILER_CPP_HAS_COPY_LIST_INITIALIZATION*/
/*#	define Z_COMPILER_CPP_HAS_CPP11_UNIVERSAL_CHARACTER_NAME*/
/*#	define Z_COMPILER_CPP_HAS_DEFAULT_MEMBER_INITIALIZER*/
/*#	define Z_COMPILER_CPP_HAS_DEFAULT_TEMPLATE_ARGUMENTS_FOR_FUNCTION_TEMPLATE*/
/*#	define Z_COMPILER_CPP_HAS_DELEGATING_CONSTRUCTORS*/
/*#	define Z_COMPILER_CPP_HAS_DELETED_FUNCTION*/
/*#	define Z_COMPILER_CPP_HAS_DIRECT_LIST_INITIALIZATION*/
/*#	define Z_COMPILER_CPP_HAS_EXPLICIT_CONVERSION_OPERATOR*/
/*#	define Z_COMPILER_CPP_HAS_EXPLICITLY_DEFAULTED_SPECIAL_MEMBER_FUNCTION*/
/*#	define Z_COMPILER_CPP_HAS_EXPRESSION_SFINAE*/
/*#	define Z_COMPILER_CPP_HAS_EXTENDED_FRIEND_DECLARATION*/
/*#	define Z_COMPILER_CPP_HAS_EXTENDED_VARIADIC_TEMPLATE_TEMPLATE_PARAMETERS*/
/*#	define Z_COMPILER_CPP_HAS_EXTERN_TEMPLATE*/
/*#	define Z_COMPILER_CPP_HAS_FIXED_ENUMERATION*/
/*#	define Z_COMPILER_CPP_HAS_INHERITING_CONSTRUCTORS*/
/*#	define Z_COMPILER_CPP_HAS_INITIALIZATION_OF_CLASS_OBJECT_BY_RVALUE*/
/*#	define Z_COMPILER_CPP_HAS_INITIALIZER_LIST*/
/*#	define Z_COMPILER_CPP_HAS_INLINE_NAMESPACE*/
/*#	define Z_COMPILER_CPP_HAS_LAMBDA*/
/*#	define Z_COMPILER_CPP_HAS_LOCAL_TYPE_AS_TEMPLATE_ARGUMENT*/
/*#	define Z_COMPILER_CPP_HAS_MOVE_SPECIAL_MEMBER_FUNCTIONS*/
/*#	define Z_COMPILER_CPP_HAS_MULTI_DECLARATOR_AUTO*/
/*#	define Z_COMPILER_CPP_HAS_OPAQUE_ENUMERATION_DECLARATION*/
/*#	define Z_COMPILER_CPP_HAS_RANGE_BASED_FOR*/
/*#	define Z_COMPILER_CPP_HAS_REFERENCE_QUALIFIED_NON_STATIC_MEMBER_FUNCTION*/
/*#	define Z_COMPILER_CPP_HAS_REMOVAL_OF_AUTO_AS_STORAGE_CLASS*/
/*#	define Z_COMPILER_CPP_HAS_RIGHT_ANGLE_BRACKETS*/
/*#	define Z_COMPILER_CPP_HAS_RVALUE_REFERENCE*/
/*#	define Z_COMPILER_CPP_HAS_SCOPED_ENUMERATION*/
/*#	define Z_COMPILER_CPP_HAS_STANDARD_LAYOUT*/
/*#	define Z_COMPILER_CPP_HAS_STANDARDIZED_ATTRIBUTE_SYNTAX*/
/*#	define Z_COMPILER_CPP_HAS_STATIC_ASSERTION*/
/*#	define Z_COMPILER_CPP_HAS_THREAD_SAFFE_STATIC_INITIALIZATION*/
/*#	define Z_COMPILER_CPP_HAS_TRAILING_COMMA_ALLOWED_IN_ENUMERATION*/
/*#	define Z_COMPILER_CPP_HAS_TRAILING_RETURN_TYPE*/
/*#	define Z_COMPILER_CPP_HAS_TYPE_ALIAS*/
/*#	define Z_COMPILER_CPP_HAS_TYPE_ALIAS_TEMPLATE*/
/*#	define Z_COMPILER_CPP_HAS_UNNAMED_TYPE_AS_TEMPLATE_ARGUMENT*/
/*#	define Z_COMPILER_CPP_HAS_UNRESTRICTED_UNION*/
/*#	define Z_COMPILER_CPP_HAS_VARIADIC_TEMPLATE*/
/*#	define Z_COMPILER_CPP_HAS_ATTRIBUTE_CARRIES_DEPENDENCY*/
/*#	define Z_COMPILER_CPP_HAS_ATTRIBUTE_NORETURN*/
/*#	define Z_COMPILER_CPP_HAS_IDENTIFIER_FUNC*/
/*#	define Z_COMPILER_CPP_HAS_LITERAL_NULLPTR*/
/*#	define Z_COMPILER_CPP_HAS_LITERAL_RAW_STRING*/
/*#	define Z_COMPILER_CPP_HAS_LITERAL_USER_DEFINED*/
/*#	define Z_COMPILER_CPP_HAS_LITERAL_UTF8_STRING*/
/*#	define Z_COMPILER_CPP_HAS_OPERATOR_ALIGNOF*/
/*#	define Z_COMPILER_CPP_HAS_OPERATOR_NOEXCEPT*/
/*#	define Z_COMPILER_CPP_HAS_OPERATOR_CASE_SIZEOF_NON_STATIC_DATA_MEMBER*/
/*#	define Z_COMPILER_CPP_HAS_OPERATOR_CASE_SIZEOF_PARAMETER_PACK*/
/*#	define Z_COMPILER_CPP_HAS_SPECIFIER_ALIGNAS*/
/*#	define Z_COMPILER_CPP_HAS_SPECIFIER_CONSTEXPR*/
/*#	define Z_COMPILER_CPP_HAS_SPECIFIER_DECLTYPE*/
/*#	define Z_COMPILER_CPP_HAS_SPECIFIER_FINAL*/
/*#	define Z_COMPILER_CPP_HAS_SPECIFIER_NOEXCEPT*/
/*#	define Z_COMPILER_CPP_HAS_SPECIFIER_OVERRIDE*/
/*#	define Z_COMPILER_CPP_HAS_SPECIFIER_CASE_DECLTYPE_INCOMPLETE_RETURN_TYPE*/
/*#	define Z_COMPILER_CPP_HAS_STORAGE_CLASS_THREAD_LOCAL*/
/*#	define Z_COMPILER_CPP_HAS_TYPE_AUTO*/
/*#	define Z_COMPILER_CPP_HAS_TYPE_CHAR16_T*/
/*#	define Z_COMPILER_CPP_HAS_TYPE_CHAR32_T*/
/*#	define Z_COMPILER_CPP_HAS_TYPE_LONG_LONG*/

	/* MARK: - Language: C++14 */

/*#	define Z_COMPILER_CPP_HAS_APOSTROPHE_AS_DIGIT_SEPARATOR*/
/*#	define Z_COMPILER_CPP_HAS_CPP14_CONSTEXPR_FUNCTION*/
/*#	define Z_COMPILER_CPP_HAS_CPP14_CONTEXTUAL_CONVERSION*/
/*#	define Z_COMPILER_CPP_HAS_DEFAULT_MEMBER_INITIALIZER_FOR_AGGREGATE*/
/*#	define Z_COMPILER_CPP_HAS_GENERIC_LAMBDA*/
/*#	define Z_COMPILER_CPP_HAS_INITIALIZED_LAMBDA_CAPTURE*/
/*#	define Z_COMPILER_CPP_HAS_RETURN_TYPE_DEDUCTION_FOR_NORMAL_FUNCTION*/
/*#	define Z_COMPILER_CPP_HAS_SIZED_DEALLOCATION*/
/*#	define Z_COMPILER_CPP_HAS_VARIABLE_TEMPLATE*/
/*#	define Z_COMPILER_CPP_HAS_ATTRIBUTE_DEPRECATED*/
/*#	define Z_COMPILER_CPP_HAS_LITERAL_BINARY_INTEGRAL*/
/*#	define Z_COMPILER_CPP_HAS_SPECIFIER_CASE_DECLTYPE_AUTO*/

	/* MARK: - Language: C++17 */

/*#	define Z_COMPILER_CPP_HAS_AGGREGATE_INITIALIZATION_FOR_DERIVED_CLASS*/
/*#	define Z_COMPILER_CPP_HAS_ATTRIBUTES_FOR_ENUMERATION*/
/*#	define Z_COMPILER_CPP_HAS_ATTRIBUTES_FOR_NAMESPACE*/
/*#	define Z_COMPILER_CPP_HAS_ATTRIBUTE_USING_PREFIX*/
/*#	define Z_COMPILER_CPP_HAS_CONSTEXPR_IF*/
/*#	define Z_COMPILER_CPP_HAS_CONSTEXPR_LAMBDA*/
/*#	define Z_COMPILER_CPP_HAS_CPP17_AUTO_DEDUCTION_FROM_LIST_INITIALIZATION*/
/*#	define Z_COMPILER_CPP_HAS_CPP17_EXPRESSION_EVALUATION_ORDER*/
/*#	define Z_COMPILER_CPP_HAS_CPP17_INHERITING_CONSTRUCTORS*/
/*#	define Z_COMPILER_CPP_HAS_CPP17_NON_TYPE_TEMPLATE_ARGUMENTS*/
/*#	define Z_COMPILER_CPP_HAS_CPP17_TEMPLATE_TEMPLATE_ARGUMENT_MATCHING*/
/*#	define Z_COMPILER_CPP_HAS_DEDUCTION_GUIDES_FOR_CLASS_TEMPLATE*/
/*#	define Z_COMPILER_CPP_HAS_DIFFERING_BEGIN_AND_END_TYPES_IN_RANGE_BASED_FOR*/
/*#	define Z_COMPILER_CPP_HAS_DIRECT_LIST_INITIALIZATION_FOR_FIXED_ENUMERATION*/
/*#	define Z_COMPILER_CPP_HAS_FOLD_EXPRESSION*/
/*#	define Z_COMPILER_CPP_HAS_GUARANTEED_COPY_ELISION*/
/*#	define Z_COMPILER_CPP_HAS_IF_WITH_INITIALIZER*/
/*#	define Z_COMPILER_CPP_HAS_IGNORING_OF_UNKNOWN_ATTRIBUTES*/
/*#	define Z_COMPILER_CPP_HAS_INLINE_VARIABLE*/
/*#	define Z_COMPILER_CPP_HAS_LAMBDA_CAPTURE_OF_STAR_THIS_BY_VALUE*/
/*#	define Z_COMPILER_CPP_HAS_NESTED_NAMESPACE_DEFINITION*/
/*#	define Z_COMPILER_CPP_HAS_NOEXCEPT_AS_PART_OF_THE_FUNCTION_TYPE*/
/*#	define Z_COMPILER_CPP_HAS_NON_TYPE_TEMPLATE_PARAMETER_WITH_AUTO_TYPE*/
/*#	define Z_COMPILER_CPP_HAS_OVER_ALIGNED_DYNAMIC_MEMORY_ALLOCATION*/
/*#	define Z_COMPILER_CPP_HAS_REMOVAL_OF_DYNAMIC_EXCEPTION_SPECIFICATION*/
/*#	define Z_COMPILER_CPP_HAS_REMOVAL_OF_BOOL_INCREMENT*/
/*#	define Z_COMPILER_CPP_HAS_REMOVAL_OF_REGISTER_AS_STORAGE_CLASS*/
/*#	define Z_COMPILER_CPP_HAS_REMOVAL_OF_TRIGRAPHS*/
/*#	define Z_COMPILER_CPP_HAS_SAFE_UNARY_FOLD_EXPRESSION*/
/*#	define Z_COMPILER_CPP_HAS_STATIC_ASSERTION_WITH_NO_MESSAGE*/
/*#	define Z_COMPILER_CPP_HAS_STRUCTURED_BINDING*/
/*#	define Z_COMPILER_CPP_HAS_SWITCH_WITH_INITIALIZER*/
/*#	define Z_COMPILER_CPP_HAS_TYPENAME_IN_TEMPLATE_TEMPLATE_PARAMETER*/
/*#	define Z_COMPILER_CPP_HAS_VARIADIC_USING*/
/*#	define Z_COMPILER_CPP_HAS_ATTRIBUTE_FALLTHROUGH*/
/*#	define Z_COMPILER_CPP_HAS_ATTRIBUTE_MAYBE_UNUSED*/
/*#	define Z_COMPILER_CPP_HAS_ATTRIBUTE_NODISCARD*/
/*#	define Z_COMPILER_CPP_HAS_LITERAL_HEXADECIMAL_FLOATING_POINT*/
/*#	define Z_COMPILER_CPP_HAS_LITERAL_UTF8_CHARACTER*/
/*#	define Z_COMPILER_CPP_HAS_PREPROCESSOR_OPERATOR_HAS_INCLUDE*/

	/* MARK: - Language: GNU C++ extensions */

/*#endif*/

/* MARK: - Attributes */

/*#define Z_COMPILER_ATTRIBUTE_ALIAS*/
/*#define Z_COMPILER_ATTRIBUTE_API_ALIAS*/
#define Z_COMPILER_ATTRIBUTE_API_EXPORT __declspec(dllexport)
#define Z_COMPILER_ATTRIBUTE_API_IMPORT __declspec(dllimport)
/*#define Z_COMPILER_ATTRIBUTE_API_EXPORT_ALIAS*/
/*#define Z_COMPILER_ATTRIBUTE_API_WEAK_EXPORT*/
/*#define Z_COMPILER_ATTRIBUTE_EBCO*/
#define Z_COMPILER_ATTRIBUTE_INLINE	__inline
/*#define Z_COMPILER_ATTRIBUTE_NO_RETURN*/
/*#define Z_COMPILER_ATTRIBUTE_NULL_TERMINATED*/
/*#define Z_COMPILER_ATTRIBUTE_PRIVATE*/
/*#define Z_COMPILER_ATTRIBUTE_PUBLIC*/
/*#define Z_COMPILER_ATTRIBUTE_THREAD_LOCAL*/
/*#define Z_COMPILER_ATTRIBUTE_WEAK*/

/* MARK: - Padding specifiers */

/*#define Z_COMPILER_DEFINE_PACKED_STRUCTURE_BEFORE_TYPEDEF*/
/*#define Z_COMPILER_DEFINE_PACKED_STRUCTURE_BEFORE_STRUCT*/
/*#define Z_COMPILER_DEFINE_PACKED_STRUCTURE_BEFORE_BODY*/
/*#define Z_COMPILER_DEFINE_PACKED_STRUCTURE_BEFORE_TYPE*/
/*#define Z_COMPILER_DEFINE_PACKED_STRUCTURE_AFTER_TYPE*/
/*#define Z_COMPILER_DEFINE_PACKED_UNION_BEFORE_TYPEDEF*/
/*#define Z_COMPILER_DEFINE_PACKED_UNION_BEFORE_UNION*/
/*#define Z_COMPILER_DEFINE_PACKED_UNION_BEFORE_BODY*/
/*#define Z_COMPILER_DEFINE_PACKED_UNION_BEFORE_TYPE*/
/*#define Z_COMPILER_DEFINE_PACKED_UNION_AFTER_TYPE*/
/*#define Z_COMPILER_PACKED_NAMED_STRUCTURE_BEFORE_STRUCT*/
/*#define Z_COMPILER_PACKED_NAMED_STRUCTURE_BEFORE_TYPE*/
/*#define Z_COMPILER_PACKED_NAMED_STRUCTURE_BEFORE_BODY*/
/*#define Z_COMPILER_PACKED_NAMED_STRUCTURE_AFTER_BODY*/
/*#define Z_COMPILER_PACKED_NAMED_UNION_BEFORE_UNION*/
/*#define Z_COMPILER_PACKED_NAMED_UNION_BEFORE_TYPE*/
/*#define Z_COMPILER_PACKED_NAMED_UNION_BEFORE_BODY*/
/*#define Z_COMPILER_PACKED_NAMED_UNION_AFTER_BODY*/
/*#define Z_COMPILER_PACKED_UNNAMED_STRUTURE_BEFORE_STRUCT*/
/*#define Z_COMPILER_PACKED_UNNAMED_STRUTURE_BEFORE_BODY*/
/*#define Z_COMPILER_PACKED_UNNAMED_STRUTURE_BEFORE_IDENTIFIER*/
/*#define Z_COMPILER_PACKED_UNNAMED_STRUTURE_AFTER_IDENTIFIER*/
/*#define Z_COMPILER_PACKED_UNNAMED_UNION_BEFORE_STRUCT*/
/*#define Z_COMPILER_PACKED_UNNAMED_UNION_BEFORE_BODY*/
/*#define Z_COMPILER_PACKED_UNNAMED_UNION_BEFORE_IDENTIFIER*/
/*#define Z_COMPILER_PACKED_UNNAMED_UNION_AFTER_IDENTIFIER*/


#endif /* Z_inspection_compiler_modules_MSVC_H */
