/* Z Kit C API - formats/keymap/Mac OS/virtual.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//___/_| Kit
Copyright (C) 2006-2017 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef __Z_formats_keymap_Mac_OS_virtual_H__
#define __Z_formats_keymap_Mac_OS_virtual_H__

#define Z_MAC_OS_KEY_CODE_ANSI_A			0
#define Z_MAC_OS_KEY_CODE_ANSI_S			1
#define Z_MAC_OS_KEY_CODE_ANSI_D			2
#define Z_MAC_OS_KEY_CODE_ANSI_F			3
#define Z_MAC_OS_KEY_CODE_ANSI_H			4
#define Z_MAC_OS_KEY_CODE_ANSI_G			5
#define Z_MAC_OS_KEY_CODE_ANSI_Z			6
#define Z_MAC_OS_KEY_CODE_ANSI_X			7
#define Z_MAC_OS_KEY_CODE_ANSI_C			8
#define Z_MAC_OS_KEY_CODE_ANSI_V			9
#define Z_MAC_OS_KEY_CODE_ISO_SECTION			10
#define Z_MAC_OS_KEY_CODE_ANSI_B			11
#define Z_MAC_OS_KEY_CODE_ANSI_Q			12
#define Z_MAC_OS_KEY_CODE_ANSI_W			13
#define Z_MAC_OS_KEY_CODE_ANSI_E			14
#define Z_MAC_OS_KEY_CODE_ANSI_R			15
#define Z_MAC_OS_KEY_CODE_ANSI_Y			16
#define Z_MAC_OS_KEY_CODE_ANSI_T			17
#define Z_MAC_OS_KEY_CODE_ANSI_1			18
#define Z_MAC_OS_KEY_CODE_ANSI_2			19
#define Z_MAC_OS_KEY_CODE_ANSI_3			20
#define Z_MAC_OS_KEY_CODE_ANSI_4			21
#define Z_MAC_OS_KEY_CODE_ANSI_6			22
#define Z_MAC_OS_KEY_CODE_ANSI_5			23
#define Z_MAC_OS_KEY_CODE_ANSI_EQUALS_SIGN		24
#define Z_MAC_OS_KEY_CODE_ANSI_9			25
#define Z_MAC_OS_KEY_CODE_ANSI_7			26
#define Z_MAC_OS_KEY_CODE_ANSI_HYPHEN_MINUS		27
#define Z_MAC_OS_KEY_CODE_ANSI_8			28
#define Z_MAC_OS_KEY_CODE_ANSI_0			29
#define Z_MAC_OS_KEY_CODE_ANSI_RIGHT_SQUARE_BRACKET	30
#define Z_MAC_OS_KEY_CODE_ANSI_O			31
#define Z_MAC_OS_KEY_CODE_ANSI_U			32
#define Z_MAC_OS_KEY_CODE_ANSI_LEFT_SQUARE_BRACKET	33
#define Z_MAC_OS_KEY_CODE_ANSI_I			34
#define Z_MAC_OS_KEY_CODE_ANSI_P			35
#define Z_MAC_OS_KEY_CODE_RETURN			36
#define Z_MAC_OS_KEY_CODE_ANSI_L			37
#define Z_MAC_OS_KEY_CODE_ANSI_J			38
#define Z_MAC_OS_KEY_CODE_ANSI_APOSTROPHE		39
#define Z_MAC_OS_KEY_CODE_ANSI_K			40
#define Z_MAC_OS_KEY_CODE_ANSI_SEMICOLON		41
#define Z_MAC_OS_KEY_CODE_ANSI_REVERSE_SOLIDUS		42
#define Z_MAC_OS_KEY_CODE_ANSI_COMMA			43
#define Z_MAC_OS_KEY_CODE_ANSI_SOLIDUS			44
#define Z_MAC_OS_KEY_CODE_ANSI_N			45
#define Z_MAC_OS_KEY_CODE_ANSI_M			46
#define Z_MAC_OS_KEY_CODE_ANSI_FULL_STOP		47
#define Z_MAC_OS_KEY_CODE_TAB				48
#define Z_MAC_OS_KEY_CODE_SPACE				49
#define Z_MAC_OS_KEY_CODE_ANSI_GRAVE_ACCENT		50
#define Z_MAC_OS_KEY_CODE_BACKSPACE			51
/* 52 - Unused? */
#define Z_MAC_OS_KEY_CODE_ESCAPE			53
#define Z_MAC_OS_KEY_CODE_RIGHT_COMMAND			54
#define Z_MAC_OS_KEY_CODE_LEFT_COMMAND			55
#define Z_MAC_OS_KEY_CODE_LEFT_SHIFT			56
#define Z_MAC_OS_KEY_CODE_CAPS_LOCK			57
#define Z_MAC_OS_KEY_CODE_LEFT_OPTION			58
#define Z_MAC_OS_KEY_CODE_LEFT_CONTROL			59
#define Z_MAC_OS_KEY_CODE_RIGHT_SHIFT			60
#define Z_MAC_OS_KEY_CODE_RIGHT_OPTION			61
#define Z_MAC_OS_KEY_CODE_RIGHT_CONTROL			62
#define Z_MAC_OS_KEY_CODE_FUNCTION			63
#define Z_MAC_OS_KEY_CODE_F17				64
#define Z_MAC_OS_KEY_CODE_ANSI_KEYPAD_DECIMAL_SEPARATOR 65
/* 66 - Unused? */
#define Z_MAC_OS_KEY_CODE_ANSI_KEYPAD_ASTERISK		67
/* 68 - Unused? */
#define Z_MAC_OS_KEY_CODE_ANSI_KEYPAD_PLUS_SIGN		69
/* 70 - Unused? */
#define Z_MAC_OS_KEY_CODE_ANSI_KEYPAD_CLEAR		71
/* 72-74 - Unused? */
#define Z_MAC_OS_KEY_CODE_ANSI_KEYPAD_SOLIDUS		75 /* PC keyboards */
#define Z_MAC_OS_KEY_CODE_ANSI_KEYPAD_ENTER		76
/* 77 - Unused? */
#define Z_MAC_OS_KEY_CODE_ANSI_KEYPAD_HYPHEN_MINUS	78
#define Z_MAC_OS_KEY_CODE_F18				79
#define Z_MAC_OS_KEY_CODE_F19				80
#define Z_MAC_OS_KEY_CODE_ANSI_KEYPAD_EQUALS_SIGN	81
#define Z_MAC_OS_KEY_CODE_ANSI_KEYPAD_0			82
#define Z_MAC_OS_KEY_CODE_ANSI_KEYPAD_1			83
#define Z_MAC_OS_KEY_CODE_ANSI_KEYPAD_2			84
#define Z_MAC_OS_KEY_CODE_ANSI_KEYPAD_3			85
#define Z_MAC_OS_KEY_CODE_ANSI_KEYPAD_4			86
#define Z_MAC_OS_KEY_CODE_ANSI_KEYPAD_5			87
#define Z_MAC_OS_KEY_CODE_ANSI_KEYPAD_6			88
#define Z_MAC_OS_KEY_CODE_ANSI_KEYPAD_7			89
#define Z_MAC_OS_KEY_CODE_F20				90
#define Z_MAC_OS_KEY_CODE_ANSI_KEYPAD_8			91
#define Z_MAC_OS_KEY_CODE_ANSI_KEYPAD_9			92
#define Z_MAC_OS_KEY_CODE_JIS_YEN_SIGN			93
#define Z_MAC_OS_KEY_CODE_JIS_LOW_LINE			94
#define Z_MAC_OS_KEY_CODE_JIS_KEYPAD_COMMA		95
#define Z_MAC_OS_KEY_CODE_F5				96
#define Z_MAC_OS_KEY_CODE_F6				97
#define Z_MAC_OS_KEY_CODE_F7				98
#define Z_MAC_OS_KEY_CODE_F3				99
#define Z_MAC_OS_KEY_CODE_F8				100
#define Z_MAC_OS_KEY_CODE_F9				101
#define Z_MAC_OS_KEY_CODE_JIS_EISU			102 /* Toggles alphanumeric characters */
#define Z_MAC_OS_KEY_CODE_F11				103
#define Z_MAC_OS_KEY_CODE_JIS_KANA			104
#define Z_MAC_OS_KEY_CODE_F13				105
#define Z_MAC_OS_KEY_CODE_F16				106
#define Z_MAC_OS_KEY_CODE_F14				107
/* 108 - Unused? */
#define Z_MAC_OS_KEY_CODE_F10				109
#define Z_MAC_OS_KEY_CODE_APPLICATION			110 /* PC/Windows keyboards */
#define Z_MAC_OS_KEY_CODE_F12				111
/* 112 - Unused? */
#define Z_MAC_OS_KEY_CODE_F15				113
#define Z_MAC_OS_KEY_CODE_HELP				114
#define Z_MAC_OS_KEY_CODE_HOME				115
#define Z_MAC_OS_KEY_CODE_PAGE_UP			116
#define Z_MAC_OS_KEY_CODE_DELETE			117
#define Z_MAC_OS_KEY_CODE_F4				118
#define Z_MAC_OS_KEY_CODE_END				119
#define Z_MAC_OS_KEY_CODE_F2				120
#define Z_MAC_OS_KEY_CODE_PAGE_DOWN			121
#define Z_MAC_OS_KEY_CODE_F1				122
#define Z_MAC_OS_KEY_CODE_LEFT_ARROW			123
#define Z_MAC_OS_KEY_CODE_RIGHT_ARROW			124
#define Z_MAC_OS_KEY_CODE_DOWN_ARROW			125
#define Z_MAC_OS_KEY_CODE_UP_ARROW			126

#endif /* __Z_formats_keymap_Mac_OS_virtual_H__ */
