/* Q API - inspection/private/floating point/IEEE 754 LD64.h
	      __	   __
  _______ ___/ /______ ___/ /__
 / __/ -_) _  / __/ _ \ _  / -_)
/_/  \__/\_,_/\__/\___/_,_/\__/
Copyright © 2006-2014 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU General Public License v3. */

#ifndef __Q_inspection_private_floating_point_H__
#define __Q_inspection_private_floating_point_H__

#include <Q/keys/floating point.h>
#include <Q/keys/value.h>

#define Q_FLOATING_POINT				Q_FLOATING_POINT_IEEE_754_LD64
#define Q_FLOATING_POINT_STRING				Q_FLOATING_POINT_STRING_IEEE_754_LD64

#define Q_FLOATING_POINT_RADIX				2

#define Q_FLOATING_POINT_FLOAT_FORMAT			Q_VALUE_FORMAT_32BIT_REAL_IEEE_754_BINARY
#define Q_FLOATING_POINT_FLOAT_BITS			32
#define Q_FLOATING_POINT_FLOAT_MAXIMUM			3.40282347e+38F
#define Q_FLOATING_POINT_FLOAT_MINIMUM			1.17549435e-38F
#define Q_FLOATING_POINT_FLOAT_EPSILON			1.19209290e-07F
#define Q_FLOATING_POINT_FLOAT_MANTISSA_DIGITS		24
#define Q_FLOATING_POINT_FLOAT_DECIMAL_DIGITS		6
#define Q_FLOATING_POINT_FLOAT_EXPONENT_MAXIMUM		128
#define Q_FLOATING_POINT_FLOAT_EXPONENT_MINIMUM		(-125)
#define Q_FLOATING_POINT_FLOAT_EXPONENT_10_MAXIMUM	38
#define Q_FLOATING_POINT_FLOAT_EXPONENT_10_MINIMUM	(-37)

#define Q_FLOATING_POINT_DOUBLE_FORMAT			Q_VALUE_FORMAT_64BIT_REAL_IEEE_754_BINARY
#define Q_FLOATING_POINT_DOUBLE_BITS			64
#define Q_FLOATING_POINT_DOUBLE_MAXIMUM			1.7976931348623157e+308
#define Q_FLOATING_POINT_DOUBLE_MINIMUM			2.2250738585072014e-308
#define Q_FLOATING_POINT_DOUBLE_EPSILON			2.2204460492503131e-16
#define Q_FLOATING_POINT_DOUBLE_MANTISSA_DIGITS		53
#define Q_FLOATING_POINT_DOUBLE_DECIMAL_DIGITS		15
#define Q_FLOATING_POINT_DOUBLE_EXPONENT_MAXIMUM	1024
#define Q_FLOATING_POINT_DOUBLE_EXPONENT_MINIMUM	(-1021)
#define Q_FLOATING_POINT_DOUBLE_EXPONENT_10_MAXIMUM	308
#define Q_FLOATING_POINT_DOUBLE_EXPONENT_10_MINIMUM	(-307)

#define Q_FLOATING_POINT_LDOUBLE_FORMAT			Q_FLOATING_POINT_DOUBLE_FORMAT
#define Q_FLOATING_POINT_LDOUBLE_BITS			Q_FLOATING_POINT_DOUBLE_BITS
#define Q_FLOATING_POINT_LDOUBLE_MAXIMUM		Q_FLOATING_POINT_DOUBLE_MAXIMUM
#define Q_FLOATING_POINT_LDOUBLE_MINIMUM		Q_FLOATING_POINT_DOUBLE_MINIMUM
#define Q_FLOATING_POINT_LDOUBLE_EPSILON		Q_FLOATING_POINT_DOUBLE_EPSILON
#define Q_FLOATING_POINT_LDOUBLE_MANTISSA_DIGITS	Q_FLOATING_POINT_DOUBLE_MANTISSA_DIGITS
#define Q_FLOATING_POINT_LDOUBLE_DECIMAL_DIGITS		Q_FLOATING_POINT_DOUBLE_DECIMAL_DIGITS
#define Q_FLOATING_POINT_LDOUBLE_EXPONENT_MAXIMUM	Q_FLOATING_POINT_DOUBLE_EXPONENT_MAXIMUM
#define Q_FLOATING_POINT_LDOUBLE_EXPONENT_MINIMUM	Q_FLOATING_POINT_DOUBLE_EXPONENT_MINIMUM
#define Q_FLOATING_POINT_LDOUBLE_EXPONENT_10_MAXIMUM	Q_FLOATING_POINT_DOUBLE_EXPONENT_10_MAXIMUM
#define Q_FLOATING_POINT_LDOUBLE_EXPONENT_10_MINIMUM	Q_FLOATING_POINT_DOUBLE_EXPONENT_10_MINIMUM

#endif /* __Q_inspection_private_floating_point_H__ */
