/* Z Kit - inspection/data model/completion.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//___/_| Kit
Copyright (C) 2006-2018 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifdef Z_DATA_MODEL_LITERAL_UINT8
#	define Z_DATA_MODEL_HAS_LITERAL_UINT8 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_UINT8 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_SINT8
#	define Z_DATA_MODEL_HAS_LITERAL_SINT8 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_SINT8 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_UINT16
#	define Z_DATA_MODEL_HAS_LITERAL_UINT16 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_UINT16 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_SINT16
#	define Z_DATA_MODEL_HAS_LITERAL_SINT16 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_SINT16 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_UINT32
#	define Z_DATA_MODEL_HAS_LITERAL_UINT32 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_UINT32 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_SINT32
#	define Z_DATA_MODEL_HAS_LITERAL_SINT32 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_SINT32 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_UINT64
#	define Z_DATA_MODEL_HAS_LITERAL_UINT64 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_UINT64 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_SINT64
#	define Z_DATA_MODEL_HAS_LITERAL_SINT64 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_SINT64 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_UINT128
#	define Z_DATA_MODEL_HAS_LITERAL_UINT128 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_UINT128 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_SINT128
#	define Z_DATA_MODEL_HAS_LITERAL_SINT128 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_SINT128 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_UINT8
#	define Z_DATA_MODEL_HAS_TYPE_UINT8 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_UINT8 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_SINT8
#	define Z_DATA_MODEL_HAS_TYPE_SINT8 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_SINT8 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_UINT16
#	define Z_DATA_MODEL_HAS_TYPE_UINT16 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_UINT16 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_SINT16
#	define Z_DATA_MODEL_HAS_TYPE_SINT16 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_SINT16 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_UINT32
#	define Z_DATA_MODEL_HAS_TYPE_UINT32 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_UINT32 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_SINT32
#	define Z_DATA_MODEL_HAS_TYPE_SINT32 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_SINT32 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_UINT64
#	define Z_DATA_MODEL_HAS_TYPE_UINT64 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_UINT64 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_SINT64
#	define Z_DATA_MODEL_HAS_TYPE_SINT64 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_SINT64 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_UINT128
#	define Z_DATA_MODEL_HAS_TYPE_UINT128 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_UINT128 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_SINT128
#	define Z_DATA_MODEL_HAS_TYPE_SINT128 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_SINT128 FALSE
#endif

/* inspection/data model/completion.h EOF */
