/* Z Kit - inspection/data model/completion.h
 _____  _______________
/_   /_/  -_/_   _/  _ |
 /____/\___/ /__//__/__| Kit
Copyright (C) 2006-2020 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef Z_inspection_data_model_completion_H
#define Z_inspection_data_model_completion_H

#ifdef Z_DATA_MODEL_TYPE_UINT8
#	define Z_DATA_MODEL_HAS_TYPE_UINT8 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_UINT8 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_UINT8
#	define Z_DATA_MODEL_HAS_LITERAL_UINT8 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_UINT8 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_SINT8
#	define Z_DATA_MODEL_HAS_TYPE_SINT8 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_SINT8 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_SINT8
#	define Z_DATA_MODEL_HAS_LITERAL_SINT8 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_SINT8 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_UINT16
#	define Z_DATA_MODEL_HAS_TYPE_UINT16 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_UINT16 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_UINT16
#	define Z_DATA_MODEL_HAS_LITERAL_UINT16 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_UINT16 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_SINT16
#	define Z_DATA_MODEL_HAS_TYPE_SINT16 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_SINT16 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_SINT16
#	define Z_DATA_MODEL_HAS_LITERAL_SINT16 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_SINT16 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_UINT24
#	define Z_DATA_MODEL_HAS_TYPE_UINT24 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_UINT24 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_UINT24
#	define Z_DATA_MODEL_HAS_LITERAL_UINT24 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_UINT24 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_SINT24
#	define Z_DATA_MODEL_HAS_TYPE_SINT24 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_SINT24 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_SINT24
#	define Z_DATA_MODEL_HAS_LITERAL_SINT24 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_SINT24 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_UINT32
#	define Z_DATA_MODEL_HAS_TYPE_UINT32 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_UINT32 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_UINT32
#	define Z_DATA_MODEL_HAS_LITERAL_UINT32 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_UINT32 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_SINT32
#	define Z_DATA_MODEL_HAS_TYPE_SINT32 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_SINT32 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_SINT32
#	define Z_DATA_MODEL_HAS_LITERAL_SINT32 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_SINT32 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_UINT40
#	define Z_DATA_MODEL_HAS_TYPE_UINT40 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_UINT40 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_UINT40
#	define Z_DATA_MODEL_HAS_LITERAL_UINT40 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_UINT40 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_SINT40
#	define Z_DATA_MODEL_HAS_TYPE_SINT40 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_SINT40 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_SINT40
#	define Z_DATA_MODEL_HAS_LITERAL_SINT40 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_SINT40 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_UINT48
#	define Z_DATA_MODEL_HAS_TYPE_UINT48 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_UINT48 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_UINT48
#	define Z_DATA_MODEL_HAS_LITERAL_UINT48 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_UINT48 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_SINT48
#	define Z_DATA_MODEL_HAS_TYPE_SINT48 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_SINT48 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_SINT48
#	define Z_DATA_MODEL_HAS_LITERAL_SINT48 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_SINT48 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_UINT56
#	define Z_DATA_MODEL_HAS_TYPE_UINT56 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_UINT56 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_UINT56
#	define Z_DATA_MODEL_HAS_LITERAL_UINT56 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_UINT56 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_SINT56
#	define Z_DATA_MODEL_HAS_TYPE_SINT56 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_SINT56 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_SINT56
#	define Z_DATA_MODEL_HAS_LITERAL_SINT56 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_SINT56 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_UINT64
#	define Z_DATA_MODEL_HAS_TYPE_UINT64 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_UINT64 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_UINT64
#	define Z_DATA_MODEL_HAS_LITERAL_UINT64 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_UINT64 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_SINT64
#	define Z_DATA_MODEL_HAS_TYPE_SINT64 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_SINT64 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_SINT64
#	define Z_DATA_MODEL_HAS_LITERAL_SINT64 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_SINT64 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_UINT128
#	define Z_DATA_MODEL_HAS_TYPE_UINT128 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_UINT128 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_UINT128
#	define Z_DATA_MODEL_HAS_LITERAL_UINT128 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_UINT128 FALSE
#endif

#ifdef Z_DATA_MODEL_TYPE_SINT128
#	define Z_DATA_MODEL_HAS_TYPE_SINT128 TRUE
#else
#	define Z_DATA_MODEL_HAS_TYPE_SINT128 FALSE
#endif

#ifdef Z_DATA_MODEL_LITERAL_SINT128
#	define Z_DATA_MODEL_HAS_LITERAL_SINT128 TRUE
#else
#	define Z_DATA_MODEL_HAS_LITERAL_SINT128 FALSE
#endif

#endif /* Z_inspection_data_model_completion_H */
