/* Z Kit C API - formats/floating point/Microsoft Visual C++.h
	      __	   __
  _______ ___/ /______ ___/ /__
 / __/ -_) _  / __/ _ \ _  / -_)
/_/  \__/\_,_/\__/\___/_,_/\__/
Copyright © 2006-2015 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef __Z_formats_floating_point_Microsoft_Visual_CPP_Ha__
#define __Z_formats_floating_point_Microsoft_Visual_CPP_Ha__

#include <Z/formats/floating point/IEEE 754.h>

/* MARK: - float */

#define Z_MICROSOFT_VISUAL_CPP_FLOAT_BITS		  Z_IEEE_754_BINARY32_BITS
#define Z_MICROSOFT_VISUAL_CPP_FLOAT_BIAS		  Z_IEEE_754_BINARY32_BIAS
#define Z_MICROSOFT_VISUAL_CPP_FLOAT_EPSILON		  1.192092896e-07
#define Z_MICROSOFT_VISUAL_CPP_FLOAT_MINIMUM		  1.175494351e-38
#define Z_MICROSOFT_VISUAL_CPP_FLOAT_MAXIMUM		  3.402823466e+38
#define Z_MICROSOFT_VISUAL_CPP_FLOAT_NORMALIZED_MINIMUM	  Z_IEEE_754_BINARY32_NORMALIZED_MINIMUM
#define Z_MICROSOFT_VISUAL_CPP_FLOAT_DECIMAL_DIGITS	  Z_IEEE_754_BINARY32_DECIMAL_DIGITS
#define Z_MICROSOFT_VISUAL_CPP_FLOAT_MANTISSA_OFFSET	  Z_IEEE_754_BINARY32_MANTISSA_OFFSET
#define Z_MICROSOFT_VISUAL_CPP_FLOAT_MANTISSA_BITS	  Z_IEEE_754_BINARY32_MANTISSA_BITS
#define Z_MICROSOFT_VISUAL_CPP_FLOAT_MANTISSA_DIGITS	  Z_IEEE_754_BINARY32_MANTISSA_DIGITS
#define Z_MICROSOFT_VISUAL_CPP_FLOAT_EXPONENT_OFFSET	  Z_IEEE_754_BINARY32_EXPONENT_OFFSET
#define Z_MICROSOFT_VISUAL_CPP_FLOAT_EXPONENT_BITS	  Z_IEEE_754_BINARY32_EXPONENT_BITS
#define Z_MICROSOFT_VISUAL_CPP_FLOAT_EXPONENT_RADIX	  Z_IEEE_754_BINARY32_EXPONENT_RADIX
#define Z_MICROSOFT_VISUAL_CPP_FLOAT_EXPONENT_MINIMUM	  -125
#define Z_MICROSOFT_VISUAL_CPP_FLOAT_EXPONENT_MAXIMUM	  128
#define Z_MICROSOFT_VISUAL_CPP_FLOAT_EXPONENT_10_MINIMUM  -37
#define Z_MICROSOFT_VISUAL_CPP_FLOAT_EXPONENT_10_MAXIMUM  38
#define Z_MICROSOFT_VISUAL_CPP_FLOAT_SIGN_OFFSET	  Z_IEEE_754_BINARY32_SIGN_OFFSET
#define Z_MICROSOFT_VISUAL_CPP_FLOAT_SIGN_BITS		  Z_IEEE_754_BINARY32_SIGN_BITS

/* MARK: - double */

#define Z_MICROSOFT_VISUAL_CPP_DOUBLE_BITS		  Z_IEEE_754_BINARY64_BITS
#define Z_MICROSOFT_VISUAL_CPP_DOUBLE_BIAS		  Z_IEEE_754_BINARY64_BIAS
#define Z_MICROSOFT_VISUAL_CPP_DOUBLE_EPSILON		  Z_IEEE_754_BINARY64_EPSILON
#define Z_MICROSOFT_VISUAL_CPP_DOUBLE_MINIMUM		  Z_IEEE_754_BINARY64_MINIMUM
#define Z_MICROSOFT_VISUAL_CPP_DOUBLE_MAXIMUM		  1.7976931348623158e+308
#define Z_MICROSOFT_VISUAL_CPP_DOUBLE_DECIMAL_DIGITS	  Z_IEEE_754_BINARY64_DECIMAL_DIGITS
#define Z_MICROSOFT_VISUAL_CPP_DOUBLE_MANTISSA_OFFSET	  Z_IEEE_754_BINARY64_MANTISSA_OFFSET
#define Z_MICROSOFT_VISUAL_CPP_DOUBLE_MANTISSA_BITS	  Z_IEEE_754_BINARY64_MANTISSA_BITS
#define Z_MICROSOFT_VISUAL_CPP_DOUBLE_MANTISSA_DIGITS	  Z_IEEE_754_BINARY64_MANTISSA_DIGITS
#define Z_MICROSOFT_VISUAL_CPP_DOUBLE_EXPONENT_OFFSET	  Z_IEEE_754_BINARY64_EXPONENT_OFFSET
#define Z_MICROSOFT_VISUAL_CPP_DOUBLE_EXPONENT_BITS	  Z_IEEE_754_BINARY64_EXPONENT_BITS
#define Z_MICROSOFT_VISUAL_CPP_DOUBLE_EXPONENT_RADIX	  Z_IEEE_754_BINARY64_EXPONENT_RADIX
#define Z_MICROSOFT_VISUAL_CPP_DOUBLE_EXPONENT_MINIMUM	  -1021
#define Z_MICROSOFT_VISUAL_CPP_DOUBLE_EXPONENT_MAXIMUM	  1024
#define Z_MICROSOFT_VISUAL_CPP_DOUBLE_EXPONENT_10_MINIMUM -307
#define Z_MICROSOFT_VISUAL_CPP_DOUBLE_EXPONENT_10_MAXIMUM 308
#define Z_MICROSOFT_VISUAL_CPP_DOUBLE_SIGN_OFFSET	  Z_IEEE_754_BINARY64_SIGN_OFFSET
#define Z_MICROSOFT_VISUAL_CPP_DOUBLE_SIGN_BITS		  Z_IEEE_754_BINARY64_SIGN_BITS

#endif /* __Z_formats_floating_point_Microsoft_Visual_CPP_Ha__ */

#ifndef Z_INSPECTING_FLOATING_POINT

#	ifndef __Z_formats_floating_point_Microsoft_Visual_CPP_Hb__
#	define __Z_formats_floating_point_Microsoft_Visual_CPP_Hb__

	typedef ZIEEE754Binary32 ZMicrosoftVisualCPPFloat;
	typedef ZIEEE754Binary64 ZMicrosoftVisualCPPDouble;

#	endif /* __Z_formats_floating_point_Microsoft_Visual_CPP_Hb__ */

#endif
