/* Z Kit C API - keys/hardware/storage medium.h
	      __	   __
  _______ ___/ /______ ___/ /__
 / __/ -_) _  / __/ _ \ _  / -_)
/_/  \__/\_,_/\__/\___/_,_/\__/
Copyright © 2006-2015 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef __Z_keys_hardware_storage_medium_H__
#define __Z_keys_hardware_storage_medium_H__

/* MARK: - ROM */

#define Z_STORAGE_MEDIUM_ROM

/* MARK: - ROM cartridges */

#define Z_STORAGE_MEDIUM_ATARI_2600_CARTRIDGE
#define Z_STORAGE_MEDIUM_ATARI_5200_CARTRIDGE
#define Z_STORAGE_MEDIUM_ATARI_7800_CARTRIDGE
#define Z_STORAGE_MEDIUM_ATARI_JAGUAR_CARTRIDGE
#define Z_STORAGE_MEDIUM_NEO_GEO_AES_CARTRIDGE
#define Z_STORAGE_MEDIUM_NEO_GEO_MVS_CARTRIDGE
#define Z_STORAGE_MEDIUM_NES_GAME_PAK
#define Z_STORAGE_MEDIUM_SNES_GAME_PAK
#define Z_STORAGE_MEDIUM_GAME_BOY_GAME_PACK

/* MARK: - Analog audio magnetic tapes */

#define Z_STORAGE_MEDIUM_COMPACT_CASSETTE

/* MARK: - Analog audio+video magnetic tapes */

#define Z_STORAGE_MEDIUM_CARTRIVISION
#define Z_STORAGE_MEDIUM_BETAMAX
#define Z_STORAGE_MEDIUM_VHS
#define Z_STORAGE_MEDIUM_VIDEO_2000

/* MARK: - Digital tapes */

#define Z_STORAGE_MEDIUM_ZX_MICRODRIVE
#define Z_STORAGE_MEDIUM_DAT

/* MARK: - Magnetic disks */

#define Z_STORAGE_MEDIUM_FLOPPY_DISK_8_INCH_IBM_23FD
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_8_INCH_MEMOREX_651
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_8_INCH_IBM_33FD_SSSD
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_8_INCH_IBM_43FD_DSSD
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_5_25_INCH_SHUGART_SA_400_35_TRACK
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_8_INCH_IBM_53FD_DSDD
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_5_25_INCH_DD
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_3_5_HEWLETT_PACKARD_SS
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_3_INCH
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_3_5_INCH_DD
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_5_25_INCH_QD
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_5_25_INCH_HD
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_3_INCH_DD
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_3_INCH_MITSUMI_QUICK_DISK
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_2_INCH
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_3_5_INCH_HD
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_3_5_INCH_ED

/* MARK: - Magneto-optical discs */

#define Z_STORAGE_MEDIUM_LS
#define Z_STORAGE_MEDIUM_ZIP_100
#define Z_STORAGE_MEDIUM_LS_120
#define Z_STORAGE_MEDIUM_LS_224
#define Z_STORAGE_MEDIUM_CALEB_UHD144
#define Z_STORAGE_MEDIUM_HI_FP
#define Z_STORAGE_MEDIUM_ZIP_250
#define Z_STORAGE_MEDIUM_ZIP_750

/* MARK: - Optical discs */

#define Z_STORAGE_MEDIUM_CD_ROM_8_CM_180
#define Z_STORAGE_MEDIUM_CD_ROM_8_CM_550
#define Z_STORAGE_MEDIUM_CD_ROM_12_CM_650
#define Z_STORAGE_MEDIUM_CD_ROM_12_CM_700
#define Z_STORAGE_MEDIUM_CD_ROM_12_CM_800
#define Z_STORAGE_MEDIUM_CD_ROM_12_CM_900
#define Z_STORAGE_MEDIUM_DVD_ROM_8_CM_SS_SL
#define Z_STORAGE_MEDIUM_DVD_ROM_8_CM_SS_DL
#define Z_STORAGE_MEDIUM_DVD_ROM_8_CM_DS_SL
#define Z_STORAGE_MEDIUM_DVD_ROM_8_CM_DS_DL
#define Z_STORAGE_MEDIUM_DVD_ROM_12_CM_SS_SL
#define Z_STORAGE_MEDIUM_DVD_ROM_12_CM_SS_DL
#define Z_STORAGE_MEDIUM_DVD_ROM_12_CM_DS_SL
#define Z_STORAGE_MEDIUM_DVD_ROM_12_CM_DS_SL_DL
#define Z_STORAGE_MEDIUM_DVD_ROM_12_CM_DS_DL

#endif /* __Z_keys_hardware_storage_medium_H__ */
