/* Z Kit C API - keys/hardware/storage medium.h
	      __	   __
  _______ ___/ /______ ___/ /__
 / __/ -_) _  / __/ _ \ _  / -_)
/_/  \__/\_,_/\__/\___/_,_/\__/
Copyright © 2006-2015 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef __Z_keys_hardware_storage_medium_H__
#define __Z_keys_hardware_storage_medium_H__

/* MARK: - ROM */

#define Z_STORAGE_MEDIUM_ROM

/* MARK: - ROM Cartridges */

#define Z_STORAGE_MEDIUM_ATARI_2600_CARTRIDGE
#define Z_STORAGE_MEDIUM_ATARI_5200_CARTRIDGE
#define Z_STORAGE_MEDIUM_ATARI_7800_CARTRIDGE
#define Z_STORAGE_MEDIUM_ATARI_JAGUAR_CARTRIDGE
#define Z_STORAGE_MEDIUM_NEO_GEO_AES_CARTRIDGE
#define Z_STORAGE_MEDIUM_NEO_GEO_MVS_CARTRIDGE
#define Z_STORAGE_MEDIUM_NES_GAME_PAK
#define Z_STORAGE_MEDIUM_SNES_GAME_PAK
#define Z_STORAGE_MEDIUM_GAME_BOY_GAME_PACK

/* MARK: - Magnetic Tapes */

#define Z_STORAGE_MEDIUM_COMPACT_CASSETTE
#define Z_STORAGE_MEDIUM_ZX_MICRODRIVE
#define Z_STORAGE_MEDIUM_DAT

/* MARK: - Magnetic Disks */

#define Z_STORAGE_MEDIUM_FLOPPY_DISK_8_INCH_IBM_23FD
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_8_INCH_MEMOREX_650
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_8_INCH_SS_SD
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_8_INCH_DS_SD
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_8_INCH_DS_DD
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_5_25_INCH_35_TRACK
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_5_25_INCH_DD
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_5_25_INCH_HD
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_5_25_INCH_APPLE_DISK_II_PRE_DOS_3_3
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_5_25_INCH_APPLE_DISK_II_DOS_3_3
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_5_25_INCH
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_3_5_INCH_DD
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_3_5_INCH_HD
#define Z_STORAGE_MEDIUM_FLOPPY_DISK_3_INCH

/* MARK: - Magneto-Optical Discs */

/* MARK: - Optical Discs */

#define Z_STORAGE_MEDIUM_CD_ROM_8_CM_180
#define Z_STORAGE_MEDIUM_CD_ROM_8_CM_550
#define Z_STORAGE_MEDIUM_CD_ROM_12_CM_650
#define Z_STORAGE_MEDIUM_CD_ROM_12_CM_700
#define Z_STORAGE_MEDIUM_CD_ROM_12_CM_800
#define Z_STORAGE_MEDIUM_CD_ROM_12_CM_900
#define Z_STORAGE_MEDIUM_DVD_ROM_8_CM_SS_SL
#define Z_STORAGE_MEDIUM_DVD_ROM_8_CM_SS_DL
#define Z_STORAGE_MEDIUM_DVD_ROM_8_CM_DS_SL
#define Z_STORAGE_MEDIUM_DVD_ROM_8_CM_DS_DL
#define Z_STORAGE_MEDIUM_DVD_ROM_12_CM_SS_SL
#define Z_STORAGE_MEDIUM_DVD_ROM_12_CM_SS_DL
#define Z_STORAGE_MEDIUM_DVD_ROM_12_CM_DS_SL
#define Z_STORAGE_MEDIUM_DVD_ROM_12_CM_DS_SL_DL
#define Z_STORAGE_MEDIUM_DVD_ROM_12_CM_DS_DL

#endif /* __Z_keys_hardware_storage_medium_H__ */
