/* Q API - keys/character set.h
	      __	   __
  _______ ___/ /______ ___/ /__
 / __/ -_) _  / __/ _ \ _  / -_)
/_/  \__/\_,_/\__/\___/_,_/\__/
Copyright © 2006-2015 Manuel Sainz de Baranda y Goñi.
Released under the terms of the GNU Lesser General Public License v3. */

#ifndef __Q_keys_character_set_H__
#define __Q_keys_character_set_H__

#define Q_CHARACTER_SET_ASCII		1
#define Q_CHARACTER_SET_UTF_8		2
#define Q_CHARACTER_SET_UTF_16		3
#define Q_CHARACTER_SET_UTF_32		4
#define Q_CHARACTER_SET_EBCDIC_CP037
#define Q_CHARACTER_SET_EBCDIC_CP930
#define Q_CHARACTER_SET_EBCDIC_CP1047
#define Q_CHARACTER_SET_ISO_8859_1
#define Q_CHARACTER_SET_ISO_8859_2
#define Q_CHARACTER_SET_ISO_8859_3
#define Q_CHARACTER_SET_ISO_8859_4
#define Q_CHARACTER_SET_ISO_8859_5
#define Q_CHARACTER_SET_ISO_8859_6
#define Q_CHARACTER_SET_ISO_8859_7
#define Q_CHARACTER_SET_ISO_8859_8
#define Q_CHARACTER_SET_ISO_8859_9
#define Q_CHARACTER_SET_ISO_8859_10
#define Q_CHARACTER_SET_ISO_8859_11
#define Q_CHARACTER_SET_ISO_8859_13
#define Q_CHARACTER_SET_ISO_8859_14
#define Q_CHARACTER_SET_ISO_8859_15
#define Q_CHARACTER_SET_ISO_8859_16
#define Q_CHARACTER_SET_CP437
#define Q_CHARACTER_SET_CP737
#define Q_CHARACTER_SET_CP850
#define Q_CHARACTER_SET_CP852
#define Q_CHARACTER_SET_CP855
#define Q_CHARACTER_SET_CP857
#define Q_CHARACTER_SET_CP858
#define Q_CHARACTER_SET_CP860
#define Q_CHARACTER_SET_CP861
#define Q_CHARACTER_SET_CP862
#define Q_CHARACTER_SET_CP863
#define Q_CHARACTER_SET_CP865
#define Q_CHARACTER_SET_CP866
#define Q_CHARACTER_SET_CP869
#define Q_CHARACTER_SET_CP872
#define Q_CHARACTER_SET_WINDOWS_1250
#define Q_CHARACTER_SET_WINDOWS_1251
#define Q_CHARACTER_SET_WINDOWS_1252
#define Q_CHARACTER_SET_WINDOWS_1253
#define Q_CHARACTER_SET_WINDOWS_1254
#define Q_CHARACTER_SET_WINDOWS_1255
#define Q_CHARACTER_SET_WINDOWS_1256
#define Q_CHARACTER_SET_WINDOWS_1257
#define Q_CHARACTER_SET_WINDOWS_1258
#define Q_CHARACTER_SET_MAC_OS_ROMAN
#define Q_CHARACTER_SET_KOI8_R
#define Q_CHARACTER_SET_KOI8_U
#define Q_CHARACTER_SET_KOI7
#define Q_CHARACTER_SET_MIK
#define Q_CHARACTER_SET_ISCII
#define Q_CHARACTER_SET_TSCII
#define Q_CHARACTER_SET_VISCII
#define Q_CHARACTER_SET_SHIFT_JIS
#define Q_CHARACTER_SET_EUC_JIS_2004
#define Q_CHARACTER_SET_ISO_2022_JP_2004
#define Q_CHARACTER_SET_GB_2312
#define Q_CHARACTER_SET_GBK
#define Q_CHARACTER_SET_GB_18030
#define Q_CHARACTER_SET_BIG5
#define Q_CHARACTER_SET_HKSCS
#define Q_CHARACTER_SET_KS_X_1001
#define Q_CHARACTER_SET_EUC_KR
#define Q_CHARACTER_SET_ISO_2022_KR
#define Q_CHARACTER_SET_ANSEL

#define Q_KEY_BITS_CHARACTER_SET 8
#define Q_KEY_LAST_CHARACTER_SET Q_CHARACTER_SET_ANSEL

#endif /* __Q_keys_character_set_H__ */
